// js/challenges-strings.js - the Challenges screen's words (js/challenges-ui.js), EN/ES.
//
// Its own file, not js/strings.js, because js/strings.js is a CACHE-FIRST shell asset and this
// screen is network-first: the first load after a deploy can pair a fresh screen with the previous
// build's shared dictionary, which prints the KEY (root CLAUDE.md, "A NEW key can be missing for one
// visit"). A dictionary that ships with the screen cannot be a build behind it.
//
// No em dashes in player-facing copy (root CLAUDE.md, copy conventions).

export const STRINGS = {
  en: {
    cx_title: 'Challenges',
    cx_close: 'Close',
    cx_back: 'Back',
    cx_loading: 'Loading…',
    cx_no_code: 'Set up your profile first, then you can challenge people.',
    cx_tab_live: 'Live',
    cx_tab_records: 'Records',
    cx_new: 'New challenge',
    cx_your_turn: 'Your turn',
    cx_their_turn: 'Their turn',
    cx_play: 'Play',
    cx_waiting_on: 'Waiting on {name}',
    cx_none_live: 'No live challenges right now. Start one!',
    cx_failed: 'Could not load: {games}. Check your connection.',
    cx_record: 'Your record',
    cx_won: 'Won',
    cx_lost: 'Lost',
    cx_drawn: 'Drawn',
    cx_wld: '{w} W · {l} L',
    cx_wld_d: '{w} W · {l} L · {d} D',
    cx_by_game: 'By game',
    cx_by_player: 'By player',
    cx_recent: 'Recent results',
    cx_no_records: 'No finished challenges yet.',
    cx_live_n: '{n} live',
    cx_res_won: 'Won vs {name}',
    cx_res_lost: 'Lost vs {name}',
    cx_res_draw: 'Draw vs {name}',
    cx_res_done: 'Finished vs {name}',
    cx_res_expired: 'Expired vs {name}',
    cx_quit_them: 'they quit',
    cx_quit_me: 'you quit',
    cx_vs_record: 'Your record vs {name}',
    cx_challenge_them: 'Challenge {name}',
    cx_live_with: 'Live with {name}',
    cx_pick_person: 'Who do you want to challenge?',
    cx_search: 'Search names',
    cx_no_people: 'Nobody found.',
    cx_pick_game: 'Challenge {name} at…',
    cx_someone: 'Someone',
    cx_game_of: 'Game {n} of {m}',
    cx_straight_up: 'Straight up',
    cx_all_machines: 'All machines',
    cx_n_games: '{n} games',
    cx_cricket: 'Cricket',
    cx_cricket_order: 'Cricket in order',
  },
  es: {
    cx_title: 'Retos',
    cx_close: 'Cerrar',
    cx_back: 'Atrás',
    cx_loading: 'Cargando…',
    cx_no_code: 'Primero crea tu perfil y luego podrás retar a la gente.',
    cx_tab_live: 'En juego',
    cx_tab_records: 'Historial',
    cx_new: 'Nuevo reto',
    cx_your_turn: 'Tu turno',
    cx_their_turn: 'Su turno',
    cx_play: 'Jugar',
    cx_waiting_on: 'Esperando a {name}',
    cx_none_live: 'No tienes retos en juego. ¡Empieza uno!',
    cx_failed: 'No se pudo cargar: {games}. Revisa la conexión.',
    cx_record: 'Tu historial',
    cx_won: 'Ganados',
    cx_lost: 'Perdidos',
    cx_drawn: 'Empates',
    cx_wld: '{w} G · {l} P',
    cx_wld_d: '{w} G · {l} P · {d} E',
    cx_by_game: 'Por juego',
    cx_by_player: 'Por jugador',
    cx_recent: 'Resultados recientes',
    cx_no_records: 'Aún no has terminado ningún reto.',
    cx_live_n: '{n} en juego',
    cx_res_won: 'Ganaste a {name}',
    cx_res_lost: 'Perdiste con {name}',
    cx_res_draw: 'Empate con {name}',
    cx_res_done: 'Terminado con {name}',
    cx_res_expired: 'Caducado con {name}',
    cx_quit_them: 'se rindió',
    cx_quit_me: 'te rendiste',
    cx_vs_record: 'Tu historial contra {name}',
    cx_challenge_them: 'Retar a {name}',
    cx_live_with: 'En juego con {name}',
    cx_pick_person: '¿A quién quieres retar?',
    cx_search: 'Buscar nombres',
    cx_no_people: 'No se encontró a nadie.',
    cx_pick_game: 'Retar a {name} a…',
    cx_someone: 'Alguien',
    cx_game_of: 'Partida {n} de {m}',
    cx_straight_up: 'Sin ayudas',
    cx_all_machines: 'Todas las máquinas',
    cx_n_games: '{n} partidas',
    cx_cricket: 'Cricket',
    cx_cricket_order: 'Cricket en orden',
  },
};

export default STRINGS;
