// js/strings.js — the ONE shared dictionary for hub chrome + the My Stats / Leaderboards /
// profile-page / add-to-home-screen surfaces. One file because these change together and
// precache as one asset (see HANDOFF-I18N-EXTRACTION.md, decision 2). Keys are prefixed by
// surface: hub_ (hub.js), gs_ (My Stats), lb_ (Leaderboards), pf_ (profile page), a2hs_
// (add-to-home-screen sheet).
//
// English is the source of truth: every key exists in `en`; `es` may lag (js/i18n.js's
// fallback shows English for anything missing, so partial translation can never break a
// screen). Spanish drafted by a working session; native-speaker review welcome — corrections
// are one-line edits here, nothing else moves.
//
// Per-game hub card blurbs are NOT here — they live as {en, es} objects on each GAMES entry
// in js/hub.js (decision 3: registry data stays co-located with its entry).

export const STRINGS = {
  en: {
    hub_stats_btn: 'My Stats',
    hub_stats_aria: 'My game stats',
    hub_leaderboard_btn: 'Leaderboards',
    hub_leaderboard_aria: 'Leaderboards',
    hub_profile_btn: 'My Profile',
    hub_back_aria: 'Back to hub',
    hub_challenge_btn: '🎁 Challenge',
    hub_games_aria: 'Games',
    hub_soon_tag: 'Soon',
    hub_test_tag: 'Test',
    hub_fav_add: 'Add {title} to favorites',
    hub_fav_remove: 'Remove {title} from favorites',
    hub_load_error: "Couldn't load {title}. Please try again.",
    hub_confirm_msg: 'Leave this game? Your current progress will be lost.',
    hub_confirm_keep: 'Keep playing',
    hub_confirm_leave: 'Leave game',
    hub_confirm_dialog_aria: 'Leave game',
    hub_fr_dialog_aria: 'Choose a name',
    hub_fr_title: 'Choose a name',
    hub_fr_langrow_aria: 'Language / Idioma',
    hub_fr_name_placeholder: 'Your name',
    hub_fr_save: 'Save',
    hub_fr_or: 'or',
    hub_fr_code_placeholder: 'Enter a code',
    hub_fr_link: 'Link',
    hub_fr_msg_enter_name: 'Enter a name.',
    hub_fr_msg_checking: 'Checking...',
    hub_fr_msg_taken: 'Taken. Use that code instead.',
    hub_fr_msg_invalid_code: 'Invalid code.',
    hub_fr_msg_linking: 'Linking...',
    hub_version_update_aria: 'Update available: {latest}. Tap to update.',
    hub_version_current_aria: 'Version {cur}. Tap to check for updates.',

    pf_title: 'Profile',
    pf_saved: 'Saved',
    pf_you_h: 'You',
    pf_you_emoji_aria: 'Choose your emoji',
    pf_name_label: 'Your name',
    pf_name_placeholder: 'Your name',
    pf_color_summary: 'Preferred color',
    pf_color_yellow: 'Yellow',
    pf_color_blue: 'Blue',
    pf_color_red: 'Red',
    pf_color_green: 'Green',
    pf_color_none: 'No preference',
    pf_sync_h: 'Sync devices',
    pf_code_aria: 'Your code',
    pf_copy_btn: 'Copy',
    pf_code_placeholder: 'Enter a code',
    pf_link_btn: 'Link',
    pf_customize_summary: 'Customize Computer Players',
    pf_add_opp_btn: '+ Add opponent',
    pf_opp_placeholder: 'Computer {n}',
    pf_opp_emoji_aria: 'Choose opponent emoji',
    pf_skill_aria: 'Skill for {name}',
    pf_skill_beginner: 'Beginner',
    pf_skill_intermediate: 'Intermediate',
    pf_skill_pro: 'Pro',
    pf_remove_opp_aria: 'Remove opponent',
    pf_devdetails_btn: 'Device details',
    pf_reset_btn: 'Reset profile',
    pf_emoji_modal_h: 'Choose an emoji',
    pf_close_aria: 'Close',
    pf_reset_dialog_aria: 'Reset profile',
    pf_reset_confirm_msg: 'Reset your profile? This deletes your name, emoji, color, and opponents on this device.',
    pf_reset_keep: 'Keep it',
    pf_devdetails_dialog_aria: 'Device details',
    pf_dev_gathering: 'Gathering...',
    pf_dev_gathering_full: 'Gathering device details...',
    pf_dev_gather_err: 'Could not gather device details: {msg}',
    pf_dev_noname: '(no name set)',
    pf_dev_sending: 'Sending to Matt...',
    pf_dev_sent_ok: 'Sent ✓ — nothing more to do here.',
    pf_dev_send_err: 'Could not send ({reason}) — shown below, still saved on this device only.',
    pf_msg_checking: 'Checking...',
    pf_msg_taken: "Taken. Enter that player's code to use it.",
    pf_msg_copied: 'Copied {code}',
    pf_msg_longpress: 'Long-press the code to copy.',
    pf_msg_invalid_code: 'Invalid code.',
    pf_msg_already_linked: 'Already linked to that code.',
    pf_msg_linking: 'Linking...',
    pf_msg_linked: 'Linked to {code}. Stats will combine.',
  },
  es: {
    hub_stats_btn: 'Mis estadísticas',
    hub_stats_aria: 'Mis estadísticas de juego',
    hub_leaderboard_btn: 'Clasificación',
    hub_leaderboard_aria: 'Clasificación',
    hub_profile_btn: 'Mi perfil',
    hub_back_aria: 'Volver al hub',
    hub_challenge_btn: '🎁 Desafío',
    hub_games_aria: 'Juegos',
    hub_soon_tag: 'Pronto',
    hub_test_tag: 'Prueba',
    hub_fav_add: 'Añadir {title} a favoritos',
    hub_fav_remove: 'Quitar {title} de favoritos',
    hub_load_error: 'No se pudo cargar {title}. Inténtalo de nuevo.',
    hub_confirm_msg: '¿Salir de esta partida? Se perderá tu progreso actual.',
    hub_confirm_keep: 'Seguir jugando',
    hub_confirm_leave: 'Salir de la partida',
    hub_confirm_dialog_aria: 'Salir de la partida',
    hub_fr_dialog_aria: 'Elige un nombre',
    hub_fr_title: 'Elige un nombre',
    hub_fr_langrow_aria: 'Language / Idioma',
    hub_fr_name_placeholder: 'Tu nombre',
    hub_fr_save: 'Guardar',
    hub_fr_or: 'o',
    hub_fr_code_placeholder: 'Introduce un código',
    hub_fr_link: 'Vincular',
    hub_fr_msg_enter_name: 'Introduce un nombre.',
    hub_fr_msg_checking: 'Comprobando...',
    hub_fr_msg_taken: 'Ya está en uso. Usa ese código en su lugar.',
    hub_fr_msg_invalid_code: 'Código no válido.',
    hub_fr_msg_linking: 'Vinculando...',
    hub_version_update_aria: 'Actualización disponible: {latest}. Toca para actualizar.',
    hub_version_current_aria: 'Versión {cur}. Toca para buscar actualizaciones.',

    pf_title: 'Perfil',
    pf_saved: 'Guardado',
    pf_you_h: 'Tú',
    pf_you_emoji_aria: 'Elige tu emoji',
    pf_name_label: 'Tu nombre',
    pf_name_placeholder: 'Tu nombre',
    pf_color_summary: 'Color preferido',
    pf_color_yellow: 'Amarillo',
    pf_color_blue: 'Azul',
    pf_color_red: 'Rojo',
    pf_color_green: 'Verde',
    pf_color_none: 'Sin preferencia',
    pf_sync_h: 'Sincronizar dispositivos',
    pf_code_aria: 'Tu código',
    pf_copy_btn: 'Copiar',
    pf_code_placeholder: 'Introduce un código',
    pf_link_btn: 'Vincular',
    pf_customize_summary: 'Personalizar jugadores del ordenador',
    pf_add_opp_btn: '+ Añadir rival',
    pf_opp_placeholder: 'Ordenador {n}',
    pf_opp_emoji_aria: 'Elige el emoji del rival',
    pf_skill_aria: 'Nivel de {name}',
    pf_skill_beginner: 'Principiante',
    pf_skill_intermediate: 'Intermedio',
    pf_skill_pro: 'Pro',
    pf_remove_opp_aria: 'Quitar rival',
    pf_devdetails_btn: 'Detalles del dispositivo',
    pf_reset_btn: 'Restablecer perfil',
    pf_emoji_modal_h: 'Elige un emoji',
    pf_close_aria: 'Cerrar',
    pf_reset_dialog_aria: 'Restablecer perfil',
    pf_reset_confirm_msg: '¿Restablecer tu perfil? Esto borra tu nombre, emoji, color y rivales en este dispositivo.',
    pf_reset_keep: 'Mantenerlo',
    pf_devdetails_dialog_aria: 'Detalles del dispositivo',
    pf_dev_gathering: 'Recopilando...',
    pf_dev_gathering_full: 'Recopilando detalles del dispositivo...',
    pf_dev_gather_err: 'No se pudieron recopilar los detalles del dispositivo: {msg}',
    pf_dev_noname: '(sin nombre configurado)',
    pf_dev_sending: 'Enviando a Matt...',
    pf_dev_sent_ok: 'Enviado ✓: no hay nada más que hacer aquí.',
    pf_dev_send_err: 'No se pudo enviar ({reason}). Se muestra abajo; sigue guardado solo en este dispositivo.',
    pf_msg_checking: 'Comprobando...',
    pf_msg_taken: 'Ya está en uso. Introduce el código de ese jugador para usarlo.',
    pf_msg_copied: 'Copiado {code}',
    pf_msg_longpress: 'Mantén pulsado el código para copiarlo.',
    pf_msg_invalid_code: 'Código no válido.',
    pf_msg_already_linked: 'Ya está vinculado a ese código.',
    pf_msg_linking: 'Vinculando...',
    pf_msg_linked: 'Vinculado a {code}. Las estadísticas se combinarán.',
  },
};

export default STRINGS;
