// js/strings.js — the ONE shared dictionary for hub chrome + the My Stats / Leaderboards /
// profile-page / add-to-home-screen surfaces. One file because these change together and
// precache as one asset (see HANDOFF-I18N-EXTRACTION.md, decision 2). Keys are prefixed by
// surface: hub_ (hub.js), gs_ (My Stats), lb_ (Leaderboards), pf_ (profile page), a2hs_
// (add-to-home-screen sheet).
//
// English is the source of truth: every key exists in `en`; `es` may lag (js/i18n.js's
// fallback shows English for anything missing, so partial translation can never break a
// screen). Spanish drafted by a working session; native-speaker review welcome — corrections
// are one-line edits here, nothing else moves.
//
// Per-game hub card blurbs are NOT here — they live as {en, es} objects on each GAMES entry
// in js/hub.js (decision 3: registry data stays co-located with its entry).

export const STRINGS = {
  en: {
    hub_stats_btn: 'My Stats',
    hub_stats_aria: 'My game stats',
    hub_leaderboard_btn: 'Leaderboards',
    hub_leaderboard_aria: 'Leaderboards',
    hub_profile_btn: 'My Profile',
    hub_back_aria: 'Back to hub',
    hub_challenge_btn: '🎁 Challenge',
    hub_games_aria: 'Games',
    hub_soon_tag: 'Soon',
    hub_test_tag: 'Test',
    hub_new_tag: 'New',
    hub_new_aria: 'New game',
    hub_fav_add: 'Add {title} to favorites',
    hub_fav_remove: 'Remove {title} from favorites',
    hub_fav_reorder: 'Reorder',
    hub_fav_done: 'Done',
    hub_all_games: 'All games',
    hub_fav_move_up: 'Move {title} up',
    hub_fav_move_down: 'Move {title} down',
    hub_load_error: "Couldn't load {title}. Please try again.",
    hub_confirm_msg: 'Leave this game? Your current progress will be lost.',
    hub_confirm_keep: 'Keep playing',
    hub_confirm_leave: 'Leave game',
    hub_confirm_dialog_aria: 'Leave game',
    hub_fr_dialog_aria: 'Choose a name',
    hub_fr_title: 'Choose a name',
    hub_fr_lead: 'Your name goes on the leaderboard with every game you play.',
    hub_fr_langrow_aria: 'Language / Idioma',
    hub_fr_name_placeholder: 'Your name',
    hub_fr_save: 'Save',
    hub_fr_or: 'or',
    hub_fr_code_placeholder: 'Enter a code',
    hub_fr_link: 'Link',
    hub_fr_msg_enter_name: 'Enter a name.',
    hub_fr_msg_checking: 'Checking...',
    hub_fr_msg_taken: 'Taken. Use that code instead.',
    hub_fr_msg_invalid_code: 'Invalid code.',
    hub_fr_msg_linking: 'Linking...',
    hub_fr_msg_placeholder_name: 'Please enter your real name.',
    hub_fr_msg_code_unknown: 'No player found for that code. Check it, or enter a name instead.',
    hub_version_update_aria: 'Update available: {latest}. Tap to update.',
    hub_version_current_aria: 'Version {cur}. Tap to check for updates.',
    hub_version_checking: 'Checking…',
    hub_version_up_to_date: 'Up to date',
    hub_theme_toggle_aria: 'Theme: {mode}. Tap to change.',
    hub_theme_light: 'Light',
    hub_theme_dark: 'Dark',
    hub_theme_auto: 'Auto',

    pf_title: 'Profile',
    pf_saved: 'Saved',
    pf_you_h: 'You',
    pf_you_emoji_aria: 'Choose your emoji',
    pf_name_label: 'Your name',
    pf_name_placeholder: 'Your name',
    pf_msg_label: 'Message for other players',
    pf_msg_placeholder: 'Shown when someone opens your profile',
    pf_color_summary: 'Preferred color',
    pf_color_yellow: 'Yellow',
    pf_color_blue: 'Blue',
    pf_color_red: 'Red',
    pf_color_green: 'Green',
    pf_color_none: 'No preference',
    pf_theme_h: 'Theme',
    pf_quickchat_summary: 'Quick chat',
    pf_quickchat_hint: 'Pick the reactions you send during multiplayer games. Your choices show for you only.',
    pf_quickchat_emojis: 'Emojis',
    pf_quickchat_phrases: 'Phrases',
    pf_quickchat_custom: 'Your own phrases',
    pf_quickchat_custom_ph: 'Type a phrase',
    pf_sync_h: 'Sync devices',
    pf_code_aria: 'Your code',
    pf_copy_btn: 'Copy',
    pf_code_placeholder: 'Enter a code',
    pf_link_btn: 'Link',
    pf_customize_summary: 'Customize Computer Players',
    pf_add_opp_btn: '+ Add opponent',
    pf_opp_placeholder: 'Computer {n}',
    pf_opp_emoji_aria: 'Choose opponent emoji',
    pf_skill_aria: 'Skill for {name}',
    pf_skill_beginner: 'Easy',
    pf_skill_intermediate: 'Medium',
    pf_skill_pro: 'Hard',
    pf_remove_opp_aria: 'Remove opponent',
    pf_reset_btn: 'Reset profile',
    pf_emoji_modal_h: 'Choose an emoji',
    pf_close_aria: 'Close',
    pf_reset_dialog_aria: 'Reset profile',
    pf_reset_confirm_msg: 'Reset your profile? This deletes your name, emoji, color, and opponents on this device.',
    pf_reset_keep: 'Keep it',
    pf_msg_checking: 'Checking...',
    pf_msg_taken: "Taken. Enter that player's code to use it.",
    pf_msg_copied: 'Copied {code}',
    pf_msg_longpress: 'Long-press the code to copy.',
    pf_msg_invalid_code: 'Invalid code.',
    pf_msg_already_linked: 'Already linked to that code.',
    pf_msg_linking: 'Linking...',
    pf_msg_linked: 'Linked to {code}. Stats will combine.',

    // Report a bug (js/bug-report-ui.js) + the one-time announcement that introduces it.
    // The announcement's own title and body are NOT here: they live as {en, es} on their entry in
    // js/announce.js, the same way a game's card blurb lives on its GAMES entry (decision 3,
    // HANDOFF-I18N-EXTRACTION.md - registry data stays co-located with its entry).
    bug_btn: '🐞 Report a bug',
    bug_btn_aria: 'Report a bug',
    bug_title: 'Report a bug',
    bug_dialog_aria: 'Report a bug',
    bug_where_label: 'What game?',
    bug_where_placeholder: 'Select one',
    bug_where_hub_group: 'Game Hub',
    bug_where_hub: 'Game Hub',
    bug_where_games: 'Games',
    bug_what_label: 'What went wrong?',
    bug_what_placeholder: 'What were you doing, and what happened?',
    bug_shots_label: 'Screenshots (optional)',
    bug_add_shot: '+ Add a screenshot',
    bug_shot_remove: 'Remove screenshot {n}',
    bug_shots_full: 'Up to {n} screenshots.',
    bug_shot_too_big: 'That picture is too big. A screenshot usually works.',
    bug_shot_err: 'Could not use that image: {msg}',
    bug_need_text: 'Say what went wrong first.',
    bug_sending: 'Sending...',
    bug_send: 'Send report',
    bug_cancel: 'Cancel',
    bug_close: 'Close',
    bug_done: 'Done',
    bug_sent_title: 'Sent. Thank you!',
    bug_sent_body: "I'll work on it and let you know when I need you to test it.",
    bug_sent_no_shots: 'Sent, but the screenshots would not upload.',
    bug_queued_title: 'Saved on this device',
    bug_queued_body: 'No connection right now. It sends itself next time you open the hub online.',
    bug_queued_no_shots: 'No room to keep the screenshots, so only your description is waiting.',
    bug_failed_title: 'Could not send it yet',
    bug_failed_body: 'Saved on this device; it will try again on its own. ({reason})',
    bug_pending_one: '1 earlier report is still waiting to send.',
    bug_pending_many: '{n} earlier reports are still waiting to send.',
    // --- Admin control page (Matt only; js/admin-ui.js over js/admin-config.js) ---
    adm_btn: '🛠️ Admin',
    adm_title: 'Admin controls',
    adm_close: 'Close',
    adm_loading: 'Loading the current settings...',
    adm_lead: 'These switches apply to every device in the family. Other phones pick them up the next time they open the hub.',
    adm_offline: "Offline: showing the last known settings. Changes need a connection.",
    adm_games_title: 'Games',
    adm_games_note: 'Live shows the game on everyone\u2019s launcher. Admin only keeps it to you and the tester for testing. Nobody\u2019s stats are touched either way.',
    adm_live: 'Live',
    adm_testing: 'Admin only',
    adm_default: 'Default',
    adm_game_default: 'App default: {state}.',
    adm_game_override: 'Set by you. App default: {state}.',
    adm_skeeball_title: 'Skeeball machines',
    adm_skeeball_note: 'Open plays right away. Unlockable is live, earned the normal way. Testing means nobody but you can play it yet. None of these ever takes away a machine somebody already unlocked.',
    adm_mode_open: 'Open',
    adm_mode_unlockable: 'Unlockable',
    adm_mode_testing: 'Testing',
    adm_machine_first: 'Always open (the first machine).',
    adm_machine_open_note: 'Everyone can play it now, no unlock needed.',
    adm_machine_unlockable_note: 'Live: everyone can earn it the normal way.',
    adm_machine_testing_note: 'Not playable yet, except by you.',
    adm_machine_mine: 'You have unlocked it.',
    adm_device_title: 'This device',
    adm_device_note: 'Local only. Nothing here changes what anyone else sees.',
    adm_update: 'Check for update',
    adm_updating: 'Checking...',
    adm_inbox: 'Bug reports',
    adm_announce_reset: 'Show announcements again',
    adm_announce_done: 'Announcements will show again on this device.',
    adm_copy_id: 'Copy device id',
    adm_copied: 'Copied.',
    adm_device_id: 'Device id: {id}',
    adm_devwrites_on: 'Allow writes from this dev server',
    adm_devwrites_off: 'Block writes from this dev server',
    adm_devwrites_now_on: 'This browser may now write to the family database.',
    adm_devwrites_now_off: 'Writes from this dev server are blocked again.',
    adm_saving: 'Saving...',
    adm_saved: 'Saved.',
    adm_save_failed: "Didn't save: {why}",
    // Admin inbox (Matt only)
    bug_inbox_btn: '🐞 Bug reports',
    bug_inbox_btn_new: '🐞 Bug reports ({n} new)',
    bug_inbox_title: 'Bug reports',
    bug_inbox_dialog_aria: 'Bug reports inbox',
    bug_inbox_loading: 'Loading...',
    bug_inbox_empty: 'No bug reports yet.',
    bug_inbox_offline: 'The inbox needs a connection.',
    bug_inbox_back: '← All reports',
    bug_inbox_shots: 'Screenshots',
    bug_inbox_details: 'Full report (JSON)',
    bug_inbox_copy: 'Copy full report',
    bug_inbox_copied: 'Copied.',
    bug_inbox_copy_err: 'Could not copy. The full report is shown below.',
    bug_inbox_mark_done: 'Mark as done',
    bug_inbox_reopen: 'Reopen',
    bug_inbox_new_tag: 'New',
    bug_inbox_done_tag: 'Done',
    bug_inbox_no_shots: 'No screenshots attached.',
    bug_inbox_preview: '👀 Preview the announcement',
    bug_inbox_replied_tag: 'replied',
    bug_inbox_all_done: 'Nothing waiting on you.',
    bug_inbox_show_done: 'Show done ({n})',
    bug_inbox_hide_done: 'Hide done ({n})',
    bug_inbox_delete: 'Delete',
    bug_inbox_delete_confirm: 'Delete, really?',
    bug_inbox_delete_note: 'This clears it from your inbox. Their copy of any reply stays.',
    bug_inbox_deleted: 'Deleted.',
    bug_inbox_undo: 'Undo',
    // --- replying (admin side) ---
    bug_reply_title: 'Reply',
    bug_reply_again: 'Reply again',
    bug_reply_placeholder: 'Tell them what happened, and what you did about it.',
    bug_reply_send: 'Send reply',
    bug_reply_sending: 'Sending...',
    bug_reply_empty: 'Write something first.',
    bug_reply_ok: 'Sent. They will see a badge on their profile.',
    bug_reply_failed: 'Could not send. Check your connection and try again.',
    bug_reply_undeliverable: 'Saved on the report, but this one has no device id, so they will not be notified.',
    bug_reply_sent_at: 'You replied, {when}',
    // --- the player's own side ---
    bug_mine_title: 'Replies to your reports',
    bug_mine_dialog_aria: 'Replies to your bug reports',
    bug_mine_btn: '📬 Replies to your reports',
    bug_mine_btn_new: '📬 Replies to your reports ({n} new)',
    bug_mine_from: 'Matt replied, {when}',
    bug_mine_empty: 'No replies yet. Anything you report shows up here once it is answered.',
    bug_mine_offline: 'Could not check for replies. You are offline.',
    ann_dialog_aria: 'Announcement',
    ann_dismiss: 'Got it',

    gs_title: 'Game Stats',
    gs_dialog_aria: 'Game stats',
    gs_close_aria: 'Close',
    gs_tabs_aria: 'Choose a game',
    gs_wins: 'Wins',
    gs_losses: 'Losses',
    gs_plays: 'Plays',
    gs_win_rate: 'Win rate',
    gs_total_games: 'Games played',
    gs_col_wl: 'W-L',
    gs_won: 'Won',
    gs_lost: 'Lost',
    gs_tied: 'Tied',
    gs_played: 'Played',
    gs_best: 'Best',
    gs_runs: 'Runs',
    gs_empty: 'No {label} games recorded yet.',
    gs_diff_table_h: 'Record by difficulty',
    gs_diff_beginner: 'Easy',
    gs_diff_intermediate: 'Medium',
    gs_diff_pro: 'Hard',
    gs_diff_expert: 'Expert',
    gs_diff_mp: 'Multiplayer',
    gs_diff_legacy: 'Earlier games',
    gs_diff_easy: 'Easy',
    gs_diff_medium: 'Medium',
    gs_diff_hard: 'Hard',
    gs_c4_player_first: 'Player first move',
    gs_c4_computer_first: 'Computer first move',
    gs_cc_games_played: 'Games played',
    gs_cc_finished: 'Finished games',
    gs_cc_victories: 'Victories',
    gs_cc_draws: 'Draws',
    gs_cc_defeats: 'Defeats',
    gs_cc_stats_h: 'Stats',
    gs_cc_closed: 'Total closed by you',
    gs_cc_minus_ten: 'Total minus ten',
    gs_cc_chinchons: 'Total chinchóns',
    gs_nb_solved: 'Levels solved',
    gs_nb_best: 'Best level',
    gs_nb_moves: 'Total moves',
    gs_nb_avg_moves: 'Avg moves',
    gs_es_escobas: 'Escobas made',
    gs_br_best: 'Best obstacles passed',
    gs_br_best_by_diff: 'Best obstacles passed by difficulty',
    gs_br_best_by_diff_classic: 'Best obstacles passed by difficulty (Classic)',
    gs_br_best_by_diff_orbital: 'Best obstacles passed by difficulty (Orbital)',
    gs_br_legacy_h: 'Best distance, before scoring changed to obstacles',
    gs_br_obstacles_cell: '{n} obstacles',
    gs_tt_classic: 'Classic',
    gs_tt_ultimate: 'Ultimate',
    gs_db_boxes: 'Boxes claimed',
    gs_db_chain: 'Longest chain',
    gs_bg_best_score: 'Best score',
    gs_bg_words: 'Words found',
    gs_bg_longest: 'Longest word',
    gs_yz_yahtzees: 'Yahtzees',
    gs_yz_best: 'Best score',
    gs_dm_rounds: 'Rounds played',
    gs_dm_best_round: 'Best round',
    gs_dm_points: 'Points scored',
    gs_sn_longest: 'Longest snake',
    gs_sn_longest_by_diff: 'Longest snake by difficulty',
    gs_sn_walls_on: 'Walls on',
    gs_sn_walls_off: 'Walls off',
    gs_hc_furthest: 'Furthest',
    gs_pb_best: 'Best score',
    gs_pb_bestball: 'Best ball',
    gs_pb_avg: 'Average',
    gs_pb_missions: 'Missions',
    gs_pb_multiballs: 'Multiballs',
    gs_pb_jackpots: 'Jackpots',
    gs_pb_ramps: 'Ramps',
    gs_pb_by_table: 'Games by table',
    gs_pb_casual: 'Casual',
    gs_pb_standard: 'Standard',
    gs_pb_tournament: 'Tournament',
    gs_hc_coins: 'Coins earned',
    gs_hc_flips: 'Flips',
    gs_hc_by_stage: 'Furthest by stage',
    gs_hc_countryside: 'Countryside',
    gs_hc_desert: 'Desert',
    gs_hc_arctic: 'Arctic',
    gs_hc_moon: 'Moon',
    gs_bs_wins: 'Wins',
    gs_bs_losses: 'Losses',
    gs_bs_shots: 'Shots fired',
    gs_bs_hit_rate: 'Hit rate',
    gs_bs_ships_sunk: 'Ships sunk',
    gs_bs_fewest_shots: 'Fewest shots to win',
    gs_sk_wins: 'Wins',
    gs_sk_losses: 'Losses',
    gs_sk_best_game: 'Best game',
    gs_sk_best_throw: 'Best throw',
    gs_sk_hundreds: '100 cups',
    gs_sk_fifties: '50s',
    gs_sk_balls: 'Balls thrown',
    gs_sk_points: 'Lifetime points',
    gs_sk_by_board: 'By machine',
    gs_sk_today: 'Today',
    gs_sk_days: 'Days played',
    gs_sk_board_classic: 'Classic',
    gs_sk_board_stars: 'Star Alley',
    gs_bs_no_wins_yet: 'Not yet',

    lb_title: 'Leaderboard',
    lb_dialog_aria: 'Leaderboard',
    lb_segs_aria: 'By player or by game',
    lb_by_player: 'By Player',
    lb_by_game: 'By Game',
    lb_unrated: 'Unrated',
    lb_unnamed_player: 'Unnamed player',
    lb_diff_filter_aria: 'Filter by difficulty',
    lb_diff_all: 'All',
    lb_filter_label: 'Filter by difficulty:',
    lb_sort_label: 'Sort by:',
    lb_sort_aria: 'Sort players',
    lb_sort_alpha: 'Alphabetical',
    lb_sort_played: 'Games Played',
    lb_sort_wins: 'Wins',
    lb_sort_points: 'Points',
    lb_sort_obstacles: 'Obstacles',
    lb_sort_longest: 'Longest',
    lb_sort_solved: 'Solved',
    lb_sort_meters: 'Distance',
    lb_played_count: '{n} played',
    lb_wins_count: '{n} wins',
    lb_wins_unit: 'wins',
    // The multiplayer chip on a game's own leaderboard board (2026-08-11): the short tag in the
    // chip; the full "Multiplayer" label (gs_diff_mp) is its tooltip.
    lb_mp_short: 'MP',
    lb_games_count: '{n} games',
    lb_unit_wins: 'wins',
    lb_unit_obstacles: 'obstacles',
    lb_unit_longest: 'longest',
    lb_unit_solved: 'solved',
    lb_unit_meters: 'meters',
    lb_unit_points: 'points',
    lb_runs_count: '{n} runs',
    lb_empty_all: 'No games recorded yet.',
    lb_no_games_yet: 'No games yet',
    lb_empty_game: 'No {label} games recorded yet.',
    lb_who_leads_h: 'Who leads what',
    lb_back_players: '&larr; Players',
    lb_back_game: '&larr; {title}',
    lb_tt_ultimate: 'Ultimate',
    lb_tt_classic: 'Classic',
    lb_sn_walls_on: 'Walls on',
    lb_sn_walls_off: 'Walls off',
    game_title_ballrun: 'Ball Run',
    game_title_boggle: 'Boggle',
    game_title_business: 'Monopoly Deal',
    game_title_chinchon: 'Chinchón',
    game_title_connect4: 'Connect 4',
    game_title_dotsboxes: 'Dots and Boxes',
    game_title_escoba: 'Escoba',
    game_title_filler: 'Filler',
    game_title_mancala: 'Mancala',
    game_title_nutsbolts: 'Nuts & Bolts',
    game_title_parchis: 'Parchís',
    game_title_snake: 'Snake',
    game_title_tictactoe: 'Tic Tac Toe',
    game_title_uno: 'Uno',
    game_title_pool: 'Pool',
    game_title_poolv2: 'Pool (retired build)',
    game_title_yahtzee: 'Yahtzee',
    game_title_dominoes: 'Dominoes',
    game_title_hillclimb: 'Hill Climb',
    game_title_battleship: 'Battleship',
    game_title_skeeball: 'Skeeball',
    game_title_pinball: 'Pinball',
    lb_offline: 'The leaderboard needs a connection. It lights up when you are online.',
    lb_back_games: '&larr; Games',
    lb_loading_aria: 'Loading standings',
    lb_tex_wins_first: 'Wins going first',
    lb_tex_wins_second: 'Wins going second',
    lb_tex_chinchons: 'Chinchóns',
    lb_tex_closes: 'Closes',
    lb_tex_minus_tens: 'Minus tens',
    lb_tex_escobas: 'Escobas',
    lb_tex_best_level: 'Best level',
    lb_tex_levels_solved: 'Levels solved',
    lb_tex_best_obstacles: 'Best obstacles',
    lb_tex_total_runs: 'Total runs',
    lb_tex_boxes_claimed: 'Boxes claimed',
    lb_tex_longest_chain: 'Longest chain',
    lb_tex_best_score: 'Best score',
    lb_tex_words_found: 'Words found',
    lb_tex_longest_word: 'Longest word',
    lb_tex_longest_snake: 'Longest snake',
    lb_tex_furthest_drive: 'Furthest drive',
    lb_tex_hc_coins: 'Coins earned',
    lb_tex_hc_flips: 'Flips landed',
    lb_tex_sk_best_game: 'Best game',
    lb_tex_sk_best_throw: 'Best throw',
    lb_tex_sk_hundreds: '100 cups hit',
    lb_tex_sk_points: 'Points all time',
    lb_tex_sk_sweeps: 'All 4 colors',
    lb_tex_classic_played: 'Classic played',
    lb_tex_ultimate_played: 'Ultimate played',
    lb_tex_draws: 'Draws',
  },
  es: {
    hub_stats_btn: 'Mis estadísticas',
    hub_stats_aria: 'Mis estadísticas de juego',
    hub_leaderboard_btn: 'Clasificación',
    hub_leaderboard_aria: 'Clasificación',
    hub_profile_btn: 'Mi perfil',
    hub_back_aria: 'Volver al hub',
    hub_challenge_btn: '🎁 Desafío',
    hub_games_aria: 'Juegos',
    hub_soon_tag: 'Pronto',
    hub_test_tag: 'Prueba',
    hub_new_tag: 'Nuevo',
    hub_new_aria: 'Juego nuevo',
    hub_fav_add: 'Añadir {title} a favoritos',
    hub_fav_remove: 'Quitar {title} de favoritos',
    hub_fav_reorder: 'Reordenar',
    hub_fav_done: 'Listo',
    hub_all_games: 'Todos los juegos',
    hub_fav_move_up: 'Subir {title}',
    hub_fav_move_down: 'Bajar {title}',
    hub_load_error: 'No se pudo cargar {title}. Inténtalo de nuevo.',
    hub_confirm_msg: '¿Salir de esta partida? Se perderá tu progreso actual.',
    hub_confirm_keep: 'Seguir jugando',
    hub_confirm_leave: 'Salir de la partida',
    hub_confirm_dialog_aria: 'Salir de la partida',
    hub_fr_dialog_aria: 'Elige un nombre',
    hub_fr_title: 'Elige un nombre',
    hub_fr_lead: 'Tu nombre aparece en la clasificación con cada partida que juegas.',
    hub_fr_langrow_aria: 'Language / Idioma',
    hub_fr_name_placeholder: 'Tu nombre',
    hub_fr_save: 'Guardar',
    hub_fr_or: 'o',
    hub_fr_code_placeholder: 'Introduce un código',
    hub_fr_link: 'Vincular',
    hub_fr_msg_enter_name: 'Introduce un nombre.',
    hub_fr_msg_checking: 'Comprobando...',
    hub_fr_msg_taken: 'Ya está en uso. Usa ese código en su lugar.',
    hub_fr_msg_invalid_code: 'Código no válido.',
    hub_fr_msg_linking: 'Vinculando...',
    hub_fr_msg_placeholder_name: 'Introduce tu nombre real.',
    hub_fr_msg_code_unknown: 'No hay ningún jugador con ese código. Compruébalo o introduce un nombre.',
    hub_version_update_aria: 'Actualización disponible: {latest}. Toca para actualizar.',
    hub_version_current_aria: 'Versión {cur}. Toca para buscar actualizaciones.',
    hub_version_checking: 'Comprobando…',
    hub_version_up_to_date: 'Actualizado',
    hub_theme_toggle_aria: 'Tema: {mode}. Toca para cambiar.',
    hub_theme_light: 'Claro',
    hub_theme_dark: 'Oscuro',
    hub_theme_auto: 'Automático',

    pf_title: 'Perfil',
    pf_saved: 'Guardado',
    pf_you_h: 'Tú',
    pf_you_emoji_aria: 'Elige tu emoji',
    pf_name_label: 'Tu nombre',
    pf_name_placeholder: 'Tu nombre',
    pf_msg_label: 'Mensaje para otros jugadores',
    pf_msg_placeholder: 'Se muestra cuando alguien abre tu perfil',
    pf_color_summary: 'Color preferido',
    pf_color_yellow: 'Amarillo',
    pf_color_blue: 'Azul',
    pf_color_red: 'Rojo',
    pf_color_green: 'Verde',
    pf_color_none: 'Sin preferencia',
    pf_theme_h: 'Tema',
    pf_quickchat_summary: 'Chat rápido',
    pf_quickchat_hint: 'Elige las reacciones que envías en las partidas multijugador. Solo las ves tú.',
    pf_quickchat_emojis: 'Emojis',
    pf_quickchat_phrases: 'Frases',
    pf_quickchat_custom: 'Tus propias frases',
    pf_quickchat_custom_ph: 'Escribe una frase',
    pf_sync_h: 'Sincronizar dispositivos',
    pf_code_aria: 'Tu código',
    pf_copy_btn: 'Copiar',
    pf_code_placeholder: 'Introduce un código',
    pf_link_btn: 'Vincular',
    pf_customize_summary: 'Personalizar jugadores del ordenador',
    pf_add_opp_btn: '+ Añadir rival',
    pf_opp_placeholder: 'Ordenador {n}',
    pf_opp_emoji_aria: 'Elige el emoji del rival',
    pf_skill_aria: 'Nivel de {name}',
    pf_skill_beginner: 'Fácil',
    pf_skill_intermediate: 'Normal',
    pf_skill_pro: 'Difícil',
    pf_remove_opp_aria: 'Quitar rival',
    pf_reset_btn: 'Restablecer perfil',
    pf_emoji_modal_h: 'Elige un emoji',
    pf_close_aria: 'Cerrar',
    pf_reset_dialog_aria: 'Restablecer perfil',
    pf_reset_confirm_msg: '¿Restablecer tu perfil? Esto borra tu nombre, emoji, color y rivales en este dispositivo.',
    pf_reset_keep: 'Mantenerlo',
    pf_msg_checking: 'Comprobando...',
    pf_msg_taken: 'Ya está en uso. Introduce el código de ese jugador para usarlo.',
    pf_msg_copied: 'Copiado {code}',
    pf_msg_longpress: 'Mantén pulsado el código para copiarlo.',
    pf_msg_invalid_code: 'Código no válido.',
    pf_msg_already_linked: 'Ya está vinculado a ese código.',
    pf_msg_linking: 'Vinculando...',
    pf_msg_linked: 'Vinculado a {code}. Las estadísticas se combinarán.',

    bug_btn: '🐞 Reportar un fallo',
    bug_btn_aria: 'Reportar un fallo',
    bug_title: 'Reportar un fallo',
    bug_dialog_aria: 'Reportar un fallo',
    bug_where_label: '¿Qué juego?',
    bug_where_placeholder: 'Elige una opción',
    bug_where_hub_group: 'Game Hub',
    bug_where_hub: 'Game Hub',
    bug_where_games: 'Juegos',
    bug_what_label: '¿Qué ha fallado?',
    bug_what_placeholder: '¿Qué estabas haciendo y qué ha pasado?',
    bug_shots_label: 'Capturas de pantalla (opcional)',
    bug_add_shot: '+ Añadir una captura',
    bug_shot_remove: 'Quitar la captura {n}',
    bug_shots_full: 'Hasta {n} capturas.',
    bug_shot_too_big: 'Esa imagen es demasiado grande. Una captura suele funcionar.',
    bug_shot_err: 'No se pudo usar esa imagen: {msg}',
    bug_need_text: 'Cuenta primero qué ha fallado.',
    bug_sending: 'Enviando...',
    bug_send: 'Enviar',
    bug_cancel: 'Cancelar',
    bug_close: 'Cerrar',
    bug_done: 'Listo',
    bug_sent_title: 'Enviado. ¡Gracias!',
    bug_sent_body: 'Me pongo con ello y te aviso cuando necesite que lo pruebes.',
    bug_sent_no_shots: 'Enviado, pero las capturas no se pudieron subir.',
    bug_queued_title: 'Guardado en este dispositivo',
    bug_queued_body: 'Ahora no hay conexión. Se enviará solo la próxima vez que abras el hub con conexión.',
    bug_queued_no_shots: 'No había sitio para guardar las capturas, así que solo espera tu descripción.',
    bug_failed_title: 'Todavía no se ha podido enviar',
    bug_failed_body: 'Guardado en este dispositivo; lo intentará de nuevo solo. ({reason})',
    bug_pending_one: 'Queda 1 reporte anterior por enviar.',
    bug_pending_many: 'Quedan {n} reportes anteriores por enviar.',
    // --- Admin control page (Matt only) ---
    adm_btn: '🛠️ Admin',
    adm_title: 'Controles de admin',
    adm_close: 'Cerrar',
    adm_loading: 'Cargando los ajustes actuales...',
    adm_lead: 'Estos ajustes valen para todos los dispositivos de la familia. Los demás móviles los cogen la próxima vez que abran el hub.',
    adm_offline: 'Sin conexión: se muestran los últimos ajustes conocidos. Para cambiarlos hace falta conexión.',
    adm_games_title: 'Juegos',
    adm_games_note: 'Publicado muestra el juego en el menú de todos. Solo admin lo deja para ti y el tester, para pruebas. En ningún caso se tocan las estadísticas de nadie.',
    adm_live: 'Publicado',
    adm_testing: 'Solo admin',
    adm_default: 'Por defecto',
    adm_game_default: 'Por defecto: {state}.',
    adm_game_override: 'Lo has puesto tú. Por defecto: {state}.',
    adm_skeeball_title: 'Máquinas de Skeeball',
    adm_skeeball_note: 'Abierta se juega ya. Desbloqueable está publicada y se gana jugando. En pruebas quiere decir que todavía no la puede jugar nadie más que tú. Ninguna de las tres le quita una máquina a quien ya la haya desbloqueado.',
    adm_mode_open: 'Abierta',
    adm_mode_unlockable: 'Desbloqueable',
    adm_mode_testing: 'En pruebas',
    adm_machine_first: 'Siempre abierta (la primera máquina).',
    adm_machine_open_note: 'Todos pueden jugarla ya, sin desbloquearla.',
    adm_machine_unlockable_note: 'Publicada: todos pueden ganarla jugando.',
    adm_machine_testing_note: 'Todavía no se puede jugar, salvo tú.',
    adm_machine_mine: 'Tú la tienes desbloqueada.',
    adm_device_title: 'Este dispositivo',
    adm_device_note: 'Solo local. Nada de aquí cambia lo que ven los demás.',
    adm_update: 'Buscar actualización',
    adm_updating: 'Buscando...',
    adm_inbox: 'Reportes de fallos',
    adm_announce_reset: 'Volver a mostrar los avisos',
    adm_announce_done: 'Los avisos volverán a mostrarse en este dispositivo.',
    adm_copy_id: 'Copiar id del dispositivo',
    adm_copied: 'Copiado.',
    adm_device_id: 'Id del dispositivo: {id}',
    adm_devwrites_on: 'Permitir escrituras desde este servidor de pruebas',
    adm_devwrites_off: 'Bloquear escrituras desde este servidor de pruebas',
    adm_devwrites_now_on: 'Este navegador ya puede escribir en la base de datos de la familia.',
    adm_devwrites_now_off: 'Las escrituras desde este servidor de pruebas vuelven a estar bloqueadas.',
    adm_saving: 'Guardando...',
    adm_saved: 'Guardado.',
    adm_save_failed: 'No se ha guardado: {why}',
    bug_inbox_btn: '🐞 Reportes de fallos',
    bug_inbox_btn_new: '🐞 Reportes de fallos ({n} nuevos)',
    bug_inbox_title: 'Reportes de fallos',
    bug_inbox_dialog_aria: 'Bandeja de reportes de fallos',
    bug_inbox_loading: 'Cargando...',
    bug_inbox_empty: 'Todavía no hay reportes.',
    bug_inbox_offline: 'La bandeja necesita conexión.',
    bug_inbox_back: '← Todos los reportes',
    bug_inbox_shots: 'Capturas',
    bug_inbox_details: 'Reporte completo (JSON)',
    bug_inbox_copy: 'Copiar el reporte completo',
    bug_inbox_copied: 'Copiado.',
    bug_inbox_copy_err: 'No se pudo copiar. El reporte completo se muestra abajo.',
    bug_inbox_mark_done: 'Marcar como resuelto',
    bug_inbox_reopen: 'Reabrir',
    bug_inbox_new_tag: 'Nuevo',
    bug_inbox_done_tag: 'Resuelto',
    bug_inbox_no_shots: 'Sin capturas adjuntas.',
    bug_inbox_preview: '👀 Ver el anuncio',
    bug_inbox_replied_tag: 'respondido',
    bug_inbox_all_done: 'No hay nada pendiente.',
    bug_inbox_show_done: 'Ver resueltos ({n})',
    bug_inbox_hide_done: 'Ocultar resueltos ({n})',
    bug_inbox_delete: 'Borrar',
    bug_inbox_delete_confirm: '¿Borrar de verdad?',
    bug_inbox_delete_note: 'Lo quita de tu bandeja. Su copia de la respuesta se queda.',
    bug_inbox_deleted: 'Borrado.',
    bug_inbox_undo: 'Deshacer',
    // --- replying (admin side) ---
    bug_reply_title: 'Responder',
    bug_reply_again: 'Responder otra vez',
    bug_reply_placeholder: 'Cuéntale qué pasaba y qué has hecho.',
    bug_reply_send: 'Enviar respuesta',
    bug_reply_sending: 'Enviando...',
    bug_reply_empty: 'Escribe algo primero.',
    bug_reply_ok: 'Enviado. Le saldrá un aviso en su perfil.',
    bug_reply_failed: 'No se pudo enviar. Revisa la conexión e inténtalo otra vez.',
    bug_reply_undeliverable: 'Guardado en el reporte, pero este no tiene id de dispositivo, así que no le llegará el aviso.',
    bug_reply_sent_at: 'Respondiste, {when}',
    // --- the player's own side ---
    bug_mine_title: 'Respuestas a tus reportes',
    bug_mine_dialog_aria: 'Respuestas a tus reportes de fallos',
    bug_mine_btn: '📬 Respuestas a tus reportes',
    bug_mine_btn_new: '📬 Respuestas a tus reportes ({n} nuevas)',
    bug_mine_from: 'Matt respondió, {when}',
    bug_mine_empty: 'Todavía no hay respuestas. Lo que reportes aparecerá aquí cuando se conteste.',
    bug_mine_offline: 'No se pudo comprobar si hay respuestas. Estás sin conexión.',
    ann_dialog_aria: 'Anuncio',
    ann_dismiss: 'Entendido',

    gs_title: 'Estadísticas de juego',
    gs_dialog_aria: 'Estadísticas de juego',
    gs_close_aria: 'Cerrar',
    gs_tabs_aria: 'Elige un juego',
    gs_wins: 'Victorias',
    gs_losses: 'Derrotas',
    gs_plays: 'Partidas',
    gs_win_rate: 'Tasa de victorias',
    gs_total_games: 'Partidas jugadas',
    gs_col_wl: 'V-D',
    gs_won: 'Ganadas',
    gs_lost: 'Perdidas',
    gs_tied: 'Empatadas',
    gs_played: 'Jugadas',
    gs_best: 'Mejor',
    gs_runs: 'Carreras',
    gs_empty: 'Todavía no hay partidas de {label} registradas.',
    gs_diff_table_h: 'Récord por dificultad',
    gs_diff_beginner: 'Fácil',
    gs_diff_intermediate: 'Normal',
    gs_diff_pro: 'Difícil',
    gs_diff_expert: 'Experto',
    gs_diff_mp: 'Multijugador',
    gs_diff_legacy: 'Partidas anteriores',
    gs_diff_easy: 'Fácil',
    gs_diff_medium: 'Normal',
    gs_diff_hard: 'Difícil',
    gs_c4_player_first: 'Primer movimiento del jugador',
    gs_c4_computer_first: 'Primer movimiento del ordenador',
    gs_cc_games_played: 'Partidas jugadas',
    gs_cc_finished: 'Partidas terminadas',
    gs_cc_victories: 'Victorias',
    gs_cc_draws: 'Empates',
    gs_cc_defeats: 'Derrotas',
    gs_cc_stats_h: 'Estadísticas',
    gs_cc_closed: 'Total cerradas por ti',
    gs_cc_minus_ten: 'Total menos diez',
    gs_cc_chinchons: 'Total de chinchones',
    gs_nb_solved: 'Niveles resueltos',
    gs_nb_best: 'Mejor nivel',
    gs_nb_moves: 'Movimientos totales',
    gs_nb_avg_moves: 'Movimientos promedio',
    gs_es_escobas: 'Escobas hechas',
    gs_br_best: 'Mejor obstáculos superados',
    gs_br_best_by_diff: 'Mejor obstáculos superados por dificultad',
    gs_br_best_by_diff_classic: 'Mejor obstáculos superados por dificultad (Clásico)',
    gs_br_best_by_diff_orbital: 'Mejor obstáculos superados por dificultad (Orbital)',
    gs_br_legacy_h: 'Mejor distancia, antes de que la puntuación cambiara a obstáculos',
    gs_br_obstacles_cell: '{n} obstáculos',
    gs_tt_classic: 'Clásico',
    gs_tt_ultimate: 'Definitivo',
    gs_db_boxes: 'Cajas capturadas',
    gs_db_chain: 'Cadena más larga',
    gs_bg_best_score: 'Mejor puntuación',
    gs_bg_words: 'Palabras encontradas',
    gs_bg_longest: 'Palabra más larga',
    gs_yz_yahtzees: 'Yahtzees',
    gs_yz_best: 'Mejor puntuación',
    gs_dm_rounds: 'Rondas jugadas',
    gs_dm_best_round: 'Mejor ronda',
    gs_dm_points: 'Puntos anotados',
    gs_sn_longest: 'Serpiente más larga',
    gs_sn_longest_by_diff: 'Serpiente más larga por dificultad',
    gs_sn_walls_on: 'Con paredes',
    gs_sn_walls_off: 'Sin paredes',
    gs_hc_furthest: 'Más lejos',
    gs_pb_best: 'Mejor puntuación',
    gs_pb_bestball: 'Mejor bola',
    gs_pb_avg: 'Media',
    gs_pb_missions: 'Misiones',
    gs_pb_multiballs: 'Multibolas',
    gs_pb_jackpots: 'Jackpots',
    gs_pb_ramps: 'Rampas',
    gs_pb_by_table: 'Partidas por mesa',
    gs_pb_casual: 'Tranquila',
    gs_pb_standard: 'Normal',
    gs_pb_tournament: 'Torneo',
    gs_hc_coins: 'Monedas ganadas',
    gs_hc_flips: 'Volteretas',
    gs_hc_by_stage: 'Más lejos por nivel',
    gs_hc_countryside: 'Campo',
    gs_hc_desert: 'Desierto',
    gs_hc_arctic: 'Ártico',
    gs_hc_moon: 'Luna',
    gs_bs_wins: 'Victorias',
    gs_bs_losses: 'Derrotas',
    gs_bs_shots: 'Disparos realizados',
    gs_bs_hit_rate: 'Precisión',
    gs_bs_ships_sunk: 'Barcos hundidos',
    gs_bs_fewest_shots: 'Menos disparos para ganar',
    gs_sk_wins: 'Ganadas',
    gs_sk_losses: 'Perdidas',
    gs_sk_best_game: 'Mejor partida',
    gs_sk_best_throw: 'Mejor lanzamiento',
    gs_sk_hundreds: 'Copas de 100',
    gs_sk_fifties: 'Cincuentas',
    gs_sk_balls: 'Bolas lanzadas',
    gs_sk_points: 'Puntos totales',
    gs_sk_by_board: 'Por máquina',
    gs_sk_today: 'Hoy',
    gs_sk_days: 'Días jugados',
    gs_sk_board_classic: 'Clásica',
    gs_sk_board_stars: 'Pista Estrella',
    gs_bs_no_wins_yet: 'Aún no',

    lb_title: 'Clasificación',
    lb_dialog_aria: 'Clasificación',
    lb_segs_aria: 'Por jugador o por juego',
    lb_by_player: 'Por jugador',
    lb_by_game: 'Por juego',
    lb_unrated: 'Sin calificar',
    lb_unnamed_player: 'Jugador sin nombre',
    lb_diff_filter_aria: 'Filtrar por dificultad',
    lb_diff_all: 'Todas',
    lb_filter_label: 'Filtrar por dificultad:',
    lb_sort_label: 'Ordenar por:',
    lb_sort_aria: 'Ordenar jugadores',
    lb_sort_alpha: 'Alfabético',
    lb_sort_played: 'Partidas jugadas',
    lb_sort_wins: 'Victorias',
    lb_sort_points: 'Puntos',
    lb_sort_obstacles: 'Obstáculos',
    lb_sort_longest: 'Más larga',
    lb_sort_solved: 'Resueltos',
    lb_sort_meters: 'Distancia',
    lb_played_count: '{n} jugadas',
    lb_wins_count: '{n} victorias',
    lb_wins_unit: 'victorias',
    lb_mp_short: 'MP',
    lb_games_count: '{n} partidas',
    lb_unit_wins: 'victorias',
    lb_unit_obstacles: 'obstáculos',
    lb_unit_longest: 'más larga',
    lb_unit_solved: 'resueltos',
    lb_unit_meters: 'metros',
    lb_unit_points: 'puntos',
    lb_runs_count: '{n} carreras',
    lb_empty_all: 'Todavía no hay partidas registradas.',
    lb_no_games_yet: 'Todavía sin partidas',
    lb_empty_game: 'Todavía no hay partidas de {label} registradas.',
    lb_who_leads_h: 'Quién lidera qué',
    lb_back_players: '&larr; Jugadores',
    lb_back_game: '&larr; {title}',
    lb_tt_ultimate: 'Definitivo',
    lb_tt_classic: 'Clásico',
    lb_sn_walls_on: 'Con paredes',
    lb_sn_walls_off: 'Sin paredes',
    game_title_ballrun: 'Carrera de Bolas',
    game_title_boggle: 'Boggle',
    game_title_business: 'Monopoly Deal',
    game_title_chinchon: 'Chinchón',
    game_title_connect4: 'Conecta 4',
    game_title_dotsboxes: 'Puntos y Cajas',
    game_title_escoba: 'Escoba',
    game_title_filler: 'Filler',
    game_title_mancala: 'Mancala',
    game_title_nutsbolts: 'Tuercas y Tornillos',
    game_title_parchis: 'Parchís',
    game_title_snake: 'Serpiente',
    game_title_tictactoe: 'Tres en Raya',
    game_title_uno: 'Uno',
    game_title_pool: 'Billar',
    game_title_poolv2: 'Pool (retired build)',
    game_title_yahtzee: 'Yahtzee',
    game_title_dominoes: 'Dominó',
    game_title_hillclimb: 'Hill Climb',
    game_title_battleship: 'Hundir la Flota',
    game_title_skeeball: 'Skeeball',
    game_title_pinball: 'Pinball',
    lb_offline: 'La clasificación necesita conexión. Se activa cuando estás en línea.',
    lb_back_games: '&larr; Juegos',
    lb_loading_aria: 'Cargando clasificación',
    lb_tex_wins_first: 'Victorias empezando primero',
    lb_tex_wins_second: 'Victorias empezando segundo',
    lb_tex_chinchons: 'Chinchones',
    lb_tex_closes: 'Cierres',
    lb_tex_minus_tens: 'Menos diez',
    lb_tex_escobas: 'Escobas',
    lb_tex_best_level: 'Mejor nivel',
    lb_tex_levels_solved: 'Niveles resueltos',
    lb_tex_best_obstacles: 'Mejor obstáculos',
    lb_tex_total_runs: 'Carreras totales',
    lb_tex_boxes_claimed: 'Cajas capturadas',
    lb_tex_longest_chain: 'Cadena más larga',
    lb_tex_best_score: 'Mejor puntuación',
    lb_tex_words_found: 'Palabras encontradas',
    lb_tex_longest_word: 'Palabra más larga',
    lb_tex_longest_snake: 'Serpiente más larga',
    lb_tex_furthest_drive: 'Distancia más larga',
    lb_tex_hc_coins: 'Monedas ganadas',
    lb_tex_hc_flips: 'Volteretas hechas',
    lb_tex_sk_best_game: 'Mejor partida',
    lb_tex_sk_best_throw: 'Mejor lanzamiento',
    lb_tex_sk_hundreds: 'Copas de 100 acertadas',
    lb_tex_sk_points: 'Puntos totales',
    lb_tex_sk_sweeps: 'Los 4 colores',
    lb_tex_classic_played: 'Clásico jugado',
    lb_tex_ultimate_played: 'Definitivo jugado',
    lb_tex_draws: 'Empates',
  },
};

export default STRINGS;
