// murdoku/js/strings.js - the EN/ES dictionary. English is the source of truth; a missing Spanish
// key falls back to English (js/i18n.js's makeT), so partial translation never breaks. Spanish is
// Spain Spanish. No em dashes anywhere (root CLAUDE.md's copy rule). Names of the cast are names
// and are not translated (they live in engine.js).
//
// The clue fragments (`frag_*`) are the sentence pieces shown under each suspect. A room name is
// stored WITH its article ("the Kitchen" / "la cocina") so a fragment is just `in {room}` /
// `en {room}` in either language.
const STRINGS = {
  en: {
    title: 'Murdoku',
    tagline: 'Place every suspect from their clues. Find who was alone with the victim.',
    setup_difficulty: 'Difficulty',
    tier_easy: 'Easy',
    tier_medium: 'Medium',
    tier_hard: 'Hard',
    tier_expert: 'Expert',
    new_case: 'New case',
    continue_case: 'Continue case',
    howto: 'How to play',
    menu: 'Menu',
    building: 'Building the crime scene…',
    build_failed: 'Could not build a case. Please try again.',
    retry: 'Try again',
    case_label: 'Case #{n}',
    howto_aria: 'How to play',
    new_aria: 'New case',
    timer_aria: 'Time',
    board_aria: 'Floor plan',
    suspects_aria: 'Suspects and their clues',
    tool_aria: 'Tool',
    tool_place: 'Place',
    tool_mark: '✕ Mark',
    status_pick: 'Tap a suspect, then a square.',
    status_place: 'Now tap a square for {name}.',
    status_mark: 'Tap a square to mark it out.',
    status_placed: '{n} of {total} placed',
    not_quite_one: 'Not quite: 1 clue is not true yet.',
    not_quite_many: 'Not quite: {n} clues are not true yet.',
    bar_broken_one: 'Not quite. The clue marked ⚠️ in the list is not true yet. Move people until it is, or tap 💡.',
    bar_broken_many: 'Not quite. The {n} clues marked ⚠️ in the list are not true yet. Move people until they are, or tap 💡.',
    bar_clash: '⚠️ means {name} shares a row or column with someone. Only one person per row and per column. Tap {name} to lift them off.',
    bar_blocked: '⚠️ means {name} is standing on {obj}. Nobody can stand there, only on chairs, rugs and empty floor. Tap {name} to lift them off.',
    no_blocked: 'Nobody can stand on {obj}. Chairs, rugs and empty floor are fine.',
    no_row: '{name} is already in this row. Only one person per row.',
    no_col: '{name} is already in this column. Only one person per column.',
    howto_line6: '⚠️ next to a clue: that clue is not true yet.',
    not_quite_rules: 'Not quite. Check the warnings on the board.',
    solved_status: 'Case closed!',
    victim_suffix: '(the victim)',
    row_selected: 'selected',
    row_placed: 'placed',
    row_waiting: 'not placed yet',
    token_aria: '{name}, placed. Tap to lift off.',
    cell_aria: 'Row {r}, column {c}, {room}',
    cell_blocked: 'blocked by {obj}',
    cell_marked: 'marked out',
    warn_clash: 'Shares a row or column with someone',
    warn_blocked: 'Standing on a blocked square',
    warn_clue: "This clue doesn't fit",
    new_confirm: 'Start a new case? Your progress on this one will be lost.',
    cancel: 'Cancel',
    win_title: 'Case closed!',
    win_line: '{name} was alone with Victor in {room}.',
    win_time: 'Solved in {time}',
    close_aria: 'Close',
    howto_title: 'How to play',
    howto_goal_a: 'Put each person on the board.',
    howto_goal_b: 'The one alone with the victim did it.',
    howto_diagram_aria: 'A three by three floor plan with two rooms. The skull and one person share the top left room, and the third person is in the other room. Each row and column holds one person.',
    howto_caption: 'Only one person shares a room with the skull.',
    howto_example: 'Beside a plant = touching it, in the same room',
    howto_line1: 'One person in every row and every column.',
    howto_line2: 'Stand on 🪑 or a rug, never on 🪴📚🎹📺.',
    howto_line3: 'A wall between two squares breaks "beside".',
    howto_line4: 'Every case has one answer. No guessing needed.',
    howto_line5: 'Tap a name, then a square. Stuck? Tap 💡.',
    learn: 'Learn to play',
    case_guided: 'Guided case',
    hint_btn: '💡 Hint',
    hint_aria: 'Show a hint',
    hint_wrong: '{name} is on the wrong square. Tap to lift them off.',
    hint_only: 'Only one square fits {name}. Tap it.',
    hint_row: 'Only {name} can fill this row.',
    hint_col: 'Only {name} can fill this column.',
    hint_look: 'Only {k} squares fit {name}. Test each one against the clues.',
    hint_more: 'Tap 💡 to see which.',
    hint_answer: '{name} goes on the solid square.',
    guided_title: 'Your first case',
    guided_1: 'Everyone goes on the board: one person in each row and each column.',
    guided_2: "Each person's clues, in the list, say where they were.",
    guided_3: 'Glowing squares show you the next step. Tap the name, then the square.',
    guided_4: 'When everyone is placed, the one alone in a room with Victor 💀 did it.',
    guided_go: "Let's go",
    rname_kitchen: 'Kitchen',
    rname_library: 'Library',
    rname_hall: 'Hall',
    rname_study: 'Study',
    rname_lounge: 'Lounge',
    rname_ballroom: 'Ballroom',
    rname_dining: 'Dining Room',
    rname_garden: 'Garden',
    rname_bedroom: 'Bedroom',
    rname_cellar: 'Cellar',
    howto_close: 'Got it',
    // --- room names, with their article -----------------------------------------------------
    room_kitchen: 'the Kitchen',
    room_library: 'the Library',
    room_hall: 'the Hall',
    room_study: 'the Study',
    room_lounge: 'the Lounge',
    room_ballroom: 'the Ballroom',
    room_dining: 'the Dining Room',
    room_garden: 'the Garden',
    room_bedroom: 'the Bedroom',
    room_cellar: 'the Cellar',
    // --- objects, with their article ----------------------------------------------------------
    obj_plant: 'a plant',
    obj_shelf: 'a bookshelf',
    obj_piano: 'a piano',
    obj_tv: 'a TV',
    obj_chair: 'a chair',
    obj_rug: 'a rug',
    // --- clue fragments -----------------------------------------------------------------------
    frag_in: 'in {room}',
    frag_notin: 'not in {room}',
    frag_on_chair: 'on a chair',
    frag_on_rug: 'on a rug',
    frag_by: 'beside {obj}',
    frag_row_top: 'in the top row',
    frag_row_bottom: 'in the bottom row',
    frag_row_left: 'in the left column',
    frag_row_right: 'in the right column',
    frag_corner: 'in a corner',
    frag_above: 'one row above {name}',
    frag_below: 'one row below {name}',
    frag_left: 'one column left of {name}',
    frag_right: 'one column right of {name}',
    frag_diag: 'diagonally touching {name}',
    frag_north: 'somewhere above {name}',
    frag_west: 'somewhere left of {name}',
    frag_with: 'same room as {name}',
    frag_notwith: "not in {name}'s room",
    frag_alone: 'alone in a room',
  },
  es: {
    title: 'Murdoku',
    tagline: 'Coloca a cada sospechoso con sus pistas. Descubre quién estaba a solas con la víctima.',
    setup_difficulty: 'Dificultad',
    tier_easy: 'Fácil',
    tier_medium: 'Normal',
    tier_hard: 'Difícil',
    tier_expert: 'Experto',
    new_case: 'Nuevo caso',
    continue_case: 'Continuar caso',
    howto: 'Cómo se juega',
    menu: 'Menú',
    building: 'Preparando la escena del crimen…',
    build_failed: 'No se pudo crear el caso. Inténtalo de nuevo.',
    retry: 'Reintentar',
    case_label: 'Caso n.º {n}',
    howto_aria: 'Cómo se juega',
    new_aria: 'Nuevo caso',
    timer_aria: 'Tiempo',
    board_aria: 'Plano de la casa',
    suspects_aria: 'Sospechosos y sus pistas',
    tool_aria: 'Herramienta',
    tool_place: 'Colocar',
    tool_mark: '✕ Marcar',
    status_pick: 'Toca a un sospechoso y luego una casilla.',
    status_place: 'Ahora toca una casilla para {name}.',
    status_mark: 'Toca una casilla para tacharla.',
    status_placed: '{n} de {total} colocados',
    not_quite_one: 'Aún no: 1 pista no se cumple.',
    not_quite_many: 'Aún no: {n} pistas no se cumplen.',
    bar_broken_one: 'Aún no. La pista marcada con ⚠️ en la lista no se cumple. Mueve a la gente hasta que se cumpla, o toca 💡.',
    bar_broken_many: 'Aún no. Las {n} pistas marcadas con ⚠️ en la lista no se cumplen. Mueve a la gente hasta que se cumplan, o toca 💡.',
    bar_clash: '⚠️ significa que {name} comparte fila o columna con alguien. Solo una persona por fila y por columna. Toca a {name} para quitarlo.',
    bar_blocked: '⚠️ significa que {name} está sobre {obj}. Ahí no se puede estar, solo en sillas, alfombras y suelo libre. Toca a {name} para quitarlo.',
    no_blocked: 'Nadie puede estar sobre {obj}. Las sillas, las alfombras y el suelo libre sí valen.',
    no_row: '{name} ya está en esta fila. Solo una persona por fila.',
    no_col: '{name} ya está en esta columna. Solo una persona por columna.',
    howto_line6: '⚠️ junto a una pista: esa pista aún no se cumple.',
    not_quite_rules: 'No es correcto. Revisa los avisos del tablero.',
    solved_status: '¡Caso cerrado!',
    victim_suffix: '(la víctima)',
    row_selected: 'seleccionado',
    row_placed: 'colocado',
    row_waiting: 'sin colocar',
    token_aria: '{name}, colocado. Toca para quitarlo.',
    cell_aria: 'Fila {r}, columna {c}, {room}',
    cell_blocked: 'bloqueada por {obj}',
    cell_marked: 'tachada',
    warn_clash: 'Comparte fila o columna con alguien',
    warn_blocked: 'Está sobre una casilla bloqueada',
    warn_clue: 'Esta pista no encaja',
    new_confirm: '¿Empezar un caso nuevo? Perderás lo que llevas de este.',
    cancel: 'Cancelar',
    win_title: '¡Caso cerrado!',
    win_line: '{name} estaba a solas con Victor en {room}.',
    win_time: 'Resuelto en {time}',
    close_aria: 'Cerrar',
    howto_title: 'Cómo se juega',
    howto_goal_a: 'Coloca a cada persona en el tablero.',
    howto_goal_b: 'El culpable está a solas con la víctima.',
    howto_diagram_aria: 'Un plano de tres por tres con dos salas. La calavera y una persona comparten la sala de arriba a la izquierda, y la tercera persona está en la otra sala. Cada fila y cada columna tiene una persona.',
    howto_caption: 'Solo una persona comparte sala con la calavera.',
    howto_example: 'Junto a una planta = tocándola, misma sala',
    howto_line1: 'Una persona en cada fila y cada columna.',
    howto_line2: 'Vale 🪑 o alfombra, nunca 🪴📚🎹📺.',
    howto_line3: 'Una pared entre dos casillas rompe "junto a".',
    howto_line4: 'Cada caso tiene una solución. Sin adivinar.',
    howto_line5: 'Toca un nombre y luego una casilla. ¿Atascado? Toca 💡.',
    learn: 'Aprende a jugar',
    case_guided: 'Caso guiado',
    hint_btn: '💡 Pista',
    hint_aria: 'Ver una pista',
    hint_wrong: '{name} está en una casilla equivocada. Tócalo para quitarlo.',
    hint_only: 'Solo una casilla encaja con {name}. Tócala.',
    hint_row: 'Solo {name} puede ocupar esta fila.',
    hint_col: 'Solo {name} puede ocupar esta columna.',
    hint_look: 'Solo {k} casillas encajan con {name}. Prueba cada una con las pistas.',
    hint_more: 'Toca 💡 para ver cuál.',
    hint_answer: '{name} va en la casilla del borde continuo.',
    guided_title: 'Tu primer caso',
    guided_1: 'Todos van en el tablero: una persona en cada fila y en cada columna.',
    guided_2: 'Las pistas de cada persona, en la lista, dicen dónde estaba.',
    guided_3: 'Las casillas marcadas te enseñan el siguiente paso. Toca el nombre y luego la casilla.',
    guided_4: 'Cuando todos estén colocados, quien esté a solas en una sala con Victor 💀 lo hizo.',
    guided_go: 'Vamos',
    rname_kitchen: 'Cocina',
    rname_library: 'Biblioteca',
    rname_hall: 'Vestíbulo',
    rname_study: 'Estudio',
    rname_lounge: 'Sala de estar',
    rname_ballroom: 'Salón de baile',
    rname_dining: 'Comedor',
    rname_garden: 'Jardín',
    rname_bedroom: 'Dormitorio',
    rname_cellar: 'Bodega',
    howto_close: 'Entendido',
    room_kitchen: 'la cocina',
    room_library: 'la biblioteca',
    room_hall: 'el vestíbulo',
    room_study: 'el estudio',
    room_lounge: 'la sala de estar',
    room_ballroom: 'el salón de baile',
    room_dining: 'el comedor',
    room_garden: 'el jardín',
    room_bedroom: 'el dormitorio',
    room_cellar: 'la bodega',
    obj_plant: 'una planta',
    obj_shelf: 'una estantería',
    obj_piano: 'un piano',
    obj_tv: 'una tele',
    obj_chair: 'una silla',
    obj_rug: 'una alfombra',
    frag_in: 'en {room}',
    frag_notin: 'no en {room}',
    frag_on_chair: 'en una silla',
    frag_on_rug: 'sobre una alfombra',
    frag_by: 'junto a {obj}',
    frag_row_top: 'en la fila de arriba',
    frag_row_bottom: 'en la fila de abajo',
    frag_row_left: 'en la columna de la izquierda',
    frag_row_right: 'en la columna de la derecha',
    frag_corner: 'en una esquina',
    frag_above: 'una fila encima de {name}',
    frag_below: 'una fila debajo de {name}',
    frag_left: 'una columna a la izquierda de {name}',
    frag_right: 'una columna a la derecha de {name}',
    frag_diag: 'en diagonal junto a {name}',
    frag_north: 'más arriba que {name}',
    frag_west: 'más a la izquierda que {name}',
    frag_with: 'en la misma sala que {name}',
    frag_notwith: 'no en la sala de {name}',
    frag_alone: 'sin nadie más en su sala',
  },
};

export default STRINGS;
