// murdoku/js/strings.js - the EN/ES dictionary. English is the source of truth; a missing Spanish
// key falls back to English (js/i18n.js's makeT), so partial translation never breaks. Spanish is
// Spain Spanish. No em dashes anywhere (root CLAUDE.md's copy rule). Names of the cast are names
// and are not translated (they live in engine.js).
//
// The clue fragments (`frag_*`) are the sentence pieces shown under each suspect. A room name is
// stored WITH its article ("the Kitchen" / "la cocina") so a fragment is just `in {room}` /
// `en {room}` in either language.
const STRINGS = {
  en: {
    title: 'Murdoku',
    tagline: 'Place every suspect from their clues. Find who was alone with the victim.',
    setup_difficulty: 'Difficulty',
    tier_easy: 'Easy',
    tier_medium: 'Medium',
    tier_hard: 'Hard',
    tier_expert: 'Expert',
    new_case: 'New case',
    continue_case: 'Continue case',
    howto: 'How to play',
    menu: 'Menu',
    building: 'Building the crime scene…',
    build_failed: 'Could not build a case. Please try again.',
    retry: 'Try again',
    case_label: 'Case #{n}',
    howto_aria: 'How to play',
    new_aria: 'New case',
    timer_aria: 'Time',
    board_aria: 'Floor plan',
    suspects_aria: 'Suspects and their clues',
    tool_aria: 'Tool',
    tool_place: 'Place',
    tool_mark: '✕ Mark',
    status_pick: 'Tap a suspect, then a square.',
    status_place: 'Now tap a square for {name}.',
    status_mark: 'Tap a square to mark it out.',
    status_placed: '{n} of {total} placed',
    not_quite_one: 'Not quite: 1 clue is not true yet.',
    not_quite_many: 'Not quite: {n} clues are not true yet.',
    bar_broken_one: 'Not quite. The clue marked ⚠️ in the list is not true yet. Move people until it is, or tap 💡.',
    bar_broken_many: 'Not quite. The {n} clues marked ⚠️ in the list are not true yet. Move people until they are, or tap 💡.',
    bar_clash: '⚠️ means {name} shares a row or column with someone. Only one person per row and per column. Tap {name} to lift her off.',
    bar_blocked: '⚠️ means {name} is standing on {obj}. Nobody can stand there, only on chairs, rugs and empty floor. Tap {name} to lift her off.',
    no_blocked: 'Nobody can stand on {obj}. Chairs, rugs and empty floor are fine.',
    no_row: '{name} is already in this row. Only one person per row.',
    no_col: '{name} is already in this column. Only one person per column.',
    not_quite_rules: 'Not quite. Check the warnings on the board.',
    solved_status: 'Case closed!',
    victim_suffix: '💀 the victim',
    row_selected: 'selected',
    row_placed: 'placed',
    row_waiting: 'not placed yet',
    token_aria: '{name}, placed. Tap to lift off.',
    cell_aria: 'Row {r}, column {c}, {room}',
    cell_blocked: 'blocked by {obj}',
    cell_marked: 'marked out',
    warn_clash: 'Shares a row or column with someone',
    warn_blocked: 'Standing on a blocked square',
    warn_clue: "This clue doesn't fit",
    new_confirm: 'Start a new case? Your progress on this one will be lost.',
    cancel: 'Cancel',
    win_title: 'Case closed!',
    win_line: '{name} was alone with {victim} in {room}.',
    win_time: 'Solved in {time}',
    close_aria: 'Close',
    howto_title: 'How to play',
    learn: 'Learn to play',
    case_guided: 'Guided case',
    hint_btn: '💡 Hint',
    hint_aria: 'Show a hint',
    hint_wrong: '{name} is on the wrong square. Tap to lift her off.',
    hint_only: 'Only one square fits {name}. Tap it.',
    hint_row: 'Only {name} can fill this row.',
    hint_col: 'Only {name} can fill this column.',
    hint_look: 'Only {k} squares fit {name}. Test each one against the clues.',
    hint_more: 'Tap 💡 to see which.',
    hint_answer: '{name} goes on the solid square.',
    guided_title: 'Your first case',
    guided_go: "Let's go",
    rname_kitchen: 'Kitchen',
    rname_library: 'Library',
    rname_hall: 'Hall',
    rname_study: 'Study',
    rname_lounge: 'Lounge',
    rname_ballroom: 'Ballroom',
    rname_dining: 'Dining Room',
    rname_garden: 'Garden',
    rname_bedroom: 'Bedroom',
    rname_cellar: 'Cellar',
    howto_close: 'Got it',
    howto_back: 'Back',
    howto_next: 'Next',
    ht1_title: 'Who is the murderer?',
    ht1_victim: 'the victim',
    ht1_a: 'Someone 💀 was murdered.',
    ht1_b: 'Use the clues to find who did it.',
    ht2_title: 'One per row and column',
    ht2_a: 'Put every person on the board.',
    ht2_b: 'Each row gets exactly one person,',
    ht2_c: 'and so does each column.',
    ht3_title: 'Follow the clues',
    ht3_a: "Each person's clues say where they were.",
    ht3_b: '"Beside" means right next to it,',
    ht3_c: 'in the same room, not through a wall.',
    ht4_title: 'Where people can stand',
    ht4_a: 'Empty floor, a chair or a rug: yes.',
    ht4_b: 'A plant, shelf, piano or TV: no.',
    ht5_title: 'Who did it?',
    ht5_tag: 'did it',
    ht5_a: 'When everyone is placed,',
    ht5_b: "look at the victim's room (💀).",
    ht5_c: 'The one person in there with her did it.',
    ht6_title: 'How to play',
    ht6_a: '1. Tap a name in the list.',
    ht6_b: '2. Tap a square on the board.',
    ht6_c: 'Stuck? Tap 💡 Hint to see the next step.',
    // --- room names, with their article -----------------------------------------------------
    room_kitchen: 'the Kitchen',
    room_library: 'the Library',
    room_hall: 'the Hall',
    room_study: 'the Study',
    room_lounge: 'the Lounge',
    room_ballroom: 'the Ballroom',
    room_dining: 'the Dining Room',
    room_garden: 'the Garden',
    room_bedroom: 'the Bedroom',
    room_cellar: 'the Cellar',
    // --- objects, with their article ----------------------------------------------------------
    obj_plant: 'a plant',
    obj_shelf: 'a bookshelf',
    obj_piano: 'a piano',
    obj_tv: 'a TV',
    obj_chair: 'a chair',
    obj_rug: 'a rug',
    // --- clue fragments -----------------------------------------------------------------------
    frag_in: 'in {room}',
    frag_notin: 'not in {room}',
    frag_on_chair: 'on a chair',
    frag_on_rug: 'on a rug',
    frag_by: 'beside {obj}',
    frag_row_top: 'in the top row',
    frag_row_bottom: 'in the bottom row',
    frag_row_left: 'in the left column',
    frag_row_right: 'in the right column',
    frag_corner: 'in a corner',
    frag_above: 'one row above {name}',
    frag_below: 'one row below {name}',
    frag_left: 'one column left of {name}',
    frag_right: 'one column right of {name}',
    frag_diag: 'diagonally touching {name}',
    frag_north: 'somewhere above {name}',
    frag_west: 'somewhere left of {name}',
    frag_with: 'same room as {name}',
    frag_notwith: "not in {name}'s room",
    frag_alone: 'alone in a room',
  },
  es: {
    title: 'Murdoku',
    tagline: 'Coloca a cada sospechoso con sus pistas. Descubre quién estaba a solas con la víctima.',
    setup_difficulty: 'Dificultad',
    tier_easy: 'Fácil',
    tier_medium: 'Normal',
    tier_hard: 'Difícil',
    tier_expert: 'Experto',
    new_case: 'Nuevo caso',
    continue_case: 'Continuar caso',
    howto: 'Cómo se juega',
    menu: 'Menú',
    building: 'Preparando la escena del crimen…',
    build_failed: 'No se pudo crear el caso. Inténtalo de nuevo.',
    retry: 'Reintentar',
    case_label: 'Caso n.º {n}',
    howto_aria: 'Cómo se juega',
    new_aria: 'Nuevo caso',
    timer_aria: 'Tiempo',
    board_aria: 'Plano de la casa',
    suspects_aria: 'Sospechosos y sus pistas',
    tool_aria: 'Herramienta',
    tool_place: 'Colocar',
    tool_mark: '✕ Marcar',
    status_pick: 'Toca a un sospechoso y luego una casilla.',
    status_place: 'Ahora toca una casilla para {name}.',
    status_mark: 'Toca una casilla para tacharla.',
    status_placed: '{n} de {total} colocados',
    not_quite_one: 'Aún no: 1 pista no se cumple.',
    not_quite_many: 'Aún no: {n} pistas no se cumplen.',
    bar_broken_one: 'Aún no. La pista marcada con ⚠️ en la lista no se cumple. Mueve a la gente hasta que se cumpla, o toca 💡.',
    bar_broken_many: 'Aún no. Las {n} pistas marcadas con ⚠️ en la lista no se cumplen. Mueve a la gente hasta que se cumplan, o toca 💡.',
    bar_clash: '⚠️ significa que {name} comparte fila o columna con alguien. Solo una persona por fila y por columna. Toca a {name} para quitarla.',
    bar_blocked: '⚠️ significa que {name} está sobre {obj}. Ahí no se puede estar, solo en sillas, alfombras y suelo libre. Toca a {name} para quitarla.',
    no_blocked: 'Nadie puede estar sobre {obj}. Las sillas, las alfombras y el suelo libre sí valen.',
    no_row: '{name} ya está en esta fila. Solo una persona por fila.',
    no_col: '{name} ya está en esta columna. Solo una persona por columna.',
    not_quite_rules: 'No es correcto. Revisa los avisos del tablero.',
    solved_status: '¡Caso cerrado!',
    victim_suffix: '💀 la víctima',
    row_selected: 'seleccionado',
    row_placed: 'colocado',
    row_waiting: 'sin colocar',
    token_aria: '{name}, colocada. Toca para quitarla.',
    cell_aria: 'Fila {r}, columna {c}, {room}',
    cell_blocked: 'bloqueada por {obj}',
    cell_marked: 'tachada',
    warn_clash: 'Comparte fila o columna con alguien',
    warn_blocked: 'Está sobre una casilla bloqueada',
    warn_clue: 'Esta pista no encaja',
    new_confirm: '¿Empezar un caso nuevo? Perderás lo que llevas de este.',
    cancel: 'Cancelar',
    win_title: '¡Caso cerrado!',
    win_line: '{name} estaba a solas con {victim} en {room}.',
    win_time: 'Resuelto en {time}',
    close_aria: 'Cerrar',
    howto_title: 'Cómo se juega',
    learn: 'Aprende a jugar',
    case_guided: 'Caso guiado',
    hint_btn: '💡 Pista',
    hint_aria: 'Ver una pista',
    hint_wrong: '{name} está en una casilla equivocada. Tócala para quitarla.',
    hint_only: 'Solo una casilla encaja con {name}. Tócala.',
    hint_row: 'Solo {name} puede ocupar esta fila.',
    hint_col: 'Solo {name} puede ocupar esta columna.',
    hint_look: 'Solo {k} casillas encajan con {name}. Prueba cada una con las pistas.',
    hint_more: 'Toca 💡 para ver cuál.',
    hint_answer: '{name} va en la casilla del borde continuo.',
    guided_title: 'Tu primer caso',
    guided_go: 'Vamos',
    rname_kitchen: 'Cocina',
    rname_library: 'Biblioteca',
    rname_hall: 'Vestíbulo',
    rname_study: 'Estudio',
    rname_lounge: 'Sala de estar',
    rname_ballroom: 'Salón de baile',
    rname_dining: 'Comedor',
    rname_garden: 'Jardín',
    rname_bedroom: 'Dormitorio',
    rname_cellar: 'Bodega',
    howto_close: 'Entendido',
    howto_back: 'Atrás',
    howto_next: 'Siguiente',
    ht1_title: '¿Quién es la culpable?',
    ht1_victim: 'la víctima',
    ht1_a: 'Alguien 💀 fue asesinada.',
    ht1_b: 'Usa las pistas para descubrir quién fue.',
    ht2_title: 'Uno por fila y columna',
    ht2_a: 'Coloca a cada persona en el tablero.',
    ht2_b: 'Cada fila tiene exactamente una persona,',
    ht2_c: 'y cada columna también.',
    ht3_title: 'Sigue las pistas',
    ht3_a: 'Las pistas dicen dónde estaba cada uno.',
    ht3_b: '"Junto a" significa justo al lado,',
    ht3_c: 'en la misma sala, no a través de una pared.',
    ht4_title: 'Dónde se puede estar',
    ht4_a: 'Suelo libre, una silla o una alfombra: sí.',
    ht4_b: 'Una planta, estantería, piano o tele: no.',
    ht5_title: '¿Quién fue?',
    ht5_tag: 'fue',
    ht5_a: 'Cuando todos estén colocados,',
    ht5_b: 'mira la sala de la víctima (💀).',
    ht5_c: 'La única persona que está con ella lo hizo.',
    ht6_title: 'Cómo jugar',
    ht6_a: '1. Toca un nombre de la lista.',
    ht6_b: '2. Toca una casilla del tablero.',
    ht6_c: '¿Atascado? Toca 💡 Pista para ver el paso.',
    room_kitchen: 'la cocina',
    room_library: 'la biblioteca',
    room_hall: 'el vestíbulo',
    room_study: 'el estudio',
    room_lounge: 'la sala de estar',
    room_ballroom: 'el salón de baile',
    room_dining: 'el comedor',
    room_garden: 'el jardín',
    room_bedroom: 'el dormitorio',
    room_cellar: 'la bodega',
    obj_plant: 'una planta',
    obj_shelf: 'una estantería',
    obj_piano: 'un piano',
    obj_tv: 'una tele',
    obj_chair: 'una silla',
    obj_rug: 'una alfombra',
    frag_in: 'en {room}',
    frag_notin: 'no en {room}',
    frag_on_chair: 'en una silla',
    frag_on_rug: 'sobre una alfombra',
    frag_by: 'junto a {obj}',
    frag_row_top: 'en la fila de arriba',
    frag_row_bottom: 'en la fila de abajo',
    frag_row_left: 'en la columna de la izquierda',
    frag_row_right: 'en la columna de la derecha',
    frag_corner: 'en una esquina',
    frag_above: 'una fila encima de {name}',
    frag_below: 'una fila debajo de {name}',
    frag_left: 'una columna a la izquierda de {name}',
    frag_right: 'una columna a la derecha de {name}',
    frag_diag: 'en diagonal junto a {name}',
    frag_north: 'más arriba que {name}',
    frag_west: 'más a la izquierda que {name}',
    frag_with: 'en la misma sala que {name}',
    frag_notwith: 'no en la sala de {name}',
    frag_alone: 'sin nadie más en su sala',
  },
};

export default STRINGS;
