// hill-climb/js/strings.js — every user-visible string in Hill Climb, EN + ES.
//
// English is the source of truth: a key missing from `es` falls back to English (js/i18n.js), so
// partial translation can never break a screen. Call t() at RENDER time, never at module scope.
// House style (root CLAUDE.md): no em dashes in player-facing copy.

export const STRINGS = {
  en: {
    title: 'Hill Climb',

    // --- garage / menu ---------------------------------------------------------------------
    tab_shop: 'Shop',
    tab_stage: 'Stage',
    tab_vehicle: 'Vehicle',
    tab_tune: 'Tune',
    tab_start: 'Start',
    coins: 'Coins',
    best_here: 'Best on {stage}',
    lifetime: 'Lifetime',
    aria_coins: 'Coins in the bank',
    aria_back: 'Back to the garage',

    veh_jeep: 'Hill Climber',
    veh_bike: 'Dirt Bike',
    veh_truck: 'Monster Truck',
    veh_rover: 'Moon Rover',
    veh_jeep_note: 'The all rounder. Forgiving throttle, honest grip.',
    veh_bike_note: 'Light and quick, flips at the smallest excuse.',
    veh_truck_note: 'Heavy, huge wheels, eats bumps for breakfast.',
    veh_rover_note: 'Near 4WD from stock. Built for low gravity.',

    stage_countryside: 'Countryside',
    stage_desert: 'Desert',
    stage_arctic: 'Arctic',
    stage_moon: 'Moon',
    stage_countryside_note: 'Gentle green hills. The place to learn.',
    stage_desert_note: 'Bigger dunes and loose sand, so less grip.',
    stage_arctic_note: 'Ice. Your tires are mostly a suggestion here.',
    stage_moon_note: 'Low gravity, huge air, very little traction.',

    part_engine: 'Engine',
    part_suspension: 'Suspension',
    part_tires: 'Tires',
    part_drive: '4WD',
    part_engine_note: 'More pulling power up the steep stuff.',
    part_suspension_note: 'Softer landings, less bouncing.',
    part_tires_note: 'Grip. Stops the wheels spinning away.',
    part_drive_note: 'Sends power to the front wheel too.',

    buy: 'Buy',
    buy_for: 'Buy {price}',
    select: 'Select',
    selected: 'Selected',
    locked: 'Locked',
    maxed: 'Maxed',
    cant_afford: 'Not enough coins',
    level_of: 'Level {n} of {max}',
    stock: 'Stock',
    shop_intro: 'Everything you can buy, in one place. Coins come from runs.',
    shop_vehicles: 'Vehicles',
    shop_stages: 'Stages',
    tune_intro: 'Upgrades apply to {vehicle} only. Each car is tuned on its own.',

    // --- gameplay HUD ----------------------------------------------------------------------
    gas: 'Gas',
    brake: 'Brake',
    boost: 'Boost',
    rpm: 'RPM',
    nitro: 'Nitro',
    meters: '{n} m',
    unit_m: 'm',
    aria_gas: 'Gas',
    aria_brake: 'Brake and reverse',
    aria_boost: 'Use a nitro charge',
    aria_pause: 'Pause',
    aria_fuel: 'Fuel remaining',
    aria_distance: 'Distance travelled',

    // --- pause / game over -----------------------------------------------------------------
    paused: 'Paused',
    resume: 'Resume',
    restart: 'Restart',
    quit: 'Back to garage',
    run_over: 'Run over',
    crashed: 'You landed on your head.',
    out_of_fuel: 'Out of fuel.',
    r_distance: 'Distance',
    r_coins: 'Coins',
    r_flips: 'Flips',
    r_best: 'Best',
    new_best: 'New best',
    retry: 'Try again',
    aria_close: 'Close',

    // --- how to play -----------------------------------------------------------------------
    how_title: 'How to play',
    how_1: 'Hold GAS to go, hold BRAKE to slow down or reverse.',
    how_2: 'There is no steering. Throttle tilts the car: gas lifts the nose, brake drops it. That is how you land flat.',
    how_3: 'Land on the driver’s head and the run is over. So is running out of fuel, so grab the red cans.',
    how_4: 'Coins buy upgrades, cars and stages. A full flip in the air pays a bonus.',
    how_close: 'Got it',
    how_open: 'How to play',
  },

  es: {
    title: 'Hill Climb',

    tab_shop: 'Tienda',
    tab_stage: 'Nivel',
    tab_vehicle: 'Vehículo',
    tab_tune: 'Ajustes',
    tab_start: 'Jugar',
    coins: 'Monedas',
    best_here: 'Récord en {stage}',
    lifetime: 'Total',
    aria_coins: 'Monedas en el banco',
    aria_back: 'Volver al garaje',

    veh_jeep: 'Todoterreno',
    veh_bike: 'Moto de cross',
    veh_truck: 'Monster Truck',
    veh_rover: 'Rover lunar',
    veh_jeep_note: 'El equilibrado. Acelerador indulgente y agarre honesto.',
    veh_bike_note: 'Ligera y rápida, vuelca a la mínima.',
    veh_truck_note: 'Pesado, ruedas enormes, se come los baches.',
    veh_rover_note: 'Casi 4x4 de serie. Hecho para la gravedad baja.',

    stage_countryside: 'Campo',
    stage_desert: 'Desierto',
    stage_arctic: 'Ártico',
    stage_moon: 'Luna',
    stage_countryside_note: 'Colinas verdes suaves. El sitio para aprender.',
    stage_desert_note: 'Dunas más grandes y arena suelta, así que menos agarre.',
    stage_arctic_note: 'Hielo. Aquí las ruedas son casi decorativas.',
    stage_moon_note: 'Gravedad baja, saltos enormes, muy poca tracción.',

    part_engine: 'Motor',
    part_suspension: 'Suspensión',
    part_tires: 'Ruedas',
    part_drive: '4x4',
    part_engine_note: 'Más fuerza para las cuestas duras.',
    part_suspension_note: 'Aterrizajes más suaves, menos rebote.',
    part_tires_note: 'Agarre. Evita que las ruedas patinen.',
    part_drive_note: 'Manda fuerza también a la rueda delantera.',

    buy: 'Comprar',
    buy_for: 'Comprar {price}',
    select: 'Elegir',
    selected: 'Elegido',
    locked: 'Bloqueado',
    maxed: 'Al máximo',
    cant_afford: 'No tienes monedas suficientes',
    level_of: 'Nivel {n} de {max}',
    stock: 'De serie',
    shop_intro: 'Todo lo que puedes comprar, en un sitio. Las monedas salen de las partidas.',
    shop_vehicles: 'Vehículos',
    shop_stages: 'Niveles',
    tune_intro: 'Las mejoras son solo para {vehicle}. Cada coche se ajusta por separado.',

    gas: 'Gas',
    brake: 'Freno',
    boost: 'Turbo',
    rpm: 'RPM',
    nitro: 'Nitro',
    meters: '{n} m',
    unit_m: 'm',
    aria_gas: 'Acelerar',
    aria_brake: 'Frenar y marcha atrás',
    aria_boost: 'Usar una carga de nitro',
    aria_pause: 'Pausa',
    aria_fuel: 'Combustible restante',
    aria_distance: 'Distancia recorrida',

    paused: 'En pausa',
    resume: 'Seguir',
    restart: 'Reiniciar',
    quit: 'Volver al garaje',
    run_over: 'Fin de la partida',
    crashed: 'Has aterrizado de cabeza.',
    out_of_fuel: 'Sin combustible.',
    r_distance: 'Distancia',
    r_coins: 'Monedas',
    r_flips: 'Volteretas',
    r_best: 'Récord',
    new_best: 'Nuevo récord',
    retry: 'Otra vez',
    aria_close: 'Cerrar',

    how_title: 'Cómo se juega',
    how_1: 'Mantén GAS para avanzar, y FRENO para frenar o ir marcha atrás.',
    how_2: 'No hay volante. El acelerador inclina el coche: el gas levanta el morro y el freno lo baja. Así se aterriza plano.',
    how_3: 'Si el conductor se da con la cabeza, se acabó. Quedarte sin combustible también, así que coge los bidones rojos.',
    how_4: 'Las monedas compran mejoras, coches y niveles. Una vuelta completa en el aire da premio.',
    how_close: 'Entendido',
    how_open: 'Cómo se juega',
  },
};

export default STRINGS;
