// repeat-the-law.mjs - keeps THE LAW repeated verbatim through CLAUDE.md at ~10% intervals.
//
// Matt's explicit instruction (2026-07-22): THE LAW must appear in full, verbatim, roughly every 10%
// of CLAUDE.md's line count, so a session working anywhere in that file cannot lose sight of it.
// 10% spacing means 10 copies: the canonical block near the top, plus 9 repeats.
//
// IDEMPOTENT. It strips every previously-generated copy first, then re-inserts from the CANONICAL
// block, so it can be re-run any time CLAUDE.md grows and the spacing will re-even itself. Copies are
// generated, never hand-edited: edit the canonical block at the top of CLAUDE.md and re-run this.
//
//   node repeat-the-law.mjs            # check spacing, report, change nothing
//   node repeat-the-law.mjs --write    # regenerate the repeats

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PATH = join(dirname(fileURLToPath(import.meta.url)), 'CLAUDE.md');
const HEAD = '## THE LAW: player data is never deleted, never lost, never put at risk';
const COPIES = 10;                                   // 1 canonical + 9 repeats == ~10% spacing
const BEGIN = (n) => `<!-- BEGIN THE LAW, repeated verbatim (copy ${n} of ${COPIES}). Generated by repeat-the-law.mjs - deliberate, do not consolidate, do not hand-edit. -->`;
const END = (n) => `<!-- END THE LAW (copy ${n} of ${COPIES}) -->`;
const IS_BEGIN = (l) => l.startsWith('<!-- BEGIN THE LAW, repeated verbatim');
const IS_END = (l) => l.startsWith('<!-- END THE LAW');

const src = readFileSync(PATH, 'utf8');
const EOL = src.includes('\r\n') ? '\r\n' : '\n';

/** Drop every repeated copy, keeping only the FIRST (canonical) one and the hand-written content.
 *  Deliberately marker-AGNOSTIC: it locates copies by the heading itself and eats the generated
 *  wrapper (blank / `---` / HTML-comment lines) around each, so it also cleans up copies left by an
 *  earlier marker format rather than silently stacking a second generation on top of them. */
function strip(lines) {
  const drop0 = new Set();
  // Pass 1: marker-delimited copies. Removed by EXACT bounds - the wrapper this script emits is
  // `--- / blank / BEGIN / blank / <block> / blank / END / blank / --- / blank` - so a strip is the
  // precise inverse of an insert and re-running never drifts by a blank line.
  for (let b = 0; b < lines.length; b++) {
    if (!IS_BEGIN(lines[b])) continue;
    let e = b + 1;
    while (e < lines.length && !IS_END(lines[e])) e++;
    if (e >= lines.length) continue;
    let from = b, to = e;
    if (lines[b - 1] === '' && (lines[b - 2] || '').trim() === '---') from = b - 2;
    if (lines[e + 1] === '' && (lines[e + 2] || '').trim() === '---' && lines[e + 3] === '') to = e + 3;
    for (let i = from; i <= to; i++) drop0.add(i);
  }
  if (drop0.size) lines = lines.filter((_, i) => !drop0.has(i));

  // Pass 2: fallback for any copy left by a different (older, hand-made) format, located by the
  // heading itself. Approximate by design - it only ever runs once, on first migration.
  const heads = [];
  for (let i = 0; i < lines.length; i++) if (lines[i] === HEAD) heads.push(i);
  if (heads.length <= 1) return lines.slice();
  const blockLen = (() => {
    const s = heads[0];
    const e = lines.findIndex((l, i) => i > s && /^## /.test(l));
    let n = (e < 0 ? lines.length : e) - s;
    while (n > 0 && lines[s + n - 1].trim() === '') n--;
    return n;
  })();
  const wrapper = (l) => l.trim() === '' || l.trim() === '---' || l.trim().startsWith('<!--');
  const drop = new Set();
  for (const s of heads.slice(1)) {
    let from = s, to = s + blockLen - 1;                       // the copy itself
    for (let k = 0; k < 4 && from - 1 >= 0 && wrapper(lines[from - 1]); k++) from--;
    for (let k = 0; k < 4 && to + 1 < lines.length && wrapper(lines[to + 1]); k++) to++;
    for (let i = from; i <= to; i++) drop.add(i);
  }
  return lines.filter((_, i) => !drop.has(i));
}

const base = strip(src.split(/\r?\n/));
const start = base.indexOf(HEAD);
if (start < 0) throw new Error('canonical LAW heading not found in CLAUDE.md');
const end = base.findIndex((l, i) => i > start && /^## /.test(l));
if (end < 0) throw new Error('could not find the end of the canonical LAW section');

let block = base.slice(start, end);
while (block.length && block[block.length - 1].trim() === '') block.pop();
const BLOCK = block.join(EOL);

// Anchors: every heading after the canonical block. Each repeat goes immediately BEFORE one, so no
// copy ever lands mid-topic.
const headings = [];
for (let i = end; i < base.length; i++) if (/^#{2,3} /.test(base[i])) headings.push(i);

// Nine evenly-spaced targets across the remainder, each snapped to the nearest unused heading.
const step = (base.length - end) / (COPIES - 1);
const chosen = new Set();
for (let i = 1; i <= COPIES - 1; i++) {
  const target = end + step * i;
  let best = -1, bestD = Infinity;
  for (const h of headings) {
    if (chosen.has(h)) continue;
    const d = Math.abs(h - target);
    if (d < bestD) { bestD = d; best = h; }
  }
  if (best >= 0) chosen.add(best);
}
const anchors = [...chosen].sort((a, b) => a - b);

const out = [];
let n = 1;
for (let i = 0; i < base.length; i++) {
  if (anchors.includes(i)) {
    n++;
    out.push('---', '', BEGIN(n), '', BLOCK, '', END(n), '', '---', '');
  }
  out.push(base[i]);
}

const result = out.join(EOL);
const lines = result.split(EOL);
const at = [];
for (let i = 0; i < lines.length; i++) if (lines[i] === HEAD) at.push(i + 1);
const gaps = at.slice(1).map((v, i) => v - at[i]);
const target = Math.round(lines.length / COPIES);

console.log(`CLAUDE.md: ${base.length} hand-written lines -> ${lines.length} with ${at.length} copies of THE LAW`);
console.log(`Copies at lines: ${at.join(', ')}`);
console.log(`Gaps: ${gaps.join(', ')}   (10% target ~${target}, range ${Math.min(...gaps)}-${Math.max(...gaps)})`);

if (at.length !== COPIES) { console.error(`FAIL: expected ${COPIES} copies, got ${at.length}`); process.exit(1); }

if (process.argv.includes('--write')) {
  writeFileSync(PATH, result, 'utf8');
  console.log('Written.');
} else if (result === src) {
  console.log('Already up to date - nothing to do.');
} else {
  console.log('Spacing is stale. Re-run with --write to regenerate.');
}
