// minesweeper/js/strings.js — every user-visible string in Minesweeper, both languages. English
// is the source of truth (every key exists in `en`); `es` may lag and js/i18n.js's fallback shows
// English for anything missing, so a partial translation can never break a screen. Shape follows
// snake/js/strings.js, the repo's reference implementation (root CLAUDE.md, "Adding a game" item 9).
//
// Spanish drafted by a working session; native-speaker review welcome — corrections are one-line
// edits here, nothing else moves. No em dashes anywhere (root CLAUDE.md's copy rule).

export const STRINGS = {
  en: {
    // Setup screen
    title: 'Minesweeper',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    expert: 'Expert',
    board_fmt: '{w} x {h}, {n} mines',
    your_best: 'Your best time',
    no_time: '--:--',
    options: 'Options',
    safe_first: 'Safe first tap',
    safe_first_sub: 'Opens an area, never a mine',
    long_press: 'Long press to flag',
    long_press_sub: 'As well as the Flag button',
    vibrate: 'Vibrate on flag',
    play: 'Play',
    resume: 'Resume',
    how_to_play: 'How to play',
    my_stats: 'My stats',
    // Game screen
    dig: 'Dig',
    flag: 'Flag',
    new_game: 'New game',
    mines_left_aria: 'Mines left: {n}',
    time_aria: 'Time: {t}',
    help_aria: 'How to play',
    cell_aria_hidden: 'Row {r}, column {c}, not opened',
    cell_aria_flag: 'Row {r}, column {c}, flagged',
    cell_aria_open: 'Row {r}, column {c}, {n} mines touching',
    cell_aria_empty: 'Row {r}, column {c}, empty',
    // Results
    boom: 'Boom',
    cleared: 'Cleared',
    result_sub_fmt: '{level}, {n} mines',
    stat_time: 'Time',
    stat_cleared: 'Cleared',
    stat_flags: 'Flags right',
    stat_old_best: 'Old best',
    stat_wins: 'Wins',
    new_best: 'New best time',
    play_again: 'Play again',
    change_difficulty: 'Change difficulty',
    leaderboard: 'Leaderboard',
    close: 'Close',
    // How to play
    help_lead: 'Open every square that is not a mine. A number says how many mines touch it.',
    help_chord_cap: 'Tap a number that already has all its flags beside it, and every other square around it opens at once.',
    help_chord_eg: '3 with 3 flags beside it = the rest opens',
    help_loupe_cap: 'Your thumb covers the square. The bubble above it shows the square you are actually on, and it only commits when you lift off.',
    help_loupe_eg: 'Slide to correct = lift to open',
    help_edge_flag: 'Long press a square to flag it without leaving Dig.',
    help_edge_safe: 'Your first tap is always safe.',
    help_edge_clock: 'The clock stops when you leave and picks up where it was.',
    back: 'Back',
  },
  es: {
    // Setup screen
    title: 'Buscaminas',
    difficulty: 'Dificultad',
    easy: 'Fácil',
    medium: 'Normal',
    hard: 'Difícil',
    expert: 'Experto',
    board_fmt: '{w} x {h}, {n} minas',
    your_best: 'Tu mejor tiempo',
    no_time: '--:--',
    options: 'Opciones',
    safe_first: 'Primer toque seguro',
    safe_first_sub: 'Abre una zona, nunca una mina',
    long_press: 'Mantén presionado para marcar',
    long_press_sub: 'Además del botón Marcar',
    vibrate: 'Vibrar al marcar',
    play: 'Jugar',
    resume: 'Continuar',
    how_to_play: 'Cómo se juega',
    my_stats: 'Mis estadísticas',
    // Game screen
    dig: 'Cavar',
    flag: 'Marcar',
    new_game: 'Partida nueva',
    mines_left_aria: 'Minas restantes: {n}',
    time_aria: 'Tiempo: {t}',
    help_aria: 'Cómo se juega',
    cell_aria_hidden: 'Fila {r}, columna {c}, sin abrir',
    cell_aria_flag: 'Fila {r}, columna {c}, marcada',
    cell_aria_open: 'Fila {r}, columna {c}, {n} minas alrededor',
    cell_aria_empty: 'Fila {r}, columna {c}, vacía',
    // Results
    boom: 'Boom',
    cleared: 'Despejado',
    result_sub_fmt: '{level}, {n} minas',
    stat_time: 'Tiempo',
    stat_cleared: 'Despejado',
    stat_flags: 'Marcas correctas',
    stat_old_best: 'Récord anterior',
    stat_wins: 'Victorias',
    new_best: 'Nuevo mejor tiempo',
    play_again: 'Jugar otra vez',
    change_difficulty: 'Cambiar dificultad',
    leaderboard: 'Tabla de posiciones',
    close: 'Cerrar',
    // How to play
    help_lead: 'Abre todas las casillas que no sean una mina. Un número indica cuántas minas la tocan.',
    help_chord_cap: 'Toca un número que ya tenga todas sus marcas alrededor, y el resto de sus casillas se abren a la vez.',
    help_chord_eg: '3 con 3 marcas alrededor = se abre el resto',
    help_loupe_cap: 'Tu dedo tapa la casilla. La burbuja de arriba muestra la casilla real, y solo se confirma al levantar el dedo.',
    help_loupe_eg: 'Desliza para corregir = levanta para abrir',
    help_edge_flag: 'Mantén presionada una casilla para marcarla sin salir de Cavar.',
    help_edge_safe: 'Tu primer toque siempre es seguro.',
    help_edge_clock: 'El reloj se detiene al salir y sigue donde iba.',
    back: 'Atrás',
  },
};

export default STRINGS;
