// GENERATED by scratchpad genlayout.cjs from Matt's editor export. Do not hand-edit; re-export
// from pinball/design/editor.html and regenerate.
//
// WHY THIS FILE EXISTS. Matt lays the board out in the editor and exports JSON. Those exports used
// to be transcribed into board.js by hand, one part at a time, and three of them were never applied
// at all - so the tool was showing him a board that existed nowhere but a scratch folder. Matt:
// *"why does the board look nothing like it did in the tool? I made many changes that you confirmed,
// but that I do not see here."* Now board.js READS the export.
//
// Shapes are in reference pixels (x 0..1100, y 0..1990), the editor's own units. `levels` is which
// deck a part belongs to; the editor's Level control writes it.
//
// THE RAMP LANE AND ITS RAILS ARE DELIBERATELY ABSENT. They were measured off the reference photo
// and rebuilt in board.js, and the editor's copy of them is still the old straight box, so letting
// this file set them would silently undo that work.

/** Parts Matt deleted in the editor. */
export const REMOVED = [
  "lane_rail_left",
  "lane_rail_right",
  "post_red_left_1",
  "post_red_right_1",
  "post_red_left_2",
  "post_red_right_2",
  "post_red_left_3",
  "post_red_right_3",
  "post_red_left_5",
  "post_red_right_5",
  "insert_dark_L1_1",
  "insert_dark_L1_2",
  "insert_dark_L1_3",
  "insert_dark_L1_4",
  "insert_yellow_side_1",
  "insert_yellow_side_2",
  "insert_green_wedge_3",
  "insert_green_wedge_4",
  "decal_teardrop"
];

/** Parts Matt drew or duplicated in the editor, with the part type each should be built as. */
export const ADDED = [
  {
    "name": "ramp_rail_right_in_copy_copy",
    "type": "wall",
    "mat": "steel",
    "levels": [
      1
    ]
  },
  {
    "name": "ramp_rail_right_in_copy_copy_copy",
    "type": "wall",
    "mat": "steel",
    "levels": [
      1
    ]
  },
  {
    "name": "ramp_rail_right_in_copy_copy_copy_2",
    "type": "wall",
    "mat": "steel",
    "levels": [
      1
    ]
  },
  {
    "name": "ramp_rail_right_in_copy_copy_copy_copy",
    "type": "wall",
    "mat": "steel",
    "levels": [
      1
    ]
  },
  {
    "name": "ramp_rail_right_in_copy_copy_copy_3",
    "type": "wall",
    "mat": "steel",
    "levels": [
      1
    ]
  },
  {
    "name": "ramp_rail_right_in_copy_copy_copy_copy_2",
    "type": "wall",
    "mat": "steel",
    "levels": [
      1
    ]
  },
  {
    "name": "insert_yellow_center_copy",
    "type": "disc",
    "mat": "yellow",
    "levels": [
      1
    ]
  },
  {
    "name": "insert_yellow_center_copy_copy",
    "type": "disc",
    "mat": "yellow",
    "levels": [
      1
    ]
  }
];

/** Every part's shape and level as the editor last exported it, by name. */
export const LAYOUT = {
  "arch_outer": {
    "k": "poly",
    "pts": [
      [
        181,
        775
      ],
      [
        171,
        757.35
      ],
      [
        161,
        739.71
      ],
      [
        153,
        722.06
      ],
      [
        147,
        704.41
      ],
      [
        144,
        686.76
      ],
      [
        140,
        669.12
      ],
      [
        138,
        651.47
      ],
      [
        135,
        633.82
      ],
      [
        132,
        616.18
      ],
      [
        131,
        598.53
      ],
      [
        128,
        580.88
      ],
      [
        126,
        563.24
      ],
      [
        124,
        545.59
      ],
      [
        130,
        510.29
      ],
      [
        145,
        457.35
      ],
      [
        165,
        413.24
      ],
      [
        195,
        369.12
      ],
      [
        213,
        333.82
      ],
      [
        227,
        316.18
      ],
      [
        239,
        298.53
      ],
      [
        247,
        280.88
      ],
      [
        263,
        263.24
      ],
      [
        285,
        261.47
      ],
      [
        345,
        257.94
      ],
      [
        425,
        253.53
      ],
      [
        495,
        250
      ],
      [
        565,
        253.53
      ],
      [
        645,
        257.94
      ],
      [
        695,
        261.47
      ],
      [
        711,
        263.24
      ],
      [
        727,
        280.88
      ],
      [
        743,
        298.53
      ],
      [
        751,
        316.18
      ],
      [
        759,
        333.82
      ],
      [
        785,
        369.12
      ],
      [
        815,
        413.24
      ],
      [
        835,
        457.35
      ],
      [
        851,
        510.29
      ],
      [
        857,
        545.59
      ],
      [
        859,
        563.24
      ],
      [
        861,
        580.88
      ],
      [
        861,
        598.53
      ],
      [
        861,
        616.18
      ],
      [
        859,
        633.82
      ],
      [
        855,
        651.47
      ],
      [
        851,
        669.12
      ],
      [
        842,
        686.76
      ],
      [
        836,
        704.41
      ],
      [
        828,
        722.06
      ],
      [
        821,
        739.71
      ],
      [
        812,
        757.35
      ],
      [
        804,
        775
      ],
      [
        771,
        775
      ],
      [
        771,
        757.35
      ],
      [
        769,
        739.71
      ],
      [
        775,
        722.06
      ],
      [
        779,
        704.41
      ],
      [
        783,
        686.76
      ],
      [
        785,
        669.12
      ],
      [
        785,
        642.65
      ],
      [
        784,
        616.18
      ],
      [
        783,
        598.53
      ],
      [
        778,
        580.88
      ],
      [
        772,
        563.24
      ],
      [
        770,
        554.41
      ],
      [
        767,
        545.59
      ],
      [
        767,
        527.94
      ],
      [
        752,
        501.47
      ],
      [
        737,
        485.59
      ],
      [
        697,
        441.47
      ],
      [
        675,
        402.65
      ],
      [
        645,
        381.47
      ],
      [
        615,
        367.35
      ],
      [
        585,
        360.29
      ],
      [
        555,
        353.24
      ],
      [
        525,
        347.94
      ],
      [
        495,
        346.18
      ],
      [
        465,
        353.24
      ],
      [
        435,
        360.29
      ],
      [
        405,
        367.35
      ],
      [
        375,
        381.47
      ],
      [
        345,
        395.59
      ],
      [
        315,
        409.71
      ],
      [
        285,
        441.47
      ],
      [
        255,
        485.59
      ],
      [
        240,
        501.47
      ],
      [
        225,
        527.94
      ],
      [
        225,
        545.59
      ],
      [
        220,
        563.24
      ],
      [
        214,
        580.88
      ],
      [
        211,
        598.53
      ],
      [
        210,
        607.35
      ],
      [
        207,
        625
      ],
      [
        203,
        651.47
      ],
      [
        201,
        669.12
      ],
      [
        203,
        686.76
      ],
      [
        209,
        704.41
      ],
      [
        213,
        722.06
      ],
      [
        217,
        757.35
      ],
      [
        219,
        775
      ]
    ]
  },
  "arch_inner": {
    "k": "poly",
    "pts": [
      [
        340,
        761.5
      ],
      [
        336,
        750.41
      ],
      [
        338,
        739.31
      ],
      [
        334,
        728.22
      ],
      [
        333,
        717.13
      ],
      [
        330,
        706.04
      ],
      [
        325,
        694.94
      ],
      [
        321,
        683.85
      ],
      [
        317,
        672.76
      ],
      [
        318,
        650.57
      ],
      [
        320,
        550.74
      ],
      [
        350,
        510.8
      ],
      [
        380,
        484.18
      ],
      [
        410,
        453.12
      ],
      [
        440,
        444.25
      ],
      [
        470,
        435.37
      ],
      [
        500,
        426.5
      ],
      [
        530,
        433.16
      ],
      [
        560,
        444.25
      ],
      [
        590,
        453.12
      ],
      [
        620,
        484.18
      ],
      [
        650,
        510.8
      ],
      [
        680,
        550.74
      ],
      [
        683,
        650.57
      ],
      [
        684,
        672.76
      ],
      [
        682,
        683.85
      ],
      [
        678,
        694.94
      ],
      [
        673,
        706.04
      ],
      [
        670,
        717.13
      ],
      [
        670,
        728.22
      ],
      [
        666,
        739.31
      ],
      [
        667,
        750.41
      ],
      [
        664,
        761.5
      ],
      [
        640,
        761.5
      ],
      [
        636,
        750.41
      ],
      [
        637,
        739.31
      ],
      [
        634,
        728.22
      ],
      [
        634,
        717.13
      ],
      [
        637,
        706.04
      ],
      [
        639,
        694.94
      ],
      [
        640,
        683.85
      ],
      [
        641,
        672.76
      ],
      [
        634,
        639.48
      ],
      [
        628,
        595.11
      ],
      [
        620,
        568.49
      ],
      [
        590,
        555.18
      ],
      [
        560,
        537.43
      ],
      [
        530,
        528.55
      ],
      [
        500,
        524.12
      ],
      [
        470,
        528.55
      ],
      [
        440,
        537.43
      ],
      [
        410,
        555.18
      ],
      [
        380,
        568.49
      ],
      [
        372,
        595.11
      ],
      [
        366,
        639.48
      ],
      [
        363,
        672.76
      ],
      [
        365,
        683.85
      ],
      [
        367,
        694.94
      ],
      [
        368,
        706.04
      ],
      [
        370,
        717.13
      ],
      [
        369,
        728.22
      ],
      [
        366,
        739.31
      ],
      [
        368,
        750.41
      ],
      [
        364,
        761.5
      ]
    ]
  },
  "arch_centre": {
    "k": "poly",
    "pts": [
      [
        432,
        700
      ],
      [
        432,
        672
      ],
      [
        436,
        646
      ],
      [
        448,
        626
      ],
      [
        468,
        614
      ],
      [
        500,
        611
      ],
      [
        532,
        614
      ],
      [
        552,
        626
      ],
      [
        564,
        646
      ],
      [
        568,
        672
      ],
      [
        568,
        700
      ],
      [
        548,
        700
      ],
      [
        548,
        676
      ],
      [
        544,
        654
      ],
      [
        534,
        640
      ],
      [
        520,
        632
      ],
      [
        500,
        630
      ],
      [
        480,
        632
      ],
      [
        466,
        640
      ],
      [
        456,
        654
      ],
      [
        452,
        676
      ],
      [
        452,
        700
      ]
    ]
  },
  "saucer_centre": {
    "k": "circle",
    "pts": [
      [
        500,
        656
      ]
    ],
    "r": 30.36
  },
  "post_big_left": {
    "k": "circle",
    "pts": [
      [
        350,
        750
      ]
    ],
    "r": 17.08
  },
  "post_big_right": {
    "k": "circle",
    "pts": [
      [
        646,
        745
      ]
    ],
    "r": 17.08
  },
  "post_exit_left": {
    "k": "circle",
    "pts": [
      [
        198,
        750
      ]
    ],
    "r": 11.39
  },
  "post_exit_right": {
    "k": "circle",
    "pts": [
      [
        783,
        750
      ]
    ],
    "r": 11.39
  },
  "post_apron_left_1": {
    "k": "circle",
    "pts": [
      [
        131.25,
        1707.5
      ]
    ],
    "r": 11.39
  },
  "post_apron_right_1": {
    "k": "circle",
    "pts": [
      [
        854.75,
        1707.5
      ]
    ],
    "r": 11.39
  },
  "post_apron_left_2": {
    "k": "circle",
    "pts": [
      [
        217.5,
        1765
      ]
    ],
    "r": 11.39
  },
  "post_apron_right_2": {
    "k": "circle",
    "pts": [
      [
        768.5,
        1765
      ]
    ],
    "r": 11.39
  },
  "post_apron_left_3": {
    "k": "circle",
    "pts": [
      [
        303.75,
        1822.5
      ]
    ],
    "r": 11.39
  },
  "post_apron_right_3": {
    "k": "circle",
    "pts": [
      [
        682.25,
        1822.5
      ]
    ],
    "r": 11.39
  },
  "apron_funnel_left": {
    "k": "capsule",
    "pts": [
      [
        390,
        1880
      ],
      [
        390,
        1950
      ]
    ],
    "w": 11.39
  },
  "apron_funnel_right": {
    "k": "capsule",
    "pts": [
      [
        596,
        1880
      ],
      [
        596,
        1950
      ]
    ],
    "w": 11.39
  },
  "flipper_lower_left": {
    "k": "capsule",
    "pts": [
      [
        325,
        1705
      ],
      [
        440,
        1795
      ]
    ],
    "w": 45.54
  },
  "flipper_lower_right": {
    "k": "capsule",
    "pts": [
      [
        661,
        1705
      ],
      [
        546,
        1795
      ]
    ],
    "w": 45.54
  },
  "flipper_upper_left": {
    "k": "capsule",
    "pts": [
      [
        330,
        622
      ],
      [
        440,
        690
      ]
    ],
    "w": 45.54
  },
  "flipper_upper_right": {
    "k": "capsule",
    "pts": [
      [
        656,
        622
      ],
      [
        546,
        690
      ]
    ],
    "w": 45.54
  },
  "bumper_upper_left": {
    "k": "circle",
    "pts": [
      [
        385,
        270
      ]
    ],
    "r": 66
  },
  "bumper_upper_right": {
    "k": "circle",
    "pts": [
      [
        601,
        270
      ]
    ],
    "r": 66
  },
  "post_red_left_4": {
    "k": "circle",
    "pts": [
      [
        150,
        440
      ]
    ],
    "r": 13.28
  },
  "post_red_right_4": {
    "k": "circle",
    "pts": [
      [
        836,
        440
      ]
    ],
    "r": 13.28
  },
  "guide_rail_upper_left": {
    "k": "capsule",
    "pts": [
      [
        150,
        440
      ],
      [
        320,
        610
      ]
    ],
    "w": 11.39
  },
  "guide_rail_upper_right": {
    "k": "capsule",
    "pts": [
      [
        836,
        440
      ],
      [
        666,
        610
      ]
    ],
    "w": 11.39
  },
  "target_bank": {
    "k": "poly",
    "pts": [
      [
        393,
        51
      ],
      [
        602,
        51
      ],
      [
        602,
        73
      ],
      [
        393,
        73
      ]
    ]
  },
  "insert_yellow_center": {
    "k": "circle",
    "pts": [
      [
        505,
        765
      ]
    ],
    "levels": [
      1
    ],
    "r": 20.87
  },
  "insert_magenta_1": {
    "k": "circle",
    "pts": [
      [
        200,
        215
      ]
    ],
    "levels": [
      2
    ],
    "r": 20.87
  },
  "insert_magenta_2": {
    "k": "circle",
    "pts": [
      [
        498,
        363
      ]
    ],
    "levels": [
      2
    ],
    "r": 20.87
  },
  "insert_magenta_3": {
    "k": "circle",
    "pts": [
      [
        493,
        118
      ]
    ],
    "levels": [
      2
    ],
    "r": 20.87
  },
  "insert_magenta_4": {
    "k": "circle",
    "pts": [
      [
        786,
        215
      ]
    ],
    "levels": [
      2
    ],
    "r": 20.87
  },
  "insert_blue_1": {
    "k": "circle",
    "pts": [
      [
        183,
        1145
      ]
    ],
    "r": 20.87
  },
  "insert_blue_2": {
    "k": "circle",
    "pts": [
      [
        239.7,
        1070.5
      ]
    ],
    "r": 20.87
  },
  "insert_blue_3": {
    "k": "circle",
    "pts": [
      [
        313.8,
        1013.3
      ]
    ],
    "r": 20.87
  },
  "insert_blue_4": {
    "k": "circle",
    "pts": [
      [
        400.2,
        977.3
      ]
    ],
    "r": 20.87
  },
  "insert_blue_5": {
    "k": "circle",
    "pts": [
      [
        493,
        965
      ]
    ],
    "r": 20.87
  },
  "insert_blue_6": {
    "k": "circle",
    "pts": [
      [
        585.8,
        977.3
      ]
    ],
    "r": 20.87
  },
  "insert_blue_7": {
    "k": "circle",
    "pts": [
      [
        672.2,
        1013.3
      ]
    ],
    "r": 20.87
  },
  "insert_blue_8": {
    "k": "circle",
    "pts": [
      [
        746.3,
        1070.5
      ]
    ],
    "r": 20.87
  },
  "insert_blue_9": {
    "k": "circle",
    "pts": [
      [
        803,
        1145
      ]
    ],
    "r": 20.87
  },
  "insert_red_1": {
    "k": "circle",
    "pts": [
      [
        265,
        1255
      ]
    ],
    "r": 20.87
  },
  "insert_red_2": {
    "k": "circle",
    "pts": [
      [
        410.5,
        1177.2
      ]
    ],
    "r": 20.87
  },
  "insert_red_3": {
    "k": "circle",
    "pts": [
      [
        575.5,
        1177.2
      ]
    ],
    "r": 20.87
  },
  "insert_red_4": {
    "k": "circle",
    "pts": [
      [
        721,
        1255
      ]
    ],
    "r": 20.87
  },
  "saucer_left": {
    "k": "circle",
    "pts": [
      [
        85,
        110
      ]
    ],
    "r": 30.36
  },
  "saucer_right": {
    "k": "circle",
    "pts": [
      [
        901,
        110
      ]
    ],
    "r": 30.36
  },
  "insert_green_wedge_1": {
    "k": "poly",
    "pts": [
      [
        155,
        940
      ],
      [
        164,
        1010.5
      ],
      [
        206,
        989.5
      ]
    ]
  },
  "insert_green_wedge_2": {
    "k": "poly",
    "pts": [
      [
        831,
        940
      ],
      [
        780,
        989.5
      ],
      [
        822,
        1010.5
      ]
    ]
  },
  "ramp_rail_right_in_copy_copy": {
    "k": "capsule",
    "pts": [
      [
        792,
        1406.92
      ],
      [
        792,
        1503.08
      ]
    ],
    "w": 3.85
  },
  "ramp_rail_right_in_copy_copy_copy": {
    "k": "capsule",
    "pts": [
      [
        199,
        1406.92
      ],
      [
        199,
        1503.08
      ]
    ],
    "w": 3.85
  },
  "ramp_rail_right_in_copy_copy_copy_2": {
    "k": "capsule",
    "pts": [
      [
        126.42,
        1553.93
      ],
      [
        307.58,
        1680.07
      ]
    ],
    "w": 8.86
  },
  "ramp_rail_right_in_copy_copy_copy_copy": {
    "k": "capsule",
    "pts": [
      [
        124,
        1349.04
      ],
      [
        124,
        1550.96
      ]
    ],
    "w": 8.08
  },
  "ramp_rail_right_in_copy_copy_copy_3": {
    "k": "capsule",
    "pts": [
      [
        868.46,
        1557.04
      ],
      [
        677.54,
        1682.96
      ]
    ],
    "w": 9.08
  },
  "ramp_rail_right_in_copy_copy_copy_copy_2": {
    "k": "capsule",
    "pts": [
      [
        867,
        1349.04
      ],
      [
        867,
        1550.96
      ]
    ],
    "w": 8.08
  },
  "slingshot_left": {
    "k": "poly",
    "pts": [
      [
        407.5,
        1632.88
      ],
      [
        305.28,
        1456.32
      ],
      [
        254.48,
        1542.83
      ]
    ]
  },
  "slingshot_right": {
    "k": "poly",
    "pts": [
      [
        577.61,
        1637.58
      ],
      [
        664.05,
        1452.78
      ],
      [
        722.2,
        1534.53
      ]
    ]
  },
  "insert_yellow_center_copy": {
    "k": "circle",
    "pts": [
      [
        500,
        570
      ]
    ],
    "levels": [
      1
    ],
    "r": 20.87
  },
  "insert_yellow_center_copy_copy": {
    "k": "circle",
    "pts": [
      [
        495,
        390
      ]
    ],
    "levels": [
      1
    ],
    "r": 20.87
  }
};
