// ball-run/js/strings.js — every user-visible string in Ball Run, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Difficulty keys (easy/medium/hard) are storage vocabulary (ballrun.difficulty) and
// stay canonical — only display labels translate. config.js's own DIFFICULTIES[].label stays
// English (a tuning/config module, same discipline as sim.js/track.js); ui.js maps the same keys
// onto t() here instead of importing it for display.

export const STRINGS = {
  en: {
    title: 'BALL RUN',
    blurb: 'Steer your ball by dragging your finger left and right. Avoid obstacles and stay on the track. Survive as long as you can!',
    best_passed: 'Best: {n} passed',
    no_runs_yet: 'No runs yet',
    map_classic: 'Classic',
    map_orbital: 'Orbital',
    map_aria: 'Map',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    diff_aria: 'Difficulty',
    play: 'PLAY',
    howto_aria: 'How to play',
    score_aria: 'Obstacles passed',
    resume: 'Tap to resume',
    close: 'Close',
    run_over: 'Run over',
    fell_off: 'You fell off!',
    crashed: 'Crashed!',
    obstacles_passed: '{n} obstacles passed',
    distance_m: 'Distance: {n} m',
    new_best: 'New best!',
    best_n: 'Best: {n}',
    play_again: 'Play Again',
    back_to_hub: 'Back to hub',
    howto_title: 'HOW TO PLAY',
    help_1: 'Hold and drag to steer.',
    help_2: 'Dodge the obstacles, or the run ends.',
    help_3: "Don't fall off the edge.",
    help_4: 'Each speedpoint makes you faster. Survive for the highest score.',
    prev_page_aria: 'Previous page',
    next_page_aria: 'Next page',
    ok: 'OK',
  },
  es: {
    title: 'CARRERA DE BOLAS',
    blurb: 'Guía tu bola arrastrando el dedo a izquierda y derecha. Esquiva obstáculos y no te salgas de la pista. ¡Sobrevive todo lo que puedas!',
    best_passed: 'Mejor: {n} superados',
    no_runs_yet: 'Todavía sin carreras',
    map_classic: 'Clásico',
    map_orbital: 'Orbital',
    map_aria: 'Mapa',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    diff_aria: 'Dificultad',
    play: 'JUGAR',
    howto_aria: 'Cómo se juega',
    score_aria: 'Obstáculos superados',
    resume: 'Toca para continuar',
    close: 'Cerrar',
    run_over: 'Carrera terminada',
    fell_off: '¡Te caíste!',
    crashed: '¡Chocaste!',
    obstacles_passed: '{n} obstáculos superados',
    distance_m: 'Distancia: {n} m',
    new_best: '¡Nuevo récord!',
    best_n: 'Mejor: {n}',
    play_again: 'Jugar otra vez',
    back_to_hub: 'Volver al hub',
    howto_title: 'CÓMO SE JUEGA',
    help_1: 'Mantén presionado y arrastra para guiar la bola.',
    help_2: 'Esquiva los obstáculos o la carrera termina.',
    help_3: 'No te salgas de la pista.',
    help_4: 'Cada punto de velocidad te hace más rápido. Sobrevive para conseguir la puntuación más alta.',
    prev_page_aria: 'Página anterior',
    next_page_aria: 'Página siguiente',
    ok: 'Aceptar',
  },
};

export default STRINGS;
