// battleship/js/strings.js — every user-visible string in Battleship, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows
// English for anything missing). Ship-class names TRANSLATE (they're vocabulary); cell notation
// (A1, B7) does NOT (it's coordinates, not a word); difficulty/size/mp keys stay canonical.
//
// `title` here is one of the THREE places the display title lives (root CLAUDE.md section 10 /
// js/CLAUDE.md "Language support") alongside js/strings.js's game_title_battleship and the hub
// GAMES entry's title — keep all three in step.

export const STRINGS = {
  en: {
    title: 'Battleship',
    tagline: 'Sink the enemy fleet before they sink yours.',
    play_vs_bot: 'Play vs. Bot',
    play_vs_friend: 'Play vs. Friend',
    options_label: 'Options',
    chip_size: 'Board',
    chip_first: 'First shot',
    chip_bonus: 'Bonus shot',
    deploy_title: 'Deploy your ships',
    random: 'Random',
    save: 'Save',
    exit: 'Exit',
    fleet_ready_hint: 'Fleet ready. Tap SAVE to sail.',
    bot_placing: 'Bot is placing ships',
    waiting_for_opponent: 'Waiting for {opp}',
    bot_thinking: 'Bot thinking',
    shot_away: 'Shot away!',
    shot_incoming: 'Incoming!',
    score_aria: 'Ships sunk: {them} theirs, {me} yours',
    valid_placement_aria: 'Fits here',
    stats_line: '{total} played · {w}-{l} · {acc}% avg accuracy',
    vs: 'vs',
    you: 'You',
    computer: 'Computer',
    row_opponent: 'Opponent',
    opponent_bot: 'Bot',
    opponent_friend: 'Play a friend',
    row_difficulty: 'Difficulty',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    row_size: 'Board size',
    size_quick: 'Quick (8x8)',
    size_classic: 'Classic (10x10)',
    hint_size_quick: 'Battleship, Cruiser, Submarine, Destroyer. Faster games.',
    hint_size_classic: 'Adds the Carrier. The full classic fleet.',
    row_first: 'First shot',
    first_alternate: 'Alternate',
    row_bonus: 'Bonus shot on hit',
    bonus_off: 'Off',
    bonus_on: 'On',
    hint_bonus: 'A hit keeps your turn. A miss passes it.',
    start: 'Place your fleet',
    howto: 'How to play',
    change_settings: 'Change settings',
    new_game: 'New game',
    play_again: 'Play again',
    restart_game: 'Restart',
    tap_again_confirm: 'Tap again to confirm',
    close: 'Close',
    game_over: 'Game over',
    you_win: 'Victory!',
    opp_wins: '{opp} wins',
    // --- placement screen ---
    placement_title: 'Place your fleet',
    placement_hint: 'Drag a ship onto the grid. Tap to rotate.',
    auto_place: 'Auto-place',
    clear_fleet: 'Clear',
    ships_remaining: '{n} ships left to place',
    ready: 'Ready',
    waiting_for_opponent_placement: 'Waiting for {opp} to place their fleet...',
    ship_carrier: 'Carrier',
    ship_battleship: 'Battleship',
    ship_cruiser: 'Cruiser',
    ship_submarine: 'Submarine',
    ship_destroyer: 'Destroyer',
    placement_cell_aria: 'Row {r}, column {c}',
    invalid_placement_aria: 'Cannot place {ship} here',
    // --- battle screen ---
    your_waters: 'Your fleet',
    // --- the shot: aim, confirm, result. Words on purpose (Matt, 2026-08-11: "There's no 'fire' or
    // confirm and then there's no 'hit' or 'miss'"). A result is news, not an instruction.
    fire: 'Fire',
    res_hit: 'HIT!',
    res_miss: 'MISS',
    res_sunk: 'SUNK!',
    your_turn: 'Your turn: fire!',
    opp_turn: "{opp}'s turn",
    opp_thinking: '{opp} is aiming...',
    bonus_turn_continues: 'Hit! Fire again.',
    shots_fired: 'Shots: {n}',
    sunk_banner: 'Sunk: {ship}',
    shot_cell_aria: 'Row {r}, column {c}, {state}',
    cell_unknown: 'unfired',
    cell_miss: 'miss',
    cell_hit: 'hit',
    cell_sunk: 'sunk',
    fleet_status_afloat: '{ship} afloat',
    fleet_status_sunk: '{ship} sunk',
    // --- how to play ---
    help_lead: 'Sink every ship in the enemy fleet before they sink yours.',
    help_caption: 'Ships may sit right next to each other, edge to edge.',
    help_rule: 'Fire once per turn, unless Bonus shot on hit is on.',
    // --- multiplayer ---
    mode_solo: 'Solo',
    mode_host: 'Host',
    mode_join: 'Join',
    mp_host_btn: 'Create room',
    mp_host_hint: 'Play someone else on their own phone.',
    mp_join_hint: 'Ask the host for their 4-character code.',
    mp_creating_room: 'Creating room...',
    mp_joining: 'Joining...',
    mp_enter_code: 'Enter code',
    mp_code_aria: 'Room code',
    mp_join_btn: 'Join',
    mp_back_btn: 'Back',
    mp_start_btn: 'Start',
    mp_share_code: 'Share this code with your opponent.',
    mp_waiting_opponent: 'Waiting for someone to join',
    mp_waiting_host: 'Waiting for host',
    mp_opponent_label: 'Opponent',
    mp_host_label: 'Host',
    mp_leave_btn: 'Leave',
    mp_series: 'You {me} · {opp} {them}',
    mp_waiting_rematch: 'Waiting for {opp} to start another game',
    mp_status_connection_error: 'Connection error',
    mp_status_resyncing: 'Resyncing...',
    mp_status_opponent_disconnected: 'Opponent disconnected',
    mp_status_waiting_placement: 'Waiting for {opp} to finish placing their fleet',
    mp_update_required: 'Update required',
    mp_err_could_not_create_room: 'Could not create a room',
    mp_err_offline: 'Offline',
    mp_err_room_not_found: 'Room not found',
    mp_err_room_full: 'Room full',
    mp_err_wrong_game: 'That code is for another game',
    mp_error_title: 'Connection error',
    mp_error_sub: 'The game could not stay in sync',
    mp_opponent_left_title: 'Opponent left',
    mp_opponent_left_sub: 'The room is closed',
    mp_cannot_resume_title: "Can't resume this match",
    mp_cannot_resume_sub: "This device lost its saved fleet, so this match can't continue here.",
    mp_back_to_setup: 'Back to setup',
  },
  es: {
    title: 'Hundir la Flota',
    tagline: 'Hunde la flota enemiga antes de que hundan la tuya.',
    play_vs_bot: 'Jugar vs. Bot',
    play_vs_friend: 'Jugar vs. Amigo',
    options_label: 'Opciones',
    chip_size: 'Tablero',
    chip_first: 'Primer disparo',
    chip_bonus: 'Disparo extra',
    deploy_title: 'Despliega tus barcos',
    random: 'Aleatorio',
    save: 'Guardar',
    exit: 'Salir',
    fleet_ready_hint: 'Flota lista. Toca GUARDAR para zarpar.',
    bot_placing: 'El bot está colocando sus barcos',
    waiting_for_opponent: 'Esperando a {opp}',
    bot_thinking: 'El bot apunta',
    shot_away: 'Disparo lanzado',
    shot_incoming: 'Fuego enemigo',
    score_aria: 'Barcos hundidos: {them} suyos, {me} tuyos',
    valid_placement_aria: 'Cabe aquí',
    stats_line: '{total} jugadas · {w}-{l} · {acc}% precisión media',
    vs: 'vs',
    you: 'Tú',
    computer: 'Ordenador',
    row_opponent: 'Rival',
    opponent_bot: 'Bot',
    opponent_friend: 'Jugar con un amigo',
    row_difficulty: 'Dificultad',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    row_size: 'Tamaño del tablero',
    size_quick: 'Rápida (8x8)',
    size_classic: 'Clásica (10x10)',
    hint_size_quick: 'Acorazado, Crucero, Submarino, Destructor. Partidas más rápidas.',
    hint_size_classic: 'Añade el Portaaviones. La flota clásica completa.',
    row_first: 'Primer disparo',
    first_alternate: 'Alternar',
    row_bonus: 'Disparo extra al acertar',
    bonus_off: 'Desactivado',
    bonus_on: 'Activado',
    hint_bonus: 'Un acierto mantiene tu turno. Un fallo lo pasa.',
    start: 'Coloca tu flota',
    howto: 'Cómo se juega',
    change_settings: 'Cambiar ajustes',
    new_game: 'Nueva partida',
    play_again: 'Jugar otra vez',
    restart_game: 'Reiniciar',
    tap_again_confirm: 'Toca otra vez para confirmar',
    close: 'Cerrar',
    game_over: 'Fin de la partida',
    you_win: '¡Victoria!',
    opp_wins: '{opp} gana',
    placement_title: 'Coloca tu flota',
    placement_hint: 'Arrastra un barco a la cuadrícula. Toca para rotarlo.',
    auto_place: 'Colocar automáticamente',
    clear_fleet: 'Borrar',
    ships_remaining: 'Quedan {n} barcos por colocar',
    ready: 'Listo',
    waiting_for_opponent_placement: 'Esperando a que {opp} coloque su flota...',
    ship_carrier: 'Portaaviones',
    ship_battleship: 'Acorazado',
    ship_cruiser: 'Crucero',
    ship_submarine: 'Submarino',
    ship_destroyer: 'Destructor',
    placement_cell_aria: 'Fila {r}, columna {c}',
    invalid_placement_aria: 'No se puede colocar {ship} aquí',
    your_waters: 'Tu flota',
    your_turn: 'Tu turno: ¡dispara!',
    fire: 'Fuego',
    res_hit: '¡TOCADO!',
    res_miss: 'AGUA',
    res_sunk: '¡HUNDIDO!',
    opp_turn: 'Turno de {opp}',
    opp_thinking: '{opp} está apuntando...',
    bonus_turn_continues: '¡Acierto! Dispara otra vez.',
    shots_fired: 'Disparos: {n}',
    sunk_banner: 'Hundido: {ship}',
    shot_cell_aria: 'Fila {r}, columna {c}, {state}',
    cell_unknown: 'sin disparar',
    cell_miss: 'agua',
    cell_hit: 'tocado',
    cell_sunk: 'hundido',
    fleet_status_afloat: '{ship} a flote',
    fleet_status_sunk: '{ship} hundido',
    help_lead: 'Hunde todos los barcos de la flota enemiga antes de que hundan los tuyos.',
    help_caption: 'Los barcos pueden colocarse justo uno junto a otro, borde con borde.',
    help_rule: 'Dispara una vez por turno, salvo que el disparo extra al acertar esté activado.',
    mode_solo: 'Solo',
    mode_host: 'Crear',
    mode_join: 'Unirse',
    mp_host_btn: 'Crear sala',
    mp_host_hint: 'Juega contra alguien en su propio móvil.',
    mp_join_hint: 'Pide al anfitrión su código de 4 caracteres.',
    mp_creating_room: 'Creando sala...',
    mp_joining: 'Uniéndose...',
    mp_enter_code: 'Introduce el código',
    mp_code_aria: 'Código de sala',
    mp_join_btn: 'Unirse',
    mp_back_btn: 'Atrás',
    mp_start_btn: 'Empezar',
    mp_share_code: 'Comparte este código con tu rival.',
    mp_waiting_opponent: 'Esperando a que alguien entre',
    mp_waiting_host: 'Esperando al anfitrión',
    mp_opponent_label: 'Rival',
    mp_host_label: 'Anfitrión',
    mp_leave_btn: 'Salir',
    mp_series: 'Tú {me} · {opp} {them}',
    mp_waiting_rematch: 'Esperando a que {opp} empiece otra partida',
    mp_status_connection_error: 'Error de conexión',
    mp_status_resyncing: 'Resincronizando...',
    mp_status_opponent_disconnected: 'Rival desconectado',
    mp_status_waiting_placement: 'Esperando a que {opp} termine de colocar su flota',
    mp_update_required: 'Actualización necesaria',
    mp_err_could_not_create_room: 'No se pudo crear la sala',
    mp_err_offline: 'Sin conexión',
    mp_err_room_not_found: 'Sala no encontrada',
    mp_err_room_full: 'Sala llena',
    mp_err_wrong_game: 'Ese código es de otro juego',
    mp_error_title: 'Error de conexión',
    mp_error_sub: 'La partida no pudo mantenerse sincronizada',
    mp_opponent_left_title: 'El rival se fue',
    mp_opponent_left_sub: 'La sala está cerrada',
    mp_cannot_resume_title: 'No se puede reanudar esta partida',
    mp_cannot_resume_sub: 'Este dispositivo perdió su flota guardada, así que la partida no puede continuar aquí.',
    mp_back_to_setup: 'Volver a ajustes',
  },
};

export default STRINGS;
