// dots-boxes/js/strings.js — every user-visible string in Dots and Boxes, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows
// English for anything missing). Values (size key small/medium/large, difficulty key
// beginner/intermediate/pro) are storage vocabulary and stay canonical — only display labels
// translate.

export const STRINGS = {
  en: {
    title: 'Dots and Boxes',
    tagline: 'Draw lines, close boxes, chain your captures.',
    stats_line: '{played} played · {w}-{l}-{t} · best chain {chain}',
    vs: 'vs',
    row_size: 'Board size',
    row_difficulty: 'Difficulty',
    row_first: 'First move',
    size_small: 'Small',
    size_medium: 'Medium',
    size_large: 'Large',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    you: 'You',
    alternate: 'Alternate',
    hint_size_boxes: '{rows}×{cols} boxes.',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'Menu',
    restart_game: 'Restart',
    tap_again_confirm: 'Tap again to confirm',
    change_settings: 'Change settings',
    tie_game: 'Tie game!',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    opp_claims_again: '{opp} claims a box and goes again...',
    opp_thinking: '{opp} is thinking...',
    you_claimed_again: 'You claimed a box! Go again',
    your_turn: 'Your turn',
    opp_turn: "{opp}'s turn",
    line_drawn: 'Line already drawn',
    draw_line: 'Draw line',
    edge_h_aria: '{state}, row {r}, between columns {c1} and {c2}',
    edge_v_aria: '{state}, column {c}, between rows {r1} and {r2}',
    box_capturable_aria: 'Box, row {r} column {c}, one line away from being claimed',
    box_empty_aria: 'Box, row {r} column {c}, empty',
    box_claimed_aria: 'Box, row {r} column {c}, claimed by {who}',
    board_aria: 'Dots and Boxes board',
    game_over: 'Game over',
    close: 'Close',
    play_again: 'Play again',
    help_lead: 'Fill in the most boxes to win.',
    help_diagram_aria: 'Completing the fourth side of a box claims it and lets you play again',
    help_caption: 'Draw the 4th side of a box to fill it in.',
    help_example: 'Complete a box = You play again',
    help_rule: 'The turn passes to your opponent.',
  },
  es: {
    title: 'Puntos y Cajas',
    tagline: 'Dibuja líneas, cierra cajas y encadena tus capturas.',
    stats_line: '{played} jugadas · {w}-{l}-{t} · mejor cadena {chain}',
    vs: 'vs',
    row_size: 'Tamaño del tablero',
    row_difficulty: 'Dificultad',
    row_first: 'Primer movimiento',
    size_small: 'Pequeño',
    size_medium: 'Mediano',
    size_large: 'Grande',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Pro',
    you: 'Tú',
    alternate: 'Alternar',
    hint_size_boxes: '{rows}×{cols} cajas.',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Menú',
    restart_game: 'Reiniciar',
    tap_again_confirm: 'Toca otra vez para confirmar',
    change_settings: 'Cambiar ajustes',
    tie_game: '¡Empate!',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    opp_claims_again: '{opp} captura una caja y sigue...',
    opp_thinking: '{opp} está pensando...',
    you_claimed_again: '¡Capturaste una caja! Sigue jugando',
    your_turn: 'Tu turno',
    opp_turn: 'Turno de {opp}',
    line_drawn: 'Línea ya dibujada',
    draw_line: 'Dibujar línea',
    edge_h_aria: '{state}, fila {r}, entre las columnas {c1} y {c2}',
    edge_v_aria: '{state}, columna {c}, entre las filas {r1} y {r2}',
    box_capturable_aria: 'Caja, fila {r} columna {c}, a una línea de ser capturada',
    box_empty_aria: 'Caja, fila {r} columna {c}, vacía',
    box_claimed_aria: 'Caja, fila {r} columna {c}, capturada por {who}',
    board_aria: 'Tablero de Dots and Boxes',
    game_over: 'Fin de la partida',
    close: 'Cerrar',
    play_again: 'Jugar otra vez',
    help_lead: 'Rellena más cajas que nadie para ganar.',
    help_diagram_aria: 'Completar el cuarto lado de una caja la captura y te deja jugar otra vez',
    help_caption: 'Dibuja el 4º lado de una caja para rellenarla.',
    help_example: 'Completa una caja = Juegas otra vez',
    help_rule: 'El turno pasa a tu rival.',
  },
};

export default STRINGS;
