// dots-boxes/js/strings.js — every user-visible string in Dots and Boxes, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows
// English for anything missing). Values (size key small/medium/large, difficulty key
// beginner/intermediate/pro) are storage vocabulary and stay canonical — only display labels
// translate.

export const STRINGS = {
  en: {
    title: 'Dots and Boxes',
    tagline: 'Draw lines, close boxes, chain your captures.',
    stats_line: '{played} played · {w}-{l}-{t} · best chain {chain}',
    vs: 'vs',
    row_size: 'Board size',
    row_difficulty: 'Difficulty',
    row_first: 'First move',
    size_small: 'Small',
    size_medium: 'Medium',
    size_large: 'Large',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    you: 'You',
    computer: 'Computer',
    alternate: 'Alternate',
    hint_size_boxes: '{rows}×{cols} boxes.',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'Menu',
    restart_game: 'Restart',
    tap_again_confirm: 'Tap again to confirm',
    change_settings: 'Change settings',
    tie_game: 'Tie game!',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    opp_claims_again: '{opp} claims a box and goes again...',
    opp_thinking: '{opp} is thinking...',
    you_claimed_again: 'You claimed a box! Go again',
    your_turn: 'Your turn',
    opp_turn: "{opp}'s turn",
    line_drawn: 'Line already drawn',
    draw_line: 'Draw line',
    edge_h_aria: '{state}, row {r}, between columns {c1} and {c2}',
    edge_v_aria: '{state}, column {c}, between rows {r1} and {r2}',
    box_capturable_aria: 'Box, row {r} column {c}, one line away from being claimed',
    box_empty_aria: 'Box, row {r} column {c}, empty',
    box_claimed_aria: 'Box, row {r} column {c}, claimed by {who}',
    board_aria: 'Dots and Boxes board',
    game_over: 'Game over',
    close: 'Close',
    play_again: 'Play again',
    help_lead: 'Fill in the most boxes to win.',
    help_diagram_aria: 'Completing the fourth side of a box claims it and lets you play again',
    help_caption: 'Draw the 4th side of a box to fill it in.',
    help_example: 'Complete a box = You play again',
    help_rule: 'The turn passes to your opponent.',
    mode_solo: 'Solo',
    mode_host: 'Host',
    mode_join: 'Join',
    mp_host_btn: 'Create room',
    mp_host_hint: 'Play someone else on their own phone.',
    mp_join_hint: 'Ask the host for their 4-character code.',
    mp_creating_room: 'Creating room...',
    mp_joining: 'Joining...',
    mp_enter_code: 'Enter code',
    mp_code_aria: 'Room code',
    mp_join_btn: 'Join',
    mp_back_btn: 'Back',
    mp_start_btn: 'Start',
    mp_share_code: 'Share this code with your opponent.',
    mp_waiting_opponent: 'Waiting for someone to join',
    mp_waiting_host: 'Waiting for host',
    mp_opponent_label: 'Opponent',
    mp_host_label: 'Host',
    mp_leave_btn: 'Leave',
    mp_status_connection_error: 'Connection error',
    mp_status_resyncing: 'Resyncing...',
    mp_status_opponent_disconnected: 'Opponent disconnected',
    mp_update_required: 'Update required',
    mp_err_could_not_create_room: 'Could not create a room',
    mp_err_offline: 'Offline',
    mp_err_room_not_found: 'Room not found',
    mp_err_room_full: 'Room full',
    mp_err_wrong_game: 'That code is for another game',
    mp_error_title: 'Connection error',
    mp_error_sub: 'The game could not stay in sync',
    mp_opponent_left_title: 'Opponent left',
    mp_opponent_left_sub: 'The room is closed',
    mp_back_to_setup: 'Back to setup',
    mp_series: 'You {me} · {opp} {them} · Drawn {d}',
    mp_waiting_rematch: 'Waiting for {opp} to start another game',
  },
  es: {
    title: 'Puntos y Cajas',
    tagline: 'Dibuja líneas, cierra cajas y encadena tus capturas.',
    stats_line: '{played} jugadas · {w}-{l}-{t} · mejor cadena {chain}',
    vs: 'vs',
    row_size: 'Tamaño del tablero',
    row_difficulty: 'Dificultad',
    row_first: 'Primer movimiento',
    size_small: 'Pequeño',
    size_medium: 'Mediano',
    size_large: 'Grande',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    you: 'Tú',
    computer: 'Ordenador',
    alternate: 'Alternar',
    hint_size_boxes: '{rows}×{cols} cajas.',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Menú',
    restart_game: 'Reiniciar',
    tap_again_confirm: 'Toca otra vez para confirmar',
    change_settings: 'Cambiar ajustes',
    tie_game: '¡Empate!',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    opp_claims_again: '{opp} captura una caja y sigue...',
    opp_thinking: '{opp} está pensando...',
    you_claimed_again: '¡Capturaste una caja! Sigue jugando',
    your_turn: 'Tu turno',
    opp_turn: 'Turno de {opp}',
    line_drawn: 'Línea ya dibujada',
    draw_line: 'Dibujar línea',
    edge_h_aria: '{state}, fila {r}, entre las columnas {c1} y {c2}',
    edge_v_aria: '{state}, columna {c}, entre las filas {r1} y {r2}',
    box_capturable_aria: 'Caja, fila {r} columna {c}, a una línea de ser capturada',
    box_empty_aria: 'Caja, fila {r} columna {c}, vacía',
    box_claimed_aria: 'Caja, fila {r} columna {c}, capturada por {who}',
    board_aria: 'Tablero de Dots and Boxes',
    game_over: 'Fin de la partida',
    close: 'Cerrar',
    play_again: 'Jugar otra vez',
    help_lead: 'Rellena más cajas que nadie para ganar.',
    help_diagram_aria: 'Completar el cuarto lado de una caja la captura y te deja jugar otra vez',
    help_caption: 'Dibuja el 4º lado de una caja para rellenarla.',
    help_example: 'Completa una caja = Juegas otra vez',
    help_rule: 'El turno pasa a tu rival.',
    mode_solo: 'Solo',
    mode_host: 'Crear',
    mode_join: 'Unirse',
    mp_host_btn: 'Crear sala',
    mp_host_hint: 'Juega contra alguien en su propio móvil.',
    mp_join_hint: 'Pide al anfitrión su código de 4 caracteres.',
    mp_creating_room: 'Creando sala...',
    mp_joining: 'Uniéndose...',
    mp_enter_code: 'Introduce el código',
    mp_code_aria: 'Código de sala',
    mp_join_btn: 'Unirse',
    mp_back_btn: 'Atrás',
    mp_start_btn: 'Empezar',
    mp_share_code: 'Comparte este código con tu rival.',
    mp_waiting_opponent: 'Esperando a que alguien entre',
    mp_waiting_host: 'Esperando al anfitrión',
    mp_opponent_label: 'Rival',
    mp_host_label: 'Anfitrión',
    mp_leave_btn: 'Salir',
    mp_status_connection_error: 'Error de conexión',
    mp_status_resyncing: 'Resincronizando...',
    mp_status_opponent_disconnected: 'Rival desconectado',
    mp_update_required: 'Actualización necesaria',
    mp_err_could_not_create_room: 'No se pudo crear la sala',
    mp_err_offline: 'Sin conexión',
    mp_err_room_not_found: 'Sala no encontrada',
    mp_err_room_full: 'Sala llena',
    mp_err_wrong_game: 'Ese código es de otro juego',
    mp_error_title: 'Error de conexión',
    mp_error_sub: 'La partida no pudo mantenerse sincronizada',
    mp_opponent_left_title: 'El rival se fue',
    mp_opponent_left_sub: 'La sala está cerrada',
    mp_back_to_setup: 'Volver a ajustes',
    mp_series: 'Tú {me} · {opp} {them} · Empates {d}',
    mp_waiting_rematch: 'Esperando a que {opp} empiece otra partida',
  },
};

export default STRINGS;
