// mancala/js/strings.js — every user-visible string in Mancala, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Values (difficulty key beginner/intermediate/pro, speed key normal/slow) stay
// canonical — only their display labels translate. AI_ROSTER names (Lucía, Diego, …) are proper
// names and stay as-is in ui.js, not routed through here.

export const STRINGS = {
  en: {
    title: 'Mancala',
    tagline: 'Sow stones counterclockwise. Bank the most in your mancala.',
    vs: 'vs',
    you: 'You',
    difficulty: 'Difficulty',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    chip_easy: 'Easy',
    chip_medium: 'Medium',
    chip_hard: 'Hard',
    chip_two_players: '2 Players',
    anim_speed: 'Animation speed',
    speed_normal: 'Normal',
    speed_slow: 'Relaxed',
    resume_game: 'Resume game',
    resume_note: 'Starting a new game below ends it.',
    play_vs: 'Play vs {name}',
    two_players: 'Two players',
    howto: 'How to play',
    help_short: 'Help',
    restart: 'Restart',
    setup: 'Setup',
    pit_aria: 'Pit',
    thinking: '{name} thinking',
    you_start: 'You start',
    name_starts: '{name} starts',
    extra_turn: 'Extra turn',
    players_turn: "{name}'s turn",
    your_turn: 'Your turn',
    player_1: 'Player 1',
    player_2: 'Player 2',
    game_over: 'Game over',
    close: 'Close',
    draw: 'Draw',
    name_wins: '{name} wins!',
    you_win: 'You win!',
    opp_wins: '{name} wins',
    play_again: 'Play again',
    change_setup: 'Change setup',
    view_board: 'View board',
    your_opponent: 'your opponent',
    help_lead: 'Collect the most stones in your mancala.',
    help_diagram_aria: 'Sowing goes counterclockwise from a pit, through your remaining pits and your mancala, along the opponent’s pits, hopping over the opponent’s mancala',
    help_caption: "Tap a pit to sow its stones counterclockwise, one per pit (your mancala counts, your opponent's is skipped); land the last stone in your own mancala to go again.",
    help_rule_capture: 'Last stone in an empty pit on your side captures it plus the opposite pit.',
    help_rule_end: 'When one side runs out, the other player keeps their remaining stones.',
    mode_solo: 'Solo',
    mode_host: 'Host',
    mode_join: 'Join',
    mp_host_btn: 'Create room',
    mp_host_hint: 'Play someone else on their own phone.',
    mp_join_hint: 'Ask the host for their 4-character code.',
    mp_creating_room: 'Creating room...',
    mp_joining: 'Joining...',
    mp_enter_code: 'Enter code',
    mp_code_aria: 'Room code',
    mp_join_btn: 'Join',
    mp_back_btn: 'Back',
    mp_start_btn: 'Start',
    mp_share_code: 'Share this code with your opponent.',
    mp_waiting_opponent: 'Waiting for someone to join',
    mp_waiting_host: 'Waiting for host',
    mp_opponent_label: 'Opponent',
    mp_host_label: 'Host',
    mp_leave_btn: 'Leave',
    mp_opp_turn: "{name}'s turn",
    mp_status_connection_error: 'Connection error',
    mp_status_resyncing: 'Resyncing...',
    mp_status_opponent_disconnected: 'Opponent disconnected',
    mp_update_required: 'Update required',
    mp_err_could_not_create_room: 'Could not create a room',
    mp_err_offline: 'Offline',
    mp_err_room_not_found: 'Room not found',
    mp_err_room_full: 'Room full',
    mp_err_wrong_game: 'That code is for another game',
    mp_error_title: 'Connection error',
    mp_error_sub: 'The game could not stay in sync',
    mp_opponent_left_title: 'Opponent left',
    mp_opponent_left_sub: 'The room is closed',
    mp_back_to_setup: 'Back to setup',
    mp_series: 'You {me} · {opp} {them} · Drawn {d}',
    mp_waiting_rematch: 'Waiting for {opp} to start another game',
  },
  es: {
    title: 'Mancala',
    tagline: 'Siembra piedras en sentido antihorario. Acumula las más en tu mancala.',
    vs: 'vs',
    you: 'Tú',
    difficulty: 'Dificultad',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    chip_easy: 'Fácil',
    chip_medium: 'Normal',
    chip_hard: 'Difícil',
    chip_two_players: '2 jugadores',
    anim_speed: 'Velocidad de animación',
    speed_normal: 'Normal',
    speed_slow: 'Relajada',
    resume_game: 'Reanudar partida',
    resume_note: 'Empezar una partida nueva abajo la termina.',
    play_vs: 'Jugar contra {name}',
    two_players: 'Dos jugadores',
    howto: 'Cómo se juega',
    help_short: 'Ayuda',
    restart: 'Reiniciar',
    setup: 'Ajustes',
    pit_aria: 'Hoyo',
    thinking: '{name} está pensando',
    you_start: 'Empiezas tú',
    name_starts: 'Empieza {name}',
    extra_turn: 'Turno extra',
    players_turn: 'Turno de {name}',
    your_turn: 'Tu turno',
    player_1: 'Jugador 1',
    player_2: 'Jugador 2',
    game_over: 'Fin de la partida',
    close: 'Cerrar',
    draw: 'Empate',
    name_wins: '¡{name} gana!',
    you_win: '¡Ganaste!',
    opp_wins: '{name} gana',
    play_again: 'Jugar otra vez',
    change_setup: 'Cambiar ajustes',
    view_board: 'Ver tablero',
    your_opponent: 'tu rival',
    help_lead: 'Acumula las piedras en tu mancala.',
    help_diagram_aria: 'La siembra va en sentido antihorario desde un hoyo, por tus hoyos y tu mancala, por los hoyos del rival, saltando la mancala del rival',
    help_caption: 'Toca un hoyo para sembrar sus piedras en sentido antihorario, una por hoyo (tu mancala cuenta, la del rival se salta); si la última piedra cae en tu mancala, vuelves a jugar.',
    help_rule_capture: 'La última piedra en un hoyo vacío de tu lado captura esa piedra y todas las del hoyo opuesto.',
    help_rule_end: 'Cuando un lado se queda sin piedras, el otro jugador conserva las que le quedan.',
    mode_solo: 'Solo',
    mode_host: 'Crear',
    mode_join: 'Unirse',
    mp_host_btn: 'Crear sala',
    mp_host_hint: 'Juega contra alguien en su propio móvil.',
    mp_join_hint: 'Pide al anfitrión su código de 4 caracteres.',
    mp_creating_room: 'Creando sala...',
    mp_joining: 'Uniéndose...',
    mp_enter_code: 'Introduce el código',
    mp_code_aria: 'Código de sala',
    mp_join_btn: 'Unirse',
    mp_back_btn: 'Atrás',
    mp_start_btn: 'Empezar',
    mp_share_code: 'Comparte este código con tu rival.',
    mp_waiting_opponent: 'Esperando a que alguien entre',
    mp_waiting_host: 'Esperando al anfitrión',
    mp_opponent_label: 'Rival',
    mp_host_label: 'Anfitrión',
    mp_leave_btn: 'Salir',
    mp_opp_turn: 'Turno de {name}',
    mp_status_connection_error: 'Error de conexión',
    mp_status_resyncing: 'Resincronizando...',
    mp_status_opponent_disconnected: 'Rival desconectado',
    mp_update_required: 'Actualización necesaria',
    mp_err_could_not_create_room: 'No se pudo crear la sala',
    mp_err_offline: 'Sin conexión',
    mp_err_room_not_found: 'Sala no encontrada',
    mp_err_room_full: 'Sala llena',
    mp_err_wrong_game: 'Ese código es de otro juego',
    mp_error_title: 'Error de conexión',
    mp_error_sub: 'La partida no pudo mantenerse sincronizada',
    mp_opponent_left_title: 'El rival se fue',
    mp_opponent_left_sub: 'La sala está cerrada',
    mp_back_to_setup: 'Volver a ajustes',
    mp_series: 'Tú {me} · {opp} {them} · Empates {d}',
    mp_waiting_rematch: 'Esperando a que {opp} empiece otra partida',
  },
};

export default STRINGS;
