// mancala/js/strings.js — every user-visible string in Mancala, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Values (difficulty key beginner/intermediate/pro, speed key normal/slow) stay
// canonical — only their display labels translate. AI_ROSTER names (Lucía, Diego, …) are proper
// names and stay as-is in ui.js, not routed through here.

export const STRINGS = {
  en: {
    title: 'Mancala',
    tagline: 'Sow stones counterclockwise. Bank the most in your mancala.',
    vs: 'vs',
    difficulty: 'Difficulty',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    chip_easy: 'Easy',
    chip_medium: 'Medium',
    chip_hard: 'Hard',
    chip_two_players: '2 Players',
    anim_speed: 'Animation speed',
    speed_normal: 'Normal',
    speed_slow: 'Relaxed',
    resume_game: 'Resume game',
    resume_note: 'Starting a new game below ends it.',
    play_vs: 'Play vs {name}',
    two_players: 'Two players',
    howto: 'How to play',
    help_short: 'Help',
    restart: 'Restart',
    setup: 'Setup',
    pit_aria: 'Pit',
    thinking: '{name} thinking',
    you_start: 'You start',
    name_starts: '{name} starts',
    extra_turn: 'Extra turn',
    players_turn: "{name}'s turn",
    your_turn: 'Your turn',
    player_1: 'Player 1',
    player_2: 'Player 2',
    game_over: 'Game over',
    close: 'Close',
    draw: 'Draw',
    name_wins: '{name} wins!',
    you_win: 'You win!',
    opp_wins: '{name} wins',
    play_again: 'Play again',
    change_setup: 'Change setup',
    view_board: 'View board',
    your_opponent: 'your opponent',
    help_board_h: 'The board',
    help_board: 'Each player has six pits and a mancala (the long tray) that stores every stone they collect. You own the blue side; {opp} owns the red side.',
    help_turn_h: 'Your turn',
    help_turn: "Tap one of your pits. All of its stones are picked up and sown counterclockwise, one per pit, including your own mancala. The opponent's mancala is skipped.",
    help_extra_h: 'Extra turn',
    help_extra: 'If the last stone lands in your mancala, you move again.',
    help_capture_h: 'Capture',
    help_capture: 'If the last stone lands in an empty pit on your side, you win that stone and every stone in the opposite pit.',
    help_end_h: 'End of the game',
    help_end: 'The game ends when all six pits on one side are empty. The other player keeps the stones left on their side. Most stones in the mancala wins.',
  },
  es: {
    title: 'Mancala',
    tagline: 'Siembra piedras en sentido antihorario. Acumula las más en tu mancala.',
    vs: 'vs',
    difficulty: 'Dificultad',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Pro',
    chip_easy: 'Fácil',
    chip_medium: 'Normal',
    chip_hard: 'Difícil',
    chip_two_players: '2 jugadores',
    anim_speed: 'Velocidad de animación',
    speed_normal: 'Normal',
    speed_slow: 'Relajada',
    resume_game: 'Reanudar partida',
    resume_note: 'Empezar una partida nueva abajo la termina.',
    play_vs: 'Jugar contra {name}',
    two_players: 'Dos jugadores',
    howto: 'Cómo se juega',
    help_short: 'Ayuda',
    restart: 'Reiniciar',
    setup: 'Ajustes',
    pit_aria: 'Hoyo',
    thinking: '{name} está pensando',
    you_start: 'Empiezas tú',
    name_starts: 'Empieza {name}',
    extra_turn: 'Turno extra',
    players_turn: 'Turno de {name}',
    your_turn: 'Tu turno',
    player_1: 'Jugador 1',
    player_2: 'Jugador 2',
    game_over: 'Fin de la partida',
    close: 'Cerrar',
    draw: 'Empate',
    name_wins: '¡{name} gana!',
    you_win: '¡Ganaste!',
    opp_wins: '{name} gana',
    play_again: 'Jugar otra vez',
    change_setup: 'Cambiar ajustes',
    view_board: 'Ver tablero',
    your_opponent: 'tu rival',
    help_board_h: 'El tablero',
    help_board: 'Cada jugador tiene seis hoyos y una mancala (la bandeja larga) que guarda cada piedra que recoge. Tú tienes el lado azul; {opp} tiene el lado rojo.',
    help_turn_h: 'Tu turno',
    help_turn: 'Toca uno de tus hoyos. Todas sus piedras se recogen y se siembran en sentido antihorario, una por hoyo, incluida tu propia mancala. La mancala del rival se salta.',
    help_extra_h: 'Turno extra',
    help_extra: 'Si la última piedra cae en tu mancala, mueves otra vez.',
    help_capture_h: 'Captura',
    help_capture: 'Si la última piedra cae en un hoyo vacío de tu lado, ganas esa piedra y todas las del hoyo opuesto.',
    help_end_h: 'Fin de la partida',
    help_end: 'La partida termina cuando los seis hoyos de un lado están vacíos. El otro jugador se queda con las piedras que le quedan en su lado. Gana quien tenga más piedras en su mancala.',
  },
};

export default STRINGS;
