// strings.js — every user-visible string in Poolv2, both languages. Root CLAUDE.md
// "Adding a game" item 9: English is the source of truth, es may lag (js/i18n.js
// falls back to English for anything missing).
export const STRINGS = {
  en: {
    title: 'Poolv2',
    tagline: '8-ball, real cue-ball physics. Vs. the computer, a friend, or practice alone.',
    mode: 'Mode',
    mode_ai: 'Vs. computer',
    mode_practice: 'Practice table',
    mode_online: 'Play online',
    difficulty: 'Difficulty',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    start: 'Start game',
    howto: 'How to play',
    you: 'You',
    computer: 'Computer',
    your_turn: 'Your turn',
    opp_turn: '{opp}\'s turn',
    opp_thinking: '{opp} is thinking…',
    place_cue: 'Ball in hand: drag the cue ball, tap to place',
    solids: 'Solids',
    stripes: 'Stripes',
    eight_ball: '8-ball',
    open_table: 'Open table',
    foul: 'Foul',
    foul_scratch: 'Scratch: cue ball pocketed',
    foul_no_contact: 'Foul: cue ball hit nothing',
    foul_wrong_ball: 'Foul: wrong ball hit first',
    foul_wrong_ball_eight: 'Foul: hit the 8-ball early',
    foul_no_rail: 'Foul: no rail after contact',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    win_scratch_on_eight: 'Scratch on the 8-ball',
    win_early_eight: 'Pocketed the 8-ball early',
    play_again: 'Play again',
    new_game: 'New game',
    quit: 'Quit',
    quit_confirm: 'Tap again to quit',
    power: 'Power',
    spin: 'Spin',
    elevate_cue: 'Raise cue',
    camera: 'Camera',
    camera_top: 'Top-down',
    camera_behind: 'Behind cue',
    shoot: 'Shoot',
    cancel: 'Cancel',
    leave_game_confirm: 'Leave this game?',
    create_room: 'Create room',
    join_room: 'Join room',
    room_code: 'Room code',
    enter_code: 'Enter 4-letter code',
    waiting_opponent: 'Waiting for an opponent…',
    share_code: 'Share this code: {code}',
    joining: 'Joining…',
    connection_lost: 'Connection lost',
    rejoin: 'Rejoin',
    back: 'Back',
    online_offline: 'You’re offline — online play needs a connection.',
    room_not_found: 'Room not found or expired.',
    room_full: 'That room is already full.',
    version_mismatch: 'Update the app to play online with this opponent.',
    breaking: 'Break',
    solid_shape_aria: 'Solid ball',
    stripe_shape_aria: 'Striped ball',
  },
  es: {
    title: 'Poolv2',
    tagline: 'Bola 8, física real de la bola blanca. Contra la computadora, un amigo, o práctica libre.',
    mode: 'Modo',
    mode_ai: 'Contra la computadora',
    mode_practice: 'Mesa de práctica',
    mode_online: 'Jugar en línea',
    difficulty: 'Dificultad',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Experto',
    start: 'Comenzar partida',
    howto: 'Cómo jugar',
    you: 'Tú',
    computer: 'Computadora',
    your_turn: 'Tu turno',
    opp_turn: 'Turno de {opp}',
    opp_thinking: '{opp} está pensando…',
    place_cue: 'Bola en mano: arrastra la bola blanca, toca para colocarla',
    solids: 'Lisas',
    stripes: 'Rayadas',
    eight_ball: 'Bola 8',
    open_table: 'Mesa abierta',
    foul: 'Falta',
    foul_scratch: 'Falta: bola blanca embocada',
    foul_no_contact: 'Falta: la bola blanca no tocó nada',
    foul_wrong_ball: 'Falta: golpeó la bola equivocada primero',
    foul_wrong_ball_eight: 'Falta: golpeó la bola 8 antes de tiempo',
    foul_no_rail: 'Falta: ninguna banda tras el contacto',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    win_scratch_on_eight: 'Falta en la bola 8',
    win_early_eight: 'Embocó la bola 8 antes de tiempo',
    play_again: 'Jugar de nuevo',
    new_game: 'Nueva partida',
    quit: 'Salir',
    quit_confirm: 'Toca de nuevo para salir',
    power: 'Fuerza',
    spin: 'Efecto',
    elevate_cue: 'Levantar el taco',
    camera: 'Cámara',
    camera_top: 'Vista superior',
    camera_behind: 'Detrás del taco',
    shoot: 'Tirar',
    cancel: 'Cancelar',
    leave_game_confirm: '¿Salir de esta partida?',
    create_room: 'Crear sala',
    join_room: 'Unirse a sala',
    room_code: 'Código de sala',
    enter_code: 'Ingresa el código de 4 letras',
    waiting_opponent: 'Esperando a un oponente…',
    share_code: 'Comparte este código: {code}',
    joining: 'Uniéndose…',
    connection_lost: 'Conexión perdida',
    rejoin: 'Reconectar',
    back: 'Atrás',
    online_offline: 'Estás sin conexión: jugar en línea necesita internet.',
    room_not_found: 'Sala no encontrada o expirada.',
    room_full: 'Esa sala ya está llena.',
    version_mismatch: 'Actualiza la app para jugar en línea con este oponente.',
    breaking: 'Rompiendo',
    solid_shape_aria: 'Bola lisa',
    stripe_shape_aria: 'Bola rayada',
  },
};

export default STRINGS;
