// strings.js - every user-visible string in Texas Hold'em, English and Spanish.
// English is the source of truth; a missing Spanish key falls back to English (js/i18n.js).
// No em dashes in player-facing copy (root CLAUDE.md).

export default {
  en: {
    title: "Texas Hold'em",
    tab_solo: 'Vs computer',
    tab_online: 'Online table',
    opponents: 'Opponents',
    skill: 'Skill',
    easy: 'Easy', medium: 'Medium', hard: 'Hard',
    blinds_speed: 'Blinds go up',
    speed_slow: 'Slowly', speed_normal: 'Normal', speed_fast: 'Fast',
    speed_hint: 'every {n} hands',
    deal: 'Deal',
    create_table: 'Create a table',
    create_hint: 'Up to 8 players. Share the code so friends can join.',
    join_title: 'Join a table',
    join_ph: 'CODE',
    join: 'Join',
    back_to_table: 'Back to table {code}',
    code_label: 'Table code',
    code_hint: 'Friends tap Online table, then enter this code.',
    players_n: 'Players ({n}/8)',
    add_bot: 'Add computer',
    remove: 'Remove',
    bot_skill: 'Computer skill',
    start_game: 'Start the game',
    need_two: 'Need at least 2 players',
    waiting_host: 'Waiting for the host to deal...',
    leave: 'Leave',
    leave_table: 'Leave table',
    leave_confirm: 'Leave the table? Your chips are forfeited.',
    // Step away and come back (2026-09-28)
    leave_solo_q: 'Leave this tournament?', leave_guest_q: 'Leave the table?', leave_host_q: 'Leave the table?',
    save_leave: 'Save and leave', save_leave_hint: 'Come back any time with Resume tournament.',
    step_away: 'Step away', step_away_hint: 'Your seat stays yours; you fold while you are gone. Rejoin with Back to table.',
    step_away_host_hint: 'The table waits for you. Come back with Back to table.',
    give_up: 'Give up (counts as a loss)', close_table: 'Close the table for everyone',
    resume_game: 'Resume tournament', give_up_saved: 'Give up this tournament',
    give_up_confirm: 'Give up your saved tournament? It counts as a loss and the buy-in is not returned.',
    hand_n: 'hand {n}',
    close_confirm: 'Close the table for everyone?',
    cancel: 'Cancel',
    host: 'Host',
    you: 'You',
    computer: 'Computer',
    connecting: 'Connecting...',
    err_offline: "Can't reach the game server. Check your connection.",
    err_busy: 'Could not create a table. Try again.',
    err_notfound: 'No table with that code.',
    err_full: 'That table is full (8 players).',
    err_version: 'Update needed: close and reopen the app, then try again.',
    err_wrong_game: 'That code is for a different game.',
    err_send: "Your move didn't send. Try again.",
    table_closed: 'The host closed the table.',
    host_away: 'Waiting for the host to come back...',
    kicked: 'You are no longer at this table.',
    hand_n: 'Hand {n}',
    blinds: 'Blinds {sb}/{bb}',
    pot: 'Pot {n}',
    fold: 'Fold',
    check: 'Check',
    call: 'Call {n}',
    bet: 'Bet',
    raise: 'Raise',
    raise_to: 'Raise to {n}',
    bet_n: 'Bet {n}',
    allin: 'All in',
    allin_n: 'All in {n}',
    min: 'Min',
    half_pot: '1/2 Pot',
    pot_btn: 'Pot',
    a_fold: 'Fold', a_check: 'Check', a_call: 'Call', a_bet: 'Bet', a_raise: 'Raise', a_allin: 'All in',
    a_sb: 'SB', a_bb: 'BB',
    your_turn: 'Your turn',
    waiting_for: 'Waiting for {name}',
    sitting_out: 'You are sitting out. You fold automatically.',
    im_back: "I'm back",
    away: 'Away',
    out: 'Out',
    left: 'Left',
    you_are_out: 'You finished {place}. Watching the rest.',
    next_game_wait: 'Game in progress. You are dealt in next game.',
    wins_pot: '{name} wins {n}',
    wins_with: '{name} wins {n} with {hand}',
    split_pot: 'Split pot {n}',
    side_pot: 'Side pot',
    you_win: 'You win!',
    you_place: 'You finished {place}',
    winner_is: '{name} wins the game',
    play_again: 'Play again',
    new_game: 'New game',
    change_players: 'Change players',
    setup: 'Settings',
    done: 'Close',
    help: 'How to play',
    help_goal: 'Make the best five-card hand from your two cards and the five on the table.',
    help_rank: 'Hands, best to worst',
    help_blinds: 'Everyone starts with {chips} chips. Blinds rise as the game goes on. Last player with chips wins.',
    place_1: '1st', place_2: '2nd', place_3: '3rd', place_n: '{n}th',
    // Hand names
    hn_0: 'High card', hn_1: 'Pair', hn_2: 'Two pair', hn_3: 'Three of a kind', hn_4: 'Straight',
    hn_5: 'Flush', hn_6: 'Full house', hn_7: 'Four of a kind', hn_8: 'Straight flush', hn_9: 'Royal flush',
    aria_card: '{rank} of {suit}',
    aria_back: 'Face-down card',
    s_0: 'spades', s_1: 'hearts', s_2: 'diamonds', s_3: 'clubs',
    dealer: 'Dealer',
    chips_n: '{n} chips',
    // The cloned table (2026-09-27)
    ban_hand: 'HAND', ban_rank: 'YOUR RANK', ban_of: 'of {n}', ban_up: 'BLINDS UP', ban_up_in: 'in {n}',
    set_raise: 'Set raise',
    raise_drag: 'Raise \u21E7',
    raise_aria: 'Raise: slide up to choose the amount, or tap for the slider',
    check_fold: 'CHECK / FOLD',
    big_check: 'CHECK', big_call: 'CALL {n}', big_bet: 'BET {n}', big_raise: 'RAISE TO {n}', big_allin: 'ALL IN {n}',
    see_cards: "See everyone's cards",
    tap_next: 'Tap the table to start the next hand',
    tap_results: 'Tap the table to see the results',
    tap_skip: 'Tap the table to skip ahead',
    // Computer speed (2026-09-28)
    pace: 'Computer speed', pace_slow: 'Slow', pace_normal: 'Normal', pace_fast: 'Fast',
    // Last hand replay (2026-09-28)
    last_hand: 'Last hand', last_title: 'Hand {n}', last_none: 'No hand has finished yet.',
    last_wins: '{name} wins {n} with {hand}', last_takes: '{name} takes {n}', last_split: 'Split: {names} share {n}',
    last_side: 'Side pot', last_folded: 'folded', last_you: 'You',
    street_preflop: 'Before the flop', street_flop: 'Flop', street_turn: 'Turn', street_river: 'River',
    lg_sb: 'small blind {n}', lg_bb: 'big blind {n}', lg_fold: 'folds', lg_check: 'checks', lg_call: 'calls {n}',
    lg_bet: 'bets {n}', lg_raise: 'raises to {n}', lg_allin: 'all in for {n}', lg_left: 'left the table',
    // the same, said to "You" (English needs the other verb form)
    lgy_sb: 'small blind {n}', lgy_bb: 'big blind {n}', lgy_fold: 'fold', lgy_check: 'check', lgy_call: 'call {n}',
    lgy_bet: 'bet {n}', lgy_raise: 'raise to {n}', lgy_allin: 'go all in for {n}', lgy_left: 'left the table',
    last_you_win: 'You win {n} with {hand}', last_you_take: 'You take {n}',
    last_back: '{name} gets {n} back (nobody called it)', last_you_back: 'You get {n} back (nobody called it)',
    next_soon: 'Next hand coming up',
    stack_n: 'Stack: {n}',
    st_sb: 'POST', st_bb: 'POST', st_fold: 'FOLD', st_check: 'CHECK', st_call: 'CALL', st_bet: 'BET',
    st_raise: 'RAISE', st_allin: 'ALL IN', st_win: 'WIN', st_you_win: 'YOU WIN', st_split: 'SPLIT', st_away: 'AWAY', st_out: 'OUT', st_left: 'LEFT',
    msg_you_take: 'You take the {n} chip pot',
    msg_takes: '{name} takes the {n} chip pot',
    msg_you_win: 'You win {n} chips with {hand}',
    msg_wins: '{name} wins {n} chips with {hand}',
    msg_split: 'Split pot: {n} chips',
    msg_you: 'You', msg_split_names: '{names} split {n} chips', and: 'and',
    msg_you_win_n: 'You win {n} chips', msg_wins_n: '{name} wins {n} chips', msg_more_pots: '{n} more side pots: see Last hand',
    hd_0: '{r} High', hd_1: 'Pair of {p}', hd_2: 'Two Pair, {p} and {q}', hd_3: 'Three of a Kind, {p}',
    hd_4: 'Straight, {r} High', hd_5: 'Flush, {r} High', hd_6: 'Full House, {p} over {q}',
    hd_7: 'Four of a Kind, {p}', hd_8: 'Straight Flush, {r} High', hd_9: 'Royal Flush',
    rn_0: 'Two', rn_1: 'Three', rn_2: 'Four', rn_3: 'Five', rn_4: 'Six', rn_5: 'Seven', rn_6: 'Eight',
    rn_7: 'Nine', rn_8: 'Ten', rn_9: 'Jack', rn_10: 'Queen', rn_11: 'King', rn_12: 'Ace',
    rp_0: 'Twos', rp_1: 'Threes', rp_2: 'Fours', rp_3: 'Fives', rp_4: 'Sixes', rp_5: 'Sevens', rp_6: 'Eights',
    rp_7: 'Nines', rp_8: 'Tens', rp_9: 'Jacks', rp_10: 'Queens', rp_11: 'Kings', rp_12: 'Aces',
    bankroll: 'Bankroll', back: 'Back', choose_table: 'Choose a table',
    bank_title: 'Bankrolls', bank_see: 'See all', bank_lifetime: 'Lifetime winnings', bank_won_short: 'Won',
    bank_profit: 'Profit', bank_best: 'Biggest prize', bank_prizes: 'Prizes', bank_prizes_n: '{a} of {b} games',
    bank_loading: 'Loading everyone\'s bankroll...', bank_offline: 'Could not load the other players. Check your connection.',
    bank_retry: 'Try again', bank_review: 'Under review',
    buy_in: '{n} buy-in', first_wins: '1st wins {n}', locked: 'Locked', table_label: 'Table',
    topup: 'Out of money? Take free chips (+{n})',
    prize_rule: 'Everyone at the table pays the buy-in. With {n} players, 1st takes 65% of the pot and 2nd the rest (heads-up, the winner takes it all).',
    prize_won: '+{n} to your bankroll',
    no_buyin: 'No buy-in (just for fun)',
    cant_cover: 'Your bankroll does not cover this buy-in, so you will play this one just for fun.',
    playing_free: 'Your bankroll does not cover this buy-in: playing this game just for fun.',
    tier_buddy: "Buddy's House", tier_vegas: 'Las Vegas Casino', tier_regional: 'Regional',
    tier_world: 'World Championship', tier_solar: 'Solar System', tier_galaxy: 'Galaxy Championship',
    tier_universe: 'Universe Championship',
  },
  es: {
    title: "Texas Hold'em",
    tab_solo: 'Contra la máquina',
    tab_online: 'Mesa en línea',
    opponents: 'Rivales',
    skill: 'Nivel',
    easy: 'Fácil', medium: 'Normal', hard: 'Difícil',
    blinds_speed: 'Las ciegas suben',
    speed_slow: 'Despacio', speed_normal: 'Normal', speed_fast: 'Rápido',
    speed_hint: 'cada {n} manos',
    deal: 'Repartir',
    create_table: 'Crear una mesa',
    create_hint: 'Hasta 8 jugadores. Comparte el código para que se unan.',
    join_title: 'Unirse a una mesa',
    join_ph: 'CÓDIGO',
    join: 'Unirse',
    back_to_table: 'Volver a la mesa {code}',
    code_label: 'Código de la mesa',
    code_hint: 'Tus amigos tocan Mesa en línea y escriben este código.',
    players_n: 'Jugadores ({n}/8)',
    add_bot: 'Añadir máquina',
    remove: 'Quitar',
    bot_skill: 'Nivel de la máquina',
    start_game: 'Empezar la partida',
    need_two: 'Hacen falta al menos 2 jugadores',
    waiting_host: 'Esperando a que el anfitrión reparta...',
    leave: 'Salir',
    leave_table: 'Salir de la mesa',
    leave_confirm: '¿Salir de la mesa? Pierdes tus fichas.',
    leave_solo_q: '¿Salir de este torneo?', leave_guest_q: '¿Salir de la mesa?', leave_host_q: '¿Salir de la mesa?',
    save_leave: 'Guardar y salir', save_leave_hint: 'Vuelve cuando quieras con Seguir torneo.',
    step_away: 'Salir un rato', step_away_hint: 'Tu asiento sigue siendo tuyo; no vas mientras no estás. Vuelve con Volver a la mesa.',
    step_away_host_hint: 'La mesa te espera. Vuelve con Volver a la mesa.',
    give_up: 'Abandonar (cuenta como derrota)', close_table: 'Cerrar la mesa para todos',
    resume_game: 'Seguir torneo', give_up_saved: 'Abandonar este torneo',
    give_up_confirm: '¿Abandonar tu torneo guardado? Cuenta como derrota y no se devuelve la entrada.',
    hand_n: 'mano {n}',
    close_confirm: '¿Cerrar la mesa para todos?',
    cancel: 'Cancelar',
    host: 'Anfitrión',
    you: 'Tú',
    computer: 'Máquina',
    connecting: 'Conectando...',
    err_offline: 'No se puede conectar con el servidor. Revisa tu conexión.',
    err_busy: 'No se pudo crear la mesa. Inténtalo de nuevo.',
    err_notfound: 'No hay ninguna mesa con ese código.',
    err_full: 'Esa mesa está llena (8 jugadores).',
    err_version: 'Hace falta actualizar: cierra y abre la app, y vuelve a intentarlo.',
    err_wrong_game: 'Ese código es de otro juego.',
    err_send: 'Tu jugada no se envió. Inténtalo de nuevo.',
    table_closed: 'El anfitrión cerró la mesa.',
    host_away: 'Esperando a que vuelva el anfitrión...',
    kicked: 'Ya no estás en esta mesa.',
    hand_n: 'Mano {n}',
    blinds: 'Ciegas {sb}/{bb}',
    pot: 'Bote {n}',
    fold: 'Retirarse',
    check: 'Pasar',
    call: 'Igualar {n}',
    bet: 'Apostar',
    raise: 'Subir',
    raise_to: 'Subir a {n}',
    bet_n: 'Apostar {n}',
    allin: 'All in',
    allin_n: 'All in {n}',
    min: 'Mín',
    half_pot: '1/2 bote',
    pot_btn: 'Bote',
    a_fold: 'Se retira', a_check: 'Pasa', a_call: 'Iguala', a_bet: 'Apuesta', a_raise: 'Sube', a_allin: 'All in',
    a_sb: 'CP', a_bb: 'CG',
    your_turn: 'Tu turno',
    waiting_for: 'Esperando a {name}',
    sitting_out: 'Estás ausente. Te retiras automáticamente.',
    im_back: 'Ya volví',
    away: 'Ausente',
    out: 'Fuera',
    left: 'Se fue',
    you_are_out: 'Quedaste {place}. Mirando el resto.',
    next_game_wait: 'Partida en curso. Entras en la siguiente.',
    wins_pot: '{name} gana {n}',
    wins_with: '{name} gana {n} con {hand}',
    split_pot: 'Bote dividido {n}',
    side_pot: 'Bote lateral',
    you_win: '¡Has ganado!',
    you_place: 'Quedaste {place}',
    winner_is: '{name} gana la partida',
    play_again: 'Jugar otra vez',
    new_game: 'Nueva partida',
    change_players: 'Cambiar jugadores',
    setup: 'Ajustes',
    done: 'Cerrar',
    help: 'Cómo se juega',
    help_goal: 'Forma la mejor mano de cinco cartas con tus dos cartas y las cinco de la mesa.',
    help_rank: 'Manos, de mejor a peor',
    help_blinds: 'Todos empiezan con {chips} fichas. Las ciegas suben durante la partida. Gana el último con fichas.',
    place_1: '1.º', place_2: '2.º', place_3: '3.º', place_n: '{n}.º',
    hn_0: 'Carta alta', hn_1: 'Pareja', hn_2: 'Doble pareja', hn_3: 'Trío', hn_4: 'Escalera',
    hn_5: 'Color', hn_6: 'Full', hn_7: 'Póker', hn_8: 'Escalera de color', hn_9: 'Escalera real',
    aria_card: '{rank} de {suit}',
    aria_back: 'Carta boca abajo',
    s_0: 'picas', s_1: 'corazones', s_2: 'diamantes', s_3: 'tréboles',
    dealer: 'Repartidor',
    chips_n: '{n} fichas',
    ban_hand: 'MANO', ban_rank: 'TU PUESTO', ban_of: 'de {n}', ban_up: 'SUBEN CIEGAS', ban_up_in: 'en {n}',
    set_raise: 'Subir',
    raise_drag: 'Subir \u21E7',
    raise_aria: 'Subir: desliza hacia arriba para elegir la cantidad, o toca para la barra',
    check_fold: 'PASAR / NO IR',
    big_check: 'PASAR', big_call: 'IGUALAR {n}', big_bet: 'APOSTAR {n}', big_raise: 'SUBIR A {n}', big_allin: 'ALL IN {n}',
    see_cards: 'Ver las cartas de todos',
    tap_next: 'Toca la mesa para la siguiente mano',
    tap_results: 'Toca la mesa para ver los resultados',
    tap_skip: 'Toca la mesa para adelantar',
    // Velocidad de los ordenadores (2026-09-28)
    pace: 'Velocidad del ordenador', pace_slow: 'Lenta', pace_normal: 'Normal', pace_fast: 'Rápida',
    // Última mano (2026-09-28)
    last_hand: 'Última mano', last_title: 'Mano {n}', last_none: 'Todavía no ha terminado ninguna mano.',
    last_wins: '{name} gana {n} con {hand}', last_takes: '{name} se lleva {n}', last_split: 'Dividido: {names} se reparten {n}',
    last_side: 'Bote secundario', last_folded: 'no fue', last_you: 'Tú',
    street_preflop: 'Antes del flop', street_flop: 'Flop', street_turn: 'Turn', street_river: 'River',
    lg_sb: 'ciega pequeña {n}', lg_bb: 'ciega grande {n}', lg_fold: 'no va', lg_check: 'pasa', lg_call: 'iguala {n}',
    lg_bet: 'apuesta {n}', lg_raise: 'sube a {n}', lg_allin: 'all in con {n}', lg_left: 'dejó la mesa',
    lgy_sb: 'ciega pequeña {n}', lgy_bb: 'ciega grande {n}', lgy_fold: 'no vas', lgy_check: 'pasas', lgy_call: 'igualas {n}',
    lgy_bet: 'apuestas {n}', lgy_raise: 'subes a {n}', lgy_allin: 'vas all in con {n}', lgy_left: 'dejaste la mesa',
    last_you_win: 'Ganas {n} con {hand}', last_you_take: 'Te llevas {n}',
    last_back: 'A {name} le vuelven {n} (nadie lo igualó)', last_you_back: 'Te vuelven {n} (nadie lo igualó)',
    next_soon: 'Enseguida la siguiente mano',
    stack_n: 'Fichas: {n}',
    st_sb: 'CIEGA', st_bb: 'CIEGA', st_fold: 'NO VA', st_check: 'PASA', st_call: 'IGUALA', st_bet: 'APUESTA',
    st_raise: 'SUBE', st_allin: 'ALL IN', st_win: 'GANA', st_you_win: '¡GANAS!', st_split: 'EMPATE', st_away: 'AUSENTE', st_out: 'FUERA', st_left: 'SE FUE',
    msg_you_take: 'Te llevas el bote de {n} fichas',
    msg_takes: '{name} se lleva el bote de {n} fichas',
    msg_you_win: 'Ganas {n} fichas con {hand}',
    msg_wins: '{name} gana {n} fichas con {hand}',
    msg_split: 'Bote dividido: {n} fichas',
    msg_you: 'Tú', msg_split_names: '{names} se reparten {n} fichas', and: 'y',
    msg_you_win_n: 'Ganas {n} fichas', msg_wins_n: '{name} gana {n} fichas', msg_more_pots: '{n} botes laterales más: mira Última mano',
    hd_0: 'Carta alta, {r}', hd_1: 'Pareja de {p}', hd_2: 'Doble pareja, {p} y {q}', hd_3: 'Trío de {p}',
    hd_4: 'Escalera al {r}', hd_5: 'Color al {r}', hd_6: 'Full de {p} y {q}',
    hd_7: 'Póker de {p}', hd_8: 'Escalera de color al {r}', hd_9: 'Escalera real',
    rn_0: 'Dos', rn_1: 'Tres', rn_2: 'Cuatro', rn_3: 'Cinco', rn_4: 'Seis', rn_5: 'Siete', rn_6: 'Ocho',
    rn_7: 'Nueve', rn_8: 'Diez', rn_9: 'Jota', rn_10: 'Reina', rn_11: 'Rey', rn_12: 'As',
    rp_0: 'Doses', rp_1: 'Treses', rp_2: 'Cuatros', rp_3: 'Cincos', rp_4: 'Seises', rp_5: 'Sietes', rp_6: 'Ochos',
    rp_7: 'Nueves', rp_8: 'Dieces', rp_9: 'Jotas', rp_10: 'Reinas', rp_11: 'Reyes', rp_12: 'Ases',
    bankroll: 'Banca', back: 'Volver', choose_table: 'Elegir mesa',
    bank_title: 'Bancas', bank_see: 'Ver todas', bank_lifetime: 'Ganancias totales', bank_won_short: 'Ganado',
    bank_profit: 'Beneficio', bank_best: 'Mayor premio', bank_prizes: 'Premios', bank_prizes_n: '{a} de {b} partidas',
    bank_loading: 'Cargando las bancas...', bank_offline: 'No se pudo cargar a los demás jugadores. Revisa tu conexión.',
    bank_retry: 'Reintentar', bank_review: 'En revisión',
    buy_in: 'Entrada {n}', first_wins: 'El 1.º gana {n}', locked: 'Bloqueada', table_label: 'Mesa',
    topup: '¿Sin dinero? Toma fichas gratis (+{n})',
    prize_rule: 'Todos en la mesa pagan la entrada. Con {n} jugadores, el 1.º se lleva el 65% del bote y el 2.º el resto (mano a mano, el ganador se lo lleva todo).',
    prize_won: '+{n} a tu banca',
    no_buyin: 'Sin entrada (solo por diversión)',
    cant_cover: 'Tu banca no cubre esta entrada, así que jugarás esta partida solo por diversión.',
    playing_free: 'Tu banca no cubre esta entrada: juegas esta partida solo por diversión.',
    tier_buddy: 'Casa de un amigo', tier_vegas: 'Casino de Las Vegas', tier_regional: 'Regional',
    tier_world: 'Campeonato Mundial', tier_solar: 'Sistema Solar', tier_galaxy: 'Campeonato Galáctico',
    tier_universe: 'Campeonato del Universo',
  },
};
