// filler/js/strings.js — every user-visible string in Filler, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Values (color index 0-5, difficulty key beginner/intermediate/pro) are storage
// vocabulary and are never touched here — only their display labels.

export const STRINGS = {
  en: {
    title: 'Filler',
    tagline: 'Flood the board. Capture the majority.',
    vs: 'vs',
    difficulty: 'Difficulty',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'New game',
    tiles_suffix: 'tiles',
    game_over: 'Game over',
    your_turn: 'Your turn: pick a color',
    opp_thinking: '{opp} is thinking...',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    draw: 'Draw',
    play_again: 'Play again',
    change_difficulty: 'Change difficulty',
    view_board: 'View board',
    close: 'Close',
    board_aria: 'Filler board',
    pick_color_aria: 'Pick a color',
    color_yellow: 'Yellow circle',
    color_blue: 'Blue triangle',
    color_vermilion: 'Vermilion square',
    color_teal: 'Teal diamond',
    color_purple: 'Purple star',
    color_pink: 'Pink cross',
    help_goal_h: 'Goal',
    help_goal: 'Capture more than half of the board: {majority} of the {tiles} tiles.',
    help_setup_h: 'Setup',
    help_setup: 'You start from the bottom-left tile. {opp} starts from the top-right tile. You move first.',
    help_turn_h: 'Your turn',
    help_turn: 'Pick one of the six colors. Your whole territory changes to that color, and every tile of that color touching your territory joins it.',
    help_blocked_h: 'Blocked colors',
    help_blocked: "You cannot pick your own current color or your opponent's current color, so you always choose from four options. Blocked buttons show who holds that color.",
    help_end_h: 'End of the game',
    help_end: 'The game ends when every tile is captured. Whoever holds more tiles wins.',
    help_tips_h: 'Tips',
    help_tip1: 'Early on, pick the color that grabs the most tiles.',
    help_tip2: 'Watch where {opp} is spreading and pick colors that cut off their path.',
    help_tip3: 'Think a turn or two ahead: a capture now also changes which colors both of you can pick next.',
    help_colors_h: 'Colors',
    help_colors: 'Every color has its own shape, so tiles are never told apart by hue alone.',
  },
  es: {
    title: 'Filler',
    tagline: 'Inunda el tablero. Captura la mayoría.',
    vs: 'vs',
    difficulty: 'Dificultad',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Pro',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Nueva partida',
    tiles_suffix: 'casillas',
    game_over: 'Fin de la partida',
    your_turn: 'Tu turno: elige un color',
    opp_thinking: '{opp} está pensando...',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    draw: 'Empate',
    play_again: 'Jugar otra vez',
    change_difficulty: 'Cambiar dificultad',
    view_board: 'Ver tablero',
    close: 'Cerrar',
    board_aria: 'Tablero de Filler',
    pick_color_aria: 'Elige un color',
    color_yellow: 'Círculo amarillo',
    color_blue: 'Triángulo azul',
    color_vermilion: 'Cuadrado bermellón',
    color_teal: 'Diamante verde azulado',
    color_purple: 'Estrella morada',
    color_pink: 'Cruz rosa',
    help_goal_h: 'Objetivo',
    help_goal: 'Captura más de la mitad del tablero: {majority} de las {tiles} casillas.',
    help_setup_h: 'Preparación',
    help_setup: 'Empiezas desde la casilla inferior izquierda. {opp} empieza desde la casilla superior derecha. Tú mueves primero.',
    help_turn_h: 'Tu turno',
    help_turn: 'Elige uno de los seis colores. Todo tu territorio cambia a ese color, y toda casilla de ese color que toque tu territorio se une a él.',
    help_blocked_h: 'Colores bloqueados',
    help_blocked: 'No puedes elegir tu propio color actual ni el de tu rival, así que siempre eliges entre cuatro opciones. Los botones bloqueados muestran quién tiene ese color.',
    help_end_h: 'Fin de la partida',
    help_end: 'La partida termina cuando se captura cada casilla. Gana quien tenga más casillas.',
    help_tips_h: 'Consejos',
    help_tip1: 'Al principio, elige el color que capture más casillas.',
    help_tip2: 'Observa hacia dónde se expande {opp} y elige colores que corten su camino.',
    help_tip3: 'Piensa uno o dos turnos por delante: una captura ahora también cambia qué colores pueden elegir ambos a continuación.',
    help_colors_h: 'Colores',
    help_colors: 'Cada color tiene su propia forma, así que las casillas nunca se distinguen solo por el tono.',
  },
};

export default STRINGS;
