// filler/js/strings.js — every user-visible string in Filler, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Values (color index 0-5, difficulty key beginner/intermediate/pro) are storage
// vocabulary and are never touched here — only their display labels.

export const STRINGS = {
  en: {
    title: 'Filler',
    tagline: 'Flood the board. Capture the majority.',
    vs: 'vs',
    difficulty: 'Difficulty',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'New game',
    restart_game: 'Restart',
    tap_again_confirm: 'Tap again to confirm',
    tiles_suffix: 'tiles',
    game_over: 'Game over',
    your_turn: 'Your turn: pick a color',
    opp_thinking: '{opp} is thinking...',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    draw: 'Draw',
    play_again: 'Play again',
    change_difficulty: 'Change difficulty',
    view_board: 'View board',
    close: 'Close',
    board_aria: 'Filler board',
    pick_color_aria: 'Pick a color',
    color_yellow: 'Yellow circle',
    color_blue: 'Blue triangle',
    color_vermilion: 'Vermilion square',
    color_teal: 'Teal diamond',
    color_purple: 'Purple star',
    color_pink: 'Pink cross',
    help_lead: 'Grow your corner to cover more than half the board.',
    help_diagram_aria: 'Two teal cells touching your territory are outlined; after picking teal, they join your territory',
    help_caption: 'Pick a color: your whole territory becomes that color and every touching cell of it joins you.',
    help_example: 'Pick teal = the teal cells touching you join your territory',
    help_bullet1: "You can't pick your own color or your opponent's.",
    help_bullet2: 'Biggest territory when the board is full wins.',
  },
  es: {
    title: 'Filler',
    tagline: 'Inunda el tablero. Captura la mayoría.',
    vs: 'vs',
    difficulty: 'Dificultad',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Nueva partida',
    restart_game: 'Reiniciar',
    tap_again_confirm: 'Toca de nuevo para confirmar',
    tiles_suffix: 'casillas',
    game_over: 'Fin de la partida',
    your_turn: 'Tu turno: elige un color',
    opp_thinking: '{opp} está pensando...',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    draw: 'Empate',
    play_again: 'Jugar otra vez',
    change_difficulty: 'Cambiar dificultad',
    view_board: 'Ver tablero',
    close: 'Cerrar',
    board_aria: 'Tablero de Filler',
    pick_color_aria: 'Elige un color',
    color_yellow: 'Círculo amarillo',
    color_blue: 'Triángulo azul',
    color_vermilion: 'Cuadrado bermellón',
    color_teal: 'Diamante verde azulado',
    color_purple: 'Estrella morada',
    color_pink: 'Cruz rosa',
    help_lead: 'Haz crecer tu esquina hasta cubrir más de la mitad del tablero.',
    help_diagram_aria: 'Dos casillas verde azulado junto a tu territorio están resaltadas; al elegir ese color, se unen a tu territorio',
    help_caption: 'Elige un color: todo tu territorio pasa a ese color y toda casilla que lo toque se une a ti.',
    help_example: 'Elige verde azulado = las casillas verde azuladas que te tocan se unen a tu territorio',
    help_bullet1: 'No puedes elegir tu propio color ni el de tu rival.',
    help_bullet2: 'Gana quien tenga más territorio cuando el tablero se llena.',
  },
};

export default STRINGS;
