// filler/js/strings.js — every user-visible string in Filler, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Values (color index 0-5, difficulty key beginner/intermediate/pro) are storage
// vocabulary and are never touched here — only their display labels.

export const STRINGS = {
  en: {
    title: 'Filler',
    tagline: 'Flood the board. Capture the majority.',
    vs: 'vs',
    difficulty: 'Difficulty',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'New game',
    tiles_suffix: 'tiles',
    game_over: 'Game over',
    your_turn: 'Your turn: pick a color',
    opp_thinking: '{opp} is thinking...',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    draw: 'Draw',
    play_again: 'Play again',
    change_difficulty: 'Change difficulty',
    view_board: 'View board',
    close: 'Close',
    board_aria: 'Filler board',
    pick_color_aria: 'Pick a color',
    color_yellow: 'Yellow circle',
    color_blue: 'Blue triangle',
    color_vermilion: 'Vermilion square',
    color_teal: 'Teal diamond',
    color_purple: 'Purple star',
    color_pink: 'Pink cross',
    help_lead: 'Own more than half the board.',
    help_diagram_aria: 'Picking a color captures every touching tile of that color into your territory',
    help_caption: 'Picking a color captures every touching cell of that color.',
    help_example: 'Pick blue = every blue cell touching your area joins it',
    help_bullet1: "You can't pick your own color or your opponent's current color.",
    help_bullet2: 'First to own more than half the board wins.',
  },
  es: {
    title: 'Filler',
    tagline: 'Inunda el tablero. Captura la mayoría.',
    vs: 'vs',
    difficulty: 'Dificultad',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Pro',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Nueva partida',
    tiles_suffix: 'casillas',
    game_over: 'Fin de la partida',
    your_turn: 'Tu turno: elige un color',
    opp_thinking: '{opp} está pensando...',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    draw: 'Empate',
    play_again: 'Jugar otra vez',
    change_difficulty: 'Cambiar dificultad',
    view_board: 'Ver tablero',
    close: 'Cerrar',
    board_aria: 'Tablero de Filler',
    pick_color_aria: 'Elige un color',
    color_yellow: 'Círculo amarillo',
    color_blue: 'Triángulo azul',
    color_vermilion: 'Cuadrado bermellón',
    color_teal: 'Diamante verde azulado',
    color_purple: 'Estrella morada',
    color_pink: 'Cruz rosa',
    help_lead: 'Ten más de la mitad del tablero.',
    help_diagram_aria: 'Elegir un color captura toda casilla contigua de ese color y la une a tu territorio',
    help_caption: 'Elegir un color captura toda casilla contigua de ese color.',
    help_example: 'Elige azul = toda casilla azul que toque tu territorio se une a él',
    help_bullet1: 'No puedes elegir tu propio color actual ni el de tu rival.',
    help_bullet2: 'Gana quien tenga primero más de la mitad del tablero.',
  },
};

export default STRINGS;
