// ui-kit/js/strings.js - every user-visible string in the UI Kit gallery, both languages.
// Follows the snake/js/strings.js reference (root CLAUDE.md, "Adding a game" item 9): English is
// the source of truth, `es` may lag, and js/i18n.js falls back to English for any missing key so
// a partial translation can never break a screen.
//
// House style (root CLAUDE.md, copy conventions): NO em dashes in user-facing copy. Commas,
// colons and parentheses only.

export const STRINGS = {
  en: {
    title: 'UI Kit',
    tagline: 'Shared design tokens and chrome primitives, for review.',

    // Tabs
    tab_tokens: 'Tokens',
    tab_parts: 'Parts',
    tab_drift: 'Drift',

    // Preview controls
    preview_theme: 'Preview theme',
    theme_light: 'Light',
    theme_dark: 'Dark',
    theme_note: 'Previews the panels below only. Your own hub theme is not changed.',

    // Tokens screen
    tokens_intro: 'One scale per axis, replacing the values currently in circulation across the 16 game stylesheets.',
    tok_radius: 'Radius',
    tok_shadow: 'Shadow',
    tok_type: 'Type',
    tok_space: 'Space',
    tok_color: 'Color',
    tok_cb: 'Colorblind-safe play palette',
    tok_cb_note: 'Wherever color is a choice, each hue is paired with a shape marker, never hue alone. These four are the agreed set.',
    cb_yellow: 'Yellow (circle)',
    cb_blue: 'Blue (triangle)',
    cb_vermilion: 'Vermilion (square)',
    cb_teal: 'Teal (diamond)',
    replaces_one: 'replaces {n} values in use',

    // Parts screen
    parts_intro: 'The chrome every game currently rebuilds for itself. Boards and play surfaces are deliberately not covered.',
    part_buttons: 'Buttons',
    part_cards: 'Cards and chips',
    part_controls: 'Segments and fields',
    part_acc: 'Accordion',
    part_modal: 'Modal',
    btn_default: 'Default',
    btn_primary: 'Primary',
    btn_ghost: 'Ghost',
    btn_danger: 'Danger',
    btn_small: 'Small',
    btn_disabled: 'Disabled',
    chip_example: 'Best: 240',
    chip_new: 'New',
    card_title: 'Card title',
    card_note: 'A card holds one idea. Padding, radius and shadow all come from the shared scale, so every card in every game matches.',
    seg_label: 'Difficulty',
    seg_easy: 'Easy',
    seg_medium: 'Medium',
    seg_hard: 'Hard',
    field_label: 'Player name',
    field_placeholder: 'Type a name',
    acc_players: 'Players',
    acc_players_val: '2 players',
    acc_players_body: 'One row open at a time, following the Escoba setup pattern.',
    acc_rules: 'Rules',
    acc_rules_val: 'Standard',
    acc_rules_body: 'The head shows the current value, so a closed accordion still reads as a summary.',
    open_modal: 'Open the modal',
    modal_title: 'You win',
    modal_body: 'Every win and lose popup gets a close (X) in its top-right corner, so it can be dismissed without forcing a rematch. That is part of the primitive here, not something each game has to remember.',
    modal_again: 'Play again',
    modal_close: 'Close',
    close: 'Close',

    // Drift screen
    drift_intro: 'Measured across the 16 game stylesheets on 2026-08-01, before the shared layer existed.',
    drift_metric: 'Measure',
    drift_count: 'Count',
    drift_hub_refs: 'Game stylesheets referencing any --hub- token',
    drift_props: 'Custom properties defined independently',
    drift_radius: 'Distinct border-radius values',
    drift_shadow: 'Distinct box-shadow values',
    drift_fs: 'Distinct font-size values',
    drift_font: 'Distinct font-family stacks',
    drift_btn: 'Games defining their own button variant set',
    drift_of16: '0 of 16',
    drift_note: 'The last row is the finding: nine games define the same four button variants under a different prefix. One component, nine implementations. Polish spent on any one of them buys exactly one game.',
    drift_scope: 'This card is dev-only and changes nothing. No game has adopted the shared layer yet, and sw.js is untouched.',
  },

  es: {
    title: 'Kit de interfaz',
    tagline: 'Tokens de diseño y piezas de interfaz compartidas, para revisar.',

    tab_tokens: 'Tokens',
    tab_parts: 'Piezas',
    tab_drift: 'Desvío',

    preview_theme: 'Tema de vista previa',
    theme_light: 'Claro',
    theme_dark: 'Oscuro',
    theme_note: 'Solo afecta a los paneles de abajo. No cambia el tema de tu hub.',

    tokens_intro: 'Una escala por eje, en lugar de los valores que hay ahora repartidos por las 16 hojas de estilo.',
    tok_radius: 'Radio',
    tok_shadow: 'Sombra',
    tok_type: 'Tipografía',
    tok_space: 'Espaciado',
    tok_color: 'Color',
    tok_cb: 'Paleta segura para daltonismo',
    tok_cb_note: 'Donde el color es una elección, cada tono lleva también una forma, nunca solo el tono. Estas cuatro son las acordadas.',
    cb_yellow: 'Amarillo (círculo)',
    cb_blue: 'Azul (triángulo)',
    cb_vermilion: 'Bermellón (cuadrado)',
    cb_teal: 'Verde azulado (rombo)',
    replaces_one: 'sustituye a {n} valores en uso',

    parts_intro: 'La interfaz que cada juego rehace por su cuenta. Los tableros y superficies de juego quedan fuera a propósito.',
    part_buttons: 'Botones',
    part_cards: 'Tarjetas y etiquetas',
    part_controls: 'Segmentos y campos',
    part_acc: 'Acordeón',
    part_modal: 'Ventana',
    btn_default: 'Normal',
    btn_primary: 'Principal',
    btn_ghost: 'Discreto',
    btn_danger: 'Peligro',
    btn_small: 'Pequeño',
    btn_disabled: 'Desactivado',
    chip_example: 'Mejor: 240',
    chip_new: 'Nuevo',
    card_title: 'Título de la tarjeta',
    card_note: 'Una tarjeta contiene una idea. El relleno, el radio y la sombra salen de la escala compartida, así que todas las tarjetas de todos los juegos coinciden.',
    seg_label: 'Dificultad',
    seg_easy: 'Fácil',
    seg_medium: 'Media',
    seg_hard: 'Difícil',
    field_label: 'Nombre del jugador',
    field_placeholder: 'Escribe un nombre',
    acc_players: 'Jugadores',
    acc_players_val: '2 jugadores',
    acc_players_body: 'Una fila abierta a la vez, siguiendo el patrón de Escoba.',
    acc_rules: 'Reglas',
    acc_rules_val: 'Estándar',
    acc_rules_body: 'La cabecera muestra el valor actual, así el acordeón cerrado sigue siendo un resumen.',
    open_modal: 'Abrir la ventana',
    modal_title: 'Ganaste',
    modal_body: 'Cada ventana de ganar o perder lleva una (X) para cerrar arriba a la derecha, así se puede cerrar sin obligar a jugar otra vez. Eso viene incluido aquí, no es algo que cada juego tenga que recordar.',
    modal_again: 'Jugar otra vez',
    modal_close: 'Cerrar',
    close: 'Cerrar',

    drift_intro: 'Medido en las 16 hojas de estilo el 2026-08-01, antes de que existiera la capa compartida.',
    drift_metric: 'Medida',
    drift_count: 'Cantidad',
    drift_hub_refs: 'Hojas de estilo que usan algún token --hub-',
    drift_props: 'Propiedades personalizadas definidas por separado',
    drift_radius: 'Valores distintos de border-radius',
    drift_shadow: 'Valores distintos de box-shadow',
    drift_fs: 'Valores distintos de font-size',
    drift_font: 'Familias tipográficas distintas',
    drift_btn: 'Juegos con su propio juego de botones',
    drift_of16: '0 de 16',
    drift_note: 'La última fila es el hallazgo: nueve juegos definen los mismos cuatro botones con un prefijo distinto. Un componente, nueve versiones. Pulir uno solo sirve para un único juego.',
    drift_scope: 'Esta tarjeta es solo para desarrollo y no cambia nada. Ningún juego usa todavía la capa compartida, y sw.js está intacto.',
  },
};

export default STRINGS;
