// dominoes/js/strings.js — every user-visible string in Dominoes, both languages.
// English is the source of truth (every key exists in `en`); `es` may lag and js/i18n.js's
// fallback shows English for anything missing, so a partial translation can never break a screen.
// Spanish drafted by a working session; native-speaker corrections are one-line edits here.

export const STRINGS = {
  en: {
    title: 'Dominoes',
    tagline: 'All Fives, to 300. Every five on the table is points.',
    // Setup
    difficulty: 'Difficulty',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    row_difficulty: 'Difficulty',
    row_goal: 'Target score',
    goal_n: '{n} points',
    play: 'Play',
    howto: 'How to play',
    // Board chrome
    goal: 'Goal',
    you: 'You',
    bot: 'Bot',
    round_n: 'Round {n}',
    boneyard: 'Boneyard',
    bot_thinking: 'Bot thinking',
    restart: 'Restart',
    tap_again_confirm: 'Tap again to restart',
    // Turn feedback (transient pills, never a running log)
    you_passed: 'No move, you pass',
    bot_passed: 'Bot passes',
    bot_drew: 'Bot draws',
    pick_an_end: 'Pick an end',
    // Round / match end
    round_over: 'Round over',
    game_over: 'Game Finished!',
    round_rule: 'When any player reaches {n} the game ends.',
    col_player: 'Player',
    col_round: 'Round',
    col_total: 'Total',
    continue: 'Continue',
    play_again: 'Play again',
    close: 'Close',
    went_out: 'Went out',
    blocked: 'Blocked',
    // How to play, one caption per carousel page (addendum section C, verbatim)
    tut_ok: 'OK',
    tut_1: 'Score points across multiple dominoes rounds. First to 300 points wins. Each player starts the round with 7 dominoes.',
    tut_2: 'The player with the highest double starts. The next player places a matching domino on the side of the double.',
    tut_3: 'Clear your hand by placing dominoes with matching end values.',
    tut_4: "If you're blocked, with no matching end values, draw dominoes from the boneyard until a move is possible. If the boneyard is empty, you pass.",
    tut_5: 'Play continues until either player empties their hand, or both players are blocked (with the boneyard empty). Then the round finishes.',
    tut_6: "Scoring: when placing a domino, the open ends on the board are added. If it's a multiple of 5 (5, 10, 15) then you gain that score.",
    tut_7: 'Scoring: when a round ends, each player also scores points for all domino values remaining in their opponent\'s hand.',
    tut_8: 'Rounds continue until a player wins by reaching 300 points. Good luck!',
    // aria
    aria_board: 'Domino chain',
    aria_hand: 'Your tiles',
    aria_tile: 'Tile {a} {b}',
    aria_end: 'Open end, value {v}',
    aria_close: 'Close',
    aria_help: 'How to play',
    aria_restart: 'Restart the game',
    aria_boneyard_tile: 'Draw a tile',
    aria_tut_pages: 'Tutorial pages',
    aria_tut_page: 'Page {n}',
    aria_tut_first: 'First page',
    aria_tut_last: 'Last page',
  },
  es: {
    title: 'Dominó',
    tagline: 'All Fives, a 300. Cada cinco sobre la mesa son puntos.',
    difficulty: 'Dificultad',
    diff_easy: 'Fácil',
    diff_medium: 'Medio',
    diff_hard: 'Difícil',
    row_difficulty: 'Dificultad',
    row_goal: 'Puntuación objetivo',
    goal_n: '{n} puntos',
    play: 'Jugar',
    howto: 'Cómo se juega',
    goal: 'Meta',
    you: 'Tú',
    bot: 'Bot',
    round_n: 'Ronda {n}',
    boneyard: 'Pozo',
    bot_thinking: 'El bot piensa',
    restart: 'Reiniciar',
    tap_again_confirm: 'Toca otra vez para reiniciar',
    you_passed: 'Sin jugada, pasas',
    bot_passed: 'El bot pasa',
    bot_drew: 'El bot roba',
    pick_an_end: 'Elige un extremo',
    round_over: 'Fin de la ronda',
    game_over: '¡Partida terminada!',
    round_rule: 'Cuando alguien llega a {n}, la partida termina.',
    col_player: 'Jugador',
    col_round: 'Ronda',
    col_total: 'Total',
    continue: 'Continuar',
    play_again: 'Jugar otra vez',
    close: 'Cerrar',
    went_out: 'Se queda sin fichas',
    blocked: 'Cierre',
    tut_ok: 'OK',
    tut_1: 'Suma puntos a lo largo de varias rondas de dominó. Gana quien llegue antes a 300 puntos. Cada jugador empieza la ronda con 7 fichas.',
    tut_2: 'Sale quien tenga el doble más alto. El siguiente jugador coloca una ficha que encaje en un lado del doble.',
    tut_3: 'Vacía tu mano colocando fichas que encajen con los extremos abiertos.',
    tut_4: 'Si te bloqueas, sin ningún extremo que encaje, roba fichas del pozo hasta poder jugar. Si el pozo está vacío, pasas.',
    tut_5: 'Se juega hasta que alguien se queda sin fichas, o hasta que los dos se bloquean con el pozo vacío. Entonces la ronda termina.',
    tut_6: 'Puntuación: al colocar una ficha se suman los extremos abiertos del tablero. Si es múltiplo de 5 (5, 10, 15), anotas esa cantidad.',
    tut_7: 'Puntuación: cuando termina una ronda, cada jugador anota además todos los puntos que le queden en la mano a su rival.',
    tut_8: 'Las rondas siguen hasta que alguien gana llegando a 300 puntos. ¡Suerte!',
    aria_board: 'Cadena de fichas',
    aria_hand: 'Tus fichas',
    aria_tile: 'Ficha {a} {b}',
    aria_end: 'Extremo abierto, valor {v}',
    aria_close: 'Cerrar',
    aria_help: 'Cómo se juega',
    aria_restart: 'Reiniciar la partida',
    aria_boneyard_tile: 'Robar una ficha',
    aria_tut_pages: 'Páginas del tutorial',
    aria_tut_page: 'Página {n}',
    aria_tut_first: 'Primera página',
    aria_tut_last: 'Última página',
  },
};

export default STRINGS;
