// dominoes/js/strings.js — every user-visible string in Dominoes, both languages.
// English is the source of truth (every key exists in `en`); `es` may lag and js/i18n.js's
// fallback shows English for anything missing, so a partial translation can never break a screen.
// Spanish drafted by a working session; native-speaker corrections are one-line edits here.

export const STRINGS = {
  en: {
    title: 'Dominoes',
    tagline: 'All Fives, to 300. Every five on the table is points.',
    // Setup
    difficulty: 'Difficulty',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    row_difficulty: 'Difficulty',
    row_goal: 'Target score',
    goal_n: '{n} points',
    play: 'Play',
    howto: 'How to play',
    // Board chrome
    goal: 'Goal',
    you: 'You',
    bot: 'Bot',
    round_n: 'Round {n}',
    boneyard: 'Boneyard',
    bot_thinking: 'Bot thinking',
    restart: 'Restart',
    tap_again_confirm: 'Tap again to restart',
    // Turn feedback (transient pills, never a running log)
    you_passed: 'No move, you pass',
    bot_passed: 'Bot passes',
    bot_drew: 'Bot draws',
    pick_an_end: 'Pick an end',
    // Round / match end
    round_over: 'Round over',
    game_over: 'Game over',
    you_win: 'You win!',
    bot_wins: 'Bot wins',
    round_rule: 'When any player reaches {n} the game ends.',
    col_player: 'Player',
    col_round: 'Round',
    col_total: 'Total',
    continue: 'Continue',
    play_again: 'Play again',
    close: 'Close',
    went_out: 'Went out',
    blocked: 'Blocked',
    // Help
    help_goal: 'Match a tile to one of the open ends. First to {n} points wins the game.',
    help_fives: 'After you place a tile, add up the open ends. If the total divides by five, you score it.',
    help_doubles: 'Doubles lie crosswise and count both halves at an end. The first double is the spinner: once the line runs past it both ways, you can branch off its two free sides.',
    help_draw: 'No move? Draw from the boneyard until you can play. If it is empty you pass.',
    help_out: 'Empty your hand and you take the pips left in the other hand as a bonus.',
    help_badges: 'The badge at each open end shows its value: green when the ends already add up to a five, amber when they do not.',
    // aria
    aria_board: 'Domino chain',
    aria_hand: 'Your tiles',
    aria_tile: 'Tile {a} {b}',
    aria_end: 'Open end, value {v}',
    aria_close: 'Close',
    aria_help: 'How to play',
    aria_restart: 'Restart the game',
    aria_boneyard_tile: 'Draw a tile',
  },
  es: {
    title: 'Dominó',
    tagline: 'All Fives, a 300. Cada cinco sobre la mesa son puntos.',
    difficulty: 'Dificultad',
    diff_easy: 'Fácil',
    diff_medium: 'Medio',
    diff_hard: 'Difícil',
    row_difficulty: 'Dificultad',
    row_goal: 'Puntuación objetivo',
    goal_n: '{n} puntos',
    play: 'Jugar',
    howto: 'Cómo se juega',
    goal: 'Meta',
    you: 'Tú',
    bot: 'Bot',
    round_n: 'Ronda {n}',
    boneyard: 'Pozo',
    bot_thinking: 'El bot piensa',
    restart: 'Reiniciar',
    tap_again_confirm: 'Toca otra vez para reiniciar',
    you_passed: 'Sin jugada, pasas',
    bot_passed: 'El bot pasa',
    bot_drew: 'El bot roba',
    pick_an_end: 'Elige un extremo',
    round_over: 'Fin de la ronda',
    game_over: 'Fin de la partida',
    you_win: '¡Ganas tú!',
    bot_wins: 'Gana el bot',
    round_rule: 'Cuando alguien llega a {n}, la partida termina.',
    col_player: 'Jugador',
    col_round: 'Ronda',
    col_total: 'Total',
    continue: 'Continuar',
    play_again: 'Jugar otra vez',
    close: 'Cerrar',
    went_out: 'Se queda sin fichas',
    blocked: 'Cierre',
    help_goal: 'Encaja una ficha en uno de los extremos abiertos. Gana quien llegue antes a {n} puntos.',
    help_fives: 'Después de colocar una ficha, suma los extremos abiertos. Si el total es múltiplo de cinco, lo anotas.',
    help_doubles: 'Los dobles se ponen cruzados y cuentan sus dos mitades en un extremo. El primer doble es el eje: cuando la línea pasa de él por los dos lados, puedes salir por sus dos lados libres.',
    help_draw: '¿Sin jugada? Roba del pozo hasta poder jugar. Si está vacío, pasas.',
    help_out: 'Si te quedas sin fichas, te llevas de premio los puntos que queden en la otra mano.',
    help_badges: 'La placa de cada extremo abierto muestra su valor: verde cuando los extremos ya suman un múltiplo de cinco, ámbar cuando no.',
    aria_board: 'Cadena de fichas',
    aria_hand: 'Tus fichas',
    aria_tile: 'Ficha {a} {b}',
    aria_end: 'Extremo abierto, valor {v}',
    aria_close: 'Cerrar',
    aria_help: 'Cómo se juega',
    aria_restart: 'Reiniciar la partida',
    aria_boneyard_tile: 'Robar una ficha',
  },
};

export default STRINGS;
