// tic-tac-toe/js/strings.js — every user-visible string in Tic Tac Toe, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback
// shows English for anything missing). Values (variant key classic/ultimate, difficulty key
// beginner/intermediate/pro, marks X/O) are storage vocabulary and stay canonical — only their
// display labels translate.

export const STRINGS = {
  en: {
    title: 'Tic Tac Toe',
    tagline: 'Classic 3x3, or Ultimate: nine boards in one.',
    stats_line: '{total} played · Classic {cw}-{cl}-{ct} · Ultimate {uw}-{ul}-{ut}',
    vs: 'vs',
    row_variant: 'Variant',
    row_difficulty: 'Difficulty',
    row_first: 'First move',
    variant_classic: 'Classic',
    variant_ultimate: 'Ultimate',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    you: 'You',
    hint_variant_ultimate: 'Nine 3x3 boards in one. The cell you play picks which board your opponent plays next.',
    hint_variant_classic: 'The original: one 3x3 board, three in a row wins.',
    hint_diff_pro_ultimate: 'Deep search under a time budget. Very tough to beat.',
    hint_diff_pro_classic: 'Perfect play: the best you can do is draw.',
    hint_diff_intermediate: 'Blocks your wins and thinks a little ahead.',
    hint_diff_beginner: 'Mostly plays at random.',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'New game',
    change_settings: 'Change settings',
    draw: 'Draw',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    opp_thinking: '{opp} is thinking...',
    your_turn_any_board: 'Your turn: play in any highlighted board',
    your_turn_board: 'Your turn: play in board {n}',
    your_turn: 'Your turn',
    opp_turn: "{opp}'s turn",
    cell_occupied_aria: 'Row {r}, column {c}, occupied by {mark}',
    cell_empty_aria: 'Row {r}, column {c}, empty',
    board_aria: 'Tic Tac Toe board',
    uboard_aria: 'Ultimate Tic Tac Toe board',
    scell_occupied_aria: 'Board {n}, row {r}, column {c}, occupied by {mark}',
    scell_empty_aria: 'Board {n}, row {r}, column {c}, empty',
    sboard_drawn_aria: 'Board {n}, drawn',
    sboard_won_aria: 'Board {n}, won by {mark}',
    sboard_aria: 'Board {n}',
    game_over: 'Game over',
    close: 'Close',
    play_again: 'Play again',
    help_lead: 'Win the big board to win the game.',
    help_diagram_aria: 'Playing the top-right cell of a board sends your opponent to the top-right board',
    help_caption: 'Your move determines the next board.',
    help_example: 'Play top right box = Opponent plays top right board',
    help_rule: 'Sent to a completed mini-board = play on any live board.',
  },
  es: {
    title: 'Tres en Raya',
    tagline: 'Clásico 3x3, o Definitivo: nueve tableros en uno.',
    stats_line: '{total} jugadas · Clásico {cw}-{cl}-{ct} · Definitivo {uw}-{ul}-{ut}',
    vs: 'vs',
    row_variant: 'Variante',
    row_difficulty: 'Dificultad',
    row_first: 'Primer movimiento',
    variant_classic: 'Clásico',
    variant_ultimate: 'Definitivo',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Pro',
    you: 'Tú',
    hint_variant_ultimate: 'Nueve tableros 3x3 en uno. La casilla que juegas elige en qué tablero juega tu rival a continuación.',
    hint_variant_classic: 'El original: un tablero 3x3, tres en línea gana.',
    hint_diff_pro_ultimate: 'Búsqueda profunda con un límite de tiempo. Muy difícil de vencer.',
    hint_diff_pro_classic: 'Juego perfecto: lo máximo que puedes lograr es un empate.',
    hint_diff_intermediate: 'Bloquea tus victorias y piensa un poco por delante.',
    hint_diff_beginner: 'Juega casi siempre al azar.',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Nueva partida',
    change_settings: 'Cambiar ajustes',
    draw: 'Empate',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    opp_thinking: '{opp} está pensando...',
    your_turn_any_board: 'Tu turno: juega en cualquier tablero resaltado',
    your_turn_board: 'Tu turno: juega en el tablero {n}',
    your_turn: 'Tu turno',
    opp_turn: 'Turno de {opp}',
    cell_occupied_aria: 'Fila {r}, columna {c}, ocupada por {mark}',
    cell_empty_aria: 'Fila {r}, columna {c}, vacía',
    board_aria: 'Tablero de Tic Tac Toe',
    uboard_aria: 'Tablero de Tic Tac Toe Definitivo',
    scell_occupied_aria: 'Tablero {n}, fila {r}, columna {c}, ocupada por {mark}',
    scell_empty_aria: 'Tablero {n}, fila {r}, columna {c}, vacía',
    sboard_drawn_aria: 'Tablero {n}, empatado',
    sboard_won_aria: 'Tablero {n}, ganado por {mark}',
    sboard_aria: 'Tablero {n}',
    game_over: 'Fin de la partida',
    close: 'Cerrar',
    play_again: 'Jugar otra vez',
    help_lead: 'Gana el tablero grande para ganar la partida.',
    help_diagram_aria: 'Jugar la casilla superior derecha de un tablero envía a tu rival al tablero superior derecho',
    help_caption: 'Tu jugada determina el siguiente tablero.',
    help_example: 'Juega la casilla superior derecha = El rival juega en el tablero superior derecho',
    help_rule: 'Enviado a un mini-tablero completo = juega en cualquier tablero activo.',
  },
};

export default STRINGS;
