// tic-tac-toe/js/strings.js — every user-visible string in Tic Tac Toe, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback
// shows English for anything missing). Values (variant key classic/ultimate, difficulty key
// beginner/intermediate/pro, marks X/O) are storage vocabulary and stay canonical — only their
// display labels translate.

export const STRINGS = {
  en: {
    title: 'Tic Tac Toe',
    tagline: 'Classic 3x3, or Ultimate: nine boards in one.',
    stats_line: '{total} played · Classic {cw}-{cl}-{ct} · Ultimate {uw}-{ul}-{ut}',
    vs: 'vs',
    row_variant: 'Variant',
    row_difficulty: 'Difficulty',
    row_first: 'First move',
    variant_classic: 'Classic',
    variant_ultimate: 'Ultimate',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    you: 'You',
    computer: 'Computer',
    first_alternate: 'Alternate',
    you_start: 'You open',
    name_starts: '{name} opens',
    hint_variant_ultimate: 'Nine 3x3 boards in one. The cell you play picks which board your opponent plays next.',
    hint_variant_classic: 'The original: one 3x3 board, three in a row wins.',
    start: 'Start game',
    howto: 'How to play',
    new_game: 'New game',
    restart_game: 'Restart',
    tap_again_confirm: 'Tap again to confirm',
    change_settings: 'Change settings',
    draw: 'Draw',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    opp_thinking: '{opp} is thinking...',
    your_turn_any_board: 'Your turn: play in any highlighted board',
    your_turn_board: 'Your turn: play in board {n}',
    your_turn: 'Your turn',
    opp_turn: "{opp}'s turn",
    cell_occupied_aria: 'Row {r}, column {c}, occupied by {mark}',
    cell_empty_aria: 'Row {r}, column {c}, empty',
    board_aria: 'Tic Tac Toe board',
    uboard_aria: 'Ultimate Tic Tac Toe board',
    scell_occupied_aria: 'Board {n}, row {r}, column {c}, occupied by {mark}',
    scell_empty_aria: 'Board {n}, row {r}, column {c}, empty',
    sboard_drawn_aria: 'Board {n}, drawn',
    sboard_won_aria: 'Board {n}, won by {mark}',
    sboard_aria: 'Board {n}',
    game_over: 'Game over',
    close: 'Close',
    play_again: 'Play again',
    help_lead: 'Win the big board to win the game.',
    help_diagram_aria: 'Playing the top-right cell of a board sends your opponent to the top-right board',
    help_caption: 'Your move determines the next board.',
    help_example: 'Play top right box = Opponent plays top right board',
    help_rule: 'Sent to a completed mini-board = play on any live board.',
    help_classic_lead: 'Get three in a row.',
    help_classic_diagram_aria: 'Three X marks in a diagonal line, highlighted',
    help_classic_caption: 'Three in a row across, down, or diagonally wins.',
    // --- multiplayer. Protocol values (host/guest, the room code alphabet,
    // the seat numbers) are never translated; only these labels are.
    mode_solo: 'Solo',
    mode_host: 'Host',
    mode_join: 'Join',
    mp_host_btn: 'Create room',
    mp_host_hint: 'Play someone else on their own phone.',
    mp_join_hint: 'Ask the host for their 4-character code.',
    mp_creating_room: 'Creating room...',
    mp_joining: 'Joining...',
    mp_enter_code: 'Enter code',
    mp_code_aria: 'Room code',
    mp_join_btn: 'Join',
    mp_back_btn: 'Back',
    mp_start_btn: 'Start',
    mp_share_code: 'Share this code with your opponent.',
    mp_waiting_opponent: 'Waiting for someone to join',
    mp_waiting_host: 'Waiting for host',
    mp_opponent_label: 'Opponent',
    mp_host_label: 'Host',
    mp_leave_btn: 'Leave',
    mp_series: 'You {me} · {opp} {them} · Drawn {d}',
    mp_waiting_rematch: 'Waiting for {opp} to start another game',
    mp_status_connection_error: 'Connection error',
    mp_status_resyncing: 'Resyncing...',
    mp_status_opponent_disconnected: 'Opponent disconnected',
    mp_update_required: 'Update required',
    mp_err_could_not_create_room: 'Could not create a room',
    mp_err_offline: 'Offline',
    mp_err_room_not_found: 'Room not found',
    mp_err_room_full: 'Room full',
    mp_err_wrong_game: 'That code is for another game',
    mp_error_title: 'Connection error',
    mp_error_sub: 'The game could not stay in sync',
    mp_opponent_left_title: 'Opponent left',
    mp_opponent_left_sub: 'The room is closed',
    mp_back_to_setup: 'Back to setup',
  },
  es: {
    title: 'Tres en Raya',
    tagline: 'Clásico 3x3, o Definitivo: nueve tableros en uno.',
    stats_line: '{total} jugadas · Clásico {cw}-{cl}-{ct} · Definitivo {uw}-{ul}-{ut}',
    vs: 'vs',
    row_variant: 'Variante',
    row_difficulty: 'Dificultad',
    row_first: 'Primer movimiento',
    variant_classic: 'Clásico',
    variant_ultimate: 'Definitivo',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    you: 'Tú',
    computer: 'Ordenador',
    first_alternate: 'Alternar',
    you_start: 'Abres tú',
    name_starts: 'Abre {name}',
    hint_variant_ultimate: 'Nueve tableros 3x3 en uno. La casilla que juegas elige en qué tablero juega tu rival a continuación.',
    hint_variant_classic: 'El original: un tablero 3x3, tres en línea gana.',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    new_game: 'Nueva partida',
    restart_game: 'Reiniciar',
    tap_again_confirm: 'Toca otra vez para confirmar',
    change_settings: 'Cambiar ajustes',
    draw: 'Empate',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    opp_thinking: '{opp} está pensando...',
    your_turn_any_board: 'Tu turno: juega en cualquier tablero resaltado',
    your_turn_board: 'Tu turno: juega en el tablero {n}',
    your_turn: 'Tu turno',
    opp_turn: 'Turno de {opp}',
    cell_occupied_aria: 'Fila {r}, columna {c}, ocupada por {mark}',
    cell_empty_aria: 'Fila {r}, columna {c}, vacía',
    board_aria: 'Tablero de Tic Tac Toe',
    uboard_aria: 'Tablero de Tic Tac Toe Definitivo',
    scell_occupied_aria: 'Tablero {n}, fila {r}, columna {c}, ocupada por {mark}',
    scell_empty_aria: 'Tablero {n}, fila {r}, columna {c}, vacía',
    sboard_drawn_aria: 'Tablero {n}, empatado',
    sboard_won_aria: 'Tablero {n}, ganado por {mark}',
    sboard_aria: 'Tablero {n}',
    game_over: 'Fin de la partida',
    close: 'Cerrar',
    play_again: 'Jugar otra vez',
    help_lead: 'Gana el tablero grande para ganar la partida.',
    help_diagram_aria: 'Jugar la casilla superior derecha de un tablero envía a tu rival al tablero superior derecho',
    help_caption: 'Tu jugada determina el siguiente tablero.',
    help_example: 'Juega la casilla superior derecha = El rival juega en el tablero superior derecho',
    help_rule: 'Enviado a un mini-tablero completo = juega en cualquier tablero activo.',
    help_classic_lead: 'Consigue tres en línea.',
    help_classic_diagram_aria: 'Tres marcas X en línea diagonal, resaltadas',
    help_classic_caption: 'Tres en línea en fila, columna o diagonal gana.',
    mode_solo: 'Solo',
    mode_host: 'Crear',
    mode_join: 'Unirse',
    mp_host_btn: 'Crear sala',
    mp_host_hint: 'Juega contra alguien en su propio móvil.',
    mp_join_hint: 'Pide al anfitrión su código de 4 caracteres.',
    mp_creating_room: 'Creando sala...',
    mp_joining: 'Uniéndose...',
    mp_enter_code: 'Introduce el código',
    mp_code_aria: 'Código de sala',
    mp_join_btn: 'Unirse',
    mp_back_btn: 'Atrás',
    mp_start_btn: 'Empezar',
    mp_share_code: 'Comparte este código con tu rival.',
    mp_waiting_opponent: 'Esperando a que alguien entre',
    mp_waiting_host: 'Esperando al anfitrión',
    mp_opponent_label: 'Rival',
    mp_host_label: 'Anfitrión',
    mp_leave_btn: 'Salir',
    mp_series: 'Tú {me} · {opp} {them} · Empates {d}',
    mp_waiting_rematch: 'Esperando a que {opp} empiece otra partida',
    mp_status_connection_error: 'Error de conexión',
    mp_status_resyncing: 'Resincronizando...',
    mp_status_opponent_disconnected: 'Rival desconectado',
    mp_update_required: 'Actualización necesaria',
    mp_err_could_not_create_room: 'No se pudo crear la sala',
    mp_err_offline: 'Sin conexión',
    mp_err_room_not_found: 'Sala no encontrada',
    mp_err_room_full: 'Sala llena',
    mp_err_wrong_game: 'Ese código es de otro juego',
    mp_error_title: 'Error de conexión',
    mp_error_sub: 'La partida no pudo mantenerse sincronizada',
    mp_opponent_left_title: 'El rival se fue',
    mp_opponent_left_sub: 'La sala está cerrada',
    mp_back_to_setup: 'Volver a ajustes',
  },
};

export default STRINGS;
