// golf/js/strings.js - {en, es}. See §13.6 of GOLF-HANDOFF.md. English is the source of truth;
// a missing Spanish key falls back to English (js/i18n.js).

export const STRINGS = {
  en: {
    title: 'Golf',
    play: 'Play',
    resume: 'Resume',
    new_round: 'New round',
    back: 'Back',
    again: 'Play again',
    hole: 'Hole',
    par: 'Par',
    yd: 'yd',
    mph: 'mph',
    lie_tee: 'Tee',
    lie_fairway: 'Fairway',
    lie_rough: 'Rough',
    lie_fringe: 'Fringe',
    lie_green: 'Green',
    lie_sand: 'Sand',
    lie_water: 'Water',
    lie_ob: 'OB',
    res_ace: 'Ace',
    res_albatross: 'Albatross',
    res_eagle: 'Eagle',
    res_birdie: 'Birdie',
    res_par: 'Par',
    res_bogey: 'Bogey',
    res_double: 'Double',
    res_triple: 'Triple',
    pen_water: 'Water +1',
    pen_ob: 'OB +1',
    skill: 'Skill level',
    strokes: 'Strokes',
    pts: 'Pts',
    total: 'Total',
    diff_casual: 'Casual',
    diff_standard: 'Standard',
    diff_pro: 'Pro',
    course_harbor: 'Harbor Links',
    locked: 'Locked',
    stats_rounds: 'Rounds',
    stats_avg: 'Avg strokes',
    stats_birdies: 'Birdies',
    stats_eagles: 'Eagles',
    stats_aces: 'Aces',
    stats_drive: 'Longest drive',
    stats_best: 'Best round',
    game_title_golf: 'Golf',
  },
  es: {
    title: 'Golf',
    play: 'Jugar',
    resume: 'Reanudar',
    new_round: 'Nueva ronda',
    back: 'Volver',
    again: 'Jugar de nuevo',
    hole: 'Hoyo',
    par: 'Par',
    yd: 'yd',
    mph: 'mph',
    lie_tee: 'Salida',
    lie_fairway: 'Calle',
    lie_rough: 'Rough',
    lie_fringe: 'Franja',
    lie_green: 'Green',
    lie_sand: 'Arena',
    lie_water: 'Agua',
    lie_ob: 'Fuera',
    res_ace: 'Hoyo en uno',
    res_albatross: 'Albatros',
    res_eagle: 'Eagle',
    res_birdie: 'Birdie',
    res_par: 'Par',
    res_bogey: 'Bogey',
    res_double: 'Doble bogey',
    res_triple: 'Triple bogey',
    pen_water: 'Agua +1',
    pen_ob: 'Fuera +1',
    skill: 'Nivel de habilidad',
    strokes: 'Golpes',
    pts: 'Pts',
    total: 'Total',
    diff_casual: 'Casual',
    diff_standard: 'Estandar',
    diff_pro: 'Pro',
    course_harbor: 'Harbor Links',
    locked: 'Bloqueado',
    stats_rounds: 'Rondas',
    stats_avg: 'Golpes promedio',
    stats_birdies: 'Birdies',
    stats_eagles: 'Eagles',
    stats_aces: 'Hoyos en uno',
    stats_drive: 'Drive mas largo',
    stats_best: 'Mejor ronda',
    game_title_golf: 'Golf',
  },
};

export default STRINGS;
