// golf/js/strings.js - {en, es}. English is the source of truth; a missing Spanish key falls back
// to English (js/i18n.js). Call t() at RENDER time, never at module scope.
//
// Button labels are lowercase and panel headings uppercase, matching the reference's own
// typographic rule (golf-reference-spec.md §15.2). No em dashes in user-facing copy.

export const STRINGS = {
  en: {
    title: 'Golf',
    course: 'Golf',
    // setup
    play: 'play',
    practice: 'practice hole',
    resume: 'resume round',
    holes_n: '3 hole',
    best_none: 'Best: -',
    best_is: 'Best: {n}',
    blurb: 'Wide fairways and still conditions.',
    blurb_pinevalley: 'Parkland. Tree lined corridors and water on nine of the eighteen.',
    blurb_redmesa: 'High desert. Narrow turf, saguaro, boulders and a lot of red dirt.',
    select_hole: 'Select practice hole:',
    back: 'back',
    // courses and rounds
    course_pinevalley: 'Pine Valley',
    course_redmesa: 'Red Mesa',
    round_quick3: '3 holes',
    round_front9: 'front 9',
    round_back9: 'back 9',
    round_full18: '18 holes',
    course_meta: '{holes} holes | par {par} | {yds} yds',
    round_meta: 'par {par} | {yds} yds',
    pick_round: 'How much do you want to play?',
    scorecard: 'scorecard',
    round_done: 'Round complete',
    out: 'out',
    in_: 'in',
    tot: 'tot',
    hole_abbr: 'hole',
    par_abbr: 'par',
    you: 'you',
    saved_best: 'New best round',
    not_counted: 'Practice holes are not scored.',
    // hud
    card: 'card',
    par_n: 'par {n}',
    shot_n: 'shot {n}',
    mode_practice: 'practice',
    mode_round: 'round',
    wind: 'wind',
    aim: 'aim',
    swing: 'swing',
    quit: 'quit',
    yds: 'yds',
    ft: 'ft',
    last_shot: 'last shot: {d}',
    power_pct: 'Power: {n}%',
    tap_to_skip: 'tap to skip',
    // lies
    lie_tee: 'Tee',
    lie_fairway: 'Fairway',
    lie_fringe: 'Fringe',
    lie_lightRough: 'Light rough',
    lie_heavyRough: 'Heavy rough',
    lie_fairwayBunker: 'Bunker',
    lie_greensideBunker: 'Bunker',
    lie_trees: 'Trees',
    lie_green: 'Green',
    lie_water: 'Water',
    // clubs
    club_driver: 'driver',
    club_3wood: '3 wood',
    club_5wood: '5 wood',
    club_2iron: '2 iron',
    club_3iron: '3 iron',
    club_4iron: '4 iron',
    club_5iron: '5 iron',
    club_6iron: '6 iron',
    club_7iron: '7 iron',
    club_8iron: '8 iron',
    club_9iron: '9 iron',
    club_pwedge: 'p. wedge',
    club_swedge: 's. wedge',
    club_lwedge: 'l. wedge',
    club_putter: 'putter',
    // aria
    a11y_aim_left: 'Aim left',
    a11y_aim_right: 'Aim right',
    a11y_club_up: 'More club',
    a11y_club_down: 'Less club',
    a11y_swing: 'Swing',
    a11y_view: 'Course view',
    last_shot_lbl: 'last shot',
    score_ace: 'Hole in one!',
    score_albatross: 'Albatross!',
    score_eagle: 'Eagle!',
    score_birdie: 'Birdie!',
    score_par: 'Par',
    score_bogey: 'Bogey',
    score_double: 'Double bogey',
    score_over: '{n} over par',
    holed_in: 'Holed in {n}',
    next_hole: 'next hole',
    finish: 'finish',
    again: 'play again',
    to_par_even: 'even',
    to_par_under: '{n} under',
    to_par_over: '{n} over',
  },
  es: {
    title: 'Golf',
    course: 'Pine Valley',
    play: 'jugar',
    practice: 'hoyo suelto',
    blurb_pinevalley: 'Parque. Calles entre árboles y agua en nueve de los dieciocho.',
    blurb_redmesa: 'Desierto alto. Césped estrecho, saguaros, rocas y mucha tierra roja.',
    course_pinevalley: 'Pine Valley',
    course_redmesa: 'Red Mesa',
    round_quick3: '3 hoyos',
    round_front9: 'primeros 9',
    round_back9: 'últimos 9',
    round_full18: '18 hoyos',
    course_meta: '{holes} hoyos | par {par} | {yds} yds',
    round_meta: 'par {par} | {yds} yds',
    pick_round: '¿Cuánto quieres jugar?',
    scorecard: 'tarjeta',
    round_done: 'Vuelta completa',
    out: 'ida',
    in_: 'vuelta',
    tot: 'tot',
    hole_abbr: 'hoyo',
    par_abbr: 'par',
    you: 'tú',
    saved_best: 'Nueva mejor vuelta',
    not_counted: 'Los hoyos sueltos no puntúan.',
    resume: 'seguir vuelta',
    holes_n: '3 hoyos',
    best_none: 'Mejor: -',
    best_is: 'Mejor: {n}',
    blurb: 'Calles anchas y sin viento.',
    select_hole: 'Elige un hoyo:',
    back: 'atrás',
    card: 'tarjeta',
    par_n: 'par {n}',
    shot_n: 'golpe {n}',
    mode_practice: 'práctica',
    mode_round: 'vuelta',
    wind: 'viento',
    aim: 'mira',
    swing: 'golpear',
    quit: 'salir',
    yds: 'yds',
    ft: 'pies',
    last_shot: 'último golpe: {d}',
    power_pct: 'Potencia: {n}%',
    tap_to_skip: 'toca para saltar',
    lie_tee: 'Tee',
    lie_fairway: 'Calle',
    lie_fringe: 'Antegreen',
    lie_lightRough: 'Rough ligero',
    lie_heavyRough: 'Rough alto',
    lie_fairwayBunker: 'Búnker',
    lie_greensideBunker: 'Búnker',
    lie_trees: 'Árboles',
    lie_green: 'Green',
    lie_water: 'Agua',
    club_driver: 'driver',
    club_3wood: 'madera 3',
    club_5wood: 'madera 5',
    club_2iron: 'hierro 2',
    club_3iron: 'hierro 3',
    club_4iron: 'hierro 4',
    club_5iron: 'hierro 5',
    club_6iron: 'hierro 6',
    club_7iron: 'hierro 7',
    club_8iron: 'hierro 8',
    club_9iron: 'hierro 9',
    club_pwedge: 'pitching',
    club_swedge: 'sand',
    club_lwedge: 'lob',
    club_putter: 'putter',
    a11y_aim_left: 'Apuntar a la izquierda',
    a11y_aim_right: 'Apuntar a la derecha',
    a11y_club_up: 'Más palo',
    a11y_club_down: 'Menos palo',
    a11y_swing: 'Golpear',
    a11y_view: 'Vista del campo',
    last_shot_lbl: 'último golpe',
    score_ace: '¡Hoyo en uno!',
    score_albatross: '¡Albatros!',
    score_eagle: '¡Eagle!',
    score_birdie: '¡Birdie!',
    score_par: 'Par',
    score_bogey: 'Bogey',
    score_double: 'Doble bogey',
    score_over: '{n} sobre par',
    holed_in: 'Embocada en {n}',
    next_hole: 'siguiente hoyo',
    finish: 'terminar',
    again: 'jugar otra vez',
    to_par_even: 'par',
    to_par_under: '{n} bajo par',
    to_par_over: '{n} sobre par',
  },
};
