// golf/js/strings.js - {en, es}. English is the source of truth; a missing Spanish key falls back
// to English (js/i18n.js). Call t() at RENDER time, never at module scope.
//
// Button labels are lowercase and panel headings uppercase, matching the reference's own
// typographic rule (golf-reference-spec.md §15.2). No em dashes in user-facing copy.

export const STRINGS = {
  en: {
    title: 'Golf',
    course: 'Golf',
    // setup
    play: 'play',
    practice: 'practice hole',
    resume: 'resume round',
    holes_n: '3 hole',
    best_none: 'Best: -',
    best_is: 'Best: {n}',
    blurb: 'Wide fairways and still conditions.',
    blurb_pinevalley: 'Parkland. Tree lined corridors and water on nine of the eighteen.',
    blurb_redmesa: 'High desert. Narrow turf, saguaro, boulders and a lot of red dirt.',
    blurb_oasissands: 'Desert links. Wide waste sand, palm lines and water on six of the nine.',
    select_hole: 'Select practice hole:',
    back: 'back',
    // courses and rounds
    course_pinevalley: 'Pine Valley',
    course_redmesa: 'Red Mesa',
    course_oasissands: 'Oasis Sands',
    // One per ROUNDS entry in js/rounds.js. A missing one is not a blank - the HUD prints the KEY,
    // which is what Matt's whole Pine Valley round showed ("round_set3b 2/3"). test.js checks that
    // every round has a label in both languages.
    round_quick3: 'holes 1-3',
    round_set3b: 'holes 4-6',
    round_set3c: 'holes 7-9',
    round_set3d: 'holes 10-12',
    round_set3e: 'holes 13-15',
    round_set3f: 'holes 16-18',
    round_front9: 'front 9',
    round_back9: 'back 9',
    round_full18: '18 holes',
    course_meta: '{holes} holes | par {par} | {yds} yds',
    round_meta: 'par {par} | {yds} yds',
    pick_round: 'How much do you want to play?',
    pick_set: 'Which holes?',
    mode_holes: '{n} holes',
    holes_range: 'Holes {range}',
    scorecard: 'scorecard',
    round_done: 'Round complete',
    out: 'out',
    in_: 'in',
    tot: 'tot',
    hole_abbr: 'hole',
    par_abbr: 'par',
    you: 'you',
    saved_best: 'New best round',
    not_counted: 'Practice holes are not scored.',
    // hud
    card: 'card',
    par_n: 'par {n}',
    shot_n: 'shot {n}',
    mode_practice: 'practice',
    mode_round: 'round',
    wind: 'wind',
    aim: 'aim',
    swing: 'swing',
    quit: 'quit',
    yds: 'yds',
    ft: 'ft',
    last_shot: 'last shot: {d}',
    power_pct: 'Power: {n}%',
    tap_to_skip: 'tap to skip',
    // lies
    lie_tee: 'Tee',
    lie_fairway: 'Fairway',
    lie_fringe: 'Fringe',
    lie_lightRough: 'Light rough',
    lie_heavyRough: 'Heavy rough',
    lie_fairwayBunker: 'Bunker',
    lie_greensideBunker: 'Bunker',
    lie_trees: 'Trees',
    lie_green: 'Green',
    lie_water: 'Water',
    // clubs
    club_driver: 'driver',
    club_3wood: '3 wood',
    club_5wood: '5 wood',
    club_2iron: '2 iron',
    club_3iron: '3 iron',
    club_4iron: '4 iron',
    club_5iron: '5 iron',
    club_6iron: '6 iron',
    club_7iron: '7 iron',
    club_8iron: '8 iron',
    club_9iron: '9 iron',
    club_pwedge: 'pitch wedge',
    club_swedge: 'sand wedge',
    club_lwedge: 'lob wedge',
    club_putter: 'putter',
    // aria
    a11y_aim_left: 'Aim left',
    a11y_aim_right: 'Aim right',
    a11y_club_up: 'More club',
    a11y_club_down: 'Less club',
    a11y_swing: 'Swing',
    a11y_view: 'Course view',
    last_shot_lbl: 'last shot',
    // The drop prompt (golf-reference-spec.md 21.2). The banner names the trouble; the modal is
    // only ever shown where the player has a real choice.
    in_water: 'In the water',
    in_trees: 'In the trees',
    penalty_stroke: 'One penalty stroke',
    drop_q: 'Would you like to take a drop or play from your lie?',
    take_drop: 'Take a drop',
    play_from_lie: 'Play from lie',
    drop_costs: 'A drop costs one stroke',
    score_ace: 'Hole in one!',
    score_albatross: 'Albatross!',
    score_eagle: 'Eagle!',
    score_birdie: 'Birdie!',
    score_par: 'Par',
    score_bogey: 'Bogey',
    score_double: 'Double bogey',
    score_over: '{n} over par',
    holed_in: 'Holed in {n}',
    next_hole: 'next hole',
    finish: 'finish',
    quit_title: 'Leave this round?',
    quit_body: 'The round is not finished, so it will not be saved.',
    quit_yes: 'leave',
    quit_no: 'keep playing',
    again: 'play again',
    to_par_even: 'even',
    to_par_under: '{n} under',
    to_par_over: '{n} over',
  },
  es: {
    title: 'Golf',
    course: 'Pine Valley',
    play: 'jugar',
    practice: 'hoyo suelto',
    blurb_pinevalley: 'Parque. Calles entre árboles y agua en nueve de los dieciocho.',
    blurb_redmesa: 'Desierto alto. Césped estrecho, saguaros, rocas y mucha tierra roja.',
    blurb_oasissands: 'Links del desierto. Arena abierta, palmeras y agua en seis de los nueve.',
    course_pinevalley: 'Pine Valley',
    course_redmesa: 'Red Mesa',
    course_oasissands: 'Oasis Sands',
    round_quick3: 'hoyos 1-3',
    round_set3b: 'hoyos 4-6',
    round_set3c: 'hoyos 7-9',
    round_set3d: 'hoyos 10-12',
    round_set3e: 'hoyos 13-15',
    round_set3f: 'hoyos 16-18',
    round_front9: 'primeros 9',
    round_back9: 'últimos 9',
    round_full18: '18 hoyos',
    course_meta: '{holes} hoyos | par {par} | {yds} yds',
    round_meta: 'par {par} | {yds} yds',
    pick_round: '¿Cuánto quieres jugar?',
    pick_set: '¿Qué hoyos?',
    mode_holes: '{n} hoyos',
    holes_range: 'Hoyos {range}',
    scorecard: 'tarjeta',
    round_done: 'Vuelta completa',
    out: 'ida',
    in_: 'vuelta',
    tot: 'tot',
    hole_abbr: 'hoyo',
    par_abbr: 'par',
    you: 'tú',
    saved_best: 'Nueva mejor vuelta',
    not_counted: 'Los hoyos sueltos no puntúan.',
    resume: 'seguir vuelta',
    holes_n: '3 hoyos',
    best_none: 'Mejor: -',
    best_is: 'Mejor: {n}',
    blurb: 'Calles anchas y sin viento.',
    select_hole: 'Elige un hoyo:',
    back: 'atrás',
    card: 'tarjeta',
    par_n: 'par {n}',
    shot_n: 'golpe {n}',
    mode_practice: 'práctica',
    mode_round: 'vuelta',
    wind: 'viento',
    aim: 'mira',
    swing: 'golpear',
    quit: 'salir',
    yds: 'yds',
    ft: 'pies',
    last_shot: 'último golpe: {d}',
    power_pct: 'Potencia: {n}%',
    tap_to_skip: 'toca para saltar',
    lie_tee: 'Tee',
    lie_fairway: 'Calle',
    lie_fringe: 'Antegreen',
    lie_lightRough: 'Rough ligero',
    lie_heavyRough: 'Rough alto',
    lie_fairwayBunker: 'Búnker',
    lie_greensideBunker: 'Búnker',
    lie_trees: 'Árboles',
    lie_green: 'Green',
    lie_water: 'Agua',
    club_driver: 'driver',
    club_3wood: 'madera 3',
    club_5wood: 'madera 5',
    club_2iron: 'hierro 2',
    club_3iron: 'hierro 3',
    club_4iron: 'hierro 4',
    club_5iron: 'hierro 5',
    club_6iron: 'hierro 6',
    club_7iron: 'hierro 7',
    club_8iron: 'hierro 8',
    club_9iron: 'hierro 9',
    club_pwedge: 'pitching wedge',
    club_swedge: 'sand wedge',
    club_lwedge: 'lob wedge',
    club_putter: 'putter',
    a11y_aim_left: 'Apuntar a la izquierda',
    a11y_aim_right: 'Apuntar a la derecha',
    a11y_club_up: 'Más palo',
    a11y_club_down: 'Menos palo',
    a11y_swing: 'Golpear',
    a11y_view: 'Vista del campo',
    last_shot_lbl: 'último golpe',
    in_water: 'En el agua',
    in_trees: 'Entre los árboles',
    penalty_stroke: 'Un golpe de penalización',
    drop_q: '¿Quieres tomar un drop o jugar la bola como está?',
    take_drop: 'Tomar un drop',
    play_from_lie: 'Jugar como está',
    drop_costs: 'El drop cuesta un golpe',
    score_ace: '¡Hoyo en uno!',
    score_albatross: '¡Albatros!',
    score_eagle: '¡Eagle!',
    score_birdie: '¡Birdie!',
    score_par: 'Par',
    score_bogey: 'Bogey',
    score_double: 'Doble bogey',
    score_over: '{n} sobre par',
    holed_in: 'Embocada en {n}',
    next_hole: 'siguiente hoyo',
    finish: 'terminar',
    quit_title: '¿Salir de la vuelta?',
    quit_body: 'La vuelta no está terminada, así que no se guardará.',
    quit_yes: 'salir',
    quit_no: 'seguir jugando',
    again: 'jugar otra vez',
    to_par_even: 'par',
    to_par_under: '{n} bajo par',
    to_par_over: '{n} sobre par',
  },
};
