// escoba/js/strings.js — every user-visible string in Escoba, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for any
// missing key -- partial translation can never break a screen).
//
// NOT translated, on purpose (see HANDOFF-I18N-EXTRACTION.md decision 7 + escoba's own rules):
// - Card-suit terms Oros/Copas/Espadas/Bastos, and named figures Sota/Caballo/Rey -- the games'
//   real vocabulary in BOTH languages.
// - "Escoba"/"Escobas"/"¡ESCOBA!" -- the game's own name and its central move, kept identical
//   in both dictionaries deliberately (same idea as the game title itself).
// - `deck.js`'s cardLabel() output (e.g. "7 de Oros") -- a pure data-layer formatter, out of
//   scope for this UI-only pass, and already Spanish-phrased regardless of hub language.
// - Round-modal bonus footnotes ("Opponent under 10 cards", "All the coins", "All four 7s") --
//   these strings are generated by escoba/js/game.js (the engine, out of scope; see root
//   CLAUDE.md "Adding a game" and the i18n handoff's "never touch normDiff/recorders/engines"
//   boundary), so they stay English even with the hub set to Spanish. A future pass would need
//   to move them into a lookup keyed by item.key rather than baking the label into the engine.
// - Storage vocabulary: difficulty ids (easy/normal/hard), deckMode ids (spanish/american), mode
//   ids (solo/host/join), and the 'version' MP-error sentinel all stay canonical -- only their
//   display labels translate.

export const STRINGS = {
  en: {
    title: 'Escoba',
    aria_menu: 'Game menu',
    aria_table: 'Table cards',
    lasthand_chip: 'Last hand',
    vs: 'vs',
    you: 'You',

    // Settings summary card
    lbl_players: 'Players',
    lbl_difficulty: 'Difficulty',
    lbl_playto: 'Play to',
    lbl_cardnumbering: 'Card numbering',
    lbl_capturehints: 'Capture hints',
    aria_your_name: 'Your name',
    aria_opp_name: 'Opponent {n} name',
    title_choose_avatar: 'Choose avatar',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    target_pts: '{n} points',
    deckmode_spanish: 'Spanish',
    deckmode_american: 'American',
    hint_deckmode_american: 'Cards 1 to 10, every card counts the number printed on it. No Caballo or Rey.',
    hint_deckmode_spanish: 'Traditional deck: Sota (printed 10) counts 8, Caballo (11) counts 9, Rey (12) counts 10.',
    assist_on: 'On',
    assist_off: 'Off',
    hint_assist_on: 'Combinable table cards are highlighted and a running sum shows as you build a capture.',
    hint_assist_off: 'Unassisted: nothing is highlighted, no running sum. You work out the 15 yourself.',

    // Join mode
    mp_update_required: 'Update required',
    mp_joining: 'Joining…',
    lbl_enter_code: 'Enter code',
    aria_room_code: 'Room code',
    btn_join: 'Join',

    // Setup screen
    stats_line: '{played} played · {won} won · {escobas} escobas',
    btn_resume: 'Resume game',
    mode_solo: 'Solo',
    mode_host: 'Host online',
    mode_join: 'Join',
    btn_host_game: 'Host game',
    btn_new_game: 'New game',
    btn_start_game: 'Start game',
    howto_label: 'How to play',

    // MP config summary / lobby
    pts_value: '{n} pts',
    pts_label: 'pts',
    deck_american_label: 'American deck',
    deck_spanish_label: 'Spanish deck',
    btn_back: 'Back',
    lbl_room_code: 'Room code',
    lbl_opponent: 'Opponent',
    mp_creating_room: 'Creating room…',
    btn_start: 'Start',
    lbl_host: 'Host',
    mp_waiting_host: 'Waiting for host',

    // Avatar picker
    avatar_title: 'Choose your avatar',
    btn_close: 'Close',
    aria_avatar: 'Avatar {av}',

    // How to play (batch D/FB3-HOWTO3: trimmed to the standard one-sheet pattern)
    howto_title: 'How to play Escoba',
    btn_done: 'Done',
    howto_goal: 'Capture cards that sum to 15.',
    howto_caption: 'On your turn play one card; if it sums to 15 with table cards, you capture them. An escoba clears the whole table.',
    score_escobas: 'Escobas: 1 point each',
    score_cards: 'Most cards: 1 point (+2 if the opponent has fewer than 10, 2 players)',
    score_coins: 'Most oros: 1 point (+2 for all 10)',
    score_sevens: 'Sevens: 1 point for most, 3 for all four (or 1 for the lone 7 of Oros)',
    howto_figures_note: 'Sota, Caballo and Rey count 8, 9 and 10, not their printed number.',

    // In-game announcements / chips
    announce_last_cards: 'Last cards',
    banner_takes_opening: '{name} takes the opening table',
    banner_clears_table: '{name} clears the table',
    announce_takes_leftover: '{name} takes the leftover cards',
    announce_plays_captures: '{name} plays {card} · captures {n}',
    announce_plays: '{name} plays {card}',
    round_n: 'Round {n}',
    first_to_n: 'First to {n}',
    title_captured: 'Cards captured',
    title_coins: 'Oros captured',
    title_escobas_round: 'Escobas this round',
    title_hand_count: 'Cards in hand',
    dealer_letter: 'D',
    dealer_title: 'Dealer',

    // Actions
    btn_results: 'Results',
    btn_place: 'Place {card}',
    btn_capture: 'Capture',

    // Round / match modals
    row_escobas: 'Escobas',
    row_cards: 'Cards',
    row_coincards: 'Coin cards',
    row_sevens: 'Sevens',
    round_points: 'Round {n} points',
    row_total_scores: 'Total scores',
    btn_table: 'Table',
    btn_scoreboard: '📈 Scoreboard',
    btn_standings: 'Standings',
    btn_next_round: 'Next round',
    aria_close: 'Close',
    reason_whitewash: 'Opponent captured no cards: instant win',
    wins_headline: '{name} wins!',
    aria_chart: 'Cumulative score by round',
    chart_target: 'target {n}',

    // In-game menu
    menu_title: 'Menu',
    menu_leave_match: 'Leave match',
    menu_newgame_samesettings: 'New game (same settings)',
    menu_quit_setup: 'Quit to setup',
    menu_confirm_lost: 'Tap again: this game will be lost',

    // MP error/opponent modals + status toasts
    mp_conn_error_title: 'Connection error',
    mp_conn_error_sub: 'The match could not stay in sync',
    btn_back_to_setup: 'Back to setup',
    mp_opponent_left_title: 'Opponent left',
    mp_final_standings: 'Final standings',
    mp_status_resyncing: 'Resyncing',
    mp_status_opp_disconnected: 'Opponent disconnected',
    mp_status_opp_left: 'Opponent left',
    mp_could_not_create_room: 'Could not create a room',
    mp_offline: 'Offline',
    mp_room_not_found: 'Room not found',
    mp_room_ended: 'Room ended',
    mp_room_full: 'Room full',
  },
  es: {
    title: 'Escoba',
    aria_menu: 'Menú del juego',
    aria_table: 'Cartas de la mesa',
    lasthand_chip: 'Última mano',
    vs: 'vs',
    you: 'Tú',

    lbl_players: 'Jugadores',
    lbl_difficulty: 'Dificultad',
    lbl_playto: 'Jugar a',
    lbl_cardnumbering: 'Numeración de cartas',
    lbl_capturehints: 'Ayudas de captura',
    aria_your_name: 'Tu nombre',
    aria_opp_name: 'Nombre del rival {n}',
    title_choose_avatar: 'Elegir avatar',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    target_pts: '{n} puntos',
    deckmode_spanish: 'Español',
    deckmode_american: 'Americano',
    hint_deckmode_american: 'Cartas del 1 al 10, cada carta vale el número impreso. Sin Caballo ni Rey.',
    hint_deckmode_spanish: 'Baraja tradicional: la Sota (impreso 10) vale 8, el Caballo (11) vale 9, el Rey (12) vale 10.',
    assist_on: 'Activado',
    assist_off: 'Desactivado',
    hint_assist_on: 'Las cartas de la mesa combinables se resaltan y una suma en curso se muestra al construir una captura.',
    hint_assist_off: 'Sin ayudas: nada se resalta, no hay suma en curso. Tú calculas el 15.',

    mp_update_required: 'Actualización necesaria',
    mp_joining: 'Uniéndose…',
    lbl_enter_code: 'Introduce el código',
    aria_room_code: 'Código de sala',
    btn_join: 'Unirse',

    stats_line: '{played} jugadas · {won} ganadas · {escobas} escobas',
    btn_resume: 'Reanudar partida',
    mode_solo: 'Solo',
    mode_host: 'Alojar en línea',
    mode_join: 'Unirse',
    btn_host_game: 'Alojar partida',
    btn_new_game: 'Nueva partida',
    btn_start_game: 'Empezar partida',
    howto_label: 'Cómo se juega',

    pts_value: '{n} pts',
    pts_label: 'pts',
    deck_american_label: 'Baraja americana',
    deck_spanish_label: 'Baraja española',
    btn_back: 'Atrás',
    lbl_room_code: 'Código de sala',
    lbl_opponent: 'Rival',
    mp_creating_room: 'Creando sala…',
    btn_start: 'Empezar',
    lbl_host: 'Anfitrión',
    mp_waiting_host: 'Esperando al anfitrión',

    avatar_title: 'Elige tu avatar',
    btn_close: 'Cerrar',
    aria_avatar: 'Avatar {av}',

    howto_title: 'Cómo se juega a la Escoba',
    btn_done: 'Hecho',
    howto_goal: 'Captura cartas que sumen 15.',
    howto_caption: 'En tu turno juega una carta; si suma 15 con cartas de la mesa, las capturas. Una escoba despeja toda la mesa.',
    score_escobas: 'Escobas: 1 punto cada una',
    score_cards: 'Más cartas: 1 punto (+2 si el rival tiene menos de 10, 2 jugadores)',
    score_coins: 'Más oros: 1 punto (+2 por los 10 oros)',
    score_sevens: 'Sietes: 1 punto por más sietes, 3 por los cuatro (o 1 por la guindis sola)',
    howto_figures_note: 'La Sota, el Caballo y el Rey valen 8, 9 y 10, no el número impreso.',

    announce_last_cards: 'Últimas cartas',
    banner_takes_opening: '{name} se lleva la mesa inicial',
    banner_clears_table: '{name} despeja la mesa',
    announce_takes_leftover: '{name} se lleva las cartas restantes',
    announce_plays_captures: '{name} juega {card} · captura {n}',
    announce_plays: '{name} juega {card}',
    round_n: 'Ronda {n}',
    first_to_n: 'Primero a {n}',
    title_captured: 'Cartas capturadas',
    title_coins: 'Oros capturados',
    title_escobas_round: 'Escobas en esta ronda',
    title_hand_count: 'Cartas en la mano',
    dealer_letter: 'D',
    dealer_title: 'Repartidor',

    btn_results: 'Resultados',
    btn_place: 'Colocar {card}',
    btn_capture: 'Capturar',

    row_escobas: 'Escobas',
    row_cards: 'Cartas',
    row_coincards: 'Cartas de Oros',
    row_sevens: 'Sietes',
    round_points: 'Puntos de la ronda {n}',
    row_total_scores: 'Puntuaciones totales',
    btn_table: 'Tabla',
    btn_scoreboard: '📈 Marcador',
    btn_standings: 'Clasificación',
    btn_next_round: 'Siguiente ronda',
    aria_close: 'Cerrar',
    reason_whitewash: 'El rival no capturó ninguna carta: victoria instantánea',
    wins_headline: '¡{name} gana!',
    aria_chart: 'Puntuación acumulada por ronda',
    chart_target: 'objetivo {n}',

    menu_title: 'Menú',
    menu_leave_match: 'Abandonar partida',
    menu_newgame_samesettings: 'Nueva partida (mismos ajustes)',
    menu_quit_setup: 'Salir a los ajustes',
    menu_confirm_lost: 'Toca otra vez: esta partida se perderá',

    mp_conn_error_title: 'Error de conexión',
    mp_conn_error_sub: 'La partida no pudo mantenerse sincronizada',
    btn_back_to_setup: 'Volver a los ajustes',
    mp_opponent_left_title: 'El rival se fue',
    mp_final_standings: 'Clasificación final',
    mp_status_resyncing: 'Resincronizando',
    mp_status_opp_disconnected: 'Rival desconectado',
    mp_status_opp_left: 'El rival se fue',
    mp_could_not_create_room: 'No se pudo crear la sala',
    mp_offline: 'Sin conexión',
    mp_room_not_found: 'Sala no encontrada',
    mp_room_ended: 'La sala terminó',
    mp_room_full: 'Sala llena',
  },
};

export default STRINGS;
