// baseball/js/strings.js - phase 3 (BB-3): the real play screen's dictionary. Root CLAUDE.md,
// "Before you build: USE WHAT EXISTS" - every visible string goes through t() at render time.

export const STRINGS = {
  en: {
    title: 'Baseball',
    setup_league: 'League',
    setup_play: 'Play',
    tune_open: 'Tune',
    league_little: 'Little League',
    league_highschool: 'High School',
    league_college: 'College',
    league_minors: 'Minors',
    league_majors: 'Majors',
    you: 'You',
    cpu: 'CPU',
    back: 'Back',
    close: 'Close',
    locked: 'Not yet',
    act_steal: 'Steal',
    act_bunt: 'Bunt',
    act_pickoff: 'Pickoff',
    act_pitch: 'Pitch',
    act_swing: 'Swing',
    pitch_fastball: 'FB',
    pitch_changeup: 'CH',
    pitch_curveball: 'CB',
    pitch_slider: 'SL',
    pitch_knuckleball: 'KN',
    pitch_screwball: 'SC',
    pitch_eephus: 'EP',
    pitch_cutter: 'CT',
    // SPEC.md section 5: Line 2 is "pitch name and mph" - the strip's own pitch_* codes above are
    // two-letter tile abbreviations, too short for a readout line.
    pitchname_fastball: 'Fastball',
    pitchname_changeup: 'Changeup',
    pitchname_curveball: 'Curveball',
    pitchname_slider: 'Slider',
    pitchname_knuckleball: 'Knuckleball',
    pitchname_screwball: 'Screwball',
    pitchname_eephus: 'Eephus',
    pitchname_cutter: 'Cutter',
    res_out: 'Out',
    res_single: 'Single',
    res_double: 'Double',
    res_triple: 'Triple',
    res_homer: 'Home run',
    res_walk: 'Walk',
    res_strikeout: 'Strikeout',
    // SPEC.md section 3/13: Line 1's verdict vocabulary, one word per pitch before the outcome
    // is known (`js/ui.js`'s `verdictWord`/`timingWord` glue, BB-3b commit 6).
    v_ball: 'Ball',
    v_strike: 'Strike',
    v_foul: 'Foul',
    v_early: 'Early',
    v_late: 'Late',
    v_perfect: 'Perfect',
    v_nice: 'Nice',
    v_hung: 'Hung',
    cancel: 'Cancel',
    leave: 'Leave',
    half_end: 'Side retired',
    confirm_forfeit: 'Leave this game? It counts as a forfeit.',
    end_win: 'You win!',
    end_loss: 'You lose',
    end_tie: 'Tie game',
    play_again: 'Play again',
    done: 'Done',
  },
  es: {
    title: 'Béisbol',
    setup_league: 'Liga',
    setup_play: 'Jugar',
    tune_open: 'Ajustes',
    league_little: 'Infantil',
    league_highschool: 'Preparatoria',
    league_college: 'Universidad',
    league_minors: 'Ligas Menores',
    league_majors: 'Grandes Ligas',
    you: 'Tú',
    cpu: 'CPU',
    back: 'Atrás',
    close: 'Cerrar',
    locked: 'Aún no',
    act_steal: 'Robar',
    act_bunt: 'Toque',
    act_pickoff: 'Sorpresa',
    act_pitch: 'Lanzar',
    act_swing: 'Batear',
    pitch_fastball: 'RE',
    pitch_changeup: 'CA',
    pitch_curveball: 'CU',
    pitch_slider: 'SL',
    pitch_knuckleball: 'NU',
    pitch_screwball: 'TB',
    pitch_eephus: 'EP',
    pitch_cutter: 'CT',
    pitchname_fastball: 'Recta',
    pitchname_changeup: 'Cambio',
    pitchname_curveball: 'Curva',
    pitchname_slider: 'Slider',
    pitchname_knuckleball: 'Nudillos',
    pitchname_screwball: 'Tornillo',
    pitchname_eephus: 'Eephus',
    pitchname_cutter: 'Cutter',
    res_out: 'Out',
    res_single: 'Sencillo',
    res_double: 'Doble',
    res_triple: 'Triple',
    res_homer: 'Jonrón',
    res_walk: 'Base por bolas',
    res_strikeout: 'Ponche',
    v_ball: 'Bola',
    v_strike: 'Strike',
    v_foul: 'Foul',
    v_early: 'Antes',
    v_late: 'Tarde',
    v_perfect: 'Perfecto',
    v_nice: 'Genial',
    v_hung: 'Colgado',
    cancel: 'Cancelar',
    leave: 'Salir',
    half_end: 'Fin de la entrada',
    confirm_forfeit: '¿Salir de este juego? Cuenta como derrota.',
    end_win: '¡Ganaste!',
    end_loss: 'Perdiste',
    end_tie: 'Empate',
    play_again: 'Jugar de nuevo',
    done: 'Listo',
  },
};

export default STRINGS;
