// boggle/js/strings.js — every user-visible string in Boggle, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows
// English for anything missing). Difficulty ids (beginner/intermediate/pro) are storage
// vocabulary and stay canonical — only display labels translate.
//
// UI chrome translates; gameplay (ENABLE word list, classic English dice) stays English on
// purpose — see boggle/CLAUDE.md and js/CLAUDE.md "Language support". The es invalid-word
// feedback and the help sheet both say so explicitly, since that is the fix for Ana's
// 2026-07-23 report of "words" showing up that the dictionary rejected.

export const STRINGS = {
  en: {
    title: 'Boggle',
    tagline: 'Shake the grid, race the clock, link touching letters into words.',
    stats_line: '{played} played · {w}-{l}-{t} · best score {score}',
    vs: 'vs',
    you: 'You',
    computer: 'Computer',
    row_timer: 'Timer',
    row_difficulty: 'Difficulty',
    timer_1: '1 min',
    timer_1_5: '1 min 30 s',
    timer_2: '2 min',
    diff_beginner: 'Easy',
    diff_intermediate: 'Medium',
    diff_pro: 'Hard',
    start: 'Start game',
    howto: 'How to play',
    loading: 'Loading the dictionary…',
    load_error: 'Could not load the dictionary. Check your connection and try again.',
    try_again: 'Try again',
    back_to_setup: 'Back to setup',
    points: 'points',
    words: 'words',
    wordbar_hint: 'Swipe through the letters',
    clear: 'Clear',
    enter: 'Enter',
    words_found: 'Words found',
    none_yet: 'None yet',
    give_up: 'Give up',
    feedback_valid: (p) => `${p.word}: ${p.n} point${p.n === 1 ? '' : 's'}`,
    feedback_duplicate: 'Already found {word}',
    feedback_invalid: '"{word}" is not in the dictionary',
    tie_game: 'Tie game!',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    end_sub: '{score1}-{score2} · {timer} · {diff}',
    your_words: "{name}'s words",
    possible_on_board: 'Possible on this board',
    browse_words: 'Browse every word on the board ›',
    hide_words: 'Hide every word on the board ›',
    play_again: 'Play again',
    change_settings: 'Change settings',
    aria_round_over: 'Round over',
    aria_close: 'Close',
    help_lead: 'Find as many words as you can before time runs out.',
    help_caption: 'Letters must touch, corners count. No tile twice in one word.',
    help_1: 'Swipe through the letters and let go to submit; slide back to undo.',
    help_2: 'Qu is one tile that counts as two letters.',
    aria_diagram: 'A word traced through three touching tiles including one diagonal step; the first tile, already used, is crossed out and cannot be tapped again',
    aria_board: 'Boggle board',
    tile_used: 'Letter {face}, already used in this word',
    tile_last: 'Letter {face}, end of the word, tap to remove it',
    tile_dead: 'Letter {face}, not touching the current letter',
    tile_live: 'Letter {face}, row {row} column {col}',
    // --- multiplayer (2026-07-28) ---
    mode_solo: 'Solo',
    mode_host: 'Host',
    mode_join: 'Join',
    mp_host_hint: "Create a room, share the code, both play the same board at once.",
    mp_host_btn: 'Create room',
    mp_creating_room: 'Creating room…',
    mp_share_code: 'Share this code with your opponent',
    mp_waiting_opponent: 'Waiting for opponent…',
    mp_opponent_label: 'Opponent',
    mp_start_btn: 'Start round',
    mp_back_btn: 'Back',
    mp_enter_code: 'Enter room code',
    mp_join_hint: 'Ask your opponent for their room code.',
    mp_join_btn: 'Join',
    mp_joining: 'Joining…',
    mp_code_aria: 'Room code',
    mp_host_label: 'Host',
    mp_waiting_host: 'Waiting for the host to start…',
    mp_err_could_not_create_room: 'Could not create a room. Try again.',
    mp_err_offline: 'Offline, or the server could not be reached.',
    mp_err_room_not_found: 'Room not found.',
    mp_err_room_full: 'That room is full.',
    mp_err_wrong_game: 'That code is for a different game.',
    mp_update_required: 'Update required to join this room. Reload the app.',
    mp_waiting_round: 'Waiting for the round to start…',
    mp_waiting_result: 'Time! Waiting for {opp}…',
    mp_status_opponent_disconnected: '{opp} seems to have disconnected…',
    mp_opponent_left_title: 'Opponent left',
    mp_opponent_left_sub: '{opp} left the room.',
    mp_error_title: 'Connection lost',
    mp_error_sub: 'Could not stay in sync with the room.',
    mp_leave_confirm: 'Leave this match? Your opponent will be left alone.',
    mp_leave_btn: 'Leave match',
    mp_rematch_wait: 'Waiting for the host to start the next round…',
    mp_end_sub: '{score1}-{score2} · {timer}',
    aria_close_mp: 'Close and leave the match',
  },
  es: {
    title: 'Boggle',
    tagline: 'Agita la cuadrícula, corre contra el reloj, une letras contiguas en palabras.',
    stats_line: '{played} jugadas · {w}-{l}-{t} · mejor puntuación {score}',
    vs: 'vs',
    you: 'Tú',
    computer: 'Ordenador',
    row_timer: 'Tiempo',
    row_difficulty: 'Dificultad',
    timer_1: '1 min',
    timer_1_5: '1 min 30 s',
    timer_2: '2 min',
    diff_beginner: 'Fácil',
    diff_intermediate: 'Normal',
    diff_pro: 'Difícil',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    loading: 'Cargando el diccionario…',
    load_error: 'No se pudo cargar el diccionario. Revisa tu conexión e inténtalo otra vez.',
    try_again: 'Intentar otra vez',
    back_to_setup: 'Volver a los ajustes',
    points: 'puntos',
    words: 'palabras',
    wordbar_hint: 'Desliza por las letras',
    clear: 'Borrar',
    enter: 'Enviar',
    words_found: 'Palabras encontradas',
    none_yet: 'Ninguna todavía',
    give_up: 'Rendirse',
    feedback_valid: (p) => `${p.word}: ${p.n} punto${p.n === 1 ? '' : 's'}`,
    feedback_duplicate: 'Ya encontraste {word}',
    feedback_invalid: '"{word}" no está en el diccionario (las palabras válidas son en inglés)',
    tie_game: '¡Empate!',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    end_sub: '{score1}-{score2} · {timer} · {diff}',
    your_words: 'Palabras de {name}',
    possible_on_board: 'Posibles en este tablero',
    browse_words: 'Ver todas las palabras del tablero ›',
    hide_words: 'Ocultar todas las palabras del tablero ›',
    play_again: 'Jugar otra vez',
    change_settings: 'Cambiar ajustes',
    aria_round_over: 'Fin de la ronda',
    aria_close: 'Cerrar',
    help_lead: 'Encuentra tantas palabras como puedas antes de que acabe el tiempo.',
    help_caption: 'Las letras deben tocarse, incluso en diagonal. No puedes usar la misma ficha dos veces.',
    help_1: 'Desliza por las letras y suelta para enviar la palabra; desliza hacia atrás para deshacer.',
    help_2: 'Qu es una sola ficha que cuenta como dos letras.',
    aria_diagram: 'Una palabra trazada por tres fichas contiguas, incluido un paso en diagonal; la primera ficha, ya usada, aparece tachada y no se puede volver a tocar',
    aria_board: 'Tablero de Boggle',
    tile_used: 'Letra {face}, ya usada en esta palabra',
    tile_last: 'Letra {face}, fin de la palabra, toca para quitarla',
    tile_dead: 'Letra {face}, no toca la letra actual',
    tile_live: 'Letra {face}, fila {row} columna {col}',
    // --- multiplayer (2026-07-28) ---
    mode_solo: 'Solo',
    mode_host: 'Anfitrión',
    mode_join: 'Unirse',
    mp_host_hint: 'Crea una sala, comparte el código, ambos juegan el mismo tablero a la vez.',
    mp_host_btn: 'Crear sala',
    mp_creating_room: 'Creando sala…',
    mp_share_code: 'Comparte este código con tu rival',
    mp_waiting_opponent: 'Esperando al rival…',
    mp_opponent_label: 'Rival',
    mp_start_btn: 'Empezar ronda',
    mp_back_btn: 'Volver',
    mp_enter_code: 'Introduce el código de sala',
    mp_join_hint: 'Pide a tu rival el código de su sala.',
    mp_join_btn: 'Unirse',
    mp_joining: 'Uniéndose…',
    mp_code_aria: 'Código de sala',
    mp_host_label: 'Anfitrión',
    mp_waiting_host: 'Esperando a que el anfitrión empiece…',
    mp_err_could_not_create_room: 'No se pudo crear la sala. Inténtalo de nuevo.',
    mp_err_offline: 'Sin conexión, o no se pudo contactar con el servidor.',
    mp_err_room_not_found: 'Sala no encontrada.',
    mp_err_room_full: 'Esa sala está llena.',
    mp_err_wrong_game: 'Ese código es de otro juego.',
    mp_update_required: 'Necesitas actualizar para unirte a esta sala. Recarga la app.',
    mp_waiting_round: 'Esperando a que empiece la ronda…',
    mp_waiting_result: '¡Tiempo! Esperando a {opp}…',
    mp_status_opponent_disconnected: '{opp} parece haberse desconectado…',
    mp_opponent_left_title: 'El rival se fue',
    mp_opponent_left_sub: '{opp} salió de la sala.',
    mp_error_title: 'Conexión perdida',
    mp_error_sub: 'No se pudo mantener la sincronía con la sala.',
    mp_leave_confirm: '¿Salir de esta partida? Tu rival se quedará solo.',
    mp_leave_btn: 'Salir de la partida',
    mp_rematch_wait: 'Esperando a que el anfitrión empiece la siguiente ronda…',
    mp_end_sub: '{score1}-{score2} · {timer}',
    aria_close_mp: 'Cerrar y salir de la partida',
  },
};

export default STRINGS;
