// boggle/js/strings.js — every user-visible string in Boggle, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows
// English for anything missing). Difficulty ids (beginner/intermediate/pro) are storage
// vocabulary and stay canonical — only display labels translate.
//
// UI chrome translates; gameplay (ENABLE word list, classic English dice) stays English on
// purpose — see boggle/CLAUDE.md and js/CLAUDE.md "Language support". The es invalid-word
// feedback and the help sheet both say so explicitly, since that is the fix for Ana's
// 2026-07-23 report of "words" showing up that the dictionary rejected.

export const STRINGS = {
  en: {
    title: 'Boggle',
    tagline: 'Shake the grid, race the clock, link touching letters into words.',
    stats_line: '{played} played · {w}-{l}-{t} · best score {score}',
    vs: 'vs',
    row_timer: 'Timer',
    row_difficulty: 'Difficulty',
    timer_2: '2 min',
    timer_3: '3 min',
    timer_5: '5 min',
    diff_beginner: 'Beginner',
    diff_intermediate: 'Intermediate',
    diff_pro: 'Pro',
    hint_diff_pro: 'Finds most of the words on the board, especially the long, high-value ones. Tough to beat.',
    hint_diff_intermediate: 'Finds close to half the words on the board, an even mix of lengths.',
    hint_diff_beginner: 'Finds about a fifth of the words on the board, mostly short ones.',
    start: 'Start game',
    howto: 'How to play',
    loading: 'Loading the dictionary…',
    load_error: 'Could not load the dictionary. Check your connection and try again.',
    try_again: 'Try again',
    back_to_setup: 'Back to setup',
    points: 'points',
    words: 'words',
    wordbar_hint: 'Swipe through the letters',
    clear: 'Clear',
    enter: 'Enter',
    words_found: 'Words found',
    none_yet: 'None yet',
    give_up: 'Give up',
    feedback_valid: (p) => `${p.word}: ${p.n} point${p.n === 1 ? '' : 's'}`,
    feedback_duplicate: 'Already found {word}',
    feedback_invalid: '"{word}" is not in the dictionary',
    tie_game: 'Tie game!',
    you_win: 'You win!',
    opp_wins: '{opp} wins',
    end_sub: '{score1}-{score2} · {timer} · {diff}',
    your_words: "{name}'s words",
    possible_on_board: 'Possible on this board',
    browse_words: 'Browse every word on the board ›',
    hide_words: 'Hide every word on the board ›',
    play_again: 'Play again',
    change_settings: 'Change settings',
    aria_round_over: 'Round over',
    aria_close: 'Close',
    help_lead: 'Find as many words as you can before time runs out.',
    help_caption: 'Letters must touch, including corners. You cannot use the same tile twice in one word.',
    help_example: 'Tiles touching corner to corner = still connected',
    help_1: 'Swipe through the letters without lifting your finger, then let go to submit.',
    help_2: 'Slide back a letter to undo it, still without lifting.',
    help_3: 'Qu is one tile that counts as two letters.',
    help_4: 'Longer words score much more: three letters is 1 point, eight letters is 11.',
    help_5: 'Words you both find still count for both of you.',
    help_6: 'Words are checked against an English dictionary.',
    aria_diagram: 'A word traced through three touching tiles including one diagonal step; the first tile, already used, is crossed out and cannot be tapped again',
    aria_board: 'Boggle board',
    tile_used: 'Letter {face}, already used in this word',
    tile_last: 'Letter {face}, end of the word, tap to remove it',
    tile_dead: 'Letter {face}, not touching the current letter',
    tile_live: 'Letter {face}, row {row} column {col}',
  },
  es: {
    title: 'Boggle',
    tagline: 'Agita la cuadrícula, corre contra el reloj, une letras contiguas en palabras.',
    stats_line: '{played} jugadas · {w}-{l}-{t} · mejor puntuación {score}',
    vs: 'vs',
    row_timer: 'Tiempo',
    row_difficulty: 'Dificultad',
    timer_2: '2 min',
    timer_3: '3 min',
    timer_5: '5 min',
    diff_beginner: 'Principiante',
    diff_intermediate: 'Intermedio',
    diff_pro: 'Pro',
    hint_diff_pro: 'Encuentra la mayoría de las palabras del tablero, sobre todo las largas y de más valor. Muy difícil de vencer.',
    hint_diff_intermediate: 'Encuentra casi la mitad de las palabras del tablero, una mezcla pareja de longitudes.',
    hint_diff_beginner: 'Encuentra como una quinta parte de las palabras del tablero, casi todas cortas.',
    start: 'Empezar partida',
    howto: 'Cómo se juega',
    loading: 'Cargando el diccionario…',
    load_error: 'No se pudo cargar el diccionario. Revisa tu conexión e inténtalo otra vez.',
    try_again: 'Intentar otra vez',
    back_to_setup: 'Volver a los ajustes',
    points: 'puntos',
    words: 'palabras',
    wordbar_hint: 'Desliza por las letras',
    clear: 'Borrar',
    enter: 'Enviar',
    words_found: 'Palabras encontradas',
    none_yet: 'Ninguna todavía',
    give_up: 'Rendirse',
    feedback_valid: (p) => `${p.word}: ${p.n} punto${p.n === 1 ? '' : 's'}`,
    feedback_duplicate: 'Ya encontraste {word}',
    feedback_invalid: '"{word}" no está en el diccionario (las palabras válidas son en inglés)',
    tie_game: '¡Empate!',
    you_win: '¡Ganaste!',
    opp_wins: '{opp} gana',
    end_sub: '{score1}-{score2} · {timer} · {diff}',
    your_words: 'Palabras de {name}',
    possible_on_board: 'Posibles en este tablero',
    browse_words: 'Ver todas las palabras del tablero ›',
    hide_words: 'Ocultar todas las palabras del tablero ›',
    play_again: 'Jugar otra vez',
    change_settings: 'Cambiar ajustes',
    aria_round_over: 'Fin de la ronda',
    aria_close: 'Cerrar',
    help_lead: 'Encuentra todas las palabras que puedas antes de que se acabe el tiempo.',
    help_caption: 'Las letras deben tocarse, incluso en diagonal. No puedes usar la misma ficha dos veces en una palabra.',
    help_example: 'Fichas que se tocan en diagonal = siguen conectadas',
    help_1: 'Desliza por las letras sin levantar el dedo y suelta para enviar la palabra.',
    help_2: 'Desliza hacia atrás sobre una letra para deshacerla, siempre sin levantar el dedo.',
    help_3: 'Qu es una sola ficha que cuenta como dos letras.',
    help_4: 'Las palabras más largas valen mucho más: tres letras es 1 punto, ocho letras es 11.',
    help_5: 'Las palabras que encuentren los dos igual cuentan para ambos.',
    help_6: 'Las palabras se comprueban con un diccionario en inglés.',
    aria_diagram: 'Una palabra trazada por tres fichas contiguas, incluido un paso en diagonal; la primera ficha, ya usada, aparece tachada y no se puede volver a tocar',
    aria_board: 'Tablero de Boggle',
    tile_used: 'Letra {face}, ya usada en esta palabra',
    tile_last: 'Letra {face}, fin de la palabra, toca para quitarla',
    tile_dead: 'Letra {face}, no toca la letra actual',
    tile_live: 'Letra {face}, fila {row} columna {col}',
  },
};

export default STRINGS;
