// nuts-bolts/js/strings.js — every user-visible string in Nuts & Bolts, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9;
// reference: snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows
// English for anything missing). Values (tier keys easy/medium/hard/extraHard, color keys,
// game.js's move-reason codes empty/locked/full/color-mismatch) are storage/engine vocabulary
// and stay canonical — only their display labels/text translate. generator.js's own
// TIER_LABELS/TIER_DESCRIPTIONS/PALETTE names stay English (that file is a pure, DOM-free engine
// module, same as game.js/ai.js elsewhere in the repo); ui.js maps the same keys onto t() here
// instead of importing them for display.

export const STRINGS = {
  en: {
    title: 'Nuts & Bolts',
    tagline: 'Choose a difficulty',
    start: 'Start',
    level_n: 'Level {n}',
    tier_easy: 'Easy',
    tier_medium: 'Medium',
    tier_hard: 'Hard',
    tier_extra_hard: 'Expert',
    color_yellow: 'Yellow',
    color_blue: 'Blue',
    color_orange: 'Orange',
    color_teal: 'Teal',
    color_purple: 'Purple',
    color_pink: 'Pink',
    color_slate: 'Slate',
    color_sky: 'Sky',
    color_red: 'Red',
    color_green: 'Green',
    color_lime: 'Lime',
    color_brown: 'Brown',
    back_to_menu_aria: 'Back to difficulty menu',
    restart_aria: 'Restart',
    undo_aria: 'Undo',
    undo_label: 'Undo',
    help_aria: 'Help',
    help_label: 'Help',
    close_aria: 'Close',
    bolt_aria: 'Bolt {n}',
    move_one: '{n} move',
    move_other: '{n} moves',
    restart_confirm_msg: 'Restart this level? Your moves will be lost.',
    cancel: 'Cancel',
    restart: 'Restart',
    howto: 'How to play',
    help_diagram_aria: 'A bolt’s top color moving onto a matching color on another bolt, and a third bolt shown complete and locked',
    help_li_1: "Tap a bolt to pick up its top color, tap another to drop it: onto a matching color or an empty bolt, if there's room.",
    help_li_2: 'Fill each bolt with a single color to complete it. A completed bolt locks.',
    help_li_3: 'Some levels have hidden nuts (shown with a "?"). Their color is revealed once they reach the top.',
    help_li_4: 'Press and hold a bolt to hear its colors by name.',
    ok: 'OK',
    next_level: 'Next level',
    win_title: 'Level {n} complete',
    win_detail_named: 'Nice one, {name}! {moves}.',
    win_detail: '{moves}.',
    reason_empty: 'That bolt is empty',
    reason_locked: 'That bolt is locked',
    reason_full: 'That bolt is full',
    reason_color_mismatch: "Colors don't match",
    empty_bolt: 'Empty bolt',
    assist_top: 'Top:',
    assist_base: 'Base:',
    assist_hidden: 'Hidden',
    assist_count: '{label} x{count}',
  },
  es: {
    title: 'Tuercas y Tornillos',
    tagline: 'Elige una dificultad',
    start: 'Empezar',
    level_n: 'Nivel {n}',
    tier_easy: 'Fácil',
    tier_medium: 'Normal',
    tier_hard: 'Difícil',
    tier_extra_hard: 'Experto',
    color_yellow: 'Amarillo',
    color_blue: 'Azul',
    color_orange: 'Naranja',
    color_teal: 'Verde azulado',
    color_purple: 'Morado',
    color_pink: 'Rosa',
    color_slate: 'Pizarra',
    color_sky: 'Celeste',
    color_red: 'Rojo',
    color_green: 'Verde',
    color_lime: 'Lima',
    color_brown: 'Marrón',
    back_to_menu_aria: 'Volver al menú de dificultad',
    restart_aria: 'Reiniciar',
    undo_aria: 'Deshacer',
    undo_label: 'Deshacer',
    help_aria: 'Ayuda',
    help_label: 'Ayuda',
    close_aria: 'Cerrar',
    bolt_aria: 'Tornillo {n}',
    move_one: '{n} movimiento',
    move_other: '{n} movimientos',
    restart_confirm_msg: '¿Reiniciar este nivel? Se perderán tus movimientos.',
    cancel: 'Cancelar',
    restart: 'Reiniciar',
    howto: 'Cómo se juega',
    help_diagram_aria: 'El color superior de un tornillo pasando a un color igual en otro tornillo, y un tercer tornillo completo y bloqueado',
    help_li_1: 'Toca un tornillo para recoger su color superior, toca otro para soltarlo: sobre un color igual o un tornillo vacío, y solo si hay espacio.',
    help_li_2: 'Llena cada tornillo con un solo color para completarlo. Un tornillo completado se bloquea.',
    help_li_3: 'Algunos niveles tienen tuercas ocultas (mostradas con un "?"). Su color se revela al llegar arriba.',
    help_li_4: 'Mantén pulsado un tornillo para escuchar sus colores por nombre.',
    ok: 'Aceptar',
    next_level: 'Siguiente nivel',
    win_title: 'Nivel {n} completado',
    win_detail_named: '¡Bien hecho, {name}! {moves}.',
    win_detail: '{moves}.',
    reason_empty: 'Ese tornillo está vacío',
    reason_locked: 'Ese tornillo está bloqueado',
    reason_full: 'Ese tornillo está lleno',
    reason_color_mismatch: 'Los colores no coinciden',
    empty_bolt: 'Tornillo vacío',
    assist_top: 'Arriba:',
    assist_base: 'Base:',
    assist_hidden: 'Oculto',
    assist_count: '{label} x{count}',
  },
};

export default STRINGS;
