// uno/js/strings.js — every user-visible string in Uno, both languages. English is the
// source of truth (every key exists in `en`); `es` may lag and js/i18n.js's fallback shows
// English for anything missing, so a partial translation can never break a screen.

export const STRINGS = {
  en: {
    title: 'Uno',
    tagline: 'Match color or number. Empty your hand first.',
    players: 'Players',
    difficulty: 'Difficulty',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    start: 'Start',
    howto: 'How to play',
    vs: 'vs',
    row_players: 'Players',
    row_difficulty: 'Difficulty',
    n_players: '{n} players',
    // in-game
    your_turn: 'Your turn',
    opp_turn: "{name}'s turn",
    opp_thinking: '{name} is thinking...',
    draw_pile: 'Draw',
    discard_pile: 'Discard',
    cards_suffix: 'cards',
    card_suffix: 'card',
    uno_banner: 'UNO!',
    pending_draw: 'Draw {n}',
    choose_color: 'Choose a color',
    color_red: 'Red',
    color_yellow: 'Yellow',
    color_green: 'Green',
    color_blue: 'Blue',
    aria_wild: 'Wild',
    aria_wild4: 'Wild Draw Four',
    aria_card: '{color} {value}',
    aria_draw_pile: 'Draw pile, {n} cards left',
    aria_discard_pile: 'Discard pile, top card {card}',
    restart_game: 'Restart',
    new_game: 'New game',
    tap_again_confirm: 'Tap again to confirm',
    // end of game
    game_over: 'Game over',
    you_win: 'You win!',
    opp_wins: '{name} wins',
    play_again: 'Play again',
    change_settings: 'Setup',
    close: 'Close',
    // how to play
    help_lead: 'Get rid of all your cards first.',
    help_caption: 'Play a card matching the color or the number of the top card, or play a wild.',
    help_example: 'Red 7 on the pile = play any red card, or any other 7.',
    help_bullet1: "No legal card? You draw until you get one, then you must play it.",
    help_bullet2: '+2 cards stack: answer with another +2 or draw the whole pile and lose your turn.',
    help_bullet3: 'Wild cards let you choose the next color.',
    aria_close: 'Close',
    aria_help: 'How to play',
  },
  es: {
    title: 'Uno',
    tagline: 'Combina color o número. Sé el primero en quedarte sin cartas.',
    players: 'Jugadores',
    difficulty: 'Dificultad',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    start: 'Empezar',
    howto: 'Cómo se juega',
    vs: 'vs',
    row_players: 'Jugadores',
    row_difficulty: 'Dificultad',
    n_players: '{n} jugadores',
    your_turn: 'Tu turno',
    opp_turn: 'Turno de {name}',
    opp_thinking: '{name} está pensando...',
    draw_pile: 'Robar',
    discard_pile: 'Descarte',
    cards_suffix: 'cartas',
    card_suffix: 'carta',
    uno_banner: '¡UNO!',
    pending_draw: 'Roba {n}',
    choose_color: 'Elige un color',
    color_red: 'Rojo',
    color_yellow: 'Amarillo',
    color_green: 'Verde',
    color_blue: 'Azul',
    aria_wild: 'Comodín',
    aria_wild4: 'Comodín +4',
    aria_card: '{color} {value}',
    aria_draw_pile: 'Mazo de robo, {n} cartas restantes',
    aria_discard_pile: 'Pila de descarte, carta superior {card}',
    restart_game: 'Reiniciar',
    new_game: 'Nueva partida',
    tap_again_confirm: 'Toca otra vez para confirmar',
    game_over: 'Fin de la partida',
    you_win: '¡Ganaste!',
    opp_wins: '{name} gana',
    play_again: 'Jugar otra vez',
    change_settings: 'Ajustes',
    close: 'Cerrar',
    help_lead: 'Sé el primero en quedarte sin cartas.',
    help_caption: 'Juega una carta que combine el color o el número de la carta superior, o juega un comodín.',
    help_example: 'Rojo 7 en la pila = juega cualquier carta roja, o cualquier otro 7.',
    help_bullet1: '¿Sin carta legal? Roba hasta conseguir una, y luego debes jugarla.',
    help_bullet2: 'Las cartas +2 se acumulan: responde con otra +2 o roba toda la pila y pierdes el turno.',
    help_bullet3: 'Los comodines te dejan elegir el siguiente color.',
    aria_close: 'Cerrar',
    aria_help: 'Cómo se juega',
  },
};

export default STRINGS;
