// brick-blitz/js/strings.js — every user-visible string, { en, es } (js/i18n.js). English is the
// source of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).
export const STRINGS = {
  en: {
    title: 'Brick Blitz',
    tagline: 'Neon breakout. Smash every brick.',
    difficulty: 'Difficulty',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    mode: 'Mode',
    mode_arcade: 'Arcade',
    mode_arcade_sub: '5 stages',
    mode_endless: 'Endless',
    mode_endless_sub: 'Waves forever',
    play: 'Play',
    howto: 'How to play',
    best: 'Best ({diff}): {n}',
    hud_score: 'Score',
    hud_stage: 'Stage',
    hud_wave: 'Wave',
    hud_lives: 'Lives',
    hud_best: 'Best',
    pause: 'Pause',
    sound: 'Sound',
    muted: 'Muted',
    aria_mute: 'Mute sound',
    aria_unmute: 'Unmute sound',
    aria_close: 'Close',
    aria_canvas: 'Playfield: neon bricks, a glowing paddle and ball',
    paused: 'Paused',
    resume: 'Resume',
    quit: 'Quit',
    over_kick: 'Signal lost',
    over_title: 'Game over',
    victory_kick: 'All five stages cleared',
    victory_title: 'Circuit complete',
    victory_note: 'Keep your score and lives and carry on into Endless?',
    go_endless: 'Go endless',
    new_best: 'New best!',
    over_note: 'Best combo x{n}. {b} bricks smashed.',
    play_again: 'Play again',
    menu: 'Menu',
    combo: 'Combo',
    banner_stage: 'Stage {n}',
    banner_wave: 'Endless · wave {n}',
    launch_touch: 'TAP TO LAUNCH',
    launch_mouse: 'CLICK OR SPACE TO LAUNCH',
    pop_clear: 'STAGE CLEAR +{n}',
    pw_M: 'Multi-ball',
    pw_W: 'Wide',
    pw_L: 'Laser',
    pw_S: 'Slow-mo',
    lvl_love: 'Love circuit',
    lvl_invader: 'Invader',
    lvl_spiral: 'Spiral',
    lvl_palm: 'Palm drive',
    lvl_sun: 'Hyper sun',
    help_goal: 'Keep the ball up and break every brick.',
    help_armor: 'Bricks with an inner outline take two hits.',
    help_caps: 'Catch falling capsules with the paddle:',
    help_M: 'M = three balls at once',
    help_W: 'W = a wider paddle',
    help_L: 'L = twin lasers fire up',
    help_S: 'S = everything slows down',
    help_combo: 'Bricks in a row without the paddle = combo, up to x12.',
    help_controls: 'Drag to steer. Tap to launch.',
    help_close: 'Got it',
    say_stage: 'Stage {n}: {name}.',
    say_wave: 'Wave {n}.',
    say_life: 'Ball lost. {n} left.',
    say_over: 'Game over. Score {n}.',
    say_clear: 'Stage clear! Bonus {n}.',
  },
  es: {
    title: 'Brick Blitz',
    tagline: 'Rompeladrillos de neón. Rómpelos todos.',
    difficulty: 'Dificultad',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    mode: 'Modo',
    mode_arcade: 'Arcade',
    mode_arcade_sub: '5 fases',
    mode_endless: 'Infinito',
    mode_endless_sub: 'Oleadas sin fin',
    play: 'Jugar',
    howto: 'Cómo se juega',
    best: 'Récord ({diff}): {n}',
    hud_score: 'Puntos',
    hud_stage: 'Fase',
    hud_wave: 'Oleada',
    hud_lives: 'Vidas',
    hud_best: 'Récord',
    pause: 'Pausa',
    sound: 'Sonido',
    muted: 'Silencio',
    aria_mute: 'Silenciar',
    aria_unmute: 'Activar sonido',
    aria_close: 'Cerrar',
    aria_canvas: 'Campo de juego: ladrillos de neón, una pala y una bola',
    paused: 'En pausa',
    resume: 'Seguir',
    quit: 'Salir',
    over_kick: 'Señal perdida',
    over_title: 'Fin',
    victory_kick: 'Las cinco fases superadas',
    victory_title: 'Circuito completo',
    victory_note: '¿Sigues en modo Infinito con tus puntos y vidas?',
    go_endless: 'Modo infinito',
    new_best: '¡Nuevo récord!',
    over_note: 'Mejor combo x{n}. {b} ladrillos rotos.',
    play_again: 'Otra vez',
    menu: 'Menú',
    combo: 'Combo',
    banner_stage: 'Fase {n}',
    banner_wave: 'Infinito · oleada {n}',
    launch_touch: 'TOCA PARA LANZAR',
    launch_mouse: 'CLIC O ESPACIO PARA LANZAR',
    pop_clear: 'FASE SUPERADA +{n}',
    pw_M: 'Multibola',
    pw_W: 'Ancha',
    pw_L: 'Láser',
    pw_S: 'Lento',
    lvl_love: 'Circuito del amor',
    lvl_invader: 'Invasor',
    lvl_spiral: 'Espiral',
    lvl_palm: 'Palmeras',
    lvl_sun: 'Hipersol',
    help_goal: 'Que no caiga la bola y rompe todos los ladrillos.',
    help_armor: 'Los ladrillos con borde interior aguantan dos golpes.',
    help_caps: 'Coge las cápsulas que caen con la pala:',
    help_M: 'M = tres bolas a la vez',
    help_W: 'W = una pala más ancha',
    help_L: 'L = dos láseres disparan hacia arriba',
    help_S: 'S = todo va más lento',
    help_combo: 'Ladrillos seguidos sin tocar la pala = combo, hasta x12.',
    help_controls: 'Arrastra para mover. Toca para lanzar.',
    help_close: 'Entendido',
    say_stage: 'Fase {n}: {name}.',
    say_wave: 'Oleada {n}.',
    say_life: 'Bola perdida. Quedan {n}.',
    say_over: 'Fin. Puntos {n}.',
    say_clear: '¡Fase superada! Bonus {n}.',
  },
};
