// contexto/js/engine.js - the word model and the rules. Pure: no DOM, no storage. The data files
// are GENERATED by build-contexto-data.mjs (repo root); read its header for what they hold.
//
// A guess's RANK is its place in the whole vocabulary sorted by closeness to the secret: the
// secret is 1, the closest other word 2, and so on. Ranks 2..K+1 come straight from the exact
// neighbour list the generator computed at full precision; everything past that is ordered by the
// compressed vectors, where a few hundred places either way cannot be seen.

// Puzzle #1 is 2026-09-28, counted in the player's LOCAL calendar so a new word arrives at their
// midnight, not UTC's.
const EPOCH = [2026, 8, 28];

/** Puzzle number for a date (1-based). Everyone on the same local date gets the same number. */
export function puzzleNumber(date = new Date()) {
  const a = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const b = Date.UTC(EPOCH[0], EPOCH[1], EPOCH[2]);
  return Math.max(1, Math.round((a - b) / 86400000) + 1);
}

// Colour bands. Also the bar's shape marker, so hue is never the only signal.
export const CLOSE = 300;
export const NEAR = 1000;
export function band(rank) { return rank <= CLOSE ? 'close' : rank <= NEAR ? 'near' : 'far'; }

const fold = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '');

/** Build a model from the parsed <lang>.json and the <lang>.bin ArrayBuffer. */
export function buildModel(json, buf) {
  const { words, forms, secrets, dim, k } = json;
  const N = words.length;
  const scales = new Float32Array(buf, 0, dim);
  const q = new Int8Array(buf, dim * 4, N * dim);
  const nb = new Uint16Array(buf.slice(dim * 4 + N * dim));
  if (nb.length !== secrets.length * k) throw new Error('contexto: data files do not match');

  const index = new Map();
  words.forEach((w, i) => index.set(w, i));
  // Accent-blind fallback ("cancion" finds "canción"). The first, i.e. most frequent, word
  // wins a folded key, so an exact spelling is always tried first and this only fills gaps.
  const folded = new Map();
  words.forEach((w, i) => { const f = fold(w); if (!folded.has(f)) folded.set(f, i); });
  const formFold = new Map();
  for (const f in forms) { const ff = fold(f); if (!formFold.has(ff)) formFold.set(ff, forms[f]); }
  const secretPos = new Map(secrets.map((w, si) => [w, si]));

  let unit = null;   // dequantized, unit-length vectors; built on first far-rank request
  function units() {
    if (unit) return unit;
    unit = new Float32Array(N * dim);
    for (let i = 0; i < N; i++) {
      let n = 0;
      for (let j = 0; j < dim; j++) { const v = q[i * dim + j] * scales[j]; unit[i * dim + j] = v; n += v * v; }
      n = Math.sqrt(n) || 1;
      for (let j = 0; j < dim; j++) unit[i * dim + j] /= n;
    }
    return unit;
  }

  const rankCache = new Map();
  /** Int32Array: rank (1-based) of every word index against this secret word index. */
  function ranks(secret) {
    if (rankCache.has(secret)) return rankCache.get(secret);
    const si = secretPos.get(secret);
    if (si === undefined) throw new Error('contexto: not a secret word');
    const r = new Int32Array(N);
    r[secret] = 1;
    for (let j = 0; j < k; j++) r[nb[si * k + j]] = j + 2;
    const u = units();
    const rest = [];
    const sims = new Float32Array(N);
    for (let i = 0; i < N; i++) {
      if (r[i]) continue;
      let d = 0;
      for (let j = 0; j < dim; j++) d += u[i * dim + j] * u[secret * dim + j];
      sims[i] = d;
      rest.push(i);
    }
    rest.sort((a, b) => sims[b] - sims[a] || a - b);
    rest.forEach((i, j) => { r[i] = k + 2 + j; });
    const byRank = new Int32Array(N + 1);
    for (let i = 0; i < N; i++) byRank[r[i]] = i;
    const out = { r, byRank };
    rankCache.clear();   // one secret at a time is all a player ever needs
    rankCache.set(secret, out);
    return out;
  }

  return {
    lang: json.lang,
    size: N,
    count: secrets.length,
    words,
    /** Word index for what the player typed, or -1. Inflected forms map to their lemma. */
    lookup(raw) {
      const w = String(raw || '').trim().toLowerCase();
      if (!w || /\s/.test(w)) return -1;
      if (index.has(w)) return index.get(w);
      if (Object.prototype.hasOwnProperty.call(forms, w)) return forms[w];
      const f = fold(w);
      if (folded.has(f)) return folded.get(f);
      if (formFold.has(f)) return formFold.get(f);
      return -1;
    },
    /** The secret word index for a puzzle number. */
    secretFor(n) { return secrets[(((n - 1) % secrets.length) + secrets.length) % secrets.length]; },
    isSecret(i) { return secretPos.has(i); },
    rankOf(secret, i) { return ranks(secret).r[i]; },
    wordAt(secret, rank) { return words[ranks(secret).byRank[rank]]; },
    indexAt(secret, rank) { return ranks(secret).byRank[rank]; },
  };
}

/** Fetch and build one language's model. Rejects if either file is missing (offline first play). */
export async function loadModel(lang) {
  const base = new URL(`../data/${lang}`, import.meta.url);
  const [json, buf] = await Promise.all([
    fetch(base + '.json').then((r) => { if (!r.ok) throw new Error('json ' + r.status); return r.json(); }),
    fetch(base + '.bin').then((r) => { if (!r.ok) throw new Error('bin ' + r.status); return r.arrayBuffer(); }),
  ]);
  return buildModel(json, buf);
}

/** The rank a hint reveals, or null when there is nothing left to give. Halves the distance to
 *  the word from the best guess so far (300 to start, or when the best is still far off); never
 *  the word itself, never a rank already on the board. */
export function hintRank(best, taken) {
  let target = !best || best > 600 ? CLOSE : Math.floor(best / 2);
  if (best && target >= best) target = best - 1;
  for (let r = target; r >= 2; r--) if (!taken.has(r)) return r;
  for (let r = target + 1; best && r < best; r++) if (!taken.has(r)) return r;
  return null;
}
