// contexto/js/strings.js - the EN/ES dictionary. English is the source of truth; a missing
// Spanish key falls back to English (js/i18n.js's makeT), so partial translation never breaks. No
// em dashes anywhere (root CLAUDE.md's copy rule). This is the HUB CHROME language only - the
// gameplay word list language (EN/ES) is a separate per-puzzle setting, see engine.js's header.
const STRINGS = {
  en: {
    title: 'Contexto',
    puzzle_label: '#{n}',
    guesses_short: '{n} guesses',
    hints_short: '{n} hints',
    lang_chip_aria: 'Word list language: {lang}. Tap to switch.',
    howto_aria: 'How to play',
    input_placeholder: 'Type a word',
    input_aria: 'Guess a word',
    go: 'Go',
    msg_unknown: '"{word}" is not in the word list',
    msg_already: '"{word}" already guessed',
    msg_inflected: '"{input}" counts as "{word}"',
    msg_hint_none: 'No more hints',
    latest_label: 'Latest guess',
    rank_aria: 'rank {rank}',
    hint_icon_aria: 'Revealed by hint',
    list_more: '+{n} more',
    action_hint: 'Hint',
    action_giveup: 'Give up',
    action_previous: 'Previous games',
    giveup_confirm_title: 'Give up on this puzzle?',
    giveup_confirm_body: 'The word will be revealed. Your guesses are kept.',
    cancel: 'Cancel',
    confirm_giveup: 'Give up',
    close_aria: 'Close',
    win_title: 'Solved!',
    gave_title: 'Word revealed',
    result_word: 'The word was "{word}"',
    result_detail_named: '{name}, puzzle #{n}, {guesses} guesses, {hints} hints',
    result_detail: 'Puzzle #{n}, {guesses} guesses, {hints} hints',
    closest_words: 'Closest words',
    page_label: 'Ranks {from} to {to}',
    page_prev_aria: 'Previous ranks',
    page_next_aria: 'Next ranks',
    play_another: 'Play another',
    no_more_puzzles: 'You have played every earlier puzzle',
    previous_games_title: 'Previous games',
    stepper_prev_aria: 'Earlier puzzle',
    stepper_next_aria: 'Later puzzle',
    status_new: 'Not played',
    status_progress: 'In progress ({n} guesses)',
    status_solved: 'Solved in {n}',
    status_gave: 'Gave up',
    random_btn: 'Random unplayed',
    play_btn: 'Play',
    loading: 'Loading words, first time only',
    load_error: 'Could not load the word list. Check your connection.',
    try_again: 'Try again',
    howto_goal: 'Guess the secret word. Every guess shows how close it is in meaning.',
    howto_caption: 'Closer meaning means a lower rank and a fuller bar. Rank 1 wins.',
    howto_example: 'Secret "cat": dog = rank 3',
    howto_edge_new: 'A new word every day.',
    howto_edge_plural: 'Plurals and verb forms count as the base word (cats counts as cat).',
    howto_close: 'Got it',
    howto_diagram_aria: 'Three example guess rows: a close word with a nearly full teal bar, a near word with a partial yellow bar, and a far word with a thin vermilion bar',
  },
  es: {
    title: 'Contexto',
    puzzle_label: '#{n}',
    guesses_short: '{n} intentos',
    hints_short: '{n} pistas',
    lang_chip_aria: 'Idioma de la lista de palabras: {lang}. Toca para cambiar.',
    howto_aria: 'Como jugar',
    input_placeholder: 'Escribe una palabra',
    input_aria: 'Adivina una palabra',
    go: 'Ir',
    msg_unknown: '"{word}" no esta en la lista de palabras',
    msg_already: '"{word}" ya la intentaste',
    msg_inflected: '"{input}" cuenta como "{word}"',
    msg_hint_none: 'No quedan mas pistas',
    latest_label: 'Ultimo intento',
    rank_aria: 'posicion {rank}',
    hint_icon_aria: 'Revelada por pista',
    list_more: '+{n} mas',
    action_hint: 'Pista',
    action_giveup: 'Rendirse',
    action_previous: 'Partidas anteriores',
    giveup_confirm_title: 'Rendirte en esta partida?',
    giveup_confirm_body: 'Se revelara la palabra. Tus intentos se conservan.',
    cancel: 'Cancelar',
    confirm_giveup: 'Rendirse',
    close_aria: 'Cerrar',
    win_title: 'Resuelto!',
    gave_title: 'Palabra revelada',
    result_word: 'La palabra era "{word}"',
    result_detail_named: '{name}, partida #{n}, {guesses} intentos, {hints} pistas',
    result_detail: 'Partida #{n}, {guesses} intentos, {hints} pistas',
    closest_words: 'Palabras mas cercanas',
    page_label: 'Posiciones {from} a {to}',
    page_prev_aria: 'Posiciones anteriores',
    page_next_aria: 'Posiciones siguientes',
    play_another: 'Jugar otra',
    no_more_puzzles: 'Ya jugaste todas las partidas anteriores',
    previous_games_title: 'Partidas anteriores',
    stepper_prev_aria: 'Partida anterior',
    stepper_next_aria: 'Partida siguiente',
    status_new: 'Sin jugar',
    status_progress: 'En curso ({n} intentos)',
    status_solved: 'Resuelta en {n}',
    status_gave: 'Te rendiste',
    random_btn: 'Al azar sin jugar',
    play_btn: 'Jugar',
    loading: 'Cargando palabras, solo la primera vez',
    load_error: 'No se pudo cargar la lista de palabras. Revisa tu conexion.',
    try_again: 'Reintentar',
    howto_goal: 'Adivina la palabra secreta. Cada intento muestra que tan cerca esta en significado.',
    howto_caption: 'Mas cerca en significado es una posicion mas baja y una barra mas llena. La posicion 1 gana.',
    howto_example: 'Secreta "gato": perro = posicion 3',
    howto_edge_new: 'Una palabra nueva cada dia.',
    howto_edge_plural: 'Plurales y formas verbales cuentan como la palabra base (gatos cuenta como gato).',
    howto_close: 'Entendido',
    howto_diagram_aria: 'Tres filas de ejemplo: una palabra cercana con una barra verde azulada casi llena, una palabra media con una barra amarilla parcial y una palabra lejana con una barra bermellon delgada',
  },
};

export default STRINGS;
export { STRINGS };
