// chinchon/js/strings.js — every user-visible string in Chinchón, both languages. Follows the
// per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference: snake/).
// English is the source of truth; es may lag (js/i18n.js's fallback shows English for anything
// missing). Values that are storage vocabulary (difficulty ids easy/normal/hard, victory/rule
// config values, settings-key contents) stay canonical — only their display labels translate.
// Card-suit terms (Oros/Copas/Espadas/Bastos) and card-rank names in the deck gallery (As, Sota,
// Caballo, Rey) are the games' real Spanish vocabulary in BOTH languages and are not run through
// this dictionary at all (see galleryLabel() in ui.js). "Chinchón" (the game name and the winning
// hand) stays as the Spanish term in both languages, same as the other loanword exclusions.

export const STRINGS = {
  en: {
    title: 'Chinchón',
    menu_btn_aria: 'Game menu',
    mode_light: 'Light mode',
    mode_dark: 'Dark mode',
    theme_toggle_aria: 'Toggle dark mode',
    mode_solo: 'Solo',
    mode_host: 'Host online',
    mode_join: 'Join',
    action_host_game: 'Host game',
    action_begin_challenge: 'Begin challenge',
    action_start_game: 'Start game',
    challenge_completed_note: 'Chinchón challenge completed. Play anyways?',
    stats_line: '{games} played · {wins} won · {closes} closes · {chinchons} chinchón',
    row_players: 'Players',
    row_difficulty: 'Difficulty',
    row_deck: 'Card deck',
    row_victory: 'Victory',
    row_closing: 'Closing rules',
    row_deckrules: 'Deck rules',
    row_other: 'Other rules',
    online_word: 'online',
    aria_opponent_name: 'Opponent {n} name',
    aria_your_name: 'Your name',
    avatar_choose_title: 'Choose avatar',
    diff_easy: 'Beginner',
    diff_average: 'Intermediate',
    diff_hard: 'Pro',
    victory_by_points: 'By points',
    victory_by_rounds: 'By rounds',
    victory_by_both: 'Rounds or points',
    seg_points: 'Points',
    seg_rounds: 'Rounds',
    seg_both: 'Both',
    pts_suffix: '{v} pts',
    rounds_suffix: '{v} rounds',
    label_score_limit: 'Score limit',
    label_rounds: 'Rounds',
    label_max_close: 'Max points to close',
    label_figures_value: 'Figures value',
    seg_flat10: 'Flat 10',
    seg_own: 'Own',
    label_flat: 'Flat',
    label_place_on_ending: 'Place cards on ending',
    seg_auto: 'Auto',
    seg_manual: 'Manual',
    seg_off: 'Off',
    place_auto_full: 'Auto placement',
    place_manual_full: 'Manual placement',
    place_off_full: 'No placement',
    closing_summary: 'Close ≤{max} · {fig} figures · {place}',
    label_use_48: 'Use 8s & 9s (48 cards)',
    label_play_joker: 'Play with Joker',
    label_ace_wild: 'Ace of Oros is wild',
    label_deck_resets: 'Deck resets',
    deck_rule_48card: '48-card',
    deck_rule_joker: 'Joker',
    deck_rule_wild_ace: 'Wild Ace',
    resets_count: ({ n }) => `${n} reset${n === 1 ? '' : 's'}`,
    label_win_chinchon: 'Win with chinchón',
    label_show_remaining: 'Show remaining cards',
    misc_chinchon_wins: 'Chinchón wins',
    misc_remaining_shown: 'Remaining shown',
    misc_off: 'Off',
    mp_update_required: 'Update required',
    mp_joining: 'Joining…',
    mp_enter_code: 'Enter code',
    aria_room_code: 'Room code',
    mp_join_btn: 'Join',
    mp_creating_room: 'Creating room…',
    mp_opponent_label: 'Opponent',
    mp_host_label: 'Host',
    mp_start_btn: 'Start',
    mp_back_btn: 'Back',
    mp_waiting_host: 'Waiting for host',
    mp_status_connection_error: 'Connection error',
    mp_status_resyncing: 'Resyncing',
    mp_status_opponent_left: 'Opponent left',
    mp_status_opponent_disconnected: 'Opponent disconnected',
    mp_48card_deck: '48-card deck',
    avatar_picker_title: 'Choose your avatar',
    close_word: 'Close',
    view_all_cards: 'View all cards',
    gallery_done: 'Done',
    gallery_hint: 'Tap any card to zoom in.',
    aria_avatar_option: 'Avatar {av}',
    deck_back_alt: '{name} back',
    pile_draw_aria: 'Draw from deck',
    pile_take_discard_aria: 'Take the discard',
    pile_deck_label: 'Deck',
    pile_discard_label: 'Discard',
    status_round: 'Round {n}',
    status_resets: 'Resets {used}/{max}',
    status_deck_count: 'Deck {n}',
    status_can_close: 'You can close! Close the round, or keep playing.',
    status_opp_playing: '{name} is playing…',
    sort_label_suit: 'by suit',
    sort_label_rank: 'by rank',
    sort_title: 'Sorted {mode} — tap to cycle',
    sort_aria: 'Sorted {mode}, tap to cycle',
    highlight_sets_title: 'Highlight sets',
    sets_btn: 'Sets',
    discard_word: 'Discard',
    close_round_btn: 'Close round ✓',
    keep_playing_btn: 'Keep playing',
    card_label_joker: 'Joker',
    toast_dealer: '{name} deals',
    toast_drew_discard: '{name} drew from the discard pile',
    toast_drew_deck: '{name} drew from the deck',
    toast_closed_round: '{name} closed the round!',
    toast_deck_reshuffled: 'Deck reshuffled',
    modal_closed_round_title: '{name} closed the round',
    modal_deck_exhausted_title: 'Deck exhausted',
    modal_sub_double_meld: 'Double meld',
    modal_sub_six_and_one: 'Six and one',
    table_header_player: 'Player',
    table_header_round: 'Round',
    table_header_total: 'Total',
    laid_off: 'laid off {n}',
    scores_btn: 'Scores',
    scoreboard_word: 'Scoreboard',
    next_round_btn: 'Next round',
    chinchon_banner_headline: '¡CHINCHÓN!',
    chinchon_banner_sub: 'Seven cards in a single run. Round won instantly.',
    bonus_chinchon: 'Chinchón bonus: {sign}',
    bonus_double_meld: 'All cards melded: {sign}',
    breakdown_hand_label: "{name}'s hand",
    match_title_plain: '{winner} wins!',
    match_title_chinchon: '{winner} wins with a Chinchón!',
    betty_win_caption: 'Betty approves 😎',
    betty_loss_caption: 'Betty is not impressed.',
    standings_word: 'Standings',
    new_game_btn: 'New game',
    retry_challenge_btn: 'Retry Challenge',
    chart_limit_label: 'limit {cap}',
    chart_aria: 'Cumulative score by round',
    menu_title: 'Menu',
    menu_confirm_tap_again: 'Tap again — you’ll lose this game',
    menu_new_game_settings: 'New game (same settings)',
    menu_leave_match: 'Leave match',
    menu_quit_setup: 'Quit to setup',
    menu_resume: 'Resume game',
    place_modal_title: 'Lay off cards?',
    place_modal_sub: "Onto {name}'s melds · −{total} pts",
    place_all_btn: 'Place all (−{total})',
    keep_them_btn: 'Keep them',
    mp_error_title: 'Connection error',
    mp_error_sub: 'The match could not stay in sync',
    back_to_setup_btn: 'Back to setup',
    mp_opponent_left_title: 'Opponent left',
    mp_final_standings_sub: 'Final standings',
    mp_err_could_not_create_room: 'Could not create a room',
    mp_err_offline: 'Offline',
    mp_err_room_not_found: 'Room not found',
    mp_err_room_ended: 'Room ended',
    mp_err_room_full: 'Room full',
    mp_err_wrong_game: 'Wrong game',
    toast_nice_choice: 'Nice choice! 🎉',
  },
  es: {
    title: 'Chinchón',
    menu_btn_aria: 'Menú del juego',
    mode_light: 'Modo claro',
    mode_dark: 'Modo oscuro',
    theme_toggle_aria: 'Cambiar modo oscuro',
    mode_solo: 'Solo',
    mode_host: 'Alojar online',
    mode_join: 'Unirse',
    action_host_game: 'Alojar partida',
    action_begin_challenge: 'Empezar desafío',
    action_start_game: 'Empezar partida',
    challenge_completed_note: 'Desafío de Chinchón completado. ¿Jugar de todos modos?',
    stats_line: '{games} jugadas · {wins} ganadas · {closes} cierres · {chinchons} chinchón',
    row_players: 'Jugadores',
    row_difficulty: 'Dificultad',
    row_deck: 'Baraja',
    row_victory: 'Victoria',
    row_closing: 'Reglas de cierre',
    row_deckrules: 'Reglas de la baraja',
    row_other: 'Otras reglas',
    online_word: 'online',
    aria_opponent_name: 'Nombre del rival {n}',
    aria_your_name: 'Tu nombre',
    avatar_choose_title: 'Elegir avatar',
    diff_easy: 'Principiante',
    diff_average: 'Intermedio',
    diff_hard: 'Pro',
    victory_by_points: 'Por puntos',
    victory_by_rounds: 'Por rondas',
    victory_by_both: 'Rondas o puntos',
    seg_points: 'Puntos',
    seg_rounds: 'Rondas',
    seg_both: 'Ambos',
    pts_suffix: '{v} pts',
    rounds_suffix: '{v} rondas',
    label_score_limit: 'Límite de puntos',
    label_rounds: 'Rondas',
    label_max_close: 'Puntos máximos para cerrar',
    label_figures_value: 'Valor de las figuras',
    seg_flat10: 'Fijo 10',
    seg_own: 'Propio',
    label_flat: 'Fijo',
    label_place_on_ending: 'Colocar cartas al cierre',
    seg_auto: 'Auto',
    seg_manual: 'Manual',
    seg_off: 'Off',
    place_auto_full: 'Colocación automática',
    place_manual_full: 'Colocación manual',
    place_off_full: 'Sin colocación',
    closing_summary: 'Cierre ≤{max} · figuras {fig} · {place}',
    label_use_48: 'Usar 8s y 9s (48 cartas)',
    label_play_joker: 'Jugar con comodín',
    label_ace_wild: 'El as de oros es comodín',
    label_deck_resets: 'Reinicios de baraja',
    deck_rule_48card: '48 cartas',
    deck_rule_joker: 'Comodín',
    deck_rule_wild_ace: 'As comodín',
    resets_count: ({ n }) => `${n} reinicio${n === 1 ? '' : 's'}`,
    label_win_chinchon: 'Ganar con chinchón',
    label_show_remaining: 'Mostrar cartas restantes',
    misc_chinchon_wins: 'Gana con chinchón',
    misc_remaining_shown: 'Restantes mostradas',
    misc_off: 'Off',
    mp_update_required: 'Actualización necesaria',
    mp_joining: 'Uniéndose…',
    mp_enter_code: 'Introduce el código',
    aria_room_code: 'Código de sala',
    mp_join_btn: 'Unirse',
    mp_creating_room: 'Creando sala…',
    mp_opponent_label: 'Rival',
    mp_host_label: 'Anfitrión',
    mp_start_btn: 'Empezar',
    mp_back_btn: 'Atrás',
    mp_waiting_host: 'Esperando al anfitrión',
    mp_status_connection_error: 'Error de conexión',
    mp_status_resyncing: 'Resincronizando',
    mp_status_opponent_left: 'El rival se fue',
    mp_status_opponent_disconnected: 'Rival desconectado',
    mp_48card_deck: '48 cartas',
    avatar_picker_title: 'Elige tu avatar',
    close_word: 'Cerrar',
    view_all_cards: 'Ver todas las cartas',
    gallery_done: 'Hecho',
    gallery_hint: 'Toca cualquier carta para ampliarla.',
    aria_avatar_option: 'Avatar {av}',
    deck_back_alt: 'Reverso de {name}',
    pile_draw_aria: 'Robar del mazo',
    pile_take_discard_aria: 'Tomar el descarte',
    pile_deck_label: 'Mazo',
    pile_discard_label: 'Descarte',
    status_round: 'Ronda {n}',
    status_resets: 'Reinicios {used}/{max}',
    status_deck_count: 'Mazo {n}',
    status_can_close: '¡Puedes cerrar! Cierra la ronda o sigue jugando.',
    status_opp_playing: '{name} está jugando…',
    sort_label_suit: 'por palo',
    sort_label_rank: 'por número',
    sort_title: 'Ordenado {mode} — toca para cambiar',
    sort_aria: 'Ordenado {mode}, toca para cambiar',
    highlight_sets_title: 'Resaltar combinaciones',
    sets_btn: 'Grupos',
    discard_word: 'Descartar',
    close_round_btn: 'Cerrar ronda ✓',
    keep_playing_btn: 'Seguir jugando',
    card_label_joker: 'Comodín',
    toast_dealer: 'Reparte {name}',
    toast_drew_discard: '{name} robó del descarte',
    toast_drew_deck: '{name} robó del mazo',
    toast_closed_round: '¡{name} cerró la ronda!',
    toast_deck_reshuffled: 'Baraja reajustada',
    modal_closed_round_title: '{name} cerró la ronda',
    modal_deck_exhausted_title: 'Mazo agotado',
    modal_sub_double_meld: 'Doble combinación',
    modal_sub_six_and_one: 'Seis y uno',
    table_header_player: 'Jugador',
    table_header_round: 'Ronda',
    table_header_total: 'Total',
    laid_off: 'colocó {n}',
    scores_btn: 'Puntos',
    scoreboard_word: 'Marcador',
    next_round_btn: 'Siguiente ronda',
    chinchon_banner_headline: '¡CHINCHÓN!',
    chinchon_banner_sub: 'Siete cartas en una sola escalera. Ronda ganada al instante.',
    bonus_chinchon: 'Bono chinchón: {sign}',
    bonus_double_meld: 'Todas las cartas combinadas: {sign}',
    breakdown_hand_label: 'Mano de {name}',
    match_title_plain: '¡{winner} gana!',
    match_title_chinchon: '¡{winner} gana con un Chinchón!',
    betty_win_caption: 'Betty lo aprueba 😎',
    betty_loss_caption: 'Betty no está impresionada.',
    standings_word: 'Clasificación',
    new_game_btn: 'Nueva partida',
    retry_challenge_btn: 'Reintentar desafío',
    chart_limit_label: 'límite {cap}',
    chart_aria: 'Puntuación acumulada por ronda',
    menu_title: 'Menú',
    menu_confirm_tap_again: 'Toca otra vez, perderás esta partida',
    menu_new_game_settings: 'Nueva partida (mismos ajustes)',
    menu_leave_match: 'Abandonar partida',
    menu_quit_setup: 'Salir a los ajustes',
    menu_resume: 'Reanudar partida',
    place_modal_title: '¿Colocar cartas?',
    place_modal_sub: 'En las combinaciones de {name} · −{total} pts',
    place_all_btn: 'Colocar todas (−{total})',
    keep_them_btn: 'Quedármelas',
    mp_error_title: 'Error de conexión',
    mp_error_sub: 'La partida no pudo mantenerse sincronizada',
    back_to_setup_btn: 'Volver a los ajustes',
    mp_opponent_left_title: 'El rival se fue',
    mp_final_standings_sub: 'Clasificación final',
    mp_err_could_not_create_room: 'No se pudo crear la sala',
    mp_err_offline: 'Sin conexión',
    mp_err_room_not_found: 'Sala no encontrada',
    mp_err_room_ended: 'La sala terminó',
    mp_err_room_full: 'Sala llena',
    mp_err_wrong_game: 'Juego incorrecto',
    toast_nice_choice: '¡Buena elección! 🎉',
  },
};

export default STRINGS;
