// darts/js/strings.js - every user-visible string, { en, es } (js/i18n.js). English is the source
// of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).
export const STRINGS = {
  en: {
    title: 'Darts',
    tagline: '301. Hit exactly zero to win.',
    online_waiting: '{n} waiting on you',
    online_waiting1: '1 waiting on you',
    mp_title: 'Multiplayer',
    mp_challenge: 'Challenge someone',
    mp_your_turn: 'Your turn',
    mp_their_turn: 'Their turn',
    mp_none: 'No matches yet. Challenge someone!',
    mp_history: 'History',
    mp_loading: 'Loading...',
    mp_scores: 'You {a}, {name} {b}',
    mp_closed: 'Closed: you {a}, {name} {b}',
    mp_pts: '{a}-{b} pts',
    mp_search: 'Find a player',
    mp_no_opp: 'Nobody found',
    mp_send: 'Challenge {name}',
    mp_send_note: 'You throw first. {name} gets it when your turn is done.',
    mp_records: 'Records',
    mp_matches: 'Matches',
    mp_no_history: 'No finished matches yet',
    mp_won: 'Won',
    mp_lost: 'Lost',
    mp_won_quit: 'Won, they quit',
    mp_you_quit: 'You quit',
    mp_more: '+{n} more',
    mp_notify: 'Notify me when it is my turn',
    mp_waiting: 'Sent! Waiting for {name}',
    mp_resign: 'Resign',
    mp_resign_q: 'Give up this match?',
    mp_resign_yes: 'Resign',
    mp_cancel: 'Cancel',
    mp_back: 'Multiplayer',
    mp_again: 'Challenge again',
    mp_game_over: 'Game over',
    mp_you_won_vs: 'You beat {name}',
    mp_you_lost_vs: '{name} beat you',
    mp_they_resigned: '{name} resigned',
    mp_you_resigned: 'You resigned',
    mp_ok: 'OK',
    mp_not_sent: 'Not sent yet. Trying again...',
    mp_send_failed: 'Could not send. Try again.',
    mp_denied: 'Online play is not switched on yet.',
    mp_offline: 'No connection. Try again.',
    mp_dev: 'Online writes are off on a dev server.',
    mp_no_code: 'Set up your profile first.',
    mp_not_found: 'That match could not be opened.',
    aria_back: 'Back',
    difficulty: 'Play the computer',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    first: 'First throw',
    first_alt: 'Alternate',
    first_me: 'Me',
    first_them_cpu: 'Computer',
    first_them_pass: 'Player 2',
    pace: 'Computer speed', pace_slow: 'Slow', pace_normal: 'Normal', pace_fast: 'Fast',
    play: 'Play',
    continue: 'Continue match',
    howto: 'How to play',
    menu: 'Menu',
    resume: 'Resume',
    quit: 'Quit match',
    new_match: 'New match',
    aria_close: 'Close',
    aria_menu: 'Menu',
    aria_darts_left: '{n} darts left this turn',
    aria_board: 'Dartboard. Flick the dart up to throw.',
    player2: 'Player 2',
    computer: 'Computer',
    you: 'You',
    hint_flick: 'Flick up to throw',
    miss: 'MISS!',
    bust: 'BUST!',
    bust_sub: 'Over zero. Back to {n}.',
    bull: 'BULLSEYE!',
    your_turn: 'Your turn',
    turn_of: '{name}',
    pass_to: 'Pass to {name}',
    tap_ready: 'Tap when ready',
    win_you: 'You win!',
    win_name: '{name} wins!',
    lose_you: 'You lose',
    result_line: 'Finished in {n} turns',
    play_again: 'Play again',
    say_hit: '{name} scored {pts}. {left} to go.',
    say_miss: '{name} missed.',
    say_bust: '{name} went bust. Back to {n}.',
    say_turn: '{name} to throw.',
    say_win: '{name} wins.',
    help_goal: 'Start at 301. Hit exactly zero to win.',
    help_cap: 'Outer thin ring doubles. Inner thin ring triples.',
    help_example: 'Treble 20 = 60 points',
    help_bull: 'Bull: 25. Bullseye: 50.',
    help_bust: 'Below zero is a bust: that turn does not count.',
    help_flick: 'Flick the dart up. Faster flicks land higher.',
    help_close: 'Got it',
    lbl_double: 'x2',
    lbl_treble: 'x3',
    game: 'Game',
    multiplayer: 'Multiplayer',
    points: 'Points',
    points_on: 'On',
    points_off: 'Off',
    game_cricket_np: 'Cricket (no points)',
    game_cricket_order_np: 'Cricket (in order, no points)',
    tagline_cricket_np: 'First to close 20 to 15 and the bull wins.',
    tagline_cricket_order_np: 'First to close 20, 19, 18, 17, 16, 15, bull wins.',
    help_c_nopoints: 'No points: extra hits on a closed number do nothing.',
    help_c_win_np: 'First to close all seven wins.',
    say_c_hit_np: '{name} hit {bed}.',
    mp_pass: 'Pass & play',
    game_cricket: 'Cricket',
    game_cricket_order: 'Cricket (in order)',
    order: 'Order',
    order_any: 'Any',
    order_order: 'In order',
    tagline_x01: '{n}. Hit exactly zero to win.',
    tagline_cricket: 'Close 20 to 15 and the bull. Outscore.',
    tagline_cricket_order: 'Close 20, 19, 18, 17, 16, 15, bull. In order.',
    mp_game_note: '{game}. You throw first. {name} gets it when your turn is done.',
    say_c_hit: '{name} hit {bed}. {score} points.',
    say_c_none: '{name} hit {bed}. It does not count.',
    aria_marks: '{name}: {list}',
    aria_mark_closed: 'closed',
    aria_mark_n: '{n} marks',
    help_c_goal: 'Close 20 to 15 and the bull, and outscore.',
    help_c_marks: 'Single 1 mark, double 2, treble 3. Three close it.',
    help_c_bull: 'Outer bull 1 mark. Bullseye 2.',
    help_c_points: 'Closed for you, open for them: hits score points.',
    help_c_any: 'Close them in any order.',
    help_c_order: 'In order: 20, 19, 18, 17, 16, 15, then the bull.',
    help_c_win: 'Everything closed and most points wins.',
    lbl_bull: 'Bull',
  },
  es: {
    title: 'Dardos',
    tagline: '301. Llega justo a cero para ganar.',
    online_waiting: '{n} esperan tu tiro',
    online_waiting1: '1 espera tu tiro',
    mp_title: 'Multijugador',
    mp_challenge: 'Retar a alguien',
    mp_your_turn: 'Te toca',
    mp_their_turn: 'Turno del rival',
    mp_none: 'Aún no hay partidas. ¡Reta a alguien!',
    mp_history: 'Historial',
    mp_loading: 'Cargando...',
    mp_scores: 'Tú {a}, {name} {b}',
    mp_closed: 'Cerrados: tú {a}, {name} {b}',
    mp_pts: '{a}-{b} ptos',
    mp_search: 'Buscar jugador',
    mp_no_opp: 'No se ha encontrado a nadie',
    mp_send: 'Retar a {name}',
    mp_send_note: 'Tiras tú primero. {name} lo recibe al acabar tu turno.',
    mp_records: 'Récords',
    mp_matches: 'Partidas',
    mp_no_history: 'Aún no hay partidas terminadas',
    mp_won: 'Ganada',
    mp_lost: 'Perdida',
    mp_won_quit: 'Ganada, se rindió',
    mp_you_quit: 'Te rendiste',
    mp_more: '+{n} más',
    mp_notify: 'Avísame cuando me toque',
    mp_waiting: '¡Enviado! Esperando a {name}',
    mp_resign: 'Rendirse',
    mp_resign_q: '¿Abandonar esta partida?',
    mp_resign_yes: 'Rendirse',
    mp_cancel: 'Cancelar',
    mp_back: 'Multijugador',
    mp_again: 'Retar otra vez',
    mp_game_over: 'Fin de la partida',
    mp_you_won_vs: 'Has ganado a {name}',
    mp_you_lost_vs: '{name} te ha ganado',
    mp_they_resigned: '{name} se rindió',
    mp_you_resigned: 'Te rendiste',
    mp_ok: 'Vale',
    mp_not_sent: 'Aún no se ha enviado. Reintentando...',
    mp_send_failed: 'No se pudo enviar. Inténtalo otra vez.',
    mp_denied: 'El juego en línea aún no está activado.',
    mp_offline: 'Sin conexión. Inténtalo otra vez.',
    mp_dev: 'En un servidor de pruebas no se escribe en línea.',
    mp_no_code: 'Primero configura tu perfil.',
    mp_not_found: 'No se pudo abrir esa partida.',
    aria_back: 'Atrás',
    difficulty: 'Contra la máquina',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    first: 'Primer tiro',
    first_alt: 'Alternar',
    first_me: 'Yo',
    first_them_cpu: 'Máquina',
    first_them_pass: 'Jugador 2',
    pace: 'Velocidad de la máquina', pace_slow: 'Lenta', pace_normal: 'Normal', pace_fast: 'Rápida',
    play: 'Jugar',
    continue: 'Seguir partida',
    howto: 'Cómo se juega',
    menu: 'Menú',
    resume: 'Seguir',
    quit: 'Salir de la partida',
    new_match: 'Nueva partida',
    aria_close: 'Cerrar',
    aria_menu: 'Menú',
    aria_darts_left: 'Te quedan {n} dardos este turno',
    aria_board: 'Diana. Desliza el dardo hacia arriba para lanzar.',
    player2: 'Jugador 2',
    computer: 'Máquina',
    you: 'Tú',
    hint_flick: 'Desliza hacia arriba para lanzar',
    miss: '¡FALLO!',
    bust: '¡TE PASAS!',
    bust_sub: 'Por debajo de cero. Vuelves a {n}.',
    bull: '¡DIANA!',
    your_turn: 'Te toca',
    turn_of: '{name}',
    pass_to: 'Pasa el móvil a {name}',
    tap_ready: 'Toca cuando estés listo',
    win_you: '¡Has ganado!',
    win_name: '¡Gana {name}!',
    lose_you: 'Has perdido',
    result_line: 'Terminó en {n} turnos',
    play_again: 'Otra vez',
    say_hit: '{name} suma {pts}. Quedan {left}.',
    say_miss: '{name} ha fallado.',
    say_bust: '{name} se pasa. Vuelve a {n}.',
    say_turn: 'Lanza {name}.',
    say_win: 'Gana {name}.',
    help_goal: 'Empiezas en 301. Llega justo a cero.',
    help_cap: 'El anillo fino de fuera dobla. El de dentro triplica.',
    help_example: 'Triple 20 = 60 puntos',
    help_bull: 'Centro: 25. Diana: 50.',
    help_bust: 'Bajar de cero es pasarse: ese turno no cuenta.',
    help_flick: 'Desliza el dardo hacia arriba. Más rápido, más alto.',
    help_close: 'Entendido',
    lbl_double: 'x2',
    lbl_treble: 'x3',
    game: 'Juego',
    multiplayer: 'Multijugador',
    points: 'Puntos',
    points_on: 'Sí',
    points_off: 'No',
    game_cricket_np: 'Cricket (sin puntos)',
    game_cricket_order_np: 'Cricket (en orden, sin puntos)',
    tagline_cricket_np: 'Gana quien cierre antes del 20 al 15 y la diana.',
    tagline_cricket_order_np: 'Gana quien cierre antes 20, 19, 18, 17, 16, 15, diana.',
    help_c_nopoints: 'Sin puntos: dar en un número cerrado no suma.',
    help_c_win_np: 'Gana quien cierre los siete primero.',
    say_c_hit_np: '{name} da en {bed}.',
    mp_pass: 'Pasar y jugar',
    game_cricket: 'Cricket',
    game_cricket_order: 'Cricket (en orden)',
    order: 'Orden',
    order_any: 'Libre',
    order_order: 'En orden',
    tagline_x01: '{n}. Llega justo a cero para ganar.',
    tagline_cricket: 'Cierra del 20 al 15 y la diana. Suma más.',
    tagline_cricket_order: 'Cierra 20, 19, 18, 17, 16, 15, diana. En orden.',
    mp_game_note: '{game}. Tiras tú primero. {name} lo recibe al acabar tu turno.',
    say_c_hit: '{name} da en {bed}. {score} puntos.',
    say_c_none: '{name} da en {bed}. No cuenta.',
    aria_marks: '{name}: {list}',
    aria_mark_closed: 'cerrado',
    aria_mark_n: '{n} marcas',
    help_c_goal: 'Cierra del 20 al 15 y la diana, y suma más.',
    help_c_marks: 'Simple 1 marca, doble 2, triple 3. Tres lo cierran.',
    help_c_bull: 'Diana exterior 1 marca. Centro 2.',
    help_c_points: 'Cerrado para ti, abierto para él: suma puntos.',
    help_c_any: 'Ciérralos en cualquier orden.',
    help_c_order: 'En orden: 20, 19, 18, 17, 16, 15 y la diana.',
    help_c_win: 'Todo cerrado y más puntos: ganas.',
    lbl_bull: 'Diana',
  },
};
