// darts/js/strings.js - every user-visible string, { en, es } (js/i18n.js). English is the source
// of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).
export const STRINGS = {
  en: {
    title: 'Darts',
    tagline: '301. Hit exactly zero to win.',
    mode: 'Play',
    mode_cpu: 'Computer',
    mode_pass: '2 players',
    mode_online: 'Online',
    online_go: 'Online matches',
    online_waiting: '{n} waiting on you',
    online_waiting1: '1 waiting on you',
    mp_title: 'Online',
    mp_challenge: 'Challenge someone',
    mp_your_turn: 'Your turn',
    mp_their_turn: 'Their turn',
    mp_none: 'No matches yet. Challenge someone!',
    mp_history: 'History',
    mp_loading: 'Loading...',
    mp_scores: 'You {a}, {name} {b}',
    mp_search: 'Find a player',
    mp_no_opp: 'Nobody found',
    mp_send: 'Challenge {name}',
    mp_send_note: 'You throw first. {name} gets it when your turn is done.',
    mp_records: 'Records',
    mp_matches: 'Matches',
    mp_no_history: 'No finished matches yet',
    mp_won: 'Won',
    mp_lost: 'Lost',
    mp_won_quit: 'Won, they quit',
    mp_you_quit: 'You quit',
    mp_more: '+{n} more',
    mp_notify: 'Notify me when it is my turn',
    mp_waiting: 'Sent! Waiting for {name}',
    mp_resign: 'Resign',
    mp_resign_q: 'Give up this match?',
    mp_resign_yes: 'Resign',
    mp_cancel: 'Cancel',
    mp_back: 'Online matches',
    mp_again: 'Challenge again',
    mp_game_over: 'Game over',
    mp_you_won_vs: 'You beat {name}',
    mp_you_lost_vs: '{name} beat you',
    mp_they_resigned: '{name} resigned',
    mp_you_resigned: 'You resigned',
    mp_ok: 'OK',
    mp_not_sent: 'Not sent yet. Trying again...',
    mp_send_failed: 'Could not send. Try again.',
    mp_denied: 'Online play is not switched on yet.',
    mp_offline: 'No connection. Try again.',
    mp_dev: 'Online writes are off on a dev server.',
    mp_no_code: 'Set up your profile first.',
    mp_not_found: 'That match could not be opened.',
    aria_back: 'Back',
    difficulty: 'Computer',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    first: 'First throw',
    first_alt: 'Alternate',
    first_me: 'Me',
    first_them_cpu: 'Computer',
    first_them_pass: 'Player 2',
    play: 'Play',
    continue: 'Continue match',
    howto: 'How to play',
    menu: 'Menu',
    resume: 'Resume',
    quit: 'Quit match',
    new_match: 'New match',
    aria_close: 'Close',
    aria_menu: 'Menu',
    aria_darts_left: '{n} darts left this turn',
    aria_board: 'Dartboard. Flick the dart up to throw.',
    player2: 'Player 2',
    computer: 'Computer',
    you: 'You',
    hint_flick: 'Flick up to throw',
    miss: 'MISS!',
    bust: 'BUST!',
    bust_sub: 'Over zero. Back to {n}.',
    bull: 'BULLSEYE!',
    your_turn: 'Your turn',
    turn_of: '{name}',
    pass_to: 'Pass to {name}',
    tap_ready: 'Tap when ready',
    win_you: 'You win!',
    win_name: '{name} wins!',
    lose_you: 'You lose',
    result_line: 'Finished in {n} turns',
    play_again: 'Play again',
    say_hit: '{name} scored {pts}. {left} to go.',
    say_miss: '{name} missed.',
    say_bust: '{name} went bust. Back to {n}.',
    say_turn: '{name} to throw.',
    say_win: '{name} wins.',
    help_goal: 'Start at 301. Hit exactly zero to win.',
    help_cap: 'Outer thin ring doubles. Inner thin ring triples.',
    help_example: 'Treble 20 = 60 points',
    help_bull: 'Bull: 25. Bullseye: 50.',
    help_bust: 'Below zero is a bust: that turn does not count.',
    help_flick: 'Flick the dart up. Faster flicks land higher.',
    help_close: 'Got it',
    lbl_double: 'x2',
    lbl_treble: 'x3',
  },
  es: {
    title: 'Dardos',
    tagline: '301. Llega justo a cero para ganar.',
    mode: 'Jugar',
    mode_cpu: 'Máquina',
    mode_pass: '2 jugadores',
    mode_online: 'En línea',
    online_go: 'Partidas en línea',
    online_waiting: '{n} esperan tu tiro',
    online_waiting1: '1 espera tu tiro',
    mp_title: 'En línea',
    mp_challenge: 'Retar a alguien',
    mp_your_turn: 'Te toca',
    mp_their_turn: 'Turno del rival',
    mp_none: 'Aún no hay partidas. ¡Reta a alguien!',
    mp_history: 'Historial',
    mp_loading: 'Cargando...',
    mp_scores: 'Tú {a}, {name} {b}',
    mp_search: 'Buscar jugador',
    mp_no_opp: 'No se ha encontrado a nadie',
    mp_send: 'Retar a {name}',
    mp_send_note: 'Tiras tú primero. {name} lo recibe al acabar tu turno.',
    mp_records: 'Récords',
    mp_matches: 'Partidas',
    mp_no_history: 'Aún no hay partidas terminadas',
    mp_won: 'Ganada',
    mp_lost: 'Perdida',
    mp_won_quit: 'Ganada, se rindió',
    mp_you_quit: 'Te rendiste',
    mp_more: '+{n} más',
    mp_notify: 'Avísame cuando me toque',
    mp_waiting: '¡Enviado! Esperando a {name}',
    mp_resign: 'Rendirse',
    mp_resign_q: '¿Abandonar esta partida?',
    mp_resign_yes: 'Rendirse',
    mp_cancel: 'Cancelar',
    mp_back: 'Partidas en línea',
    mp_again: 'Retar otra vez',
    mp_game_over: 'Fin de la partida',
    mp_you_won_vs: 'Has ganado a {name}',
    mp_you_lost_vs: '{name} te ha ganado',
    mp_they_resigned: '{name} se rindió',
    mp_you_resigned: 'Te rendiste',
    mp_ok: 'Vale',
    mp_not_sent: 'Aún no se ha enviado. Reintentando...',
    mp_send_failed: 'No se pudo enviar. Inténtalo otra vez.',
    mp_denied: 'El juego en línea aún no está activado.',
    mp_offline: 'Sin conexión. Inténtalo otra vez.',
    mp_dev: 'En un servidor de pruebas no se escribe en línea.',
    mp_no_code: 'Primero configura tu perfil.',
    mp_not_found: 'No se pudo abrir esa partida.',
    aria_back: 'Atrás',
    difficulty: 'Máquina',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    first: 'Primer tiro',
    first_alt: 'Alternar',
    first_me: 'Yo',
    first_them_cpu: 'Máquina',
    first_them_pass: 'Jugador 2',
    play: 'Jugar',
    continue: 'Seguir partida',
    howto: 'Cómo se juega',
    menu: 'Menú',
    resume: 'Seguir',
    quit: 'Salir de la partida',
    new_match: 'Nueva partida',
    aria_close: 'Cerrar',
    aria_menu: 'Menú',
    aria_darts_left: 'Te quedan {n} dardos este turno',
    aria_board: 'Diana. Desliza el dardo hacia arriba para lanzar.',
    player2: 'Jugador 2',
    computer: 'Máquina',
    you: 'Tú',
    hint_flick: 'Desliza hacia arriba para lanzar',
    miss: '¡FALLO!',
    bust: '¡TE PASAS!',
    bust_sub: 'Por debajo de cero. Vuelves a {n}.',
    bull: '¡DIANA!',
    your_turn: 'Te toca',
    turn_of: '{name}',
    pass_to: 'Pasa el móvil a {name}',
    tap_ready: 'Toca cuando estés listo',
    win_you: '¡Has ganado!',
    win_name: '¡Gana {name}!',
    lose_you: 'Has perdido',
    result_line: 'Terminó en {n} turnos',
    play_again: 'Otra vez',
    say_hit: '{name} suma {pts}. Quedan {left}.',
    say_miss: '{name} ha fallado.',
    say_bust: '{name} se pasa. Vuelve a {n}.',
    say_turn: 'Lanza {name}.',
    say_win: 'Gana {name}.',
    help_goal: 'Empiezas en 301. Llega justo a cero.',
    help_cap: 'El anillo fino de fuera dobla. El de dentro triplica.',
    help_example: 'Triple 20 = 60 puntos',
    help_bull: 'Centro: 25. Diana: 50.',
    help_bust: 'Bajar de cero es pasarse: ese turno no cuenta.',
    help_flick: 'Desliza el dardo hacia arriba. Más rápido, más alto.',
    help_close: 'Entendido',
    lbl_double: 'x2',
    lbl_treble: 'x3',
  },
};
