// darts/js/strings.js - every user-visible string, { en, es } (js/i18n.js). English is the source
// of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).
export const STRINGS = {
  en: {
    title: 'Darts',
    tagline: '301. Hit exactly zero to win.',
    mode: 'Play',
    mode_cpu: 'Vs computer',
    mode_pass: 'Pass and play',
    difficulty: 'Computer',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    first: 'First throw',
    first_alt: 'Alternate',
    first_me: 'Me',
    first_them_cpu: 'Computer',
    first_them_pass: 'Player 2',
    play: 'Play',
    continue: 'Continue match',
    howto: 'How to play',
    menu: 'Menu',
    resume: 'Resume',
    quit: 'Quit match',
    new_match: 'New match',
    aria_close: 'Close',
    aria_menu: 'Menu',
    aria_darts_left: '{n} darts left this turn',
    aria_board: 'Dartboard. Flick the dart up to throw.',
    player2: 'Player 2',
    computer: 'Computer',
    you: 'You',
    hint_flick: 'Flick up to throw',
    miss: 'MISS!',
    bust: 'BUST!',
    bust_sub: 'Over zero. Back to {n}.',
    bull: 'BULLSEYE!',
    your_turn: 'Your turn',
    turn_of: '{name}',
    pass_to: 'Pass to {name}',
    tap_ready: 'Tap when ready',
    win_you: 'You win!',
    win_name: '{name} wins!',
    lose_you: 'You lose',
    result_line: 'Finished in {n} turns',
    play_again: 'Play again',
    say_hit: '{name} scored {pts}. {left} to go.',
    say_miss: '{name} missed.',
    say_bust: '{name} went bust. Back to {n}.',
    say_turn: '{name} to throw.',
    say_win: '{name} wins.',
    help_goal: 'Start at 301. Hit exactly zero to win.',
    help_cap: 'Outer thin ring doubles. Inner thin ring triples.',
    help_example: 'Treble 20 = 60 points',
    help_bull: 'Bull: 25. Bullseye: 50.',
    help_bust: 'Below zero is a bust: that turn does not count.',
    help_flick: 'Flick the dart up. Faster flicks land higher.',
    help_close: 'Got it',
    lbl_double: 'x2',
    lbl_treble: 'x3',
  },
  es: {
    title: 'Dardos',
    tagline: '301. Llega justo a cero para ganar.',
    mode: 'Jugar',
    mode_cpu: 'Contra la máquina',
    mode_pass: 'Pasar el móvil',
    difficulty: 'Máquina',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    first: 'Primer tiro',
    first_alt: 'Alternar',
    first_me: 'Yo',
    first_them_cpu: 'Máquina',
    first_them_pass: 'Jugador 2',
    play: 'Jugar',
    continue: 'Seguir partida',
    howto: 'Cómo se juega',
    menu: 'Menú',
    resume: 'Seguir',
    quit: 'Salir de la partida',
    new_match: 'Nueva partida',
    aria_close: 'Cerrar',
    aria_menu: 'Menú',
    aria_darts_left: 'Te quedan {n} dardos este turno',
    aria_board: 'Diana. Desliza el dardo hacia arriba para lanzar.',
    player2: 'Jugador 2',
    computer: 'Máquina',
    you: 'Tú',
    hint_flick: 'Desliza hacia arriba para lanzar',
    miss: '¡FALLO!',
    bust: '¡TE PASAS!',
    bust_sub: 'Por debajo de cero. Vuelves a {n}.',
    bull: '¡DIANA!',
    your_turn: 'Te toca',
    turn_of: '{name}',
    pass_to: 'Pasa el móvil a {name}',
    tap_ready: 'Toca cuando estés listo',
    win_you: '¡Has ganado!',
    win_name: '¡Gana {name}!',
    lose_you: 'Has perdido',
    result_line: 'Terminó en {n} turnos',
    play_again: 'Otra vez',
    say_hit: '{name} suma {pts}. Quedan {left}.',
    say_miss: '{name} ha fallado.',
    say_bust: '{name} se pasa. Vuelve a {n}.',
    say_turn: 'Lanza {name}.',
    say_win: 'Gana {name}.',
    help_goal: 'Empiezas en 301. Llega justo a cero.',
    help_cap: 'El anillo fino de fuera dobla. El de dentro triplica.',
    help_example: 'Triple 20 = 60 puntos',
    help_bull: 'Centro: 25. Diana: 50.',
    help_bust: 'Bajar de cero es pasarse: ese turno no cuenta.',
    help_flick: 'Desliza el dardo hacia arriba. Más rápido, más alto.',
    help_close: 'Entendido',
    lbl_double: 'x2',
    lbl_treble: 'x3',
  },
};
