// air-hockey/js/strings.js - every user-visible string, { en, es } (js/i18n.js makeT). English is
// the source of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).

export const STRINGS = {
  en: {
    title: 'Air Hockey',
    tagline: 'First to 7 wins',
    play: 'Play',
    you: 'You',
    cpu: 'CPU',
    pause: 'Pause',
    paused: 'Paused',
    resume: 'Resume',
    quit: 'Quit',
    goal: 'Goal!',
    you_win: 'You win!',
    cpu_wins: 'CPU wins',
    rematch: 'Rematch',
    back: 'Back',
    hint: 'Drag in your half to move your mallet',
    aria_close: 'Close',
    aria_canvas: 'Air hockey table. Drag in the bottom half to move your mallet.',
    aria_score: 'Score: you {a}, computer {b}',
    say_goal_you: 'You scored. {a} to {b}.',
    say_goal_cpu: 'The computer scored. {a} to {b}.',
  },
  es: {
    title: 'Hockey de aire',
    tagline: 'Gana quien llegue a 7',
    play: 'Jugar',
    you: 'Tú',
    cpu: 'CPU',
    pause: 'Pausa',
    paused: 'En pausa',
    resume: 'Seguir',
    quit: 'Salir',
    goal: '¡Gol!',
    you_win: '¡Has ganado!',
    cpu_wins: 'Gana la CPU',
    rematch: 'Revancha',
    back: 'Volver',
    hint: 'Arrastra en tu mitad para mover tu mazo',
    aria_close: 'Cerrar',
    aria_canvas: 'Mesa de hockey de aire. Arrastra en la mitad de abajo para mover tu mazo.',
    aria_score: 'Marcador: tú {a}, ordenador {b}',
    say_goal_you: 'Has marcado. {a} a {b}.',
    say_goal_cpu: 'Ha marcado el ordenador. {a} a {b}.',
  },
};
