// air-hockey/js/strings.js - every user-visible string, { en, es } (js/i18n.js makeT). English is
// the source of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).

export const STRINGS = {
  en: {
    title: 'Air Hockey',
    tagline: 'First to 7 wins',
    play: 'Play',
    you: 'You',
    cpu: 'CPU',
    pause: 'Pause',
    paused: 'Paused',
    resume: 'Resume',
    quit: 'Quit',
    goal: 'Goal!',
    you_win: 'You win!',
    cpu_wins: 'CPU wins',
    rematch: 'Rematch',
    back: 'Back',
    difficulty: 'Difficulty',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    rec_vs: 'Vs {diff}: {w} won, {l} lost',
    howto: 'How to play',
    help_goal: 'First to 7 goals wins.',
    help_caption: 'Drag anywhere in your half.',
    help_example: 'Fast swipe = hard shot',
    help_in: 'The puck must go all the way in.',
    help_serve: 'Whoever is scored on serves.',
    help_stuck: 'A puck left still 5 s goes to that side.',
    help_close: 'Got it',
    hl_half: 'Your half',
    hl_finger: 'Finger',
    hl_puck: 'Puck',
    hl_goal: 'Goal',
    aria_close: 'Close',
    aria_canvas: 'Air hockey table. Drag in the bottom half to move your mallet.',
    aria_score: 'Score: you {a}, computer {b}',
    say_goal_you: 'You scored. {a} to {b}.',
    say_goal_cpu: 'The computer scored. {a} to {b}.',
  },
  es: {
    title: 'Hockey de aire',
    tagline: 'Gana quien llegue a 7',
    play: 'Jugar',
    you: 'Tú',
    cpu: 'CPU',
    pause: 'Pausa',
    paused: 'En pausa',
    resume: 'Seguir',
    quit: 'Salir',
    goal: '¡Gol!',
    you_win: '¡Has ganado!',
    cpu_wins: 'Gana la CPU',
    rematch: 'Revancha',
    back: 'Volver',
    difficulty: 'Dificultad',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    rec_vs: 'Contra {diff}: {w} ganadas, {l} perdidas',
    howto: 'Cómo se juega',
    help_goal: 'Gana quien marque 7 goles.',
    help_caption: 'Arrastra en cualquier parte de tu mitad.',
    help_example: 'Golpe rápido = tiro fuerte',
    help_in: 'El disco tiene que entrar del todo.',
    help_serve: 'Saca quien recibe el gol.',
    help_stuck: 'Un disco quieto 5 s pasa a ese lado.',
    help_close: 'Entendido',
    hl_half: 'Tu mitad',
    hl_finger: 'Dedo',
    hl_puck: 'Disco',
    hl_goal: 'Portería',
    aria_close: 'Cerrar',
    aria_canvas: 'Mesa de hockey de aire. Arrastra en la mitad de abajo para mover tu mazo.',
    aria_score: 'Marcador: tú {a}, ordenador {b}',
    say_goal_you: 'Has marcado. {a} a {b}.',
    say_goal_cpu: 'Ha marcado el ordenador. {a} a {b}.',
  },
};
