// air-hockey/js/strings.js - every user-visible string, { en, es } (js/i18n.js makeT). English is
// the source of truth; a missing Spanish key falls back to English. No em dashes (root CLAUDE.md).

export const STRINGS = {
  en: {
    title: 'Air Hockey',
    tagline: 'First to 7 wins',
    play: 'Play',
    you: 'You',
    cpu: 'CPU',
    pause: 'Pause',
    paused: 'Paused',
    resume: 'Resume',
    quit: 'Quit',
    goal: 'Goal!',
    you_win: 'You win!',
    cpu_wins: 'CPU wins',
    rematch: 'Rematch',
    back: 'Back',
    difficulty: 'Difficulty',
    diff_easy: 'Easy',
    diff_medium: 'Medium',
    diff_hard: 'Hard',
    diff_expert: 'Expert',
    table: 'Table',
    table_is: 'Table: {name}',
    table_classic: 'Classic',
    table_arcade: 'Arcade',
    table_neon: 'Neon',
    table_ice: 'Ice',
    fastest_shot: 'Fastest shot: {v}',
    new_best_shot: 'New fastest shot!',
    shutout: 'Shutout!',
    streak: '{n} wins in a row',
    invite_player: 'Invite a player',
    invite_who: 'Who do you want to play?',
    send_invite: 'Send invite',
    loading_players: 'Loading players...',
    pick_player: 'Choose a player',
    pick_first: 'Choose a player first.',
    invite_none: 'No players found. Check your connection.',
    invite_text: 'Want to play Air Hockey? Tap Join, or use code {code}.',
    invite_sent: 'Invite sent to {name}. They get a notification.',
    invite_failed: 'Couldn\'t send the invite. Share the code instead.',
    rec_vs: 'Vs {diff}: {w} won, {l} lost',
    howto: 'How to play',
    help_goal: 'First to 7 goals wins.',
    help_caption: 'Drag anywhere in your half.',
    help_example: 'Fast swipe = hard shot',
    help_in: 'The puck must go all the way in.',
    help_serve: 'Whoever is scored on serves.',
    help_stuck: 'A puck left still 5 s goes to that side.',
    help_close: 'Got it',
    hl_half: 'Your half',
    hl_finger: 'Finger',
    hl_puck: 'Puck',
    hl_goal: 'Goal',
    play_online: 'Play online',
    create_game: 'Create a game',
    or_join: 'Or join a friend\'s game',
    join: 'Join',
    code_ph: 'CODE',
    code_label: 'Game code',
    share_code: 'Give your friend this code',
    waiting_join: 'Waiting for them to join...',
    cancel: 'Cancel',
    connecting: 'Connecting...',
    err_offline: 'Can\'t reach the server. Check your connection.',
    err_busy: 'Couldn\'t make a game. Try again.',
    err_code: 'Type the 4-letter code.',
    err_not_found: 'No game with that code.',
    err_full: 'That game already has two players.',
    err_version: 'Update the app on both phones, then try again.',
    wait_for: 'Waiting for {name}...',
    end_match: 'End match',
    left: '{name} left the match.',
    name_wins: '{name} wins',
    rematch_wait: 'Waiting for {name}...',
    rematch_asked: '{name} wants a rematch',
    rec_online: 'Online: {w} won, {l} lost',
    say_goal_opp: '{name} scored. {a} to {b}.',
    friend: 'Friend',
    aria_close: 'Close',
    aria_canvas: 'Air hockey table. Drag in the bottom half to move your mallet.',
    aria_score: 'Score: you {a}, computer {b}',
    say_goal_you: 'You scored. {a} to {b}.',
    say_goal_cpu: 'The computer scored. {a} to {b}.',
  },
  es: {
    title: 'Hockey de aire',
    tagline: 'Gana quien llegue a 7',
    play: 'Jugar',
    you: 'Tú',
    cpu: 'CPU',
    pause: 'Pausa',
    paused: 'En pausa',
    resume: 'Seguir',
    quit: 'Salir',
    goal: '¡Gol!',
    you_win: '¡Has ganado!',
    cpu_wins: 'Gana la CPU',
    rematch: 'Revancha',
    back: 'Volver',
    difficulty: 'Dificultad',
    diff_easy: 'Fácil',
    diff_medium: 'Normal',
    diff_hard: 'Difícil',
    diff_expert: 'Experto',
    table: 'Mesa',
    table_is: 'Mesa: {name}',
    table_classic: 'Clásica',
    table_arcade: 'Arcade',
    table_neon: 'Neón',
    table_ice: 'Hielo',
    fastest_shot: 'Tiro más rápido: {v}',
    new_best_shot: '¡Tu tiro más rápido!',
    shutout: '¡Portería a cero!',
    streak: '{n} victorias seguidas',
    invite_player: 'Invitar a un jugador',
    invite_who: '¿Con quién quieres jugar?',
    send_invite: 'Enviar invitación',
    loading_players: 'Cargando jugadores...',
    pick_player: 'Elige un jugador',
    pick_first: 'Elige un jugador primero.',
    invite_none: 'No hay jugadores. Revisa tu conexión.',
    invite_text: '¿Jugamos al hockey de aire? Pulsa Unirse, o usa el código {code}.',
    invite_sent: 'Invitación enviada a {name}. Le llegará un aviso.',
    invite_failed: 'No se pudo enviar la invitación. Comparte el código.',
    rec_vs: 'Contra {diff}: {w} ganadas, {l} perdidas',
    howto: 'Cómo se juega',
    help_goal: 'Gana quien marque 7 goles.',
    help_caption: 'Arrastra en cualquier parte de tu mitad.',
    help_example: 'Golpe rápido = tiro fuerte',
    help_in: 'El disco tiene que entrar del todo.',
    help_serve: 'Saca quien recibe el gol.',
    help_stuck: 'Un disco quieto 5 s pasa a ese lado.',
    help_close: 'Entendido',
    hl_half: 'Tu mitad',
    hl_finger: 'Dedo',
    hl_puck: 'Disco',
    hl_goal: 'Portería',
    play_online: 'Jugar en línea',
    create_game: 'Crear partida',
    or_join: 'O únete a la partida de un amigo',
    join: 'Unirse',
    code_ph: 'CÓDIGO',
    code_label: 'Código de la partida',
    share_code: 'Dale este código a tu amigo',
    waiting_join: 'Esperando a que se una...',
    cancel: 'Cancelar',
    connecting: 'Conectando...',
    err_offline: 'No hay conexión con el servidor. Revisa tu conexión.',
    err_busy: 'No se pudo crear la partida. Inténtalo otra vez.',
    err_code: 'Escribe el código de 4 letras.',
    err_not_found: 'No hay ninguna partida con ese código.',
    err_full: 'Esa partida ya tiene dos jugadores.',
    err_version: 'Actualiza la app en los dos móviles y vuelve a intentarlo.',
    wait_for: 'Esperando a {name}...',
    end_match: 'Terminar partida',
    left: '{name} ha dejado la partida.',
    name_wins: 'Gana {name}',
    rematch_wait: 'Esperando a {name}...',
    rematch_asked: '{name} quiere la revancha',
    rec_online: 'En línea: {w} ganadas, {l} perdidas',
    say_goal_opp: 'Ha marcado {name}. {a} a {b}.',
    friend: 'Amigo',
    aria_close: 'Cerrar',
    aria_canvas: 'Mesa de hockey de aire. Arrastra en la mitad de abajo para mover tu mazo.',
    aria_score: 'Marcador: tú {a}, ordenador {b}',
    say_goal_you: 'Has marcado. {a} a {b}.',
    say_goal_cpu: 'Ha marcado el ordenador. {a} a {b}.',
  },
};
