// sudoku/js/generator.js - board generation. Pure: no DOM, no timers, no ambient randomness.
//
// BUILD THE SOLUTION FIRST, THEN DIG. A full, valid 9x9 grid is generated by randomised
// backtracking, then cells are removed one at a time in random order, checking after every
// removal that the puzzle STILL has exactly one solution (js/solver.js's `countSolutions`,
// capped at 2 so a non-unique puzzle is detected quickly rather than fully explored). A cell
// whose removal breaks uniqueness is put back. This guarantees a shipped puzzle always has
// exactly one solution - "generate and hope" is how a puzzle game ships an unsolvable (or
// multi-solution) level to a real player.
//
// GRADED BY TECHNIQUE, NOT BY GIVENS COUNT ALONE. `gradeGrid` (solver.js) reports the hardest
// human technique needed and whether the puzzle even finishes without backtracking; the givens
// count is a secondary target for FEEL (a tier's puzzles all sit in a similar visual density),
// not the difficulty signal itself.
import { countSolutions, gradeGrid, PEERS } from './solver.js';

const N = 81;

export const TIER_ORDER = ['easy', 'medium', 'hard', 'expert'];

/** [low, high] givens target per tier - secondary to the technique grade, see header. */
const TIER_GIVENS = {
  easy: [38, 45],
  medium: [32, 37],
  hard: [27, 31],
  expert: [22, 26],
};

export function tierGivensRange(tier) { return TIER_GIVENS[tier] || TIER_GIVENS.easy; }

/** Deterministic PRNG so a seed reproduces a board exactly (mulberry32-style, matches the
 *  shape used elsewhere in this repo, e.g. pipes/js/generator.js's `rng`). */
export function rng(seed) {
  let s = (seed >>> 0) || 1;
  return () => {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5; s >>>= 0;
    return s / 4294967296;
  };
}

function shuffle(arr, rnd) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    const t = arr[i]; arr[i] = arr[j]; arr[j] = t;
  }
  return arr;
}

/**
 * Build one full, valid 9x9 grid by randomised backtracking: fill cells in order, trying digits
 * in a SHUFFLED order at each cell, backtracking on a dead end. This is the standard trick that
 * makes full-grid generation fast (a few milliseconds) despite naive ordering - the vast majority
 * of random fills complete with zero or very few backtracks.
 */
export function fillGrid(rnd) {
  const grid = new Uint8Array(N);
  function candidatesAt(i) {
    let mask = 511;
    for (const j of PEERS[i]) if (grid[j]) mask &= ~(1 << (grid[j] - 1));
    return mask;
  }
  function place(i) {
    if (i === N) return true;
    const mask = candidatesAt(i);
    const digits = [];
    for (let d = 1; d <= 9; d++) if (mask & (1 << (d - 1))) digits.push(d);
    shuffle(digits, rnd);
    for (const d of digits) {
      grid[i] = d;
      if (place(i + 1)) return true;
      grid[i] = 0;
    }
    return false;
  }
  place(0);
  return grid;
}

/**
 * Dig a full grid down toward `target` givens, checking uniqueness after every removal.
 * Cells are visited in a random order; a removal that breaks uniqueness is undone immediately.
 * Stops at `target` givens or once no more cells can be safely removed (whichever comes first).
 */
export function dig(solution, target, rnd) {
  const puzzle = Uint8Array.from(solution);
  const order = shuffle(Array.from({ length: N }, (_, i) => i), rnd);
  let givens = N;
  for (const i of order) {
    if (givens <= target) break;
    const saved = puzzle[i];
    puzzle[i] = 0;
    if (countSolutions(puzzle, 2) !== 1) { puzzle[i] = saved; continue; }
    givens--;
  }
  return puzzle;
}

export function countGivens(puzzle) {
  let n = 0;
  for (let i = 0; i < N; i++) if (puzzle[i]) n++;
  return n;
}

/** grade -> tier name, from gradeGrid()'s {solved, maxTechnique} plus the givens count (the
 *  givens split between hard/expert only matters once the technique solver has already stalled -
 *  see the table in the handoff/CLAUDE.md). */
function tierOfGrade(solvedInfo, givens) {
  if (solvedInfo.solved) return solvedInfo.maxTechnique <= 2 ? 'easy' : 'medium';
  return givens >= 27 ? 'hard' : 'expert';
}

const MAX_ATTEMPTS = 40;

/**
 * MEDIUM is graded, not just dug-and-checked: measured, a puzzle that genuinely needs a
 * technique past naked/hidden singles (pointing pair / box-line, naked/hidden pair) but does NOT
 * stall is RARE under plain random digging - about 1 in 150 attempts at a "medium" givens count,
 * because these techniques rarely matter unless the digging is pushed further than an
 * unconstrained random dig usually goes. So this digs cell-by-cell, accepting a removal only
 * when the puzzle STAYS solvable by the technique set (never stalls), and stops the moment the
 * puzzle first needs technique 3 or 4 - the least-dug (highest-givens) puzzle that qualifies as
 * medium along this particular random order. If the whole board digs out with singles always
 * sufficing, no medium puzzle was found on this order and the caller tries a new seed.
 */
function digForMedium(solution, rnd) {
  const puzzle = Uint8Array.from(solution);
  const order = shuffleIdx(rnd);
  for (const i of order) {
    const saved = puzzle[i];
    puzzle[i] = 0;
    if (countSolutions(puzzle, 2) !== 1) { puzzle[i] = saved; continue; }
    const graded = gradeGrid(puzzle);
    if (!graded.solved) { puzzle[i] = saved; continue; }
    if (graded.maxTechnique >= 3) return puzzle;
  }
  return null; // this order never required a technique past singles
}

function shuffleIdx(rnd) { return shuffle(Array.from({ length: N }, (_, i) => i), rnd); }

/**
 * Build one puzzle for `tier`, deterministic on (tier, seed). Regenerates (advancing the seed)
 * until the technique grade matches the requested tier, capped at MAX_ATTEMPTS; on exhaustion it
 * ships the closest-graded attempt and logs loudly rather than hang - a phone must never spin
 * forever on this.
 *
 * Returns { tier, seed, puzzle: Uint8Array, solution: Uint8Array, givens, grade, attempts }.
 */
export function generate(tier, seed) {
  const t = TIER_ORDER.includes(tier) ? tier : 'easy';
  const [lo, hi] = tierGivensRange(t);
  let s = (seed === undefined ? Math.floor(Math.random() * 0xffffffff) : seed) >>> 0;
  let fallback = null;
  const rankOf = (tier2) => TIER_ORDER.indexOf(tier2);

  if (t === 'medium') {
    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      const rnd = rng(s);
      const solution = fillGrid(rnd);
      const puzzle = digForMedium(solution, rnd);
      if (puzzle) {
        const givens = countGivens(puzzle);
        return { tier: t, seed: s, puzzle, solution, givens, grade: 'medium', attempts: attempt };
      }
      // This order never needed a technique past singles - still a valid, honestly-graded easy
      // puzzle, kept as the fallback if every attempt below misses.
      if (!fallback) {
        const easyPuzzle = dig(solution, lo, rnd);
        fallback = { tier: t, seed: s, puzzle: easyPuzzle, solution, givens: countGivens(easyPuzzle), grade: 'easy', attempts: attempt };
      }
      s = (s + 0x9e3779b9) >>> 0;
    }
    console.error(`[sudoku] generation exhausted ${MAX_ATTEMPTS} attempts for tier "medium"; ` +
      `shipping closest grade "${fallback.grade}" (${fallback.givens} givens)`);
    return fallback;
  }

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const rnd = rng(s);
    const solution = fillGrid(rnd);
    const target = lo + Math.floor(rnd() * (hi - lo + 1));
    const puzzle = dig(solution, target, rnd);
    const givens = countGivens(puzzle);
    const graded = gradeGrid(puzzle);
    const grade = tierOfGrade(graded, givens);
    const result = { tier: t, seed: s, puzzle, solution, givens, grade, attempts: attempt };
    if (grade === t) return result;
    if (!fallback || Math.abs(rankOf(grade) - rankOf(t)) < Math.abs(rankOf(fallback.grade) - rankOf(t))) {
      fallback = result;
    }
    s = (s + 0x9e3779b9) >>> 0;
  }
  console.error(`[sudoku] generation exhausted ${MAX_ATTEMPTS} attempts for tier "${t}"; ` +
    `shipping closest grade "${fallback.grade}" (${fallback.givens} givens)`);
  return fallback;
}

export default { TIER_ORDER, tierGivensRange, rng, fillGrid, dig, countGivens, generate };
