// sudoku/js/strings.js - the EN/ES dictionary. English is the source of truth; a missing Spanish
// key falls back to English (js/i18n.js's makeT), so partial translation never breaks. No em
// dashes anywhere (root CLAUDE.md's copy rule).
const STRINGS = {
  en: {
    title: 'Sudoku',
    tagline: 'Classic 9x9. Fill every row, column and box with 1 to 9.',
    setup_difficulty: 'Difficulty',
    tier_easy: 'Easy',
    tier_medium: 'Medium',
    tier_hard: 'Hard',
    tier_expert: 'Expert',
    start: 'Start',
    resume: 'Resume',
    howto: 'How to play',
    howto_close: 'Got it',
    howto_caption: 'A small "5" beside a big digit is a pencil mark (a note), not an answer.',
    howto_label_answer: 'Answer',
    howto_label_notes: 'Notes',
    howto_diagram_aria: 'An answer cell with one large digit, beside a notes cell with small pencil-mark digits',
    new_puzzle: 'New puzzle',
    new_puzzle_confirm: 'Start a new puzzle? Your progress on this one will be lost.',
    cancel: 'Cancel',
    change_difficulty: 'Change difficulty',
    undo: 'Undo',
    undo_aria: 'Undo',
    erase: 'Erase',
    erase_aria: 'Erase',
    notes: 'Notes',
    notes_aria: 'Toggle notes mode',
    notes_on: 'Notes on',
    notes_off: 'Notes off',
    hint: 'Hint',
    hint_aria: 'Hint',
    timer_aria: 'Time elapsed',
    mistakes_label: 'Mistakes',
    mistakes_aria: 'Mistakes',
    hints_label: 'Hints',
    back_aria: 'Back to setup',
    close_aria: 'Close',
    win_title: 'Solved!',
    win_detail_named: '{name}, {time}, {mistakes} mistakes, {hints} hints',
    win_detail: '{time}, {mistakes} mistakes, {hints} hints',
    next_puzzle: 'Next puzzle',
    conflict_aria: 'conflict',
    given_aria: 'given',
  },
  es: {
    title: 'Sudoku',
    tagline: 'El clasico 9x9. Rellena cada fila, columna y caja con 1 al 9.',
    setup_difficulty: 'Dificultad',
    tier_easy: 'Facil',
    tier_medium: 'Normal',
    tier_hard: 'Dificil',
    tier_expert: 'Experto',
    start: 'Empezar',
    resume: 'Continuar',
    howto: 'Como jugar',
    howto_close: 'Entendido',
    howto_caption: 'Un "5" pequeno junto a un digito grande es una nota a lapiz, no una respuesta.',
    howto_label_answer: 'Respuesta',
    howto_label_notes: 'Notas',
    howto_diagram_aria: 'Una casilla de respuesta con un digito grande, junto a una casilla de notas con digitos pequenos a lapiz',
    new_puzzle: 'Nuevo tablero',
    new_puzzle_confirm: 'Empezar un tablero nuevo? Perderas el progreso de este.',
    cancel: 'Cancelar',
    change_difficulty: 'Cambiar dificultad',
    undo: 'Deshacer',
    undo_aria: 'Deshacer',
    erase: 'Borrar',
    erase_aria: 'Borrar',
    notes: 'Notas',
    notes_aria: 'Alternar modo notas',
    notes_on: 'Notas activas',
    notes_off: 'Notas desactivadas',
    hint: 'Pista',
    hint_aria: 'Pista',
    timer_aria: 'Tiempo transcurrido',
    mistakes_label: 'Errores',
    mistakes_aria: 'Errores',
    hints_label: 'Pistas',
    back_aria: 'Volver a la configuracion',
    close_aria: 'Cerrar',
    win_title: 'Resuelto!',
    win_detail_named: '{name}, {time}, {mistakes} errores, {hints} pistas',
    win_detail: '{time}, {mistakes} errores, {hints} pistas',
    next_puzzle: 'Siguiente tablero',
    conflict_aria: 'conflicto',
    given_aria: 'dado',
  },
};

export default STRINGS;
export { STRINGS };
