// pinball/js/strings.js - the EN/ES dictionary (js/i18n.js, root CLAUDE.md "Adding a game" item 9).
// English is the source of truth; a missing Spanish key falls back to English, so partial
// translation can never break a screen. Call t() at RENDER time, never at module scope.
//
// Pinball vocabulary is a real, borrowed vocabulary in Spanish exactly as card-suit names are in
// English (root CLAUDE.md's standing rule): "flipper", "bumper", "jackpot", "tilt" and "multiball"
// are what Spanish players say, so they stay. Everything that has a real Spanish word gets it.

export const STRINGS = {
  en: {
    title: 'Pinball',

    // setup
    setup_new: 'New game',
    setup_table: 'Table',
    diff_easy: 'Casual',
    diff_medium: 'Standard',
    diff_hard: 'Tournament',
    diff_easy_note: '5 balls, 12 second ball save, outlanes closed by a save post.',
    diff_medium_note: '3 balls, 8 second ball save, outlanes open.',
    diff_hard_note: '3 balls, 3 second ball save, a steeper, faster table.',
    play: 'Play',
    howto: 'How to play',
    your_best: 'Your best',
    no_best: 'No games yet',

    // hud
    hud_ball: 'Ball',
    hud_bonus: 'Bonus',
    hud_save: 'Ball save',
    hud_locks: 'Locks',
    hud_pull: 'Pull and release to launch',
    btn_nudge: 'Nudge',
    btn_launch: 'Launch',
    btn_pause: 'Pause',
    btn_left_flipper: 'Left flipper',
    btn_right_flipper: 'Right flipper',
    aria_table: 'Pinball table',

    // pause
    paused: 'Paused',
    resume: 'Resume',
    quit: 'End game',
    close: 'Close',

    // in-game messages
    msg_ball_n: 'Ball {n}',
    msg_ball_saved: 'Ball saved',
    msg_shoot_again: 'Shoot again',
    msg_tilt: 'TILT',
    msg_tilt_warn: 'Careful',
    msg_bank_done: 'Scoop lit for a mission',
    msg_bank_again: 'Bank cleared',
    msg_lock_lit: 'Lock is lit',
    msg_lock_n: 'Ball {n} locked',
    msg_multiball: 'MULTIBALL',
    msg_wizard: 'WIZARD MULTIBALL',
    msg_jackpot: 'Jackpot {n}',
    msg_super_lit: 'Super jackpot lit',
    msg_super: 'SUPER JACKPOT',
    msg_mission_done: 'Mission complete, {n}',
    msg_mission_fail: 'Mission over',
    msg_bonus_x: 'Bonus {n}x',
    msg_extra_ball: 'Extra ball',

    // missions
    mission_bumper: 'Bumper Rush',
    mission_spin: 'Spinner Mania',
    mission_ramp: 'Ramp Frenzy',
    mission_target: 'Target Storm',
    task_bumper: 'Hit the pop bumpers',
    task_spin: 'Rip the spinner',
    task_ramp: 'Shoot the ramp',
    task_target: 'Drop the targets',

    // standing objective, shown on the dot-matrix line when nothing else is
    hint_bank: 'Drop the 4 targets',
    hint_scoop: 'Scoop lit: start a mission',
    hint_ramp: 'Ramps light the lock',
    hint_lock: 'Scoop to lock a ball',
    hint_jackpot: 'Ramp for the jackpot',
    hint_super: 'Scoop for the super jackpot',
    hint_locks: '{n} of 3 locked',

    // score labels
    lbl_ramp: 'Ramp',
    lbl_jackpot: 'Jackpot',
    lbl_super: 'Super',
    lbl_orbit: 'Orbit',
    lbl_spinner: 'Spinner',
    lbl_bank: 'Bank',
    lbl_scoop: 'Scoop',
    lbl_lock: 'Lock',
    lbl_lanes: 'H U B',
    lbl_mission: 'Mission',
    lbl_multiball: 'Multiball',

    // game over
    over_h: 'Game over',
    over_final: 'Final score',
    over_best: 'New personal best',
    over_again: 'Play again',
    over_stats: 'This game',
    over_missions: 'Missions',
    over_multiballs: 'Multiballs',
    over_jackpots: 'Jackpots',
    over_bestball: 'Best ball',

    // How to play. Follows the repo-wide pattern (tic-tac-toe/CLAUDE.md, "How-to-play screens"):
    // one bold sentence, ONE diagram carrying the non-obvious part, a caption, an X = Y example,
    // then any remaining rules as short plain sentences. Everything a person already knows about
    // pinball is deliberately absent. The non-obvious part here is WHERE THIS TABLE'S SHOTS ARE,
    // which is a picture, not a paragraph.
    howto_h: 'How to play',
    help_lead: 'Keep the ball alive. Shoot the lit shots.',
    help_s1: 'Ramp',
    help_s2: 'Scoop',
    help_s3: 'Targets',
    help_s4: 'Orbit',
    help_caption: 'Four shots. Lit ones are worth the most.',
    help_ex1: '4 targets = the scoop starts a mission',
    help_ex2: '5 ramps = lock, 3 locks = multiball',
    help_rule1: 'Tap the left half of the table for the left flipper, the right half for the right.',
    help_rule2: 'Nudge can save a ball. Three nudges too fast and the table tilts.',
    help_diagram_aria: 'Playfield diagram: the ramp up the middle, the scoop up the right, the drop targets on the upper left, and the orbit round the top.',
  },

  es: {
    title: 'Pinball',

    setup_new: 'Partida nueva',
    setup_table: 'Mesa',
    diff_easy: 'Tranquila',
    diff_medium: 'Normal',
    diff_hard: 'Torneo',
    diff_easy_note: '5 bolas, salvabolas de 12 segundos, calles laterales cerradas con un poste.',
    diff_medium_note: '3 bolas, salvabolas de 8 segundos, calles laterales abiertas.',
    diff_hard_note: '3 bolas, salvabolas de 3 segundos, mesa más inclinada y rápida.',
    play: 'Jugar',
    howto: 'Cómo se juega',
    your_best: 'Tu mejor marca',
    no_best: 'Aún no has jugado',

    hud_ball: 'Bola',
    hud_bonus: 'Bonus',
    hud_save: 'Salvabolas',
    hud_locks: 'Bolas guardadas',
    hud_pull: 'Mantén pulsado y suelta para lanzar',
    btn_nudge: 'Empujar',
    btn_launch: 'Lanzar',
    btn_pause: 'Pausa',
    btn_left_flipper: 'Flipper izquierdo',
    btn_right_flipper: 'Flipper derecho',
    aria_table: 'Mesa de pinball',

    paused: 'En pausa',
    resume: 'Continuar',
    quit: 'Terminar partida',
    close: 'Cerrar',

    msg_ball_n: 'Bola {n}',
    msg_ball_saved: 'Bola salvada',
    msg_shoot_again: 'Lanza otra vez',
    msg_tilt: 'TILT',
    msg_tilt_warn: 'Cuidado',
    msg_bank_done: 'Hoyo listo para una misión',
    msg_bank_again: 'Dianas tumbadas',
    msg_lock_lit: 'Bloqueo encendido',
    msg_lock_n: 'Bola {n} guardada',
    msg_multiball: 'MULTIBOLA',
    msg_wizard: 'MULTIBOLA FINAL',
    msg_jackpot: 'Jackpot {n}',
    msg_super_lit: 'Súper jackpot listo',
    msg_super: 'SÚPER JACKPOT',
    msg_mission_done: 'Misión cumplida, {n}',
    msg_mission_fail: 'Misión terminada',
    msg_bonus_x: 'Bonus {n}x',
    msg_extra_ball: 'Bola extra',

    hint_bank: 'Tumba las 4 dianas',
    hint_scoop: 'Hoyo listo: empieza una misión',
    hint_ramp: 'Las rampas encienden el bloqueo',
    hint_lock: 'Hoyo para guardar una bola',
    hint_jackpot: 'Rampa para el jackpot',
    hint_super: 'Hoyo para el súper jackpot',
    hint_locks: '{n} de 3 guardadas',

    mission_bumper: 'Fiebre de Bumpers',
    mission_spin: 'Locura del Spinner',
    mission_ramp: 'Rampa sin Freno',
    mission_target: 'Tormenta de Dianas',
    task_bumper: 'Golpea los bumpers',
    task_spin: 'Haz girar el spinner',
    task_ramp: 'Encesta la rampa',
    task_target: 'Tumba las dianas',

    lbl_ramp: 'Rampa',
    lbl_jackpot: 'Jackpot',
    lbl_super: 'Súper',
    lbl_orbit: 'Órbita',
    lbl_spinner: 'Spinner',
    lbl_bank: 'Dianas',
    lbl_scoop: 'Hoyo',
    lbl_lock: 'Bloqueo',
    lbl_lanes: 'H U B',
    lbl_mission: 'Misión',
    lbl_multiball: 'Multibola',

    over_h: 'Fin de la partida',
    over_final: 'Puntuación final',
    over_best: 'Nueva mejor marca',
    over_again: 'Jugar otra vez',
    over_stats: 'Esta partida',
    over_missions: 'Misiones',
    over_multiballs: 'Multibolas',
    over_jackpots: 'Jackpots',
    over_bestball: 'Mejor bola',

    howto_h: 'Cómo se juega',
    help_lead: 'Mantén la bola viva. Encesta los tiros encendidos.',
    help_s1: 'Rampa',
    help_s2: 'Hoyo',
    help_s3: 'Dianas',
    help_s4: 'Órbita',
    help_caption: 'Cuatro tiros. Los encendidos valen más.',
    help_ex1: '4 dianas = el hoyo empieza una misión',
    help_ex2: '5 rampas = bloqueo, 3 bloqueos = multibola',
    help_rule1: 'Toca la mitad izquierda de la mesa para el flipper izquierdo, y la derecha para el derecho.',
    help_rule2: 'Empujar puede salvar una bola. Tres empujones seguidos y la mesa hace tilt.',
    help_diagram_aria: 'Esquema de la mesa: la rampa por el centro, el hoyo por la derecha, las dianas arriba a la izquierda y la órbita por arriba.',
  },
};

export default STRINGS;
