// pinball/js/strings.js - the EN/ES dictionary (js/i18n.js, root CLAUDE.md "Adding a game" item 9).
// English is the source of truth; a missing Spanish key falls back to English, so partial
// translation can never break a screen. Call t() at RENDER time, never at module scope.
//
// Pinball vocabulary is a real, borrowed vocabulary in Spanish exactly as card-suit names are in
// English (root CLAUDE.md's standing rule): "flipper", "bumper", "jackpot", "tilt" and "multiball"
// are what Spanish players say, so they stay. Everything that has a real Spanish word gets it.

export const STRINGS = {
  en: {
    title: 'Pinball',

    // setup
    setup_new: 'New game',
    setup_table: 'Table',
    setup_sound: 'Sound',
    diff_easy: 'Casual',
    diff_medium: 'Standard',
    diff_hard: 'Tournament',
    diff_easy_note: '5 balls, 12 second ball save, outlanes closed by a save post.',
    diff_medium_note: '3 balls, 8 second ball save, outlanes open.',
    diff_hard_note: '3 balls, 3 second ball save, a steeper, faster table.',
    sound_on: 'On',
    sound_off: 'Off',
    play: 'Play',
    howto: 'How to play',
    your_best: 'Your best',
    no_best: 'No games yet',

    // hud
    hud_ball: 'Ball',
    hud_bonus: 'Bonus',
    hud_save: 'Ball save',
    hud_locks: 'Locks',
    hud_pull: 'Pull and release to launch',
    btn_nudge: 'Nudge',
    btn_launch: 'Launch',
    btn_pause: 'Pause',
    btn_left_flipper: 'Left flipper',
    btn_right_flipper: 'Right flipper',
    aria_table: 'Pinball table',

    // pause
    paused: 'Paused',
    resume: 'Resume',
    quit: 'End game',
    close: 'Close',

    // in-game messages
    msg_ball_n: 'Ball {n}',
    msg_ball_saved: 'Ball saved',
    msg_shoot_again: 'Shoot again',
    msg_tilt: 'TILT',
    msg_tilt_warn: 'Careful',
    msg_bank_done: 'Scoop lit for a mission',
    msg_bank_again: 'Bank cleared',
    msg_lock_lit: 'Lock is lit',
    msg_lock_n: 'Ball {n} locked',
    msg_multiball: 'MULTIBALL',
    msg_wizard: 'WIZARD MULTIBALL',
    msg_jackpot: 'Jackpot {n}',
    msg_super_lit: 'Super jackpot lit',
    msg_super: 'SUPER JACKPOT',
    msg_mission_done: 'Mission complete, {n}',
    msg_mission_fail: 'Mission over',
    msg_bonus_x: 'Bonus {n}x',
    msg_extra_ball: 'Extra ball',

    // missions
    mission_bumper: 'Bumper Rush',
    mission_spin: 'Spinner Mania',
    mission_ramp: 'Ramp Frenzy',
    mission_target: 'Target Storm',
    task_bumper: 'Hit the pop bumpers',
    task_spin: 'Rip the spinner',
    task_ramp: 'Shoot the ramp',
    task_target: 'Drop the targets',

    // standing objective, shown on the dot-matrix line when nothing else is
    hint_bank: 'Drop the 4 targets',
    hint_scoop: 'Scoop lit: start a mission',
    hint_ramp: 'Ramps light the lock',
    hint_lock: 'Scoop to lock a ball',
    hint_jackpot: 'Ramp for the jackpot',
    hint_super: 'Scoop for the super jackpot',
    hint_locks: '{n} of 3 locked',

    // score labels
    lbl_ramp: 'Ramp',
    lbl_jackpot: 'Jackpot',
    lbl_super: 'Super',
    lbl_orbit: 'Orbit',
    lbl_spinner: 'Spinner',
    lbl_bank: 'Bank',
    lbl_scoop: 'Scoop',
    lbl_lock: 'Lock',
    lbl_lanes: 'H U B',
    lbl_mission: 'Mission',
    lbl_multiball: 'Multiball',

    // game over
    over_h: 'Game over',
    over_final: 'Final score',
    over_best: 'New personal best',
    over_again: 'Play again',
    over_stats: 'This game',
    over_missions: 'Missions',
    over_multiballs: 'Multiballs',
    over_jackpots: 'Jackpots',
    over_bestball: 'Best ball',

    // how to play
    howto_h: 'How to play',
    howto_launch_h: 'Launch',
    howto_launch_b: 'Hold the launch button to pull the plunger back, then let go. A short pull dribbles back down the lane and you can just pull again. A long pull sends the ball all the way round the top orbit.',
    howto_flip_h: 'Flippers',
    howto_flip_b: 'Tap anywhere on the left half of the table for the left flipper, the right half for the right one. On a keyboard, use the left and right arrows or the shift keys.',
    howto_nudge_h: 'Nudge',
    howto_nudge_b: 'Nudge shoves the whole table and can rescue a ball heading for an outlane. Three nudges too close together and the table tilts: the flippers die, the bonus is wiped, and the ball is lost.',
    howto_shots_h: 'The shots',
    howto_shots_b: 'Ramp up the middle. Scoop up the right wall. Drop target bank on the upper left. The left orbit runs past the spinner, round the top and back down. H, U and B lanes across the top raise your end of ball bonus.',
    howto_modes_h: 'Missions and multiball',
    howto_modes_b: 'Clear all four drop targets to light the scoop, then shoot the scoop to start a timed mission. Five ramps light the lock; three locks start multiball, where the ramp is the jackpot and the scoop is the super jackpot. Finish all four missions for wizard multiball at triple scoring.',
  },

  es: {
    title: 'Pinball',

    setup_new: 'Partida nueva',
    setup_table: 'Mesa',
    setup_sound: 'Sonido',
    diff_easy: 'Tranquila',
    diff_medium: 'Normal',
    diff_hard: 'Torneo',
    diff_easy_note: '5 bolas, salvabolas de 12 segundos, calles laterales cerradas con un poste.',
    diff_medium_note: '3 bolas, salvabolas de 8 segundos, calles laterales abiertas.',
    diff_hard_note: '3 bolas, salvabolas de 3 segundos, mesa más inclinada y rápida.',
    sound_on: 'Sí',
    sound_off: 'No',
    play: 'Jugar',
    howto: 'Cómo se juega',
    your_best: 'Tu mejor marca',
    no_best: 'Aún no has jugado',

    hud_ball: 'Bola',
    hud_bonus: 'Bonus',
    hud_save: 'Salvabolas',
    hud_locks: 'Bolas guardadas',
    hud_pull: 'Mantén pulsado y suelta para lanzar',
    btn_nudge: 'Empujar',
    btn_launch: 'Lanzar',
    btn_pause: 'Pausa',
    btn_left_flipper: 'Flipper izquierdo',
    btn_right_flipper: 'Flipper derecho',
    aria_table: 'Mesa de pinball',

    paused: 'En pausa',
    resume: 'Continuar',
    quit: 'Terminar partida',
    close: 'Cerrar',

    msg_ball_n: 'Bola {n}',
    msg_ball_saved: 'Bola salvada',
    msg_shoot_again: 'Lanza otra vez',
    msg_tilt: 'TILT',
    msg_tilt_warn: 'Cuidado',
    msg_bank_done: 'Hoyo listo para una misión',
    msg_bank_again: 'Dianas tumbadas',
    msg_lock_lit: 'Bloqueo encendido',
    msg_lock_n: 'Bola {n} guardada',
    msg_multiball: 'MULTIBOLA',
    msg_wizard: 'MULTIBOLA FINAL',
    msg_jackpot: 'Jackpot {n}',
    msg_super_lit: 'Súper jackpot listo',
    msg_super: 'SÚPER JACKPOT',
    msg_mission_done: 'Misión cumplida, {n}',
    msg_mission_fail: 'Misión terminada',
    msg_bonus_x: 'Bonus {n}x',
    msg_extra_ball: 'Bola extra',

    hint_bank: 'Tumba las 4 dianas',
    hint_scoop: 'Hoyo listo: empieza una misión',
    hint_ramp: 'Las rampas encienden el bloqueo',
    hint_lock: 'Hoyo para guardar una bola',
    hint_jackpot: 'Rampa para el jackpot',
    hint_super: 'Hoyo para el súper jackpot',
    hint_locks: '{n} de 3 guardadas',

    mission_bumper: 'Fiebre de Bumpers',
    mission_spin: 'Locura del Spinner',
    mission_ramp: 'Rampa sin Freno',
    mission_target: 'Tormenta de Dianas',
    task_bumper: 'Golpea los bumpers',
    task_spin: 'Haz girar el spinner',
    task_ramp: 'Encesta la rampa',
    task_target: 'Tumba las dianas',

    lbl_ramp: 'Rampa',
    lbl_jackpot: 'Jackpot',
    lbl_super: 'Súper',
    lbl_orbit: 'Órbita',
    lbl_spinner: 'Spinner',
    lbl_bank: 'Dianas',
    lbl_scoop: 'Hoyo',
    lbl_lock: 'Bloqueo',
    lbl_lanes: 'H U B',
    lbl_mission: 'Misión',
    lbl_multiball: 'Multibola',

    over_h: 'Fin de la partida',
    over_final: 'Puntuación final',
    over_best: 'Nueva mejor marca',
    over_again: 'Jugar otra vez',
    over_stats: 'Esta partida',
    over_missions: 'Misiones',
    over_multiballs: 'Multibolas',
    over_jackpots: 'Jackpots',
    over_bestball: 'Mejor bola',

    howto_h: 'Cómo se juega',
    howto_launch_h: 'Lanzamiento',
    howto_launch_b: 'Mantén pulsado el botón de lanzar para tensar el muelle y suéltalo. Un tirón corto deja la bola caer otra vez por el carril y puedes volver a lanzar. Un tirón largo la manda por toda la órbita superior.',
    howto_flip_h: 'Flippers',
    howto_flip_b: 'Toca cualquier punto de la mitad izquierda de la mesa para el flipper izquierdo, y la mitad derecha para el derecho. Con teclado, usa las flechas izquierda y derecha o las teclas mayúsculas.',
    howto_nudge_h: 'Empujar',
    howto_nudge_b: 'Empujar mueve toda la mesa y puede salvar una bola camino de una calle lateral. Tres empujones demasiado seguidos y la mesa hace tilt: los flippers se apagan, el bonus se borra y pierdes la bola.',
    howto_shots_h: 'Los tiros',
    howto_shots_b: 'Rampa por el centro. Hoyo subiendo por la pared derecha. Dianas abatibles arriba a la izquierda. La órbita izquierda pasa por el spinner, da la vuelta por arriba y baja de nuevo. Las calles H, U y B de arriba suben tu bonus de final de bola.',
    howto_modes_h: 'Misiones y multibola',
    howto_modes_b: 'Tumba las cuatro dianas para encender el hoyo y luego encesta en el hoyo para empezar una misión con tiempo. Cinco rampas encienden el bloqueo; tres bloqueos arrancan la multibola, donde la rampa es el jackpot y el hoyo el súper jackpot. Completa las cuatro misiones para la multibola final con triple puntuación.',
  },
};

export default STRINGS;
