// hoops4/js/strings.js - EN/ES. English is the source of truth; a missing Spanish key falls back
// to English, so a partial translation can never break a screen. Call t() at RENDER time.
export const STRINGS = {
  en: {
    title: 'Connect 4 Hoops',
    tagline: 'Sink a hoop, drop a disc. Four in a row wins.',
    opponent: 'Opponent',
    // THE HUB'S OWN DIFFICULTY WORDS, not this game's. They were 'Beginner / Steady /
    // Sharpshooter' - invented here and nowhere else in the repo. Matt: "you created brand new
    // terminology for the difficulties. Don't do that."
    cpu1: 'Easy', cpu2: 'Medium', cpu3: 'Hard',
    twoPlayer: 'Two players',
    play: 'Play',
    howto: 'How to play',
    howtoBody: 'Swipe up the lane to shoot. How hard you swipe sets the arc, the angle picks the hoop. Sink any hoop and your disc drops down that column. Miss and you simply shoot again, so a turn only ends when a ball goes in. A ball that rims out into the next hoop still counts, in that column.',
    close: 'Close',
    yourTurn: 'Your turn', theirTurn: 'Their turn',
    // WHOSE SHOT IT IS, said before the shot rather than after it. Matt: "it's not clear when
    // it's the computers turn. There's no indication until they've thrown."
    you: 'You', shooting: 'is shooting', yourShot: 'Your shot',
    leaveKept: 'Your match is saved. Pick it up whenever you like.',
    menu: 'Menu',
    // The full-screen challenge card (showCeremony in ui.js).
    cerHead: 'CHALLENGE', cerHeadTurn: 'YOUR TURN',
    cerChallenged: '{who} has challenged you to Connect 4 Hoops',
    cerYourTurn: 'It is your turn against {who}',
    cerVs: 'VS',
    cerGo: 'Let\u2019s play', cerGoTurn: 'Take my shot', cerLater: 'Not now',
    cerGone: 'That match is not there any more.',
    leaveQ: 'Leave this game?',
    leaveLost: 'This game is not saved. Leaving ends it.',
    leaveYes: 'Leave', leaveNo: 'Keep playing',
    red: 'Red', yellow: 'Yellow',
    shots: 'Shots', shot: 'Shot',
    swipeHint: 'Swipe up to shoot',
    miss: 'Miss', full: 'Column full', inCol: 'Column {n}',
    youWin: 'You win', youLose: 'You lose', redWins: 'Red wins', yellowWins: 'Yellow wins',
    draw: 'Draw',
    accuracy: 'Accuracy',
    again: 'Play again', quit: 'Quit',
    loadError: 'Could not load the machine. Check your connection and try again.',
    // --- the setup screen -----------------------------------------------------------------
    mode: 'Game',
    solo: 'On this phone', online: 'Play a friend',
    shotMode: 'Shots per turn',
    shotsUntil: 'Till you make one', shotsOne: 'One shot only',
    // --- multiplayer ----------------------------------------------------------------------
    mp: 'Play a friend',
    mpLive: 'Live game', mpLiveNote: 'Both of you play now, one after the other.',
    mpTurns: 'Turn by turn', mpTurnsNote: 'Take your shot and hand it over. They play when they next open the hub.',
    mpHost: 'Host a game', mpJoin: 'Join a game',
    mpCode: 'Room code', mpCodeHint: 'Give them this code',
    mpEnterCode: 'Enter their code', mpJoinBtn: 'Join',
    mpWaiting: 'Waiting for your friend...', mpJoined: 'Connected',
    mpLost: 'Lost the connection. They may have closed the game.',
    mpRejoin: 'Reconnecting...',
    mpBadCode: 'No game with that code.',
    mpTheirTurn: 'Waiting for them to shoot',
    mpYouAre: 'You are {who}',
    mpChallenge: 'Challenge', mpPick: 'Who are you playing?',
    mpNoOne: 'Nobody to challenge yet. A player shows up here once they have opened the hub.',
    mpSent: 'Sent. They play next.', mpYourMove: 'Your move',
    mpGames: 'Your games', mpNoGames: 'No games yet.',
    mpWaitingOn: 'Waiting on {who}', mpOver: 'Finished',
    mpResign: 'Resign', mpResigned: '{who} resigned',
    mpOffline: 'You are offline. The move is saved and will send itself.',
    mpNeedName: 'Set up your profile first so they know who is playing.',
    mpOnline: 'online', mpOpponent: 'Opponent',
    mpUnavailable: 'Turn by turn is not switched on yet. Live games still work.',
  },
  es: {
    title: 'Connect 4 Hoops',
    tagline: 'Encesta y suelta una ficha. Cuatro en raya gana.',
    opponent: 'Rival',
    cpu1: 'Fácil', cpu2: 'Normal', cpu3: 'Difícil',
    twoPlayer: 'Dos jugadores',
    play: 'Jugar',
    howto: 'Cómo se juega',
    howtoBody: 'Desliza hacia arriba para tirar. La fuerza marca el arco y el ángulo elige la canasta. Si encestas, tu ficha cae por esa columna. Si fallas, vuelves a tirar, así que el turno solo termina cuando entra una bola. Una bola que rebota y entra en la canasta de al lado también cuenta, en esa columna.',
    close: 'Cerrar',
    yourTurn: 'Tu turno', theirTurn: 'Su turno',
    you: 'Tú', shooting: 'está tirando', yourShot: 'Tu tiro',
    leaveKept: 'Tu partida está guardada. Puedes seguir cuando quieras.',
    menu: 'Menú',
    cerHead: 'RETO', cerHeadTurn: 'TE TOCA',
    cerChallenged: '{who} te ha retado a Connect 4 Hoops',
    cerYourTurn: 'Te toca contra {who}',
    cerVs: 'VS',
    cerGo: 'A jugar', cerGoTurn: 'Tirar', cerLater: 'Ahora no',
    cerGone: 'Esa partida ya no está.',
    leaveQ: '¿Salir de esta partida?',
    leaveLost: 'Esta partida no se guarda. Si sales, se termina.',
    leaveYes: 'Salir', leaveNo: 'Seguir jugando',
    red: 'Rojo', yellow: 'Amarillo',
    shots: 'Tiros', shot: 'Tiro',
    swipeHint: 'Desliza para tirar',
    miss: 'Fallo', full: 'Columna llena', inCol: 'Columna {n}',
    youWin: 'Ganas', youLose: 'Pierdes', redWins: 'Gana Rojo', yellowWins: 'Gana Amarillo',
    draw: 'Empate',
    accuracy: 'Puntería',
    again: 'Jugar otra vez', quit: 'Salir',
    loadError: 'No se pudo cargar la máquina. Revisa tu conexión e inténtalo de nuevo.',
    // --- the setup screen -----------------------------------------------------------------
    mode: 'Partida',
    solo: 'En este telefono', online: 'Jugar con alguien',
    shotMode: 'Tiros por turno',
    shotsUntil: 'Hasta encestar', shotsOne: 'Un solo tiro',
    // --- multiplayer ----------------------------------------------------------------------
    mp: 'Jugar con alguien',
    mpLive: 'Partida en vivo', mpLiveNote: 'Los dos juegan ahora, por turnos.',
    mpTurns: 'Por turnos', mpTurnsNote: 'Tira y pasasela. Jugara la proxima vez que abra el hub.',
    mpHost: 'Crear partida', mpJoin: 'Unirse a una partida',
    mpCode: 'Codigo', mpCodeHint: 'Dale este codigo',
    mpEnterCode: 'Escribe su codigo', mpJoinBtn: 'Unirse',
    mpWaiting: 'Esperando a tu amigo...', mpJoined: 'Conectado',
    mpLost: 'Se perdio la conexion. Puede que haya cerrado el juego.',
    mpRejoin: 'Reconectando...',
    mpBadCode: 'No hay ninguna partida con ese codigo.',
    mpTheirTurn: 'Esperando su tiro',
    mpYouAre: 'Eres {who}',
    mpChallenge: 'Retar', mpPick: 'Contra quien juegas?',
    mpNoOne: 'Todavia no hay nadie a quien retar. Un jugador aparece aqui cuando abre el hub.',
    mpSent: 'Enviado. Le toca a el.', mpYourMove: 'Te toca',
    mpGames: 'Tus partidas', mpNoGames: 'Todavia no hay partidas.',
    mpWaitingOn: 'Esperando a {who}', mpOver: 'Terminada',
    mpResign: 'Rendirse', mpResigned: '{who} se rindio',
    mpOffline: 'Estas sin conexion. La jugada se guarda y se enviara sola.',
    mpNeedName: 'Configura tu perfil primero para que sepan quien juega.',
    mpOnline: 'en linea', mpOpponent: 'Rival',
    mpUnavailable: 'El modo por turnos todavia no esta activado. Las partidas en vivo si funcionan.',
  },
};
export default STRINGS;
