// hoops4/js/strings.js - EN/ES. English is the source of truth; a missing Spanish key falls back
// to English, so a partial translation can never break a screen. Call t() at RENDER time.
export const STRINGS = {
  en: {
    title: 'Connect 4 Hoops',
    tagline: 'Sink a hoop, drop a disc. Four in a row wins.',
    opponent: 'Opponent',
    cpu1: 'Beginner', cpu2: 'Steady', cpu3: 'Sharpshooter',
    twoPlayer: 'Two players',
    cpuNote: 'The computer picks its column well. Whether it hits it is the difficulty.',
    play: 'Play',
    howto: 'How to play',
    howtoBody: 'Swipe up the lane to shoot. How hard you swipe sets the arc, the angle picks the hoop. Sink any hoop and your disc drops down that column. Miss and you simply shoot again, so a turn only ends when a ball goes in. A ball that rims out into the next hoop still counts, in that column.',
    close: 'Close',
    yourTurn: 'Your turn', theirTurn: 'Their turn',
    red: 'Red', yellow: 'Yellow',
    shots: 'Shots', shot: 'Shot',
    swipeHint: 'Swipe up to shoot',
    miss: 'Miss', full: 'Column full', inCol: 'Column {n}',
    youWin: 'You win', youLose: 'You lose', redWins: 'Red wins', yellowWins: 'Yellow wins',
    draw: 'Draw',
    accuracy: 'Accuracy',
    again: 'Play again', quit: 'Quit',
    loadError: 'Could not load the machine. Check your connection and try again.',
  },
  es: {
    title: 'Connect 4 Hoops',
    tagline: 'Encesta y suelta una ficha. Cuatro en raya gana.',
    opponent: 'Rival',
    cpu1: 'Principiante', cpu2: 'Firme', cpu3: 'Certero',
    twoPlayer: 'Dos jugadores',
    cpuNote: 'La computadora elige bien su columna. La dificultad es si acierta el tiro.',
    play: 'Jugar',
    howto: 'Cómo se juega',
    howtoBody: 'Desliza hacia arriba para tirar. La fuerza marca el arco y el ángulo elige la canasta. Si encestas, tu ficha cae por esa columna. Si fallas, vuelves a tirar, así que el turno solo termina cuando entra una bola. Una bola que rebota y entra en la canasta de al lado también cuenta, en esa columna.',
    close: 'Cerrar',
    yourTurn: 'Tu turno', theirTurn: 'Su turno',
    red: 'Rojo', yellow: 'Amarillo',
    shots: 'Tiros', shot: 'Tiro',
    swipeHint: 'Desliza para tirar',
    miss: 'Fallo', full: 'Columna llena', inCol: 'Columna {n}',
    youWin: 'Ganas', youLose: 'Pierdes', redWins: 'Gana Rojo', yellowWins: 'Gana Amarillo',
    draw: 'Empate',
    accuracy: 'Puntería',
    again: 'Jugar otra vez', quit: 'Salir',
    loadError: 'No se pudo cargar la máquina. Revisa tu conexión e inténtalo de nuevo.',
  },
};
export default STRINGS;
