// hoops4/js/strings.js - EN/ES. English is the source of truth; a missing Spanish key falls back
// to English, so a partial translation can never break a screen. Call t() at RENDER time.
export const STRINGS = {
  en: {
    title: 'Connect 4 Hoops',
    // THE HUB'S OWN DIFFICULTY WORDS, not this game's. They were 'Beginner / Steady /
    // Sharpshooter' - invented here and nowhere else in the repo. Matt: "you created brand new
    // terminology for the difficulties. Don't do that."
    cpu1: 'Easy', cpu2: 'Medium', cpu3: 'Hard',
    play: 'Play',
    howto: 'How to play',
    // THE ONE MECHANIC THAT IS NOT OBVIOUS, drawn rather than described - everybody already knows
    // Connect 4 and everybody already knows basketball; what they do not know is that the two are
    // wired together. docs/BUILDING-A-GAME.md, "How-to-play screens". Matt, on the paragraph this
    // replaces: "The How To Play is even worse. it's JUST words."
    howtoGoal: 'Four in a row wins.',
    howtoCap: 'The hoop you sink picks the column.',
    howtoEg: 'Sink hoop 3 = disc down column 3.',
    howtoArc: 'Swipe harder for a higher arc.',
    howtoAim: 'The angle picks the hoop.',
    howtoRim: 'Rim out into the next hoop? That one counts.',
    close: 'Close',
    yourTurn: 'Your turn', theirTurn: 'Their turn',
    // WHOSE TURN IT IS, said before the shot rather than after it. Matt: "it's not clear when
    // it's the computers turn. There's no indication until they've thrown." Then (2026-09-22):
    // "change the 'Your shot' and the 'Hard is shooting'. Those are not good."
    you: 'You', turnYou: 'Your turn', turnCpu: 'Computer\u2019s turn', turnOf: '{name}\u2019s turn',
    leaveKept: 'Your match is saved. Pick it up whenever you like.',
    mpShootToSend: 'Take your first shot to send the challenge.',
    pushOn: 'Notify me when it\'s my turn',
    pushAskQ: 'Want a notification when {who} plays back?',
    pushAskYes: 'Yes, notify me', pushAskNo: 'Not now',
    pushDone: 'Done. Your phone will buzz when it\'s your turn.',
    pushDenied: 'Notifications are blocked for Game Hub. Turn them on in your phone\'s Settings.',
    pushFailed: 'That didn\'t work. Check your connection and try again.',
    pushInstall: 'To get a notification when it\'s your turn, add Game Hub to your Home Screen and open it from there.',
    menu: 'Menu',
    // THE PAUSE SHEET. Matt asked for skeeball's button and skeeball's options, so these mirror
    // its `paused`/`resume`/`new_game` - except the third, which goes where THIS game's menu
    // button has always gone (its own setup screen), not out to a gallery this game does not have.
    paused: 'Paused',
    resume: 'Resume',
    newGame: 'New game',
    backSetup: 'Back to setup screen',
    backMp: 'Back to multiplayer',
    // --- the setup screen, restructured 2026-09-22 ------------------------------------------
    // Matt: "What is 2 player? There should be options to play the computer player and
    // 'Multiplayer Options'... The computer player options should just have the difficulties and
    // the shots per turn option."
    vsCpu: 'Play the computer',
    difficulty: 'Difficulty',
    multiplayer: 'Multiplayer',
    mpHome: 'Multiplayer',
    // The multiplayer home, reorganised 2026-09-23 (Matt: "Make this page better/easier to
    // navigate. And let people quit games.")
    mpChallengeBig: 'Challenge someone', mpHostShort: 'Host', mpJoinShort: 'Join', mpPassShort: 'Pass & play',
    youAreRed: 'You are Red', youAreYellow: 'You are Yellow', mpSecEnded: 'Game over', mpSeeResult: 'tap to see', mpSecYours: 'Your turn', mpSecTheirs: 'Waiting on them', mpWaiting2: 'Waiting',
    mpQuit: 'Quit', mpQuitAria: 'Quit your game with {who}', mpQuitQ: 'Quit this game?',
    mpQuitBody: 'Your game with {who} ends and counts as a loss for you.',
    mpQuitNo: 'Keep playing', mpQuitYes: 'Quit',
    mpSeriesAt: 'series {s}', mpStartN: 'Start game {n}', mpTheyStart: 'they start it',
    mpQuitFail: 'Could not quit. Check your connection and try again.',
    mpPassPlay: 'Pass and play',
    mpActive: 'Active games',
    // --- the terms of a challenge (2026-09-22) ----------------------------------------------
    // Matt: "Before you challenge someone or anything, you should be able to select the shots per
    // turn setting and if you want to play a single game, best of 3 series or best of 5 series.
    // And when you accept a challenge and go to play, you should see what the shot settings and
    // the series selection is."
    chTitle: 'Challenge {who}',
    chSeries: 'Series',
    chSingle: 'Single game', chBo3: 'Best of 3', chBo5: 'Best of 5',
    chCaption: 'Say something (optional)',
    chCaptionPh: 'Good luck...',
    chSend: 'Send challenge',
    gameOf: 'Game {n} of {m}',
    seriesScore: 'Series {a}\u2013{b}',
    nextGame: 'Next game',
    seriesWon: '{who} takes the series', seriesDrawn: 'Series drawn',
    youTakeIt: 'You take the series',
    mpNoActive: 'No games yet. Challenge somebody above.',
    // The full-screen challenge card (showCeremony in ui.js).
    cerHead: 'CHALLENGE', cerHeadTurn: 'YOUR TURN',
    cerChallenged: '{who} has challenged you to Connect 4 Hoops',
    cerYourTurn: 'It is your turn against {who}',
    cerVs: 'VS',
    cerGo: 'Let\u2019s play', cerGoTurn: 'Take my shot', cerLater: 'Not now',
    cerGone: 'That match is not there any more.',
    leaveQ: 'Leave this game?',
    leaveLost: 'This game is not saved. Leaving ends it.',
    leaveYes: 'Leave', leaveNo: 'Keep playing',
    red: 'Red', yellow: 'Yellow',
    shots: 'Shots', shot: 'Shot',
    swipeHint: 'Swipe up to shoot',
    miss: 'Miss', full: 'Column full', inCol: 'Column {n}',
    youWin: 'You win', youLose: 'You lose', redWins: 'Red wins', yellowWins: 'Yellow wins',
    draw: 'Draw',
    accuracy: 'Accuracy',
    again: 'Play again', quit: 'Quit',
    loadError: 'Could not load the machine. Check your connection and try again.',
    // --- the setup screen -----------------------------------------------------------------
    mode: 'Game',
    solo: 'On this phone', online: 'Play a friend',
    shotMode: 'Shots per turn',
    shotsUntil: 'Till you make one', shotsOne: 'One shot only',
    // --- multiplayer ----------------------------------------------------------------------
    mp: 'Play a friend',
    mpHost: 'Host a game', mpJoin: 'Join a game',
    mpCode: 'Room code', mpCodeHint: 'Give them this code',
    mpEnterCode: 'Enter their code', mpJoinBtn: 'Join',
    mpWaiting: 'Waiting for your friend...', mpJoined: 'Connected',
    mpLost: 'Lost the connection. They may have closed the game.',
    mpRejoin: 'Reconnecting...',
    mpBadCode: 'No game with that code.',
    mpTheirTurn: 'Waiting for them to shoot',
    mpYouAre: 'You are {who}',
    mpChallenge: 'Challenge', mpPick: 'Who are you playing?',
    mpNoOne: 'Nobody to challenge yet. A player shows up here once they have opened the hub.',
    mpSent: 'Sent. They play next.', mpYourMove: 'Your move',
    mpGames: 'Your games',
    mpWaitingOn: 'Waiting on {who}', mpOver: 'Finished',
    mpResign: 'Resign', mpResigned: '{who} resigned',
    mpOffline: 'You are offline. The move is saved and will send itself.',
    mpNeedName: 'Set up your profile first so they know who is playing.',
    mpOnline: 'online', mpOpponent: 'Opponent',
    mpUnavailable: 'Turn by turn is not switched on yet. Live games still work.',
    // Quick chat inside a match (2026-09-22). The preset phrases themselves come from the hub's
    // shared quick-chat palette (js/mp-reactions.js), already translated there.
    chat: 'Chat', chatPh: 'Say something', chatSend: 'Send', chatYou: 'You',
    chatNone: 'Nothing said yet.', chatNotSent: 'Message not sent. Try again.',
    // Challenge history (2026-09-22).
    mpHistory: 'History', histRecords: 'Records', histGames: 'Finished games',
    histNone: 'No finished games yet.',
    histWon: 'Won', histLost: 'Lost', histDraw: 'Draw', histResigned: 'Resigned',
    histTheyResigned: 'Won, they resigned', histUnknown: 'Finished',
    histLine: 'W {w} · L {l} · D {d}',
  },
  es: {
    title: 'Connect 4 Hoops',
    cpu1: 'Fácil', cpu2: 'Normal', cpu3: 'Difícil',
    play: 'Jugar',
    howto: 'Cómo se juega',
    howtoGoal: 'Cuatro en raya gana.',
    howtoCap: 'La canasta que encestas elige la columna.',
    howtoEg: 'Encesta la 3 = ficha en la columna 3.',
    howtoArc: 'Desliza más fuerte para un arco más alto.',
    howtoAim: 'El ángulo elige la canasta.',
    howtoRim: '¿Rebota a la de al lado? Cuenta esa.',
    close: 'Cerrar',
    yourTurn: 'Tu turno', theirTurn: 'Su turno',
    you: 'Tú', turnYou: 'Tu turno', turnCpu: 'Turno de la CPU', turnOf: 'Turno de {name}',
    leaveKept: 'Tu partida está guardada. Puedes seguir cuando quieras.',
    mpShootToSend: 'Haz tu primer tiro para enviar el reto.',
    pushOn: 'Avísame cuando me toque',
    pushAskQ: '¿Quieres un aviso cuando {who} te devuelva el tiro?',
    pushAskYes: 'Sí, avísame', pushAskNo: 'Ahora no',
    pushDone: 'Listo. Tu teléfono sonará cuando te toque.',
    pushDenied: 'Las notificaciones están bloqueadas para Game Hub. Actívalas en los Ajustes del teléfono.',
    pushFailed: 'No funcionó. Revisa tu conexión e inténtalo otra vez.',
    pushInstall: 'Para recibir un aviso cuando te toque, añade Game Hub a tu pantalla de inicio y ábrelo desde allí.',
    menu: 'Menú',
    paused: 'En pausa',
    resume: 'Continuar',
    newGame: 'Partida nueva',
    backSetup: 'Volver a la pantalla de inicio',
    backMp: 'Volver a multijugador',
    vsCpu: 'Jugar contra la máquina',
    difficulty: 'Dificultad',
    multiplayer: 'Multijugador',
    mpHome: 'Multijugador',
    mpChallengeBig: 'Retar a alguien', mpHostShort: 'Crear', mpJoinShort: 'Unirse', mpPassShort: 'Pasar y jugar',
    youAreRed: 'Eres Rojo', youAreYellow: 'Eres Amarillo', mpSecEnded: 'Partida terminada', mpSeeResult: 'toca para ver', mpSecYours: 'Te toca', mpSecTheirs: 'Esperando al rival', mpWaiting2: 'Esperando',
    mpQuit: 'Abandonar', mpQuitAria: 'Abandonar la partida con {who}', mpQuitQ: '¿Abandonar esta partida?',
    mpQuitBody: 'Tu partida con {who} termina y cuenta como derrota.',
    mpQuitNo: 'Seguir jugando', mpQuitYes: 'Abandonar',
    mpSeriesAt: 'serie {s}', mpStartN: 'Empezar partida {n}', mpTheyStart: 'la empieza el rival',
    mpQuitFail: 'No se pudo abandonar. Revisa tu conexión e inténtalo de nuevo.',
    mpPassPlay: 'Pasar y jugar',
    mpActive: 'Partidas activas',
    chTitle: 'Retar a {who}',
    chSeries: 'Serie',
    chSingle: 'Una partida', chBo3: 'Al mejor de 3', chBo5: 'Al mejor de 5',
    chCaption: 'Di algo (opcional)',
    chCaptionPh: 'Suerte...',
    chSend: 'Enviar reto',
    gameOf: 'Partida {n} de {m}',
    seriesScore: 'Serie {a}\u2013{b}',
    nextGame: 'Siguiente partida',
    seriesWon: '{who} gana la serie', seriesDrawn: 'Serie empatada',
    youTakeIt: 'Ganas la serie',
    mpNoActive: 'Aún no hay partidas. Reta a alguien arriba.',
    cerHead: 'RETO', cerHeadTurn: 'TE TOCA',
    cerChallenged: '{who} te ha retado a Connect 4 Hoops',
    cerYourTurn: 'Te toca contra {who}',
    cerVs: 'VS',
    cerGo: 'A jugar', cerGoTurn: 'Tirar', cerLater: 'Ahora no',
    cerGone: 'Esa partida ya no está.',
    leaveQ: '¿Salir de esta partida?',
    leaveLost: 'Esta partida no se guarda. Si sales, se termina.',
    leaveYes: 'Salir', leaveNo: 'Seguir jugando',
    red: 'Rojo', yellow: 'Amarillo',
    shots: 'Tiros', shot: 'Tiro',
    swipeHint: 'Desliza para tirar',
    miss: 'Fallo', full: 'Columna llena', inCol: 'Columna {n}',
    youWin: 'Ganas', youLose: 'Pierdes', redWins: 'Gana Rojo', yellowWins: 'Gana Amarillo',
    draw: 'Empate',
    accuracy: 'Puntería',
    again: 'Jugar otra vez', quit: 'Salir',
    loadError: 'No se pudo cargar la máquina. Revisa tu conexión e inténtalo de nuevo.',
    // --- the setup screen -----------------------------------------------------------------
    mode: 'Partida',
    solo: 'En este telefono', online: 'Jugar con alguien',
    shotMode: 'Tiros por turno',
    shotsUntil: 'Hasta encestar', shotsOne: 'Un solo tiro',
    // --- multiplayer ----------------------------------------------------------------------
    mp: 'Jugar con alguien',
    mpHost: 'Crear partida', mpJoin: 'Unirse a una partida',
    mpCode: 'Codigo', mpCodeHint: 'Dale este codigo',
    mpEnterCode: 'Escribe su codigo', mpJoinBtn: 'Unirse',
    mpWaiting: 'Esperando a tu amigo...', mpJoined: 'Conectado',
    mpLost: 'Se perdio la conexion. Puede que haya cerrado el juego.',
    mpRejoin: 'Reconectando...',
    mpBadCode: 'No hay ninguna partida con ese codigo.',
    mpTheirTurn: 'Esperando su tiro',
    mpYouAre: 'Eres {who}',
    mpChallenge: 'Retar', mpPick: 'Contra quien juegas?',
    mpNoOne: 'Todavia no hay nadie a quien retar. Un jugador aparece aqui cuando abre el hub.',
    mpSent: 'Enviado. Le toca a el.', mpYourMove: 'Te toca',
    mpGames: 'Tus partidas',
    mpWaitingOn: 'Esperando a {who}', mpOver: 'Terminada',
    mpResign: 'Rendirse', mpResigned: '{who} se rindio',
    mpOffline: 'Estas sin conexion. La jugada se guarda y se enviara sola.',
    mpNeedName: 'Configura tu perfil primero para que sepan quien juega.',
    mpOnline: 'en linea', mpOpponent: 'Rival',
    mpUnavailable: 'El modo por turnos todavia no esta activado. Las partidas en vivo si funcionan.',
    chat: 'Chat', chatPh: 'Di algo', chatSend: 'Enviar', chatYou: 'Tú',
    chatNone: 'Nadie ha dicho nada.', chatNotSent: 'Mensaje no enviado. Inténtalo otra vez.',
    mpHistory: 'Historial', histRecords: 'Récords', histGames: 'Partidas terminadas',
    histNone: 'Aún no hay partidas terminadas.',
    histWon: 'Ganada', histLost: 'Perdida', histDraw: 'Empate', histResigned: 'Te rendiste',
    histTheyResigned: 'Ganada, se rindió', histUnknown: 'Terminada',
    histLine: 'G {w} · P {l} · E {d}',
  },
};
export default STRINGS;
