// cup-pong/js/strings.js - EN/ES. English is the source of truth; a missing Spanish key falls back
// to English, so a partial translation can never break a screen. Call t() at RENDER time.
export const STRINGS = {
  en: {
    title: 'Cup Pong',
    practice: 'Practice',
    cupsLeft: '{n} cups left',
    oneCupLeft: '1 cup left',
    throws: '{n} throws',
    oneThrow: '1 throw',
    swipeHint: 'Flick up to throw',
    swipeArea: 'Throwing area. Flick up to throw the ball.',
    made: 'Cup!',
    bounceMade: 'Bounce cup!',
    miss: 'Miss',
    rimOut: 'Off the rim',
    lastThrow: 'Power {p} · Aim {a}',
    menu: 'Menu',
    paused: 'Paused',
    resume: 'Resume',
    newRack: 'New rack',
    close: 'Close',
    cleared: 'Rack cleared!',
    clearedIn: 'All 10 cups in {n} throws',
    again: 'Rack again',
    loadError: 'The table did not load. Check your connection and try again.',
    retry: 'Try again',
  },
  es: {
    title: 'Cup Pong',
    practice: 'Práctica',
    cupsLeft: 'Quedan {n} vasos',
    oneCupLeft: 'Queda 1 vaso',
    throws: '{n} tiros',
    oneThrow: '1 tiro',
    swipeHint: 'Desliza hacia arriba para tirar',
    swipeArea: 'Zona de tiro. Desliza hacia arriba para lanzar la pelota.',
    made: '¡Vaso!',
    bounceMade: '¡Vaso de rebote!',
    miss: 'Fallo',
    rimOut: 'Rebotó en el borde',
    lastThrow: 'Fuerza {p} · Puntería {a}',
    menu: 'Menú',
    paused: 'Pausa',
    resume: 'Seguir',
    newRack: 'Colocar de nuevo',
    close: 'Cerrar',
    cleared: '¡Todos los vasos!',
    clearedIn: 'Los 10 vasos en {n} tiros',
    again: 'Otra vez',
    loadError: 'La mesa no cargó. Revisa tu conexión e inténtalo de nuevo.',
    retry: 'Reintentar',
  },
};
export default STRINGS;
