// cup-pong/js/strings.js - EN/ES. English is the source of truth; a missing Spanish key falls back
// to English, so a partial translation can never break a screen. Call t() at RENDER time.
export const STRINGS = {
  en: {
    title: 'Cup Pong',
    practice: 'Practice',
    cupsLeft: '{n} cups left',
    oneCupLeft: '1 cup left',
    throws: '{n} throws',
    oneThrow: '1 throw',
    swipeHint: 'Flick up to throw',
    swipeArea: 'Throwing area. Flick up to throw the ball.',
    made: 'Cup!',
    bounceMade: 'Bounce cup!',
    miss: 'Miss',
    rimOut: 'Off the rim',
    lastThrow: 'Power {p} · Aim {a}',
    menu: 'Menu',
    paused: 'Paused',
    resume: 'Resume',
    newRack: 'New rack',
    close: 'Close',
    cleared: 'Rack cleared!',
    clearedIn: 'All 10 cups in {n} throws',
    again: 'Rack again',
    loadError: 'The table did not load. Check your connection and try again.',
    retry: 'Try again',
    // --- stage 2: the match ---
    vsCpu: 'Play the computer',
    easy: 'Easy', medium: 'Medium', hard: 'Hard',
    gentlemans: "Gentleman's",
    gentlemansHint: 'Last 2 cups stand in a line',
    on: 'On', off: 'Off',
    play: 'Play',
    practiceBtn: 'Practice',
    yourTurn: 'Your turn',
    cpuTurn: 'Computer',
    cupsScore: 'You {a} \u00b7 {b} Computer',
    ballsBack: 'Balls Back',
    heatingUp: 'Heating Up',
    onFire: 'On Fire!',
    rebuttal: 'Rebuttal',
    rebuttalYou: 'Rebuttal: make them all',
    overtime: 'Overtime',
    gentlemansDone: "Gentleman's",
    youWin: 'You win!',
    youLose: 'You lose',
    playAgain: 'Play again',
    backSetup: 'Change settings',
    newGame: 'New game',
    leaveQ: 'Quit this game?',
    firstYou: 'You go first',
    firstCpu: 'The computer goes first',
  },
  es: {
    title: 'Cup Pong',
    practice: 'Práctica',
    cupsLeft: 'Quedan {n} vasos',
    oneCupLeft: 'Queda 1 vaso',
    throws: '{n} tiros',
    oneThrow: '1 tiro',
    swipeHint: 'Desliza hacia arriba para tirar',
    swipeArea: 'Zona de tiro. Desliza hacia arriba para lanzar la pelota.',
    made: '¡Vaso!',
    bounceMade: '¡Vaso de rebote!',
    miss: 'Fallo',
    rimOut: 'Rebotó en el borde',
    lastThrow: 'Fuerza {p} · Puntería {a}',
    menu: 'Menú',
    paused: 'Pausa',
    resume: 'Seguir',
    newRack: 'Colocar de nuevo',
    close: 'Cerrar',
    cleared: '¡Todos los vasos!',
    clearedIn: 'Los 10 vasos en {n} tiros',
    again: 'Otra vez',
    loadError: 'La mesa no cargó. Revisa tu conexión e inténtalo de nuevo.',
    retry: 'Reintentar',
    vsCpu: 'Jugar contra la computadora',
    easy: 'Fácil', medium: 'Normal', hard: 'Difícil',
    gentlemans: 'Caballero',
    gentlemansHint: 'Los 2 últimos vasos en fila',
    on: 'Sí', off: 'No',
    play: 'Jugar',
    practiceBtn: 'Práctica',
    yourTurn: 'Tu turno',
    cpuTurn: 'Computadora',
    cupsScore: 'Tú {a} \u00b7 {b} Computadora',
    ballsBack: 'Otra ronda',
    heatingUp: 'En racha',
    onFire: '¡En llamas!',
    rebuttal: 'Réplica',
    rebuttalYou: 'Réplica: mételos todos',
    overtime: 'Prórroga',
    gentlemansDone: 'Caballero',
    youWin: '¡Ganaste!',
    youLose: 'Perdiste',
    playAgain: 'Otra vez',
    backSetup: 'Cambiar ajustes',
    newGame: 'Nueva partida',
    leaveQ: '¿Salir de esta partida?',
    firstYou: 'Empiezas tú',
    firstCpu: 'Empieza la computadora',
  },
};
export default STRINGS;
