// cup-pong/js/strings.js - EN/ES. English is the source of truth; a missing Spanish key falls back
// to English, so a partial translation can never break a screen. Call t() at RENDER time.
export const STRINGS = {
  en: {
    title: 'Cup Pong',
    practice: 'Practice',
    cupsLeft: '{n} cups left',
    oneCupLeft: '1 cup left',
    throws: '{n} throws',
    oneThrow: '1 throw',
    swipeHint: 'Flick up to throw',
    swipeArea: 'Throwing area. Flick up to throw the ball.',
    made: 'Cup!',
    bounceMade: 'Bounce cup!',
    miss: 'Miss',
    rimOut: 'Off the rim',
    lastThrow: 'Power {p} · Aim {a}',
    menu: 'Menu',
    paused: 'Paused',
    resume: 'Resume',
    newRack: 'New rack',
    close: 'Close',
    cleared: 'Rack cleared!',
    clearedIn: 'All 10 cups in {n} throws',
    again: 'Rack again',
    loadError: 'The table did not load. Check your connection and try again.',
    retry: 'Try again',
    // --- stage 2: the match ---
    vsCpu: 'Play the computer',
    easy: 'Easy', medium: 'Medium', hard: 'Hard',
    gentlemans: "Gentleman's",
    gentlemansHint: 'Last 2 cups stand in a line',
    on: 'On', off: 'Off',
    play: 'Play',
    practiceBtn: 'Practice',
    yourTurn: 'Your turn',
    cpuTurn: 'Computer',
    cupsScore: 'You {a} \u00b7 {b} Computer',
    ballsBack: 'Balls Back',
    heatingUp: 'Heating Up',
    onFire: 'On Fire!',
    rebuttal: 'Rebuttal',
    rebuttalYou: 'Rebuttal: make them all',
    overtime: 'Overtime',
    gentlemansDone: "Gentleman's",
    youWin: 'You win!',
    youLose: 'You lose',
    playAgain: 'Play again',
    backSetup: 'Change settings',
    newGame: 'New game',
    leaveQ: 'Quit this game?',
    firstYou: 'You go first',
    firstCpu: 'The computer goes first',
    reracks: 'Reracks',
    reracksHint: 'Each player, each game',
    gentlemansQ: "Gentleman's",
    rerackQ: 'Rerack ({n})',
    islandQ: 'Island',
    rerack: 'Rerack',
    islandCalled: 'Island called',
    islandHit: 'Island! Two cups',
    pickIsland: 'Tap the island to call',
    pickYours: 'Island! Tap one of your cups to remove',
    lastCup: 'Last cup! Same cup wins',
    sameCup: 'Same cup!',
    ballHeating: 'Ball {n} heating up',
    ballOnFire: 'Ball {n} on fire',
    cpuGentlemans: "Computer: Gentleman's",
    cpuRerack: 'Computer reracked',
    cpuIsland: 'Computer calls island',
    rk_tri: 'Triangle', rk_diamond: 'Diamond', rk_wall333: '3-3-3', rk_zipper: 'Zipper', rk_r323: '3-2-3',
    rk_honeycomb: 'Honeycomb', rk_wall33: '3-3 wall', rk_house: 'House', rk_r32: '3-2', rk_tri31: '3-1',
    rk_line: 'Line', rk_square: 'Square', rk_side: 'Side by side', rk_center: 'Center',
    solo: 'Solo',
    soloHint: 'All 10 cups, fewest throws',
    soloBtn: 'Play solo',
    soloBest: 'Your best: {n} throws',
    soloNewBest: 'New best!',
  },
  es: {
    title: 'Cup Pong',
    practice: 'Práctica',
    cupsLeft: 'Quedan {n} vasos',
    oneCupLeft: 'Queda 1 vaso',
    throws: '{n} tiros',
    oneThrow: '1 tiro',
    swipeHint: 'Desliza hacia arriba para tirar',
    swipeArea: 'Zona de tiro. Desliza hacia arriba para lanzar la pelota.',
    made: '¡Vaso!',
    bounceMade: '¡Vaso de rebote!',
    miss: 'Fallo',
    rimOut: 'Rebotó en el borde',
    lastThrow: 'Fuerza {p} · Puntería {a}',
    menu: 'Menú',
    paused: 'Pausa',
    resume: 'Seguir',
    newRack: 'Colocar de nuevo',
    close: 'Cerrar',
    cleared: '¡Todos los vasos!',
    clearedIn: 'Los 10 vasos en {n} tiros',
    again: 'Otra vez',
    loadError: 'La mesa no cargó. Revisa tu conexión e inténtalo de nuevo.',
    retry: 'Reintentar',
    vsCpu: 'Jugar contra la computadora',
    easy: 'Fácil', medium: 'Normal', hard: 'Difícil',
    gentlemans: 'Caballero',
    gentlemansHint: 'Los 2 últimos vasos en fila',
    on: 'Sí', off: 'No',
    play: 'Jugar',
    practiceBtn: 'Práctica',
    yourTurn: 'Tu turno',
    cpuTurn: 'Computadora',
    cupsScore: 'Tú {a} \u00b7 {b} Computadora',
    ballsBack: 'Otra ronda',
    heatingUp: 'En racha',
    onFire: '¡En llamas!',
    rebuttal: 'Réplica',
    rebuttalYou: 'Réplica: mételos todos',
    overtime: 'Prórroga',
    gentlemansDone: 'Caballero',
    youWin: '¡Ganaste!',
    youLose: 'Perdiste',
    playAgain: 'Otra vez',
    backSetup: 'Cambiar ajustes',
    newGame: 'Nueva partida',
    leaveQ: '¿Salir de esta partida?',
    firstYou: 'Empiezas tú',
    firstCpu: 'Empieza la computadora',
    reracks: 'Recolocar',
    reracksHint: 'Cada jugador, cada partida',
    gentlemansQ: 'Caballero',
    rerackQ: 'Recolocar ({n})',
    islandQ: 'Isla',
    rerack: 'Recolocar',
    islandCalled: 'Isla cantada',
    islandHit: '¡Isla! Dos vasos',
    pickIsland: 'Toca la isla que cantas',
    pickYours: '¡Isla! Toca uno de tus vasos para quitarlo',
    lastCup: '¡Último vaso! Mismo vaso gana',
    sameCup: '¡Mismo vaso!',
    ballHeating: 'Pelota {n} en racha',
    ballOnFire: 'Pelota {n} en llamas',
    cpuGentlemans: 'Computadora: Caballero',
    cpuRerack: 'La computadora recolocó',
    cpuIsland: 'La computadora canta isla',
    rk_tri: 'Triángulo', rk_diamond: 'Rombo', rk_wall333: '3-3-3', rk_zipper: 'Cremallera', rk_r323: '3-2-3',
    rk_honeycomb: 'Panal', rk_wall33: 'Muro 3-3', rk_house: 'Casa', rk_r32: '3-2', rk_tri31: '3-1',
    rk_line: 'Línea', rk_square: 'Cuadrado', rk_side: 'Lado a lado', rk_center: 'Centro',
    solo: 'Solo',
    soloHint: 'Los 10 vasos, en menos tiros',
    soloBtn: 'Jugar solo',
    soloBest: 'Tu récord: {n} tiros',
    soloNewBest: '¡Nuevo récord!',
  },
};
export default STRINGS;
