// season.js : the pure season/standings/playoff model (doc §4). No DOM, no game.js dependency,
// no randomness outside a seeded `hashSeed`/`mulberry32` pair - a reusable module both the phase 2
// simulator and, later, phase 4's real career loop can share, the way `js/leaderboard-rank.js`
// serves both the leaderboard UI and its own headless tests.
//
// A league is `makeLeague(league)`'s 8 CPU teams, ordered weakest to strongest (index 0..7,
// teams.js's own contract), plus the player as a ninth entry (doc §4: "Top 4 of 9 make the
// playoffs"). This module never plays a game itself - every CPU-vs-CPU result is SCRIPTED (doc
// §17/§18's own wording), and the player's own games are played through the real engine by the
// caller and folded in as `playerResults`.

import { hashSeed, mulberry32 } from './rng.js';
import { BRACKET_MODEL, STANDINGS_MODEL, STANDINGS_TIEBREAK, SCHEDULE_SHAPE, SEASON } from './settings.js';

// doc §4, [Draft]: "12 regular season games per league across 8 opponents." doc §8, [Locked]: "the
// schedule puts harder opponents later in the season... the championship opponent is always the
// toughest team in the league." BB-2c commit 4, doc §13 Open item 13: three shapes, all weakest to
// strongest on the first pass and meeting the champion (index 7) exactly once, in game 12 - see
// `settings.js`'s `SCHEDULE_SHAPE` for the full rationale and the measured proposal.
const OPPONENT_ORDERS = {
  repeatTop: [0, 1, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7],
  repeatBottom: [0, 0, 1, 1, 2, 2, 3, 3, 4, 5, 6, 7],
  repeatMiddle: [0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7],
};

/** A Fisher-Yates shuffle of a seeded home/away flag array - "home and away six and six shuffled
 *  by seed" (doc §4). R16: for ANY season length, `ceil(n/2)` home and `floor(n/2)` away. At
 *  n = 12 that is the same six-and-six array, shuffled by the same draws, as before R16. */
export function shuffledHomeFlags(rand01, n = SEASON.gamesPerSeason) {
  const count = Math.max(0, Math.trunc(n));
  const flags = [];
  for (let i = 0; i < count; i++) flags.push(i < Math.ceil(count / 2));
  for (let i = flags.length - 1; i > 0; i--) {
    const j = Math.floor(rand01() * (i + 1));
    const tmp = flags[i]; flags[i] = flags[j]; flags[j] = tmp;
  }
  return flags;
}

/** R16: the opponent order for a season of ANY length over a league of ANY size (0 weakest ..
 *  size-1 champion), generalising the three fixed 12-game `OPPONENT_ORDERS` arrays above.
 *
 *  - n >= size: every opponent once, ascending, and the extra games are added to the MIDDLE slots
 *    in turn (`repeatMiddle`; `repeatBottom`/`repeatTop` keep their own fill sets at size 8). At
 *    n = 12 over 8 teams this reproduces `OPPONENT_ORDERS` byte for byte, which
 *    `baseball/js/test.js` asserts for all three shapes.
 *  - n < size: n slots spread evenly across the ladder, always including the weakest and the
 *    champion - Little League's 3 games over slots [1, 4, 7] become one game each.
 *
 *  Either way the order is ascending and the champion is met exactly ONCE, last (doc §8,
 *  [Locked]: "the schedule puts harder opponents later... the championship opponent is always the
 *  toughest team in the league"). */
function opponentOrder(n, size, scheduleShape) {
  const counts = new Array(size).fill(0);
  if (n >= size) {
    for (let i = 0; i < size; i++) counts[i] = 1;
    const fill = size === 8
      ? (scheduleShape === 'repeatBottom' ? [0, 1, 2, 3] : scheduleShape === 'repeatTop' ? [4, 5, 6, 7] : [2, 3, 4, 5])
      : Array.from({ length: Math.max(1, size - 2) }, (_, i) => i + 1);
    for (let k = 0; k < n - size; k++) counts[fill[k % fill.length]] += 1;
  } else {
    for (let k = 0; k < n; k++) counts[Math.round((k * (size - 1)) / Math.max(1, n - 1))] += 1;
  }
  const order = [];
  for (let i = 0; i < size; i++) for (let c = 0; c < counts[i]; c++) order.push(i);
  return order;
}

/**
 * The regular-season schedule for one league/season seed.
 *
 * R16: `n` (how many games) and `size` (how many CPU teams the season is played against) are
 * arguments, because a season's length is now per league (`SEASON.gamesPerLeague`) and Little
 * League is a 4-team league. THE OLD THREE-ARGUMENT FORM STILL WORKS: a STRING third argument is
 * read as `scheduleShape`, with n = `SEASON.gamesPerSeason` over 8 teams, so every caller written
 * before R16 - and every stored season that was generated by one - keeps its exact schedule.
 *
 * @param {string} league
 * @param {number|string} seasonSeed
 * @param {number|string} [n] - how many regular-season games; a string is the legacy `scheduleShape`
 * @param {number} [size] - how many CPU teams (default 8)
 * @param {string} [scheduleShape] - `'repeatTop'` | `'repeatBottom'` | `'repeatMiddle'`, defaults
 *   to `settings.SCHEDULE_SHAPE`
 * @returns {Array<{opponentIndex:number, home:boolean}>} `opponentIndex` indexes the season's own
 *   team array (0 = weakest .. size-1 = strongest); a repeated index appears more than once.
 */
export function makeSchedule(league, seasonSeed, n = SEASON.gamesPerSeason, size = 8, scheduleShape = SCHEDULE_SHAPE) {
  let games = n;
  let shape = scheduleShape;
  if (typeof n === 'string') { shape = n; games = SEASON.gamesPerSeason; }
  const teams = Math.max(1, Math.trunc(size) || 8);
  const count = Math.max(1, Math.trunc(games) || SEASON.gamesPerSeason);
  const rand01 = mulberry32(hashSeed('bb-schedule', league, seasonSeed));
  const homeFlags = shuffledHomeFlags(rand01, count);
  const order = (teams === 8 && count === 12)
    ? (OPPONENT_ORDERS[shape] || OPPONENT_ORDERS[SCHEDULE_SHAPE] || OPPONENT_ORDERS.repeatTop)
    : opponentOrder(count, teams, shape);
  return order.map((opponentIndex, i) => ({ opponentIndex, home: homeFlags[i] }));
}

/**
 * The scripted CPU-only standings for a league of 8 teams plus the player (doc §4/§8, [Locked]):
 * "each CPU team beats every weaker CPU team, so the strongest always tops the table" - a full
 * round robin among the 8 (7 games each) resolved purely by strength, with no game actually
 * played. The player's OWN record (from real games, played by the caller) is folded in as a ninth
 * row and ranked by the same `wins` column; ties break on strength rank for two CPU teams (which
 * cannot actually tie under this rule) and, for the player, on career wins per doc §5's own
 * leaderboard tie-break.
 *
 * `standingsModel` (BB-2b commit 2, doc §4/§13 Open item 13): `'rawWins7'` is the original scripted
 * record - a 7-game round robin among the 8 CPUs, so a CPU team's win total tops out at 7 no matter
 * how long the PLAYER's own season is. `'scaledTo12'` scripts the same rank ordering onto a 12-game
 * scale instead (`round(12 * rank / (n-1))`), directly comparable to the player's own 12-game
 * record - see `settings.js`'s `STANDINGS_MODEL` for the full rationale and default.
 * @param {Array} teams - `makeLeague(league)`'s 8 teams, weakest to strongest (index 0..7)
 * @param {{wins:number, losses:number}} playerResults - the player's own regular-season record
 * @param {string} [standingsModel] - `'rawWins7'` | `'scaledTo12'`, defaults to `settings.STANDINGS_MODEL`
 * @returns {Array<{id:string, styleId?:string, wins:number, losses:number, isPlayer:boolean, strengthRank:number}>}
 *   sorted strongest/most-wins first (index 0 = the standings leader)
 */
export function scriptedStandings(teams, playerResults, games = SEASON.gamesPerSeason,
  standingsModel = STANDINGS_MODEL, tieBreak = STANDINGS_TIEBREAK, played = null) {
  // R16: the legacy three-argument form `scriptedStandings(teams, record, 'rawWins7')` still
  // works - a STRING third argument is the model, and the season length falls back to the frozen
  // `SEASON.gamesPerSeason`.
  let n = games;
  let model = standingsModel;
  if (typeof games === 'string') { model = games; n = SEASON.gamesPerSeason; }
  const seasonGames = Math.max(1, Math.trunc(n) || SEASON.gamesPerSeason);
  const size = teams.length;
  const rows = teams.map((team, rank) => {
    const scaled = model === 'scaledTo12' || model === 'scaledToSeason' || model === 'withResults';
    const scale = model === 'scaledTo12' ? 12 : seasonGames;
    let wins = scaled ? Math.round((scale * rank) / Math.max(1, size - 1)) : rank;
    let losses = scaled ? scale - wins : (size - 1) - rank;
    // 2026-09-23 (doc open item 13): MID-SEASON, a CPU team has played as many games as the player,
    // not its whole season. `played` games in, its record is its final one pro-rated
    // (round(finalWins * played / games)), so it grows with the player's and lands exactly on the
    // final record at the last game. Rounding is monotone in finalWins, so a weaker team never
    // passes a stronger one. The end-of-season table (which decides the playoff cut) is unchanged.
    if (model === 'withResults') {
      // Doc open item 13, Matt 2026-09-23: "make them match". A CPU team's games against the
      // PLAYER count as they actually went (a team you beat carries that loss); only its other
      // games are scripted, at its final scripted win rate. `played` defaults to the full season.
      const g = played != null ? Math.max(0, Math.trunc(played)) : scale;
      const vs = (playerResults.results || []).filter((r) => r.opponentIndex === rank);
      const cpuGames = Math.max(0, g - vs.length);
      wins = Math.round((wins * cpuGames) / scale) + vs.filter((r) => !r.won).length;
      losses = g - wins;
    } else if (scaled && played != null && played < scale) {
      const g = Math.max(0, Math.trunc(played));
      wins = Math.round((wins * g) / scale);
      losses = g - wins;
    }
    return {
      id: team.name,
      styleId: team.styleId,
      wins,
      losses,
      isPlayer: false,
      strengthRank: rank,
    };
  });
  rows.push({
    id: 'you',
    wins: playerResults.wins || 0,
    losses: playerResults.losses || 0,
    isPlayer: true,
    // R16 (`STANDINGS_TIEBREAK`): 'player' puts the player ABOVE every CPU team on equal wins;
    // 'cpu' is the shipped behaviour, where -1 lost them every tie.
    strengthRank: tieBreak === 'player' ? size + 1 : -1,
  });
  rows.sort((a, b) => {
    if (b.wins !== a.wins) return b.wins - a.wins;
    return b.strengthRank - a.strengthRank;
  });
  return rows;
}

/**
 * doc §4, [Locked]: "Regular season, then semifinal, then championship. No quarterfinal." Top 4
 * seed 1-4 (seed 1 strongest/most wins). "The strongest team always wins its semifinal" resolves
 * any semifinal with NO player in it outright; a semifinal the player IS in is left `null` for the
 * caller to resolve by actually playing the game.
 *
 * `bracketModel` (BB-2b commit 2, doc §4/§13 Open item 13): `'asCoded'` is the original positional
 * bracket (seed 1 v seed 4, seed 2 v seed 3) - since a low-skill player is nearly always seed 4
 * under `'rawWins7'` standings, this pairs the player against the single STRONGEST of the four
 * qualifiers in the semifinal, and the championship opponent (always the league's overall
 * strongest team, decided by the caller, never by this function) is that same team again.
 * `'strongestInFinal'` is the bracket doc §8's own wording implies ("the championship opponent is
 * always the toughest team in the league") - the player's semifinal opponent is chosen to EXCLUDE
 * the strongest of the four qualifiers (by `strengthRank`, which is 1:1 with `makeLeague`'s own
 * slot order), so that team reaches the final by winning ITS OWN scripted semifinal instead of by
 * being fed to the player twice. See `settings.js`'s `BRACKET_MODEL` for the measured effect and
 * default. Player-absent seasons fall back to the positional pairing (this function is only ever
 * called by a caller that already knows the player qualified, but never assumes it here).
 * @param {Array} standings - `scriptedStandings()`'s sorted output
 * @param {string} [bracketModel] - `'asCoded'` | `'strongestInFinal'`, defaults to `settings.BRACKET_MODEL`
 * @returns {{seeds:Array, semifinals:Array<Array>, winners:Array}}
 */
export function playoffs(standings, bracketModel = BRACKET_MODEL, format = 'top4') {
  // R16 (Matt, 2026-09-22: "all teams should make the playoffs... just little league"): the
  // EVERYONE-IN bracket. Every row is a seed, paired 1 v 4 and 2 v 3 (the positional bracket, the
  // only one that makes sense when the field IS the league) - so at Little League's four teams the
  // player always plays a semifinal and, on winning it, a final. The CPU-only semifinal resolves
  // by strength, exactly as it does below: `standings` is already sorted strongest first, so
  // `pair[0]` is both the better record and the higher `strengthRank`.
  if (format === 'all') {
    const all = standings.slice();
    const semifinals = [];
    for (let i = 0; i < Math.floor(all.length / 2); i++) semifinals.push([all[i], all[all.length - 1 - i]]);
    const winners = semifinals.map((pair) => (pair.some((t) => t.isPlayer) ? null : pair[0]));
    return { seeds: all, semifinals, winners };
  }
  const seeds = standings.slice(0, 4);
  const playerIdx = seeds.findIndex((s) => s.isPlayer);
  if (bracketModel === 'strongestInFinal' && playerIdx !== -1) {
    const cpuSeeds = seeds.filter((s) => !s.isPlayer);
    const strongest = cpuSeeds.reduce((a, b) => (b.strengthRank > a.strengthRank ? b : a));
    const others = cpuSeeds.filter((s) => s !== strongest);
    const semifinals = [[seeds[playerIdx], others[0]], [strongest, others[1]]];
    const winners = semifinals.map((pair) => (pair.some((t) => t.isPlayer) ? null : pair[0]));
    return { seeds, semifinals, winners };
  }
  const semifinals = [[seeds[0], seeds[3]], [seeds[1], seeds[2]]];
  const winners = semifinals.map((pair) => (pair.some((t) => t.isPlayer) ? null : pair[0]));
  return { seeds, semifinals, winners };
}

/**
 * doc §4, [Locked]: "Lose the semifinal = Bronze. Lose the championship = Silver. Win it = Gold."
 * Missing the playoffs entirely (doc: "Miss the playoffs = replay that league's season") is 0,
 * matching `baseball/CLAUDE.md`'s frozen trophy scale (0 none, 1 bronze, 2 silver, 3 gold).
 * @param {{reachedSemifinal:boolean, reachedChampionship:boolean, wonChampionship:boolean}} result
 * @returns {0|1|2|3}
 */
export function trophyFor(result) {
  if (result.wonChampionship) return 3;
  if (result.reachedChampionship) return 2;
  if (result.reachedSemifinal) return 1;
  return 0;
}

export default { makeSchedule, scriptedStandings, playoffs, trophyFor };
