// connect-four/js/strings.js — every user-visible string in Connect Four, both languages.
// Follows the per-game dictionary convention (root CLAUDE.md, "Adding a game" item 9; reference:
// snake/). English is the source of truth; es may lag (js/i18n.js's fallback shows English for
// anything missing). Difficulty values (easy/medium/hard/expert, ai.js's Difficulty enum) are
// storage vocabulary and stay canonical — only display labels translate. The hidden-challenge
// strings here (syncChallengeUi's "Begin challenge"/"Retry Challenge"/etc.) are unreachable dead
// code (challengeActive is hardcoded false, per ui.js's own comment) but translated anyway for
// consistency, per THE LAW rule 9 discipline — no new prose invented, just the existing English
// carried into Spanish.

export const STRINGS = {
  en: {
    title: 'Connect Four',
    setup_aria: 'Game setup',
    difficulty: 'Difficulty',
    diff_easy: 'Beginner',
    diff_medium: 'Intermediate',
    diff_hard: 'Pro',
    diff_expert: 'Expert',
    who_first: 'Who goes first',
    you: 'You',
    alternate: 'Alternate',
    you_start: 'You start',
    name_starts: '{name} starts',
    start_game: 'Start game',
    your_move: 'Your move',
    undo_title: 'Take back your last move',
    undo_btn: '↩ Undo',
    menu: 'Menu',
    tap_column_hint: 'Tap a column to drop ↓',
    board_aria: 'Connect Four board — press number keys 1 to 7 to drop in a column',
    close: 'Close',
    rematch: 'Rematch',
    change_settings: 'Change settings',
    menu_dialog_aria: 'Game menu',
    show_best_moves: 'Show best moves',
    menu_note: 'Marks the engine’s best column each turn. Before the board is solvable the mark is a guess; once solved, + / − scores assume perfect play by both sides.',
    menu_undo: '↩ Undo your last move',
    restart_game: 'Restart game',
    quit_to_setup: 'Quit to setup',
    resume_game: 'Resume game',
    confirm_dialog_aria: 'Confirm',
    cancel: 'Cancel',
    confirm: 'Confirm',
    col_row_empty_aria: 'Column {col}, row {row}, empty',
    col_row_occ_aria: 'Column {col}, row {row}, {occ}',
    your_disc: 'your disc',
    computer_disc: 'computer disc',
    empty: 'empty',
    begin_challenge: 'Begin challenge',
    challenge_completed_note: 'Connect 4 challenge completed. Play anyways?',
    retry_challenge: 'Retry Challenge',
    tap_again_confirm: 'Tap again to confirm',
    hint_toggle_confirm: "Using Show Best Moves means this game won't count towards your stats. Turn it on anyway?",
    undo_confirm: "Undoing a move means this game won't count towards your stats. Undo anyway?",
    opp_thinking: '{opp} is thinking…',
    opp_move: "{opp}'s move",
    you_win: 'You win! 🎉',
    opp_wins: '{opp} wins',
    draw: "It's a draw",
    not_counted: ' (not counted towards stats)',
    eval_solved: 'Solved vs perfect play · + you win, − you lose · best ringed',
    eval_estimate: 'Not solved yet · ★ = engine’s guess',
    eval_fallible: 'The computer at this level can still make mistakes.',
    analyzing: 'Analyzing',
  },
  es: {
    title: 'Conecta 4',
    setup_aria: 'Ajustes de la partida',
    difficulty: 'Dificultad',
    diff_easy: 'Principiante',
    diff_medium: 'Intermedio',
    diff_hard: 'Pro',
    diff_expert: 'Experto',
    who_first: 'Quién empieza',
    you: 'Tú',
    alternate: 'Alternar',
    you_start: 'Empiezas tú',
    name_starts: 'Empieza {name}',
    start_game: 'Empezar partida',
    your_move: 'Tu turno',
    undo_title: 'Deshacer tu último movimiento',
    undo_btn: '↩ Deshacer',
    menu: 'Menú',
    tap_column_hint: 'Toca una columna para soltar ↓',
    board_aria: 'Tablero de Connect Four — pulsa las teclas del 1 al 7 para soltar en una columna',
    close: 'Cerrar',
    rematch: 'Revancha',
    change_settings: 'Cambiar ajustes',
    menu_dialog_aria: 'Menú del juego',
    show_best_moves: 'Mostrar mejores movimientos',
    menu_note: 'Marca la mejor columna del motor cada turno. Antes de que el tablero sea resoluble, la marca es una intuición; una vez resuelto, las puntuaciones + / − asumen juego perfecto de ambos lados.',
    menu_undo: '↩ Deshacer tu último movimiento',
    restart_game: 'Reiniciar partida',
    quit_to_setup: 'Salir a ajustes',
    resume_game: 'Reanudar partida',
    confirm_dialog_aria: 'Confirmar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    col_row_empty_aria: 'Columna {col}, fila {row}, vacía',
    col_row_occ_aria: 'Columna {col}, fila {row}, {occ}',
    your_disc: 'tu ficha',
    computer_disc: 'ficha del ordenador',
    empty: 'vacía',
    begin_challenge: 'Empezar desafío',
    challenge_completed_note: 'Desafío de Connect 4 completado. ¿Jugar de todas formas?',
    retry_challenge: 'Reintentar desafío',
    tap_again_confirm: 'Toca otra vez para confirmar',
    hint_toggle_confirm: 'Usar Mostrar mejores movimientos hace que esta partida no cuente para tus estadísticas. ¿Activarlo de todas formas?',
    undo_confirm: 'Deshacer un movimiento hace que esta partida no cuente para tus estadísticas. ¿Deshacer de todas formas?',
    opp_thinking: '{opp} está pensando…',
    opp_move: 'Turno de {opp}',
    you_win: '¡Ganaste! 🎉',
    opp_wins: '{opp} gana',
    draw: 'Empate',
    not_counted: ' (no contabilizada en las estadísticas)',
    eval_solved: 'Resuelto vs juego perfecto · + ganas, − pierdes · el mejor va marcado',
    eval_estimate: 'Aún sin resolver · ★ = intuición del motor',
    eval_fallible: 'El ordenador en este nivel todavía puede fallar.',
    analyzing: 'Analizando',
  },
};

export default STRINGS;
